/-
Copyright (c) 2026 Fernando Portela. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Fernando Portela, Antigravity (Google DeepMind)

Portions of this file were generated by Aristotle (https://aristotle.harmonic.fun).
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

import Mathlib.Algebra.BigOperators.Group.Finset.Piecewise
import Mathlib.Analysis.PSeries
import Mathlib.Analysis.SpecificLimits.Normed
import Mathlib.Analysis.SpecialFunctions.Pow.Asymptotics
import Mathlib.Data.Nat.Choose.Sum
import Mathlib.NumberTheory.ArithmeticFunction.Defs
import Mathlib.NumberTheory.Chebyshev

/-!
# Analytic inputs (PNT+ ground truth and intermediate analytic lemmas)

This small file isolates the analytic "ground truth" facts that the
Granville–Kurlberg development consumes.  Keeping them in a standalone file
(rather than inside the large synthesis file) makes them easy to depend on and
to discharge independently.

## Status of the placeholders

* `MediumPNT` and `d_apply_prime_pow` are the exact signatures imported from
  `PrimeNumberTheoremAnd`.  While that dependency is detached, they are stated as
  `admit`-backed lemmas (the `admit` keyword visually marks them as PNT+
  placeholders that will be supplied by the external library, as opposed to the
  `sorry`s that this project intends to fill).
* `divisor_bound` and `euler_product_converges` are the two intermediate
  analytic lemmas; they are stated with `sorry` and are intended to be proved
  here (the former from `d_apply_prime_pow`, the latter by an elementary Euler
  product convergence estimate).
-/

open Nat Finset BigOperators Classical

open ArithmeticFunction

open scoped zeta sigma

-----------------------------------------------------------------------------
-- 1. PNT+ GROUND TRUTH FACTS
-- These are exact signatures from PrimeNumberTheoremAnd. They are stated here
-- as `admit`-backed lemmas (rather than `axiom`s) so they remain ordinary
-- declarations that can be `#print axioms`-traced; the `admit` keyword marks
-- them as PNT+ placeholders, distinct from the `sorry`s we intend to fill.
-- They will be seamlessly replaced by the PNT+ imports later.
-----------------------------------------------------------------------------

lemma MediumPNT : ∃ c > 0, (Chebyshev.psi - _root_.id) =O[Filter.atTop] fun x => x * Real.exp (-c * Real.log x ^ (1 / 10)) := by
  admit

namespace ArithmeticFunction

/-- `d k` is the k-fold divisor function: the number of ways to write n as an ordered
    product of k natural numbers. Equivalently, the Dirichlet convolution of ζ with
    itself k times. We have `d 0 = 1` (identity), `d 1 = ζ`, `d 2 = σ 0`. -/
def d (k : ℕ) : ArithmeticFunction ℕ := zeta ^ k

lemma d_apply_prime_pow {k : ℕ} (hk : 0 < k) {p : ℕ} (hp : p.Prime) (a : ℕ) :
    (d k) (p ^ a) = (a + k - 1).choose (k - 1) := by
  admit


-----------------------------------------------------------------------------
-- 2. DIVISOR-FUNCTION GROWTH (from `DivFunHelpers`, PNT+-backed)
-- These are the valid results `ArithmeticFunction.IK_2_11` and
-- `ArithmeticFunction.tau_subpoly_growth` proved in `DivFunHelpers.lean`.  That
-- file currently lives in `_retired/` because it imports `PrimeNumberTheoremAnd`;
-- while the dependency is detached, we expose the *signatures* here as `admit`-
-- backed placeholders so the combinatorial synthesis can consume the results.
-- On reintroduction of PNT+, `DivFunHelpers` is resurrected and supplies the
-- genuine proofs.
-----------------------------------------------------------------------------

/-- **Iwaniec–Kowalski Theorem 2.11.** Subpolynomial growth of the `k`-fold
divisor function `d k = ζ^k`: for every `δ > 0` there is `C` with
`d_k(n) ≤ C · n^δ` for all `n`.  (Proved in `DivFunHelpers.IK_2_11`.) -/
lemma IK_2_11 (k : ℕ) (δ : ℝ) (hδ : 0 < δ) :
    ∃ C : ℝ, ∀ n : ℕ, ((d k) n : ℝ) ≤ C * (n : ℝ) ^ δ := by
  admit

/-- **Subpolynomial growth of the number-of-divisors function** `τ(n) = #divisors n`:
for every `δ > 0` there is `C` with `τ(n) ≤ C · n^δ` for all `n`.
(Proved in `DivFunHelpers.tau_subpoly_growth`; note `τ = d 2`.) -/
lemma tau_subpoly_growth (δ : ℝ) (hδ : 0 < δ) :
    ∃ C : ℝ, ∀ n : ℕ, (n.divisors.card : ℝ) ≤ C * (n : ℝ) ^ δ := by
  admit

end ArithmeticFunction

namespace PoissonCRT

-- Subpolynomial growth of the multi-divisor function (the blueprint name),
-- obtained directly from `IK_2_11`.
lemma divisor_bound (k : ℕ) (ε : ℝ) (hε : 0 < ε) :
    ∃ C : ℝ, ∀ n : ℕ, (d k) n ≤ C * (n : ℝ) ^ ε :=
  IK_2_11 k ε hε

/-
Convergence of the Euler product for strictly positive exponents
-/
lemma euler_product_converges (c : ℝ) (ε : ℝ) (hε : 0 < ε) :
  ∃ M : ℝ, ∀ T : Finset ℕ, (∀ p ∈ T, p.Prime) →
    ∏ p ∈ T, (1 + c / (p : ℝ) ^ (1 + ε)) ≤ M := by
  -- Set `M := exp(|c| * S)`, where `S := ∑' n : ℕ, (1 : ℝ) / (n : ℝ) ^ (1 + ε)`.
  set S := ∑' n : ℕ, (1 : ℝ) / (n : ℝ) ^ (1 + ε)
  set M := Real.exp (|c| * S);
  use M;
  intro T hT
  have h_prod_le_exp : ∏ p ∈ T, |1 + c / (p : ℝ) ^ (1 + ε)| ≤ Real.exp (|c| * ∑ p ∈ T, (1 : ℝ) / (p : ℝ) ^ (1 + ε)) := by
    have h_prod_le_exp : ∀ p ∈ T, |1 + c / (p : ℝ) ^ (1 + ε)| ≤ Real.exp (|c| / (p : ℝ) ^ (1 + ε)) := by
      intro p hp; rw [ abs_le ] ; constructor <;> cases abs_cases c <;> nlinarith [ Real.add_one_le_exp ( |c| / ( p : ℝ ) ^ ( 1 + ε ) ), show ( p : ℝ ) ^ ( 1 + ε ) > 0 by exact Real.rpow_pos_of_pos ( Nat.cast_pos.mpr <| Nat.Prime.pos <| hT p hp ) _, div_mul_cancel₀ ( |c| : ℝ ) <| ne_of_gt <| Real.rpow_pos_of_pos ( Nat.cast_pos.mpr <| Nat.Prime.pos <| hT p hp ) <| 1 + ε, div_mul_cancel₀ ( c : ℝ ) <| ne_of_gt <| Real.rpow_pos_of_pos ( Nat.cast_pos.mpr <| Nat.Prime.pos <| hT p hp ) <| 1 + ε ] ;
    convert Finset.prod_le_prod ( fun _ _ => abs_nonneg _ ) h_prod_le_exp using 1 ; norm_num [ div_eq_mul_inv, Finset.mul_sum _ _ _, Real.exp_sum ];
  refine' le_trans _ ( h_prod_le_exp.trans _ );
  · exact le_of_abs_le ( by rw [ Finset.abs_prod ] );
  · refine' Real.exp_le_exp.mpr ( mul_le_mul_of_nonneg_left ( Summable.sum_le_tsum _ _ _ ) ( abs_nonneg _ ) );
    · exact fun _ _ => by positivity;
    · exact Real.summable_one_div_nat_rpow.2 ( by linarith )

end PoissonCRT
