/-
Copyright (c) 2026 Fernando Portela. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Fernando Portela
-/

/-
Portions of this file were generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.28.0
Mathlib version: 8f9d9cff6bd728b17a24e163c9402775d9e6a365

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

import PoissonViaCRT.Defs
import Mathlib.Algebra.Order.Ring.Star
import Mathlib.Data.Int.Star
import Mathlib.Data.Real.StarOrdered

set_option linter.unusedVariables false

/-!
# Box Collision Bound Helpers

Helper lemmas for `box_collision_sum_bound`, which controls the collision sum
arising in the L1 deviation synthesis.
-/

open Finset BigOperators Classical

namespace PoissonCRT

/-- Extend `h : Fin m → ℤ` to `Fin (m+1) → ℤ` by prepending `0`. -/
@[expose]
public noncomputable def extendH (m : ℕ) (h : Fin m → ℤ) : Fin (m + 1) → ℤ := Fin.cons 0 h

/-! ## 1. Strict monotonicity and injectivity from box membership -/

/-
For `h` in the scaled box with offset `v = 0`, the extended sequence
`extendH m h` is strictly monotone: `0 < h(0) < h(1) < ⋯ < h(m-1)`.
-/
public lemma inScaledBox_cons_strictMono {m : ℕ} (X : Box m) (s : ℝ) (hs : 1 ≤ s)
    (h : Fin m → ℤ)
    (hbox : inScaledBox X s (fun _ => 0) h) :
    StrictMono (extendH m h) := by
  unfold extendH;
  intro i j hij;
  induction' j using Fin.inductionOn with j ih;
  · tauto;
  · cases lt_or_eq_of_le ( show i ≤ Fin.castSucc j from Nat.le_of_lt_succ hij ) <;> simp_all +decide [ Fin.cons ];
    · have := hbox j;
      rcases j with ⟨ _ | j, hj ⟩ <;> norm_num at *;
      linarith;
    · have := hbox j;
      rcases j with ⟨ _ | j, hj ⟩ <;> norm_num at *;
      · linarith;
      · linarith

/-
The extended values are bounded: `extendH m h i ≤ ⌈s * ∑ X.sides⌉` for all `i`.
-/
public lemma inScaledBox_cons_le_ceil {m : ℕ} (X : Box m) (s : ℝ) (hs : 1 ≤ s)
    (h : Fin m → ℤ)
    (hbox : inScaledBox X s (fun _ => 0) h) (i : Fin (m + 1)) :
    extendH m h i ≤ ⌈s * ∑ j, X.sides j⌉ := by
  induction i using Fin.inductionOn <;> norm_num at *;
  · exact Int.le_of_lt_add_one ( by rw [ show extendH m h 0 = 0 by rfl ] ; exact lt_add_of_le_of_pos ( Int.ceil_nonneg ( mul_nonneg ( by positivity ) ( Finset.sum_nonneg fun _ _ => le_of_lt ( X.sides_pos _ ) ) ) ) zero_lt_one );
  · rename_i i hi;
    have h_ind : ∀ j : Fin (m + 1), extendH m h j ≤ s * ∑ k ∈ Finset.univ.filter (fun k => k.val < j.val), X.sides k := by
      intro j;
      induction' j using Fin.inductionOn with j ih;
      · norm_num [ extendH ];
      · have := hbox j;
        rcases j with ⟨ _ | j, hj ⟩ <;> norm_num [ Finset.sum_filter, Finset.sum_range_succ ] at *;
        · rcases m with ( _ | _ | m ) <;> norm_num [ Fin.sum_univ_succ ] at *;
          · contradiction;
          · exact this.2;
          · exact this.2;
        · simp_all +decide [Finset.sum_ite];
          rw [ show ( Finset.filter ( fun x : Fin m => ( x : ℕ ) ≤ j + 1 ) Finset.univ : Finset ( Fin m ) ) = Finset.filter ( fun x : Fin m => ( x : ℕ ) ≤ j ) Finset.univ ∪ { ⟨ j + 1, hj ⟩ } from ?_, Finset.sum_union ] <;> norm_num;
          · linarith!;
          · grind;
    refine' Int.le_of_lt_add_one _;
    exact_mod_cast ( by nlinarith [ h_ind ( Fin.succ i ), Int.le_ceil ( s * ∑ j : Fin m, X.sides j ), show ( ∑ k : Fin m with k.val < ( i.succ : ℕ ), X.sides k ) ≤ ∑ j : Fin m, X.sides j from Finset.sum_le_sum_of_subset_of_nonneg ( fun x hx => Finset.mem_univ _ ) fun _ _ _ => le_of_lt ( X.sides_pos _ ) ] : ( extendH m h ( Fin.succ i ) : ℝ ) < ⌈s * ∑ j : Fin m, X.sides j⌉ + 1 )

/-
The extended values are nonneg.
-/
public lemma inScaledBox_cons_nonneg {m : ℕ} (X : Box m) (s : ℝ) (hs : 1 ≤ s)
    (h : Fin m → ℤ)
    (hbox : inScaledBox X s (fun _ => 0) h) (i : Fin (m + 1)) :
    (0 : ℤ) ≤ extendH m h i := by
  -- We prove the statement using induction on the size of the block $\textit{m}$.
  induction' m with m ih;
  · fin_cases i ; rfl;
  · refine' Fin.cases _ ( fun i => _ ) i <;> simp_all +decide [ Fin.forall_fin_succ, extendH ];
    induction' i using Fin.inductionOn with i IH;
    · have := hbox 0; simp_all +decide [ Fin.forall_fin_succ, inScaledBox ] ;
      linarith;
    · exact le_trans IH ( le_of_lt ( by have := hbox i.succ; aesop ) )

/-
For `p > ⌈s * ∑ X.sides⌉`, the extended map mod `p` is injective.
-/
public lemma injective_fin_cons_of_large {m : ℕ} (X : Box m) (s : ℝ) (hs : 1 ≤ s)
    (h : Fin m → ℤ)
    (hbox : inScaledBox X s (fun _ => 0) h)
    (p : ℕ) [NeZero p] (hp : (⌈s * ∑ j, X.sides j⌉ : ℤ) < p) :
    Function.Injective (Fin.cons (0 : ZMod p) (fun i => (h i : ZMod p))) := by
  -- By definition of `extendH`, we know that `extendH m h` is injective.
  have h_injured : Function.Injective (extendH m h) := by
    convert StrictMono.injective ( inScaledBox_cons_strictMono X s hs h hbox ) using 1;
  -- Since all values of `extendH m h` are in `[0, p-1]`, the map to `ZMod p` is injective.
  have h_injured_mod_p : Function.Injective (fun i => (extendH m h i : ZMod p)) := by
    intro i j hij
    have h_eq : extendH m h i = extendH m h j := by
      have h_eq : ∀ i j : Fin (m + 1), 0 ≤ extendH m h i ∧ extendH m h i < p ∧ 0 ≤ extendH m h j ∧ extendH m h j < p := by
        exact fun i j => ⟨ inScaledBox_cons_nonneg X s hs h hbox i, lt_of_le_of_lt ( inScaledBox_cons_le_ceil X s hs h hbox i ) hp, inScaledBox_cons_nonneg X s hs h hbox j, lt_of_le_of_lt ( inScaledBox_cons_le_ceil X s hs h hbox j ) hp ⟩;
      simp_all +decide [ ZMod.intCast_eq_intCast_iff' ];
      exact Int.modEq_iff_dvd.mp hij.symm |> fun ⟨ k, hk ⟩ => by nlinarith [ show k = 0 by nlinarith [ h_eq i j ] ] ;
    exact h_injured h_eq;
  convert h_injured_mod_p using 1;
  exact funext fun i => by cases i using Fin.cases <;> simp +decide [ extendH ] ;

/-! ## 2. Non-injectivity implies divisibility of some difference -/

/-- The set of ordered pairs `(i, j)` with `i < j` in `Fin (m + 1)`. -/
@[expose]
public noncomputable def pairsBelow (m : ℕ) : Finset (Fin (m + 1) × Fin (m + 1)) :=
  Finset.univ.filter fun ij => ij.1 < ij.2

/-
The non-injectivity indicator is at most the sum of divisibility indicators
over all pairs `(i, j)` with `i < j`.
-/
public lemma collision_indicator_le_sum_pairs {m : ℕ} (p : ℕ) (hp : 1 ≤ p)
    (h : Fin m → ℤ) :
    (if Function.Injective (Fin.cons (0 : ZMod p) (fun i => (h i : ZMod p)))
     then (0 : ℝ) else 1) ≤
    ∑ ij ∈ pairsBelow m,
      if (p : ℤ) ∣ (extendH m h ij.2 - extendH m h ij.1) then 1 else 0 := by
  split_ifs <;> simp_all +decide [ Function.Injective ];
  rename_i h; rcases h with ⟨ i, j, hij, h ⟩ ; rcases lt_trichotomy i j with hij' | rfl | hij' <;> simp_all +decide [ Fin.cons, extendH ] ;
  · refine' ⟨ ⟨ i, j ⟩, _ ⟩ ; simp_all +decide [ pairsBelow ];
    simp_all +decide [ Fin.cases, ← ZMod.intCast_zmod_eq_zero_iff_dvd ];
    induction i using Fin.inductionOn <;> induction j using Fin.inductionOn <;> aesop;
  · refine' ⟨ ⟨ j, i ⟩, _ ⟩ ; simp_all +decide [ pairsBelow ];
    simp_all +decide [ ← ZMod.intCast_zmod_eq_zero_iff_dvd ];
    cases i using Fin.inductionOn <;> cases j using Fin.inductionOn <;> aesop

/-! ## 3. Helper: indicator vanishes for large primes -/

/-- When a prime `p` exceeds `⌈s * ∑ sides⌉`, the collision indicator is `0` for every
`h` in the scaled box. This is the key lemma that makes the sum vanish when `U` contains
a large prime. -/
public lemma indicator_zero_of_large_prime {m : ℕ} (X : Box m) (s : ℝ) (hs : 1 ≤ s)
    (h : Fin m → ℤ) (hbox : inScaledBox X s (fun _ => 0) h)
    (p : ℕ) (hp : Nat.Prime p) (hlarge : (⌈s * ∑ j, X.sides j⌉ : ℤ) < p) :
    (if Function.Injective (Fin.cons (0 : ZMod p) (fun i => (h i : ZMod p)))
     then (0 : ℝ) else 1) = 0 := by
  haveI : NeZero p := ⟨hp.ne_zero⟩
  simp [injective_fin_cons_of_large X s hs h hbox p hlarge]

/-! ## 4. Helper: product vanishes when any factor does -/

end PoissonCRT
