/-
Copyright (c) 2026 Fernando Portela. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Fernando Portela
-/

/-
Portions of this file were generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.28.0
Mathlib version: 8f9d9cff6bd728b17a24e163c9402775d9e6a365

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

import PoissonViaCRT.Defs
import Mathlib.Combinatorics.Enumerative.Stirling
import Mathlib.Data.Pi.Interval

/-!
# Combinatorics of Gamma Structures (§3.1)

This file formalizes the combinatorial machinery from Section 3.1 of
"Poisson statistics via the Chinese remainder theorem" by
Granville–Kurlberg.

## Main Results

* `PoissonCRT.GammaStructure.gammaProd_perm_invariant`:
  The product `γ(Γ)` is invariant under permutations
  (unnumbered lemma in §3.1).
* `PoissonCRT.countGammaStructures_le`:
  Bound on the number of Gamma structures with given
  `γ(Γ) = γ` (Lemma 3.1).
* `PoissonCRT.countTuples_bound_prop`:
  Upper bound on `M_Γ(H)` (Proposition 3.2).
* `PoissonCRT.countTuples_bound_cor`:
  Corollary 3.3: Refined bound on `M_Γ(H)`.

## References

* [A. Granville, P. Kurlberg, *Poisson statistics via the
  Chinese remainder theorem*] [arXiv:math/0412135v2], §3.1
-/

open Finset BigOperators Nat

namespace PoissonCRT

variable {k : ℕ}

/-- Pascal's identity for `choose 2`: `C(n+1, 2) = C(n, 2) + n`. -/
lemma Nat.choose_two_succ (n : ℕ) : (n + 1).choose 2 = n.choose 2 + n := by
  simp +arith +decide [ Nat.choose ]

/-- For `n ≥ 2`, `C(n, 2) ≥ 1`. -/
lemma Nat.one_le_choose_two (n : ℕ) (hn : 2 ≤ n) : 1 ≤ n.choose 2 := by
  exact Nat.choose_pos hn

/--
Stirling numbers of the second kind bound: `S(m + d, m) ≤ C(m + d, 2)^d` for `m, d ≥ 1`.
This is a key combinatorial bound proved by double induction using the standard recurrence.
-/
theorem stirlingSecond_le_choose_pow_aux :
    ∀ d m : ℕ, 1 ≤ d → 1 ≤ m →
    stirlingSecond (m + d) m ≤ ((m + d).choose 2) ^ d := by
  -- We proceed by induction on $d$.
  intro d m hd hm
  induction d generalizing m
  case zero => contradiction
  case succ d ih =>
    induction hm <;> simp_all +decide only [le_add_iff_nonneg_left, _root_.zero_le, Nat.pow_succ']
    case refl =>
      refine Nat.recOn d ?_ ?_ <;> simp_all +decide [ Nat.stirlingSecond, Nat.choose ]
      grind +suggestions
    case step m hm ih =>
      by_cases hd : 1 ≤ d
      · simp_all +decide only [forall_const, le_eq, succ_eq_add_one]
        have h_combined : (m + 2 + d).choose 2 ^ (d + 1)
          ≥ (m + 1) * (m + 1 + d).choose 2 ^ d + (m + 1 + d).choose 2 ^ (d + 1) := by
          have h_combined : (m + 2 + d).choose 2 ^ (d + 1)
            ≥ ((m + 1 + d).choose 2 + (m + 1)) * (m + 1 + d).choose 2 ^ d := by
            rw [ show m + 2 + d = m + 1 + d + 1 by ring, Nat.choose_two_succ ]
            rw [ pow_succ' ]
            exact Nat.mul_le_mul ( by linarith ) ( Nat.pow_le_pow_left ( by linarith ) _ )
          grind
        have h_combined : (m + 1) * (m + 1 + d).stirlingSecond (m + 1)
          + (m + 1 + d).stirlingSecond m
          ≤ (m + 1) * (m + 1 + d).choose 2 ^ d + (m + 1 + d).choose 2 ^ (d + 1) := by
          apply Nat.add_le_add
          · exact Nat.mul_le_mul_left _ ( by
              simpa only [ add_comm, add_left_comm, add_assoc ]
                using ‹∀ m : ℕ, 1 ≤ m → ( m + d ).stirlingSecond m
                  ≤ ( m + d ).choose 2 ^ d› ( m + 1 ) ( by linarith ) )
          · grind
        convert h_combined.trans ‹_› using 1
        ring_nf
      · simp_all +decide [ Nat.stirlingSecond_succ_succ, Nat.choose_two_succ ]
        simp +decide [ Nat.stirlingSecond_eq_zero_of_lt ]
        simp_all +arith +decide [ Nat.stirlingSecond_self ]

/-- Apply a permutation `σ` of `{0, …, k-1}` to a Gamma
structure. The permuted structure has
`γ^(σ)_{i,j} = γ_{σ(i), σ(j)}`. -/
def GammaStructure.permute (Γ : GammaStructure k)
    (σ : Equiv.Perm (Fin k)) : GammaStructure k where
  gamma i j := Γ.gamma (σ i) (σ j)
  symm i j := Γ.symm (σ i) (σ j)
  pos i j hij := Γ.pos (σ i) (σ j)
    (fun h => hij (σ.injective h))
  sqfree i j hij := Γ.sqfree (σ i) (σ j)
    (fun h => hij (σ.injective h))
  compat i j l hij hjl hil := Γ.compat (σ i) (σ j) (σ l)
    (fun h => hij (σ.injective h))
    (fun h => hjl (σ.injective h))
    (fun h => hil (σ.injective h))
  diag i := Γ.diag (σ i)

/-! ### Permutation invariance of `γ(Γ)` -/

-- See docs/proof_sketches.md for full proof sketch.
lemma GammaStructure.prime_dvd_trans
    (Γ : GammaStructure k) {p : ℕ} (_hp : Nat.Prime p)
    {i j l : Fin k} (hij : i ≠ j) (hjl : j ≠ l)
    (hil : i ≠ l) (h1 : p ∣ Γ.gamma i j)
    (h2 : p ∣ Γ.gamma j l) : p ∣ Γ.gamma i l :=
  dvd_trans (Nat.dvd_gcd h1 h2)
    (Γ.compat i j l hij hjl hil)

/-- The relation `fun i j => p ∣ Γ.gamma (f i) (f j) ∨ i = j`
is an equivalence relation for any injective
`f : Fin k → Fin k`. -/
private lemma GammaStructure.prime_dvd_or_eq_equiv
    (Γ : GammaStructure k) (p : ℕ) (hp : Nat.Prime p)
    (f : Fin k → Fin k) (hf : Function.Injective f) :
    Equivalence
      (fun i j => p ∣ Γ.gamma (f i) (f j) ∨ i = j) where
  refl i := Or.inr rfl
  symm {i j} hij := by
    rcases hij with h | rfl
    · exact Or.inl (by rwa [Γ.symm])
    · exact Or.inr rfl
  trans {i j l} hij hjl := by
    rcases eq_or_ne i j with rfl | hne_ij
    · exact hjl
    rcases eq_or_ne j l with rfl | hne_jl
    · exact hij
    rcases eq_or_ne i l with rfl | hne_il
    · exact Or.inr rfl
    exact Or.inl (Γ.prime_dvd_trans hp
      (hf.ne hne_ij) (hf.ne hne_jl) (hf.ne hne_il)
      (hij.resolve_right hne_ij)
      (hjl.resolve_right hne_jl))

-- See docs/proof_sketches.md for full proof sketch.
/-- The product of squarefree integers remains squarefree if they are pairwise coprime, which
implies that the row product `γⱼ` is squarefree. -/
lemma GammaStructure.gammaRow_squarefree
    (Γ : GammaStructure k) (j : Fin k) :
    Squarefree (Γ.gammaRow j) := by
  have h_lcm_sqfree : ∀ {S : Finset ℕ},
      (∀ s ∈ S, Squarefree s) → Squarefree (Finset.lcm S id) := by
    intros S hS
    have h_lcm_sqfree : ∀ p : ℕ, Nat.Prime p → (Nat.factorization (Finset.lcm S id)) p ≤ 1 := by
      intros p hp
      have h_lcm_sqfree : ∀ s ∈ S,
          (Nat.factorization s) p ≤ 1 := fun s hs =>
        Nat.le_of_not_lt fun h => hp.not_dvd_one <| by
          have := hS s hs
          exact absurd (this.natFactorization_le_one p) (by aesop)
      induction S using Finset.induction <;> simp_all
      by_cases h : ‹ℕ› = 0 <;>
        by_cases h' : Finset.lcm ‹_› id = 0 <;>
        simp_all +decide [GCDMonoid.lcm, Nat.factorization_lcm]
      have := hS.2 0 h'; simp_all +decide
    rw [Nat.squarefree_iff_prime_squarefree]
    intro x hx_prime hx_div
    have h_exp : (Nat.factorization (Finset.lcm S id)) x ≥ 2 := by
      obtain ⟨k, hk⟩ := hx_div
      rcases k with (_ | _ | k) <;>
        simp_all +decide only [mul_zero, factorization_zero, Finsupp.coe_zero, Pi.zero_apply,
          _root_.zero_le, implies_true, Finset.lcm_eq_zero_iff, id_eq, exists_eq_right, ge_iff_le,
          zero_add, mul_one, ne_eq, Nat.Prime.ne_zero, not_false_eq_true, factorization_mul,
          Prime.factorization, Finsupp.coe_add, Pi.add_apply, Finsupp.single_eq_same, reduceAdd,
          _root_.mul_eq_zero, or_self, Nat.add_eq_zero_iff, and_false, and_self,
          le_add_iff_nonneg_right]
      exact absurd (hS 0 hk) (by norm_num)
    linarith [h_lcm_sqfree x hx_prime]
  convert h_lcm_sqfree _
  rw [Finset.lcm_image]
  congr! 1
  simp +zetaDelta only [mem_image, mem_Iio, forall_exists_index, and_imp,
    forall_apply_eq_imp_iff₂] at *
  exact fun i hi => Γ.sqfree i j (ne_of_lt hi)

-- See docs/proof_sketches.md for full proof sketch.
/-- The prime factorization multiplicity of `gammaRow j` at any prime is at most 1, since it
is squarefree. -/
lemma GammaStructure.factorization_gammaRow_le_one
    (Γ : GammaStructure k) (j : Fin k) (p : ℕ) :
    Nat.factorization (Γ.gammaRow j) p ≤ 1 :=
  (gammaRow_squarefree Γ j).natFactorization_le_one p

-- See docs/proof_sketches.md for full proof sketch.
/-- The prime factorization multiplicity of `gammaRow j` at a prime `p` is 1 if `p` divides
any entry in the column `i < j`, and 0 otherwise. -/
lemma GammaStructure.factorization_gammaRow_eq
    (Γ : GammaStructure k) (j : Fin k) (p : ℕ)
    (hp : Nat.Prime p) :
    Nat.factorization (Γ.gammaRow j) p =
      if ∃ i ∈ Finset.Iio j, p ∣ Γ.gamma i j
      then 1 else 0 := by
  split_ifs with h
  · have h_lcm_div : p ∣ Γ.gammaRow j := dvd_trans h.choose_spec.2 (Finset.dvd_lcm h.choose_spec.1)
    exact Nat.factorization_eq_one_of_squarefree (gammaRow_squarefree Γ j) hp h_lcm_div
  · simp_all +decide only [mem_Iio, not_exists, not_and, gammaRow, factorization_eq_zero_iff,
      not_true_eq_false, Finset.lcm_eq_zero_iff, false_or]
    apply Or.inl _
    intro H
    have := Nat.dvd_trans H (Finset.lcm_dvd fun i hi => Finset.dvd_prod_of_mem _ hi)
    simp_all +decide only [Nat.Prime.dvd_iff_not_coprime hp, ne_eq, Decidable.not_not]
    exact this <| Nat.Coprime.prod_right fun i hi => h i <| Finset.mem_Iio.mp hi

-- See docs/proof_sketches.md for full proof sketch.
/-- The multiplicity of `p` in the factorization of `γ(Γ)` equals the number of columns `j`
such that `p` divides some entry `gamma i j` with `i < j`. -/
lemma GammaStructure.factorization_gammaProd_eq
    (Γ : GammaStructure k) (p : ℕ)
    (hp : Nat.Prime p) :
    Nat.factorization Γ.gammaProd p = (Finset.univ.filter fun j : Fin k =>
        ∃ i ∈ Finset.Iio j, p ∣ Γ.gamma i j).card := by
  convert Finset.sum_congr rfl (fun j _ => Γ.factorization_gammaRow_eq j p hp) using 1
  any_goals exact Finset.univ
  · rw [show Γ.gammaProd = ∏ j : Fin k, Γ.gammaRow j from rfl, Nat.factorization_prod]
    simp_all only [Finsupp.coe_finsetSum, sum_apply]
    intro j _; have := Γ.gammaRow_squarefree j; aesop
  · rw [Finset.card_filter]

-- See docs/proof_sketches.md for full proof sketch.
/-- Counts the number of indices `j` that are not the minimal representative of their
equivalence class under the relation `R`. -/
lemma card_filter_exists_lt_equiv {n : ℕ}
    (R : Fin n → Fin n → Prop)
    [DecidableRel R]
    (hrefl : ∀ i, R i i)
    (hsymm : ∀ i j, R i j → R j i)
    (htrans : ∀ i j l, R i j → R j l → R i l) :
    (Finset.univ.filter fun j : Fin n =>
      ∃ i, i < j ∧ R i j).card = n - (Finset.univ.image fun j : Fin n =>
        (Finset.univ.filter fun i => R i j).min' ⟨j, Finset.mem_filter.mpr
          ⟨Finset.mem_univ _, hrefl j⟩⟩).card := by
  have h_complementary :
    Finset.filter (fun j => ∃ i < j, R i j) (Finset.univ : Finset (Fin n)) =
      Finset.univ \ Finset.image
        (fun j => Finset.min'
          (Finset.filter (fun i => R i j) (Finset.univ : Finset (Fin n)))
          ⟨j, by grind +splitImp⟩)
        (Finset.univ : Finset (Fin n)) := by
    all_goals generalize_proofs at *
    ext j
    simp only [mem_filter, mem_univ, true_and, mem_sdiff, mem_image, not_exists]
    constructor <;> intro h
    · intro x hx
      have := Finset.min'_mem (Finset.filter (fun i => R i x) Finset.univ)
      simp_all +decide only [min', id_eq, mem_filter, mem_univ, true_and, forall_const]
      contrapose! hx; simp_all only [ne_eq]
      obtain ⟨i, hi, hi'⟩ := h
      exact ne_of_lt (lt_of_le_of_lt (Finset.inf'_le _ <| by aesop) hi)
    · contrapose! h
      use j; simp only [min', id_eq]
      apply le_antisymm _ _ <;> simp_all only [inf'_le_iff, le_inf'_iff, mem_filter, mem_univ,
        true_and]
      · exact ⟨j, hrefl j, le_rfl⟩
      · exact fun i hi => le_of_not_gt fun hi' => h i hi' hi
  rw [h_complementary, Finset.card_sdiff]
  norm_num [Finset.card_univ]

/-
See docs/proof_sketches.md for full proof sketch.

Applying a permutation to an equivalence relation preserves the number of distinct
equivalence classes.
-/
lemma card_image_classMin_eq_of_perm {n : ℕ}
    (R₁ R₂ : Fin n → Fin n → Prop)
    [DecidableRel R₁] [DecidableRel R₂]
    (hrefl₁ : ∀ i, R₁ i i)
    (hsymm₁ : ∀ i j, R₁ i j → R₁ j i)
    (htrans₁ : ∀ i j l, R₁ i j → R₁ j l → R₁ i l)
    (hrefl₂ : ∀ i, R₂ i i)
    (hsymm₂ : ∀ i j, R₂ i j → R₂ j i)
    (htrans₂ : ∀ i j l, R₂ i j → R₂ j l → R₂ i l)
    (σ : Equiv.Perm (Fin n))
    (hcompat : ∀ i j, R₁ i j ↔ R₂ (σ i) (σ j)) :
    (Finset.univ.image fun j : Fin n =>
      (Finset.univ.filter fun i => R₁ i j).min'
        ⟨j, Finset.mem_filter.mpr
          ⟨Finset.mem_univ _, hrefl₁ j⟩⟩).card =
    (Finset.univ.image fun j : Fin n =>
      (Finset.univ.filter fun i => R₂ i j).min'
        ⟨j, Finset.mem_filter.mpr
          ⟨Finset.mem_univ _, hrefl₂ j⟩⟩).card := by
  fapply Finset.card_bij (fun m hm => Finset.min' (Finset.univ.filter fun i => R₂ i (σ m))
      ⟨σ m, Finset.mem_filter.mpr ⟨Finset.mem_univ _, hrefl₂ _⟩⟩)
  · aesop
  · intros a₁ ha₁ a₂ ha₂ h_eq_min
    obtain ⟨j₁, hj₁⟩ : ∃ j₁, a₁ = Finset.min'
        (Finset.univ.filter fun i => R₁ i j₁)
        ⟨j₁, Finset.mem_filter.mpr ⟨Finset.mem_univ _, hrefl₁ j₁⟩⟩ := by aesop
    obtain ⟨j₂, hj₂⟩ : ∃ j₂, a₂ = Finset.min'
        (Finset.univ.filter fun i => R₁ i j₂)
        ⟨j₂, Finset.mem_filter.mpr ⟨Finset.mem_univ _, hrefl₁ j₂⟩⟩ := by
      rw [Finset.mem_image] at ha₂
      obtain ⟨j₂, _, rfl⟩ := ha₂; exact ⟨j₂, rfl⟩
    have h_eq_classes : R₂ (σ j₁) (σ j₂) := by
      have h_eq_classes : R₂ (σ a₁) (σ a₂) := by
        have h_eq_classes :
            R₂ (Finset.min'
              (Finset.univ.filter fun i => R₂ i (σ a₁))
              ⟨σ a₁, Finset.mem_filter.mpr ⟨Finset.mem_univ _, hrefl₂ _⟩⟩) (σ a₁) ∧
            R₂ (Finset.min'
              (Finset.univ.filter fun i => R₂ i (σ a₂))
              ⟨σ a₂, Finset.mem_filter.mpr ⟨Finset.mem_univ _, hrefl₂ _⟩⟩) (σ a₂) :=
          ⟨(Finset.mem_filter.mp (Finset.min'_mem
              (Finset.univ.filter fun i => R₂ i (σ a₁))
              ⟨σ a₁, Finset.mem_filter.mpr ⟨Finset.mem_univ _, hrefl₂ _⟩⟩)).2,
           (Finset.mem_filter.mp (Finset.min'_mem
              (Finset.univ.filter fun i => R₂ i (σ a₂))
              ⟨σ a₂, Finset.mem_filter.mpr ⟨Finset.mem_univ _, hrefl₂ _⟩⟩)).2⟩
        grind +ring
      generalize_proofs at *
      have h_eq_classes : R₁ a₁ j₁ ∧ R₁ a₂ j₂ := by
        exact ⟨hj₁.symm ▸ Finset.min'_mem _ _ |> fun x => by simpa using x,
          hj₂.symm ▸ Finset.min'_mem _ _ |> fun x => by simpa using x⟩
      generalize_proofs at *
      grind +ring
    have h_eq_classes' : R₁ j₁ j₂ := hcompat _ _ |>.2 h_eq_classes
    have h_eq_classes'' : a₁ = a₂ := by
      have h_eq_classes'' :
          Finset.filter (fun i => R₁ i j₁) Finset.univ =
          Finset.filter (fun i => R₁ i j₂) Finset.univ := by grind +ring
      simp_all +decide [Finset.ext_iff]
    exact h_eq_classes''
  · simp +zetaDelta at *
    intro a
    use σ.symm a
    congr! 1
    ext i; simp +decide
    have := Finset.min'_mem ( Finset.univ.filter fun i => R₁ i ( σ.symm a ) ) ⟨ σ.symm a, by aesop ⟩
    aesop

/-
    simp +zetaDelta [mem_image, mem_univ, true_and, exists_prop, exists_exists_eq_and,
      forall_exists_index, forall_apply_eq_imp_iff] at *
    intro a
    use σ⁻¹ a
    congr! 3
    have := Finset.min'_mem (Finset.univ.filter fun i => R₁ i (σ⁻¹ a))
      ⟨σ⁻¹ a, Finset.mem_filter.mpr ⟨Finset.mem_univ _, hrefl₁ _⟩⟩
    aesop -/

/-- Two equivalence relations on `Fin n` that have the same
equivalence classes (up to bijection) yield the same count of
non-minimal elements. -/
lemma card_filter_exists_lt_equiv_eq {n : ℕ}
    (R₁ R₂ : Fin n → Fin n → Prop)
    [DecidableRel R₁] [DecidableRel R₂]
    (hrefl₁ : ∀ i, R₁ i i)
    (hsymm₁ : ∀ i j, R₁ i j → R₁ j i)
    (htrans₁ : ∀ i j l, R₁ i j → R₁ j l → R₁ i l)
    (hrefl₂ : ∀ i, R₂ i i)
    (hsymm₂ : ∀ i j, R₂ i j → R₂ j i)
    (htrans₂ : ∀ i j l, R₂ i j → R₂ j l → R₂ i l)
    (σ : Equiv.Perm (Fin n))
    (hcompat : ∀ i j, R₁ i j ↔ R₂ (σ i) (σ j)) :
    (Finset.univ.filter fun j : Fin n => ∃ i, i < j ∧ R₁ i j).card =
    (Finset.univ.filter fun j : Fin n => ∃ i, i < j ∧ R₂ i j).card := by
  rw [card_filter_exists_lt_equiv R₁ hrefl₁ hsymm₁ htrans₁,
      card_filter_exists_lt_equiv R₂ hrefl₂ hsymm₂ htrans₂,
      card_image_classMin_eq_of_perm R₁ R₂ hrefl₁ hsymm₁ htrans₁ hrefl₂ hsymm₂ htrans₂ σ hcompat]

-- See docs/proof_sketches.md for full proof sketch.
/-- The number of non-minimal column indices under the prime divisibility equivalence
relation is invariant under permutations of the index set. -/
lemma GammaStructure.perm_count_eq
    (Γ : GammaStructure k)
    (σ : Equiv.Perm (Fin k)) (p : ℕ)
    (hp : Nat.Prime p) :
    (Finset.univ.filter fun j : Fin k => ∃ i ∈ Finset.Iio j, p ∣ Γ.gamma (σ i) (σ j)).card =
    (Finset.univ.filter fun j : Fin k => ∃ i ∈ Finset.Iio j, p ∣ Γ.gamma i j).card := by
  set R₁ : Fin k → Fin k → Prop := fun i j => p ∣ Γ.gamma i j ∨ i = j
  set R₂ : Fin k → Fin k → Prop := fun i j => p ∣ Γ.gamma (σ i) (σ j) ∨ i = j
  have hR₁_equiv : Equivalence R₁ := Γ.prime_dvd_or_eq_equiv p hp id Function.injective_id
  have hR₂_equiv : Equivalence R₂ := Γ.prime_dvd_or_eq_equiv p hp σ σ.injective
  have hR₁R₂_classes :
      ∀ i j, R₁ i j ↔ R₂ (σ.symm i) (σ.symm j) := by
    aesop
  have h_card_eq :
      (Finset.univ.filter (fun j => ∃ i, i < j ∧ R₁ i j)).card =
      (Finset.univ.filter (fun j => ∃ i, i < j ∧ R₂ i j)).card := by
    apply card_filter_exists_lt_equiv_eq
    any_goals tauto
    · exact fun i j hij => hR₁_equiv.symm hij
    · exact fun i j l hij hjl => hR₁_equiv.trans hij hjl
    · exact fun i j hij => hR₂_equiv.symm hij
    · exact fun i j l hij hjl => hR₂_equiv.trans hij hjl
  convert h_card_eq.symm using 2 <;>
    simp +decide [Finset.mem_Iio]
  · grind +qlia
  · grind

/-! ### `gammaRow` positivity helpers -/

/-- `gammaRow` is always positive: it is an lcm of squarefree
numbers (or 1 if the index set is empty). -/
lemma GammaStructure.gammaRow_pos
    (Γ : GammaStructure k) (j : Fin k) :
    0 < Γ.gammaRow j := by
  refine Nat.pos_of_ne_zero fun h => ?_
  have := Γ.gammaRow_squarefree j
  simp_all

/-- The row product `gammaRow` is strictly non-zero. -/
lemma GammaStructure.gammaRow_ne_zero
    (Γ : GammaStructure k) (j : Fin k) :
    Γ.gammaRow j ≠ 0 := (Γ.gammaRow_pos j).ne'

/-- The real cast of `gammaRow` is strictly positive. -/
lemma GammaStructure.gammaRow_cast_pos
    (Γ : GammaStructure k) (j : Fin k) :
    (0 : ℝ) < (Γ.gammaRow j : ℝ) := Nat.cast_pos.mpr (Γ.gammaRow_pos j)

/-- The real cast of `gammaRow` is non-zero. -/
lemma GammaStructure.gammaRow_cast_ne_zero
    (Γ : GammaStructure k) (j : Fin k) :
    (Γ.gammaRow j : ℝ) ≠ 0 := (Γ.gammaRow_cast_pos j).ne'

/-- The cast of `gammaRow` to `ℝ` is at least 1. -/
lemma GammaStructure.gammaRow_cast_ge_one
    (Γ : GammaStructure k) (j : Fin k) :
    (Γ.gammaRow j : ℝ) ≥ 1 := Nat.one_le_cast.mpr (Γ.gammaRow_pos j)

/-- The global Gamma product `γ(Γ)` is strictly positive. -/
public lemma GammaStructure.gammaProd_pos
    (Γ : GammaStructure k) : 0 < Γ.gammaProd := Finset.prod_pos fun j _ => Γ.gammaRow_pos j

/-! ### Permutation invariance of `γ(Γ)` -/

-- See docs/proof_sketches.md for full proof sketch.
/-- The product `γ(Γ)` is invariant under permutations of the underlying Gamma structure. -/
theorem GammaStructure.gammaProd_perm_invariant
    (hk : 0 < k) (Γ : GammaStructure k)
    (σ : Equiv.Perm (Fin k))
    (_hσ : σ ⟨0, hk⟩ = ⟨0, hk⟩) :
    (Γ.permute σ).gammaProd = Γ.gammaProd := by
  apply Nat.factorization_inj _ _ _
  · exact Nat.ne_of_gt (GammaStructure.gammaProd_pos _)
  · exact Nat.ne_of_gt (GammaStructure.gammaProd_pos Γ)
  · ext p
    by_cases hp : Nat.Prime p <;>
      simp_all +decide only [factorization_gammaProd_eq, mem_Iio, not_false_eq_true,
        factorization_eq_zero_of_not_prime]
    convert GammaStructure.perm_count_eq Γ σ p hp using 1
    · simp +decide [GammaStructure.permute]; try rfl
    · simp +decide [Finset.mem_Iio]; try rfl

/-- Every entry `Γ.gamma i j` is bounded by `Γ.gammaProd`. When `i = j` the entry is zero
otherwise it divides `gammaRow (max i j)` which in turn divides `gammaProd`. -/
lemma GammaStructure.gamma_le_gammaProd
    (Γ : GammaStructure k) (i j : Fin k) :
    Γ.gamma i j ≤ Γ.gammaProd := by
  by_cases hij : i = j
  · simp +decide [ hij, Γ.diag ]
  · -- Since $i \neq j$, we have $Γ.gamma i j \mid Γ.gammaRow (max i j)$
    -- by definition of `gammaRow`.
    have h_div : Γ.gamma i j ∣ Γ.gammaRow (max i j) := by
      cases le_total i j
      · simp_all +decide only [gammaRow, sup_of_le_right]
        exact Finset.dvd_lcm ( Finset.mem_Iio.mpr ( lt_of_le_of_ne ‹_› hij ) )
      · simp_all +decide only [gammaRow, sup_of_le_left]
        exact Finset.dvd_lcm ( Finset.mem_Iio.mpr ( lt_of_le_of_ne ‹_› ( Ne.symm hij ) ) ) |>
          dvd_trans ( by simp +decide [ Γ.symm ] )
    exact Nat.le_of_dvd ( Γ.gammaProd_pos )
      ( dvd_trans h_div ( Finset.dvd_prod_of_mem _ ( Finset.mem_univ _ ) ) )

/-! ### Finset of Gamma structures with fixed product -/

/-- Two `GammaStructure`s are equal iff their `gamma` matrices agree. -/
public theorem GammaStructure.ext_iff {Γ₁ Γ₂ : GammaStructure k} :
    Γ₁ = Γ₂ ↔ Γ₁.gamma = Γ₂.gamma := by
  constructor
  · rintro rfl; rfl
  · intro h; cases Γ₁; cases Γ₂; simp_all

public instance : DecidableEq (GammaStructure k) := fun Γ₁ Γ₂ =>
  if h : Γ₁.gamma = Γ₂.gamma then
    .isTrue (GammaStructure.ext_iff.mpr h)
  else
    .isFalse (fun heq => h (GammaStructure.ext_iff.mp heq))

/-- The finite set of all `GammaStructure k` with `gammaProd = γ`. Every entry of such
a structure is bounded by `γ` (by `gamma_le_gammaProd`), so the carrier is a subset
of the finite set of `k × k` matrices with entries in `Finset.range (γ + 1)`. -/
@[expose]
public noncomputable def finsetGammaStructures (γ : ℕ) : Finset (GammaStructure k) :=
  let mats := (Fintype.piFinset fun _ : Fin k =>
      Fintype.piFinset fun _ : Fin k =>
        Finset.range (γ + 1)).filter fun mat =>
    (∀ i, mat i i = 0) ∧
    (∀ i j, mat i j = mat j i) ∧
    (∀ i j, i ≠ j → 0 < mat i j) ∧
    (∀ i j, i ≠ j → Squarefree (mat i j)) ∧
    (∀ i j l, i ≠ j → j ≠ l → i ≠ l → Nat.gcd (mat i j) (mat j l) ∣ mat i l) ∧
    (∏ j : Fin k, (Finset.Iio j).lcm fun i => mat i j) = γ
  mats.attach.image fun ⟨mat, hmat⟩ =>
    have hf := (Finset.mem_filter.mp hmat).2
    { gamma := mat
      diag := hf.1
      symm := hf.2.1
      pos := hf.2.2.1
      sqfree := hf.2.2.2.1
      compat := hf.2.2.2.2.1 }

/-- Simplification lemma extracting `Γ.gammaProd = γ` from membership in the finset. -/
@[simp]
public theorem mem_finsetGammaStructures {γ : ℕ} {Γ : GammaStructure k} :
    Γ ∈ finsetGammaStructures γ ↔ Γ.gammaProd = γ := by
  constructor
  · unfold finsetGammaStructures
    simp +zetaDelta only [ne_eq, mem_image, mem_attach, true_and, Subtype.exists, mem_filter,
      Fintype.mem_piFinset, mem_range, Order.lt_add_one_iff, forall_exists_index,
      forall_and_index] at *
    rintro x hx₁ hx₂ hx₃ hx₄ hx₅ hx₆ hx₇ rfl; exact hx₇
  · intro h
    simp +decide only [finsetGammaStructures, ne_eq, mem_image, mem_attach, true_and,
      Subtype.exists, ← h, mem_filter, Fintype.mem_piFinset, mem_range, Order.lt_add_one_iff]
    exact ⟨ Γ.gamma, ⟨ fun i j =>
      Γ.gamma_le_gammaProd i j, Γ.diag, Γ.symm, Γ.pos, Γ.sqfree, Γ.compat, rfl ⟩, rfl ⟩

/-! ### Bound on number of Gamma structures
(Lemma 3.1) -/

/-- Each off-diagonal entry of a `GammaStructure` divides `gammaProd`. -/
lemma GammaStructure.gamma_dvd_gammaProd (Γ : GammaStructure k) (i j : Fin k)
    (hij : i ≠ j) : Γ.gamma i j ∣ Γ.gammaProd := by
  unfold GammaStructure.gammaProd
  cases le_total i j <;> simp_all +decide only [ne_eq]
  · -- Since Γ.gamma i j divides Γ.gammaRow j and Γ.gammaRow j divides Γ.gammaProd, we have
    -- Γ.gamma i j ∣ Γ.gammaProd.
    have h_div : Γ.gamma i j ∣ Γ.gammaRow j := by
      exact Finset.dvd_lcm ( Finset.mem_Iio.mpr ( lt_of_le_of_ne ‹_› hij ) )
    exact dvd_trans h_div (Finset.dvd_prod_of_mem _ (Finset.mem_univ _))
  · apply dvd_trans _ ( Finset.dvd_prod_of_mem _ ( Finset.mem_univ i ) )
    exact Finset.dvd_lcm ( Finset.mem_Iio.mpr ( lt_of_le_of_ne ‹_› ( Ne.symm hij ) ) ) |>
      dvd_trans ( by simp +decide [ Γ.symm ] )

/-- The number of squarefree divisors of `n` is `2 ^ n.primeFactors.card`. -/
lemma card_squarefree_divisors (n : ℕ) (hn : n ≠ 0) :
    (n.divisors.filter Squarefree).card = 2 ^ n.primeFactors.card := by
  convert Nat.divisors_filter_squarefree hn using 1
  constructor <;> intro h
  · exact divisors_filter_squarefree hn
  · convert congr_arg Multiset.card h using 1
    simp +decide [ Nat.factors_eq ]

/-- Each off-diagonal entry of `Γ` with `Γ.gammaProd = γ` is a squarefree divisor of `γ`. -/
lemma GammaStructure.gamma_mem_squarefree_divisors {Γ : GammaStructure k} {γ : ℕ}
    (hΓ : Γ.gammaProd = γ) (i j : Fin k) (hij : i ≠ j) :
    Γ.gamma i j ∈ γ.divisors.filter Squarefree := by
  apply Finset.mem_filter.mpr ⟨ Nat.mem_divisors.mpr
    ⟨ hΓ ▸ GammaStructure.gamma_dvd_gammaProd Γ i j hij, _ ⟩, Γ.sqfree i j hij ⟩
  exact hΓ ▸ Nat.pos_iff_ne_zero.mp ( Γ.gammaProd_pos )

/-- The number of ordered pairs `(i, j)` with `i < j` in `Fin k` is `k.choose 2`. -/
lemma card_upper_triangular_pairs (k : ℕ) :
    (Finset.univ.filter (fun p : Fin k × Fin k => p.1 < p.2)).card = k.choose 2 := by
  rw [ Nat.choose_two_right ]
  convert Finset.card_filter ( fun p : Fin k × Fin k => p.1 < p.2 ) Finset.univ using 1
  rw [show (Finset.univ : Finset (Fin k × Fin k)) = Finset.univ ×ˢ Finset.univ from rfl,
    Finset.sum_product]
  rw [ ← Finset.sum_range_id ]
  simp +decide only [sum_boole, filter_lt_eq_Ioi, Fin.card_Ioi, cast_tsub, cast_id, cast_one]
  rw [ ← Finset.sum_range_reflect, Finset.sum_range ]

/-- The number of Gamma structures with a fixed product `γ(Γ) = γ` is bounded by
`(2 ^ k.choose 2) ^ γ.primeFactors.card` (Lemma 3.1). -/
public theorem countGammaStructures_le (γ : ℕ) (hγ : 0 < γ) :
    (finsetGammaStructures γ : Finset (GammaStructure k)).card ≤
      (2 ^ k.choose 2) ^ γ.primeFactors.card := by
  -- Each GammaStructure is determined by its upper triangular entries gamma(i,j) for i < j.
  have h_upper_triangular : ∀ Γ₁ Γ₂ : GammaStructure k, Γ₁.gammaProd =
    γ → Γ₂.gammaProd = γ → (∀ i j, i < j → Γ₁.gamma i j = Γ₂.gamma i j) → Γ₁ = Γ₂ := by
    intros Γ₁ Γ₂ hΓ₁ hΓ₂ h_eq
    apply GammaStructure.ext_iff.mpr
    ext i j
    by_cases hij : i = j
    generalize_proofs at *; (
    simp +decide [ hij, Γ₁.diag, Γ₂.diag ])
    cases lt_or_gt_of_ne hij <;>
      [ exact h_eq _ _ ‹_› ; exact Γ₁.symm i j ▸ Γ₂.symm i j ▸ h_eq _ _ ‹_› ]
  -- Define a map from GammaStructure k to (Fin k → Fin k → ℕ) by f(Γ) = Γ.gamma.
  set f : GammaStructure k → (Fin k → Fin k → ℕ) := fun Γ => Γ.gamma
  -- The image of `finsetGammaStructures γ` under `f` is a subset of the set of functions
  -- from `{p : Fin k × Fin k // p.1 < p.2}` to `(γ.divisors.filter Squarefree)`.
  have h_image : (Finset.image f (finsetGammaStructures γ)).card
    ≤ (Finset.univ.filter (fun p : Fin k × Fin k => p.1 < p.2)).prod
      (fun p => (γ.divisors.filter Squarefree).card) := by
    have h_image : (Finset.image f (finsetGammaStructures γ)).card
      ≤ (Finset.image (fun Γ : GammaStructure k => fun p : {p : Fin k × Fin k // p.1 < p.2} =>
        Γ.gamma p.val.1 p.val.2) (finsetGammaStructures γ)).card := by
      rw [ Finset.card_image_of_injOn, Finset.card_image_of_injOn ]
      · intros Γ₁ hΓ₁ Γ₂ hΓ₂ h_eq
        exact h_upper_triangular Γ₁ Γ₂ ( by simpa using hΓ₁ ) ( by simpa using hΓ₂ ) fun i j hij =>
          congr_fun h_eq ⟨ ( i, j ), hij ⟩
      · exact fun Γ₁ hΓ₁ Γ₂ hΓ₂ h => GammaStructure.ext_iff.mpr h
    refine le_trans h_image ?_
    apply le_trans ( Finset.card_le_card <| Finset.image_subset_iff.mpr _ ) _
    exact Finset.image ( fun p : { p : Fin k × Fin k // p.1 < p.2 } →
        { x : ℕ // x ∈ γ.divisors.filter Squarefree } => fun p' => p p' |>.1 ) ( Finset.univ )
    · simp +zetaDelta only [mem_finsetGammaStructures, mem_image, mem_univ, true_and] at *
      exact fun Γ hΓ => ⟨ fun p => ⟨ Γ.gamma p.val.1 p.val.2,
        GammaStructure.gamma_mem_squarefree_divisors hΓ p.val.1 p.val.2 ( ne_of_lt p.prop ) ⟩, rfl ⟩
    · apply le_trans ( Finset.card_image_le ) _
      simp +decide [ Fintype.card_subtype ]
  rw [ Finset.card_image_of_injOn ] at h_image
  · refine le_trans h_image ?_
    rw [ card_squarefree_divisors γ hγ.ne' ]
    rw [ Finset.prod_const, card_upper_triangular_pairs ]
    rw [ ← pow_mul, mul_comm, pow_mul ]
  · intro Γ₁ hΓ₁ Γ₂ hΓ₂ h_eq; specialize h_upper_triangular Γ₁ Γ₂; aesop

/-! ### Helper lemmas for Proposition 3.2 -/

-- See docs/proof_sketches.md for full proof sketch.
/-- The number of elements in an interval `[0, H]` that are pairwise congruent modulo `m`
is bounded by `H / m + 1`. -/
lemma card_set_pairwise_dvd_le {m : ℕ} (hm : 0 < m)
    (H : ℕ) (S : Finset ℤ)
    (hS : ∀ x ∈ S, 0 ≤ x ∧ x ≤ H)
    (hdvd : ∀ x ∈ S, ∀ y ∈ S,
      (m : ℤ) ∣ (x - y)) :
    (S.card : ℝ) ≤ (H : ℝ) / m + 1 := by
  field_simp
  norm_cast
  by_cases hS_empty : S = ∅
  · aesop
  · obtain ⟨x₀, hx₀⟩ : ∃ x₀ ∈ S, ∀ x ∈ S, x₀ ≤ x :=
      ⟨Finset.min' S (Finset.nonempty_of_ne_empty hS_empty),
       Finset.min'_mem _ _, fun x hx => Finset.min'_le _ _ hx⟩
    have h_map : S.image (fun x => (x - x₀) / m) ⊆ Finset.Icc 0 (H / m) :=
      Finset.image_subset_iff.mpr fun x hx =>
        Finset.mem_Icc.mpr ⟨Int.ediv_nonneg (sub_nonneg.mpr (hx₀.2 x hx)) (Nat.cast_nonneg _),
          Int.ediv_le_ediv (by positivity) (by linarith [hS x hx, hS x₀ hx₀.1])⟩
    have := Finset.card_le_card h_map
    simp_all only [Int.card_Icc, sub_zero, ge_iff_le]
    rw [Finset.card_image_of_injOn] at this
    · nlinarith [
        Int.toNat_of_nonneg (by positivity : 0 ≤ (H : ℤ) / m + 1),
        Int.mul_ediv_add_emod H m,
        Int.emod_nonneg H (by positivity : (m : ℤ) ≠ 0),
        Int.emod_lt_of_pos H (by positivity : (m : ℤ) > 0)]
    · intro x hx y hy
      have := hdvd x hx y hy; aesop

-- See docs/proof_sketches.md for full proof sketch.
/-- If two valid tuples agree on all indices `< j`, their difference at index `j` must be
divisible by the row product `gammaRow j`. -/
lemma gammaRow_dvd_diff_of_valid
    {Γ : GammaStructure (k + 1)}
    {h h' : Fin (k + 1) → ℤ}
    {j : Fin (k + 1)}
    (hgcd : ∀ i l, i ≠ l → Nat.gcd Γ.sqfreepart (Int.natAbs (h l - h i)) = Γ.gamma i l)
    (hgcd' : ∀ i l, i ≠ l → Nat.gcd Γ.sqfreepart (Int.natAbs (h' l - h' i)) = Γ.gamma i l)
    (heq : ∀ i : Fin (k + 1), i < j → h i = h' i) :
    (Γ.gammaRow j : ℤ) ∣ (h j - h' j) := by
  have h_div : ∀ i < j, (Γ.gamma i j : ℤ) ∣ (h j - h' j) := by
    intros i hi
    specialize hgcd i j; specialize hgcd' i j
    simp_all
    have := hgcd (ne_of_lt hi) ▸ Nat.gcd_dvd_right _ _
    have := hgcd' (ne_of_lt hi) ▸ Nat.gcd_dvd_right _ _
    simp_all +decide [← Int.natCast_dvd_natCast]
    simpa using dvd_sub ‹(Γ.gamma i j : ℤ) ∣ h j - h' i› this |> fun x => by simpa using x
  generalize_proofs at *
  convert Finset.lcm_dvd fun i hi => h_div i (Finset.mem_Iio.mp hi) using 1
  generalize_proofs at *
  simp [GammaStructure.gammaRow]
  induction (Finset.Iio j : Finset (Fin (k + 1))) using Finset.induction <;>
    simp_all +decide [Finset.lcm_insert]
  simp +decide [← ‹_›, GCDMonoid.lcm]

/-- Given a sequence of moduli `m_j`, if agreeing on the prefix `< j` forces differences at `j`
to be divisible by `m_j`, then the total number of such valid tuples bounded by `H` is at
most the product of `H / m_j + 1`. -/
lemma card_filtered_le_prod_of_fiber_dvd
    (n : ℕ) (H : ℕ) (m : Fin n → ℕ)
    (hm : ∀ j, 0 < m j)
    (S : Finset (Fin n → ℤ))
    (hS : ∀ h ∈ S, ∀ i, 0 ≤ h i ∧ h i ≤ H)
    (hfib : ∀ j : Fin n, ∀ h ∈ S, ∀ h' ∈ S,
      (∀ i : Fin n, i < j → h i = h' i) → (m j : ℤ) ∣ (h j - h' j)) :
    S.card ≤ ∏ j : Fin n, (H / m j + 1) := by
  induction n
  case zero => exact le_trans ( Finset.card_le_univ _ ) ( by norm_num )
  case succ n ih =>
    -- Let `proj` be the projection onto the first `n` coordinates.
    set proj : (Fin (Nat.succ n) → ℤ) → (Fin n → ℤ) := fun h => fun i => h (Fin.castSucc i)
    nontriviality
    -- Let `I := S.image proj`.
    set I := S.image proj with hI_def
    -- For each `g ∈ I`, the fiber `F_g := S.filter (fun h => proj h = g)` has cardinality
    -- at most `H / m (last n) + 1`.
    have h_fiber_card : ∀ g ∈ I,
        (S.filter (fun h => proj h = g)).card ≤ H / m (Fin.last n) + 1 := by
      intro g hg
      have h_fiber : ∀ h ∈ S.filter (fun h => proj h = g), ∀ h' ∈ S.filter (fun h => proj h = g),
          (m (Fin.last n) : ℤ) ∣ (h (Fin.last n) - h' (Fin.last n)) := by
        intros h hh h' hh'
        apply hfib (Fin.last n) h (Finset.mem_filter.mp hh).left h' (Finset.mem_filter.mp hh').left
        intro i hi
        have h1 := (Finset.mem_filter.mp hh).2
        have h2 := (Finset.mem_filter.mp hh').2
        have h1' := congr_fun h1 ⟨i, hi⟩
        have h2' := congr_fun h2 ⟨i, hi⟩
        exact h1'.trans h2'.symm
      have h_fiber_card :
          (Finset.image (fun h => h (Fin.last n)) (S.filter (fun h => proj h = g))).card
          ≤ H / m (Fin.last n) + 1 := by
        have h_fiber_card :
            ∀ x ∈ Finset.image (fun h => h (Fin.last n)) (S.filter (fun h => proj h = g)),
            ∀ y ∈ Finset.image (fun h => h (Fin.last n)) (S.filter (fun h => proj h = g)),
            (m (Fin.last n) : ℤ) ∣ (x - y) := by
          intro x hx y hy
          simp only [Finset.mem_image, Finset.mem_filter] at hx hy
          obtain ⟨a, ⟨haS, _⟩, rfl⟩ := hx
          obtain ⟨b, ⟨hbS, _⟩, rfl⟩ := hy
          exact h_fiber a (Finset.mem_filter.mpr ⟨haS, ‹_›⟩) b (Finset.mem_filter.mpr ⟨hbS, ‹_›⟩)
        have := @card_set_pairwise_dvd_le ( m ( Fin.last n ) ) ( hm ( Fin.last n ) ) H
            ( Finset.image ( fun h => h ( Fin.last n ) )
              ( Finset.filter ( fun h => proj h = g ) S ) ) ?_ ?_
        · rw [ div_add_one, le_div_iff₀ ] at this <;> norm_cast at *
          · nlinarith [ Nat.div_add_mod H ( m ( Fin.last n ) ), Nat.mod_lt H ( hm ( Fin.last n ) ),
              hm ( Fin.last n ) ]
          · exact hm _
          · linarith [ hm ( Fin.last n ) ]
        · intro x hx
          simp only [Finset.mem_image, Finset.mem_filter] at hx
          obtain ⟨a, ⟨haS, _⟩, rfl⟩ := hx
          exact hS a haS (Fin.last n)
        · exact h_fiber_card
      rwa [ Finset.card_image_of_injOn ] at h_fiber_card
      intro h hh h' hh' h_eq
      have hhinit := (Finset.mem_filter.mp hh).2
      have hh'init := (Finset.mem_filter.mp hh').2
      funext i
      by_cases hi : i.val < n
      · have hh1 := congr_fun hhinit ⟨i.val, hi⟩
        have hh2 := congr_fun hh'init ⟨i.val, hi⟩
        simp only [proj] at hh1 hh2
        have hcast : Fin.castSucc ⟨i.val, hi⟩ = i := by ext; simp
        rw [hcast] at hh1 hh2; linarith
      · have : i = Fin.last n := le_antisymm (Fin.le_last _) (by omega)
        rw [this]; exact h_eq
    -- By the induction hypothesis, we have $I.card \leq \prod_{j : Fin n} (H / m j + 1)$.
    have h_ind : I.card ≤ ∏ j : Fin n, (H / m (Fin.castSucc j) + 1) := by
      apply ih (fun j => m (Fin.castSucc j)) (fun j => hm (Fin.castSucc j)) I
      · intro a ha i
        simp only [I, Finset.mem_image] at ha
        obtain ⟨a', ha'S, rfl⟩ := ha
        exact hS a' ha'S (Fin.castSucc i)
      · intro j a ha b hb hab
        simp only [I, Finset.mem_image] at ha hb
        obtain ⟨a', ha'S, rfl⟩ := ha
        obtain ⟨b', hb'S, rfl⟩ := hb
        apply hfib (Fin.castSucc j) a' ha'S b' hb'S
        intro i hi
        have hlt : i.val < n := by
          have := Fin.val_lt_last (show Fin.castSucc j ≠ Fin.last n by simp [Fin.ext_iff]; omega)
          simp [Fin.lt_def] at hi; omega
        have := hab ⟨i.val, hlt⟩ (by simp only [Fin.lt_def, Fin.val_castSucc] at hi ⊢; exact hi)
        simp only [proj] at this
        have hcast : Fin.castSucc ⟨i.val, hlt⟩ = i := by ext; simp
        rw [hcast] at this; exact this
    have h_card_S : S.card = ∑ g ∈ I, (S.filter (fun h => proj h = g)).card := by
      exact Finset.card_eq_sum_card_image proj S
    rw [ h_card_S, Fin.prod_univ_castSucc ]
    exact le_trans ( Finset.sum_le_sum h_fiber_card )
      ( by simpa [ mul_comm ] using Nat.mul_le_mul_right ( H / m ( Fin.last n ) + 1 ) h_ind )

/-! ### Upper bound on `M_Γ(H)` (Proposition 3.2) -/

/-- Proposition 3.2: The number of tuples consistent with a Gamma structure `Γ` bounded by `H`
is at most `∏ (H / γ_j + 1)`. -/
theorem countTuples_bound_prop
    (Γ : GammaStructure (k + 1)) (H : ℕ) :
    (countTuplesWithGamma Γ H : ℝ) ≤ ∏ i : Fin k, ((H : ℝ) / (Γ.gammaRow i.succ) + 1) := by
  have h_card :
      (countTuplesWithGamma Γ H : ℝ) ≤ ∏ j : Fin k, (H / Γ.gammaRow (Fin.succ j) + 1) := by
    set τ : (Fin (k + 1) → ℤ) → (Fin k → ℤ) := fun h i => h (Fin.succ i)
    set S :=
      (Fintype.piFinset fun _ : Fin (k + 1) => Finset.Icc 0 (H : ℤ)).filter (fun h =>
        h 0 = 0 ∧ (∀ i j, i ≠ j → h i ≠ h j) ∧
        ∀ i j, i ≠ j → Nat.gcd Γ.sqfreepart (Int.natAbs (h j - h i)) = Γ.gamma i j) |>
      Finset.image τ
    have h_card_S: S.card ≤ ∏ j : Fin k, (H / Γ.gammaRow (Fin.succ j) + 1) := by
      apply card_filtered_le_prod_of_fiber_dvd k H
        (fun j => Γ.gammaRow (Fin.succ j)) (fun j => Γ.gammaRow_pos (Fin.succ j)) S
      · grind
      · intros j h hh h' hh' h_eq
        obtain ⟨h'', hh'', rfl⟩ := Finset.mem_image.mp hh
        obtain ⟨h''', hh''', rfl⟩ := Finset.mem_image.mp hh'
        apply gammaRow_dvd_diff_of_valid
        · aesop
        · aesop
        · intro i hi
          induction i using Fin.inductionOn <;> aesop
    rw [Finset.card_image_of_injOn] at h_card_S
    · exact_mod_cast h_card_S
    · intro h₁ hh₁ h₂ hh₂ h_eq
      simp_all +decide only [ne_eq, Fin.forall_fin_succ, not_true_eq_false, implies_true, true_and,
        Fin.succ_ne_zero, not_false_eq_true, forall_const, Fin.succ_inj, sub_self, Int.natAbs_zero,
        Nat.gcd_zero_right, IsEmpty.forall_iff, coe_filter, Fintype.mem_piFinset, mem_Icc,
        Set.mem_setOf_eq, funext_iff]
      exact h_eq
  refine le_trans h_card ?_
  norm_num [Finset.prod_add]
  refine Finset.sum_le_sum fun s hs => ?_
  rw [← Finset.prod_const, ← Finset.prod_div_distrib]
  exact Finset.prod_le_prod (fun _ _ => by positivity) fun i _ => by
    rw [le_div_iff₀ (Γ.gammaRow_cast_pos i.succ)]
    exact_mod_cast Nat.div_mul_le_self H (Γ.gammaRow i.succ)

/-- Corollary 3.3: If all row products `γ_j` are bounded by `H`, then the tuple count is
bounded by `2^k * H^k / γ(Γ)`. -/
public theorem countTuples_bound_small_gamma
    (Γ : GammaStructure (k + 1)) (H : ℕ)
    (hsmall : ∀ i : Fin k, Γ.gammaRow i.succ ≤ H) :
    (countTuplesWithGamma Γ H : ℝ) ≤ 2 ^ k * (H : ℝ) ^ k / Γ.gammaProd := by
  rw [le_div_iff₀]
  · have h_bound :
      (countTuplesWithGamma Γ H : ℝ) * (∏ i : Fin k, Γ.gammaRow i.succ) ≤ (2 * H : ℝ) ^ k := by
      have h_bound :
        (countTuplesWithGamma Γ H : ℝ) ≤ ∏ i : Fin k, ((H : ℝ) / (Γ.gammaRow i.succ) + 1) :=
          countTuples_bound_prop Γ H
      have h_bound :
          (∏ i : Fin k, ((H : ℝ) / (Γ.gammaRow i.succ) + 1)) *
            (∏ i : Fin k, Γ.gammaRow i.succ) ≤ (∏ i : Fin k, (2 * H : ℝ)) := by
        rw [Nat.cast_prod, ← Finset.prod_mul_distrib]
        exact Finset.prod_le_prod (fun _ _ => mul_nonneg
          (add_nonneg (div_nonneg (Nat.cast_nonneg _) (Nat.cast_nonneg _)) zero_le_one)
          (Nat.cast_nonneg _))
          (fun i _hi => by
            nlinarith [ Γ.gammaRow_cast_ge_one i.succ,
              div_mul_cancel₀ (H : ℝ) (Γ.gammaRow_cast_ne_zero i.succ),
              show (Γ.gammaRow i.succ : ℝ) ≤ H from mod_cast hsmall i])
      exact le_trans (mul_le_mul_of_nonneg_right ‹_› <| Nat.cast_nonneg _) <| h_bound.trans <| by
        norm_num
    convert h_bound using 1
    norm_num [mul_pow, Fin.prod_univ_succ]
    · unfold GammaStructure.gammaProd GammaStructure.gammaRow
      norm_cast
      simp +decide only [Fin.prod_univ_succ]
      simp +decide only [Finset.lcm]
      exact Or.inl (by change 1 * _ = _; rw [one_mul])
    · rw [mul_pow]
  · exact Nat.cast_pos.mpr (GammaStructure.gammaProd_pos Γ)

end PoissonCRT
