/-
Copyright (c) 2026 Fernando Portela. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Fernando Portela
-/

/-
Portions of this file were generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.28.0
Mathlib version: 8f9d9cff6bd728b17a24e163c9402775d9e6a365

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

import PoissonViaCRT.CommonTactics
import PoissonViaCRT.MainDefs


/-!
# Poisson Statistics via the Chinese Remainder Theorem — Definitions

Formalization of key definitions from "Poisson statistics via the Chinese remainder theorem"
by Andrew Granville and Pär Kurlberg (arXiv:math/0412135v2).

## Main Definitions

* `PoissonCRT.density`, `PoissonCRT.avgSpacing`: The density `r_q` and average spacing `s_q`.
* `PoissonCRT.GammaStructure`: The combinatorial data `Γ = {γᵢⱼ}` from §3.1.

## References

* [A. Granville, P. Kurlberg, *Poisson statistics via the Chinese remainder theorem*]
  [arXiv:math/0412135v2]
-/

open Finset BigOperators Classical

namespace PoissonCRT

/-- Membership in the CRT subset is equivalent to all local conditions being satisfied. -/
@[simp]
public theorem mem_crtSubset_iff {q : ℕ} [NeZero q] {Ω : ∀ p : ℕ, Finset (ZMod p)}
    {x : ZMod q} :
    x ∈ crtSubset q Ω ↔
      ∀ p, ∀ hp : p ∈ q.primeFactors,
        ZMod.castHom (Nat.dvd_of_mem_primeFactors hp) (ZMod p) x ∈ Ω p := by
  simp [crtSubset]

/-! ### Density and average spacing -/

/-- The density `r_q = |Ω_q| / q`, the probability a random element belongs to `Ω_q`. -/
@[expose]
public noncomputable def density {q : ℕ} [NeZero q] (Ω : Finset (ZMod q)) : ℚ :=
  Ω.card / q

/-- The average spacing `s_q = q / |Ω_q|` between consecutive elements of `Ω_q`. -/
@[expose]
public noncomputable def avgSpacing {q : ℕ} [NeZero q] (Ω : Finset (ZMod q)) : ℚ :=
  q / Ω.card

/-! ### Poisson distribution definition (§1, §2)

The spacings of elements in `Ω_{q_n}` become Poisson distributed if for all `k ≥ 2` and
all boxes `X ∈ 𝔹_k`:
$$R_k(X, \Omega_{q_n}) \to \operatorname{vol}(X) \text{ as } n \to \infty.$$
-/

/-- The spacings of a sequence of subsets `Ω_{q_n}` become Poisson distributed if the
`k`-level correlation converges to the volume of the test box for all `k` and all boxes. -/
def IsPoissonDistributed
    (Q : ℕ → ℕ) [∀ n, NeZero (Q n)]
    (Ω : ∀ n, Finset (ZMod (Q n))) : Prop :=
  ∀ (k : ℕ) (_ : 2 ≤ k) (X : Box (k - 1)),
    Filter.Tendsto (fun n => kCorrelation (Ω n) X) Filter.atTop
      (nhds X.volume)

/-- The radical of a natural number: the product of its distinct prime factors. -/
@[expose]
public def radical (n : ℕ) : ℕ :=  ∏ p ∈ n.primeFactors, p

/-- A `GammaStructure` encodes the combinatorial data `Γ = {γᵢⱼ}` from §3.1.
Given `k` indices `{0, …, k-1}`, a Gamma structure assigns to each unordered pair
`{i, j}` a positive squarefree integer `γᵢⱼ = γⱼᵢ`, subject to the compatibility condition
`gcd(γᵢⱼ, γⱼₗ) | γᵢₗ` for distinct `i, j, l`. -/
public structure GammaStructure (k : ℕ) where
  /-- The values `γᵢⱼ` for `i ≠ j`. We set `γᵢᵢ = 0` by convention. -/
  gamma : Fin k → Fin k → ℕ
  /-- Diagonal is zero. -/
  diag : ∀ i, gamma i i = 0
  /-- Symmetry: `γᵢⱼ = γⱼᵢ`. -/
  symm : ∀ i j, gamma i j = gamma j i
  /-- Positivity: `γᵢⱼ > 0` when `i ≠ j`. -/
  pos : ∀ i j, i ≠ j → 0 < gamma i j
  /-- Squarefreeness: each `γᵢⱼ` is squarefree when `i ≠ j`. -/
  sqfree : ∀ i j, i ≠ j → Squarefree (gamma i j)
  /-- Compatibility: `gcd(γᵢⱼ, γⱼₗ) | γᵢₗ` for distinct `i, j, l` (equation ✱). -/
  compat : ∀ i j l, i ≠ j → j ≠ l → i ≠ l →
    Nat.gcd (gamma i j) (gamma j l) ∣ gamma i l

/-- The value `γⱼ := lcm_{0 ≤ i < j} γᵢⱼ` from §3.1. -/
@[expose]
public def GammaStructure.gammaRow {k : ℕ} (Γ : GammaStructure k) (j : Fin k) : ℕ :=
  (Finset.Iio j).lcm fun i => Γ.gamma i j

/-- The product `γ(Γ) := γ₁ · γ₂ · ⋯ · γₖ₋₁` from §3.1. -/
@[expose]
public def GammaStructure.gammaProd {k : ℕ} (Γ : GammaStructure k) : ℕ :=
  ∏ j : Fin k, Γ.gammaRow j

/-- `c(Γ)` is the radical (squarefree part) of `γ(Γ)`:
the product of primes dividing `γ(Γ)`. -/
@[expose]
public def GammaStructure.sqfreepart {k : ℕ} (Γ : GammaStructure k) : ℕ :=
  radical Γ.gammaProd

/-! ### The counting function `M_Γ(H)` from §3.1 -/

/-- `M_Γ(H)` counts the number of tuples `(h₀ = 0, h₁, …, hₖ₋₁)` with `0 ≤ hᵢ ≤ H`,
all `hᵢ` distinct, and the gcd structure matching `Γ`. -/
@[expose]
public noncomputable def countTuplesWithGamma (Γ : GammaStructure (k + 1)) (H : ℕ) : ℕ :=
  ((Fintype.piFinset fun _ : Fin (k + 1) => Finset.Icc 0 (H : ℤ)).filter fun h =>
    h 0 = 0 ∧
    (∀ i j, i ≠ j → h i ≠ h j) ∧
    ∀ i j, i ≠ j →
      Nat.gcd Γ.sqfreepart (Int.natAbs (h j - h i)) = Γ.gamma i j).card

/-! ### The Gamma structure induced by a tuple (§3.1) -/

/-- Given a squarefree positive integer `c` and distinct integers `h₀ = 0, h₁, …, hₖ₋₁`,
define `γᵢⱼ(h) := gcd(c, |hⱼ - hᵢ|)` for `i ≠ j` and `γᵢᵢ = 0`. -/
@[expose]
public def gammaOfTuple (c : ℕ) (h : Fin k → ℤ) (i j : Fin k) : ℕ :=
  if i = j then 0 else Nat.gcd c (Int.natAbs (h j - h i))

/-- The diagonal entries of `gammaOfTuple` are zero by definition. -/
@[simp]
public theorem gammaOfTuple_self (c : ℕ) (h : Fin k → ℤ) (i : Fin k) :
    gammaOfTuple c h i i = 0 := by
  simp [gammaOfTuple]

/-- The off-diagonal entries of `gammaOfTuple` equal the GCD. -/
public theorem gammaOfTuple_of_ne (c : ℕ) (h : Fin k → ℤ) {i j : Fin k} (hij : i ≠ j) :
    gammaOfTuple c h i j = Nat.gcd c (Int.natAbs (h j - h i)) := by
  simp [gammaOfTuple, hij]

/--
The gamma structure induced by a squarefree integer `c` and a tuple `h` with
distinct entries. Each off-diagonal entry is `gcd(c, |h j - h i|)`.
-/
@[expose]
public def GammaStructure.ofTuple (c : ℕ) (hc : Squarefree c) (h : Fin k → ℤ)
    (h_dist : ∀ i j, i ≠ j → h i ≠ h j) : GammaStructure k where
  gamma := gammaOfTuple c h
  diag := gammaOfTuple_self c h
  symm := fun i j => by
    simp only [gammaOfTuple]
    split_ifs with h1 h2 h2
    · rfl
    · exact absurd h1.symm h2
    · exact absurd h2.symm h1
    · congr 1; rw [show h i - h j = -(h j - h i) from by ring, Int.natAbs_neg]
  pos := fun i j hij => by
    rw [gammaOfTuple_of_ne c h hij]
    exact Nat.pos_of_ne_zero (by
      intro heq
      rw [Nat.gcd_eq_zero_iff] at heq
      exact h_dist i j hij
        (by have := heq.2; rw [Int.natAbs_eq_zero, sub_eq_zero] at this; exact this.symm))
  sqfree := fun i j hij => by
    rw [gammaOfTuple_of_ne c h hij]
    exact hc.gcd_left _
  compat := fun i j l hij hjl hil => by
    simp only [gammaOfTuple_of_ne c h hij, gammaOfTuple_of_ne c h hjl,
      gammaOfTuple_of_ne c h hil]
    apply Nat.dvd_gcd ( Nat.dvd_trans ( Nat.gcd_dvd_left _ _ ) ( Nat.gcd_dvd_left _ _ ) ) _
    convert Int.dvd_natAbs.mpr ( Int.dvd_add ( Int.gcd_dvd_right _ _ |> Int.dvd_trans <|
      Int.natCast_dvd.mpr <| Nat.gcd_dvd_right _ _ ) ( Int.gcd_dvd_right _ _ |> Int.dvd_trans <|
        Int.natCast_dvd.mpr <| Nat.gcd_dvd_right _ _ ) ) using 1 ; ring_nf
    rotate_left
    exact 0
    exact 0
    norm_num [ Int.gcd, Int.natAbs_mul ]
    rw [ show -h i + h l = ( h j - h i ) + ( -h j + h l ) by ring ]
    exact Int.natAbs_dvd_natAbs.mpr ( dvd_add
      ( Int.natCast_dvd.mpr ( Nat.dvd_trans ( Nat.gcd_dvd_left _ _ ) ( Nat.gcd_dvd_right _ _ ) ) )
      ( Int.natCast_dvd.mpr ( Nat.dvd_trans ( Nat.gcd_dvd_right _ _ ) ( Nat.gcd_dvd_right _ _ ) ) )
    )

/-- `M_γ(H)` sums `M_Γ(H)` over all `Γ` with `γ(Γ) = γ` (equation ✱₀ from §3.1). -/
@[expose]
public noncomputable def countTuplesWithGammaProd (k : ℕ) (γ H : ℕ) : ℕ :=
  Set.ncard {h : Fin (k + 1) → ℤ |
    h 0 = 0 ∧
    (∀ i j, i ≠ j → h i ≠ h j) ∧
    (∀ i, 0 ≤ h i ∧ h i ≤ H) ∧
    ∃ Γ : GammaStructure (k + 1), Γ.gammaProd = γ ∧
      ∀ i j, i ≠ j → Nat.gcd Γ.sqfreepart (Int.natAbs (h j - h i)) = Γ.gamma i j}

/-! ### Error term decomposition (§3.2) -/

/-- The error term `ε_k(h, p)` is defined by `N_k(h, Ω_p) = r_p^{k-1} · |Ω_p| · (1 + ε_k(h, p))`.
We represent this as the relative deviation of the tuple count from its expected value. -/
@[expose]
public noncomputable def epsilonError {p : ℕ} [NeZero p] (Ω : Finset (ZMod p))
    (h : Fin k → ZMod p) : ℝ :=
  if Ω.card = 0 then 0
  else (tupleCount Ω h : ℝ) / ((Ω.card : ℝ) ^ k / (p : ℝ) ^ (k - 1)) - 1

/-- `lambdaExponent k` is less than or equal to 1. -/
public lemma lambdaExponent_le_one (k : ℕ) : lambdaExponent k ≤ 1 := by
  unfold lambdaExponent
  split_ifs
  · rfl
  · next h1 h2 =>
    have : Real.sqrt 17 ≤ 5 := by
      have h5 : (5 : ℝ) = Real.sqrt 25 := by norm_num
      rw [h5]
      exact Real.sqrt_le_sqrt (by norm_num)
    linarith
  · next h1 h2 h3 => linarith
  · next h1 h2 h3 =>
    have hk : 4 ≤ k := by omega
    have hk_r : (4 : ℝ) ≤ (k : ℝ) := by exact_mod_cast hk
    have h1 : (1 : ℝ) ≤ (k : ℝ) - 1 := by linarith
    have hpos : (0 : ℝ) ≤ (k : ℝ) - 1 := by linarith
    exact div_le_one_of_le₀ h1 hpos

/-! ### Gamma product of a box point -/

/-- The gamma product of a box point `h ∈ ℤ^n` with respect to a set `T`
of primes. This is the gamma product of the `(n+1)`-tuple `(0, h₁, …, hₙ)`
with respect to `c = ∏_{p ∈ T} p`:
  `γ(h) = ∏_{j=0}^{n} lcm_{i<j} gcd(c, |h'_j − h'_i|)`
where `h' = Fin.cons 0 h`.

This function is defined for *any* `h`, without requiring distinct entries.
When `h` arises from an `inScaledBox` lattice point, the entries of
`Fin.cons 0 h` are automatically distinct (by `inScaledBox_strictMono`),
and this function agrees with `(GammaStructure.ofTuple c hc h' h_dist).gammaProd`. -/
@[expose]
public noncomputable def gammaProdOfBoxPoint (T : Finset ℕ) {n : ℕ} (h : Fin n → ℤ) : ℕ :=
  let c := ∏ p ∈ T, p
  let h' := Fin.cons (0 : ℤ) h
  ∏ j : Fin (n + 1), (Finset.Iio j).lcm
    (fun i => Nat.gcd c (Int.natAbs (h' j - h' i)))

end PoissonCRT
