/-
Copyright (c) 2026 Fernando Portela. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Fernando Portela
-/

/-
Portions of this file were generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.28.0
Mathlib version: 8f9d9cff6bd728b17a24e163c9402775d9e6a365

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

module
public import Mathlib.Analysis.SpecialFunctions.Pow.Real
import Mathlib.Analysis.PSeries

set_option linter.unusedVariables false

/-!
# Euler Weight Bounds

This file contains bounds on local Euler weight factors used in the
spatial synthesis step of the Möbius deviation bound. The Euler
weights arise from the inclusion-exclusion decomposition over
squarefree divisors and control the multiplicative contribution
of each prime factor to the residue multiplicity estimate.

## Main results

* `omega_card_le_prime`: `|Ω_p| ≤ p` for prime factors `p` of `q`.
* `omega_ratio_pow_le_one`: `(|Ω_p| / p)^k ≤ 1`.
* `local_factor_le_k_rpow`: Each local factor
  `p · (1 − |Ω_p|/p) · p^{−ε} ≤ k · p^{−ε}`.
* `prod_local_factor_le`: Product version of the above bound.
* `combinedEulerWeight`: The combined Euler weight `(1 − |Ω_p|/p) · p^{−ε}`.
* `tail_sum_decay`: Tail-sum decay via Rankin's trick.
-/

open Finset BigOperators Classical

namespace PoissonCRT

/-- For `p` a prime factor of `q`, the residue set satisfies
`(Ω p).card ≤ p`. This is the basic cardinality bound used in
the Euler weight estimates for the spatial synthesis. -/
public lemma omega_card_le_prime (q : ℕ) [NeZero q]
    (Ω : ∀ p : ℕ, Finset (ZMod p)) (p : ℕ) (hp : p ∈ q.primeFactors) :
    ((Ω p).card : ℝ) ≤ (p : ℝ) := by
  haveI : Fact p.Prime := ⟨Nat.prime_of_mem_primeFactors hp⟩
  exact_mod_cast le_trans (Finset.card_le_univ (Ω p)) (by simp +decide [ZMod.card])

/-- The residue ratio `|Ω_p| / p` is at most `1`, so its
`k`-th power is also at most `1`. Used to control the
Euler weight in the residue multiplicity bounds. -/
lemma omega_ratio_pow_le_one (q : ℕ) [NeZero q]
    (Ω : ∀ p : ℕ, Finset (ZMod p)) (k : ℕ) (p : ℕ) (hp : p ∈ q.primeFactors) :
    ((Ω p).card / (p : ℝ)) ^ k ≤ 1 := by
  apply pow_le_one₀ (div_nonneg (Nat.cast_nonneg _) (Nat.cast_nonneg _))
  exact div_le_one_of_le₀ (omega_card_le_prime q Ω p hp) (Nat.cast_nonneg _)

/-- Each local Euler weight factor
`p · (1 − |Ω_p| / p) · p^{−ε}` is bounded above by
`k · p^{−ε}`, using the spacing hypothesis `hrp`. This
pointwise bound feeds into the product bound
`prod_local_factor_le`. -/
lemma local_factor_le_k_rpow (p : ℕ) (ε : ℝ) (k : ℕ)
    (Ω : ∀ p : ℕ, Finset (ZMod p))
    (hp : p.Prime)
    (hrp : 1 - (Ω p).card / (p : ℝ) ≤ k / (p : ℝ)) :
    (p : ℝ) * (1 - (Ω p).card / (p : ℝ)) * (p : ℝ) ^ (-ε) ≤
      (k : ℝ) * (p : ℝ) ^ (-ε) := by
  exact mul_le_mul_of_nonneg_right ( by convert mul_le_mul_of_nonneg_left hrp ( Nat.cast_nonneg p ) using 1 ; rw [ mul_div_cancel₀ _ ( Nat.cast_ne_zero.mpr hp.ne_zero ) ] ) ( Real.rpow_nonneg ( Nat.cast_nonneg p ) _ )

/-- Product version of `local_factor_le_k_rpow`: the product
over a subset `T ⊆ q.primeFactors` of the local Euler weight
factors is bounded by `∏ p ∈ T, k · p^{−ε}`. This is the key
multiplicative estimate used in the inclusion-exclusion
deviation bound. -/
public lemma prod_local_factor_le (T : Finset ℕ) (ε : ℝ) (k : ℕ) (q : ℕ)
    (Ω : ∀ p : ℕ, Finset (ZMod p))
    (hT_sub : T ⊆ q.primeFactors)
    (hrp : ∀ (p : ℕ), p.Prime → 1 - (Ω p).card / (p : ℝ) ≤ k / (p : ℝ)) :
    ∏ p ∈ T, ((p : ℝ) * (1 - (Ω p).card / (p : ℝ)) * (p : ℝ) ^ (-ε)) ≤
      ∏ p ∈ T, ((k : ℝ) * (p : ℝ) ^ (-ε)) := by
  apply Finset.prod_le_prod;
  · intro p hp;
    refine mul_nonneg ( mul_nonneg ( Nat.cast_nonneg _ ) ?_ ) ( Real.rpow_nonneg ( Nat.cast_nonneg _ ) _ );
    have := Nat.prime_of_mem_primeFactors ( hT_sub hp );
    haveI := Fact.mk this; exact sub_nonneg_of_le ( div_le_one_of_le₀ ( mod_cast le_trans ( Finset.card_le_univ _ ) ( by norm_num ) ) ( Nat.cast_nonneg _ ) ) ;
  · exact fun p hp => mul_le_mul_of_nonneg_right ( by have := hrp p ( Nat.prime_of_mem_primeFactors ( hT_sub hp ) ) ; rw [ le_div_iff₀ ( Nat.cast_pos.mpr ( Nat.Prime.pos ( Nat.prime_of_mem_primeFactors ( hT_sub hp ) ) ) ) ] at this; nlinarith ) ( Real.rpow_nonneg ( Nat.cast_nonneg p ) _ )

/-! ## Combined Euler Weight and Tail-Sum Decay

These definitions and lemmas were relocated from `GammaDeviationSynthesis.lean`
(which is now a dead-end module) so that `MobiusSynthesis.lean` can drop that import.
-/

/-- **Combined Euler weight.** The weight `(1 − |Ω_p|/p) · p^{−ε}` assigned
to each prime `p` in the Rankin-trick tail-sum bound. With the spacing
hypothesis `1 − |Ω_p|/p ≤ k/p`, this is `O(k · p^{−1−ε})`, so the
associated Euler product converges. -/
@[expose]
public noncomputable def combinedEulerWeight (ε : ℝ) (_k : ℕ)
    (Ω : ∀ p : ℕ, Finset (ZMod p)) (p : ℕ) : ℝ :=
  (1 - (Ω p).card / (p : ℝ)) * (p : ℝ) ^ (-ε)

/-- `combinedEulerWeight` is nonneg for primes `p`, since `|Ω_p| ≤ p`
(giving `1 − |Ω_p|/p ≥ 0`) and `p^{−ε} ≥ 0`. -/
public lemma combinedEulerWeight_nonneg (ε : ℝ) (k : ℕ) (Ω : ∀ p : ℕ, Finset (ZMod p))
    (p : ℕ) (hp : p.Prime) :
    0 ≤ combinedEulerWeight ε k Ω p := by
  refine mul_nonneg ?_ (Real.rpow_nonneg (Nat.cast_nonneg _) _)
  haveI := Fact.mk hp
  exact sub_nonneg.2 <| div_le_one_of_le₀ (mod_cast le_trans (Finset.card_le_univ _) <| by norm_num)
    <| Nat.cast_nonneg _

/-- With the spacing hypothesis, `combinedEulerWeight ≤ k · p^{−(1+ε)}`. -/
lemma combinedEulerWeight_le (ε : ℝ) (hε : 0 < ε) (k : ℕ) (Ω : ∀ p : ℕ, Finset (ZMod p))
    (hrp : ∀ p, p.Prime → 1 - (Ω p).card / (p : ℝ) ≤ k / (p : ℝ))
    (p : ℕ) (hp : p.Prime) :
    combinedEulerWeight ε k Ω p ≤ k * (p : ℝ) ^ (-(1 + ε)) := by
  convert mul_le_mul_of_nonneg_right (hrp p hp)
    (Real.rpow_nonneg (Nat.cast_nonneg p) (-ε)) using 1 ; ring_nf;
  rw [show (-1 - ε : ℝ) = -1 + (-ε) by ring, Real.rpow_add (Nat.cast_pos.mpr hp.pos),
    Real.rpow_neg_one]
  ring

/-- **Rankin's trick for powerset sums.**
For a nonneg weight function `w` on a finset `S`, the sum over subsets `T`
whose product exceeds `s` is bounded by `s^{−α}` times the Euler product
`∏_{p ∈ S} (1 + w(p) · p^α)`. -/
lemma rankin_powerset_bound (S : Finset ℕ) (w : ℕ → ℝ)
    (hw : ∀ i ∈ S, 0 ≤ w i) (s : ℝ) (hs : 0 < s) (α : ℝ) (hα : 0 < α) :
    ∑ T ∈ S.powerset.filter (fun (T : Finset ℕ) => ¬(∏ i ∈ T, (i : ℝ) ≤ s)),
      ∏ i ∈ T, w i ≤
    s ^ (-α) * ∏ i ∈ S, (1 + w i * (i : ℝ) ^ α) := by
  have h_term : ∀ T ∈ S.powerset, ¬(∏ i ∈ T, (i : ℝ) ≤ s) →
      (∏ i ∈ T, w i) ≤ s ^ (-α) * ∏ i ∈ T, (w i * (i : ℝ) ^ α) := by
    intro T hT hts
    have h_prod : (∏ i ∈ T, (i : ℝ)) ^ α ≥ s ^ α := by
      exact Real.rpow_le_rpow hs.le (le_of_not_ge hts) hα.le
    rw [Finset.prod_mul_distrib, Real.rpow_neg hs.le]
    rw [← div_eq_inv_mul, le_div_iff₀ (by positivity)]
    exact mul_le_mul_of_nonneg_left
      (by rwa [Real.finset_prod_rpow _ _ fun x _ => Nat.cast_nonneg x])
      (Finset.prod_nonneg fun x hx => hw x (Finset.mem_powerset.mp hT hx))
  refine le_trans (Finset.sum_le_sum fun T hT =>
    h_term T (Finset.mem_filter.mp hT |>.1) (Finset.mem_filter.mp hT |>.2)) ?_
  simp +decide [Finset.mul_sum _ _ _, add_comm, Finset.prod_add]
  exact Finset.sum_le_sum_of_subset_of_nonneg (Finset.filter_subset _ _)
    fun _ _ _ => mul_nonneg (Real.rpow_nonneg hs.le _)
      (Finset.prod_nonneg fun _ _ => mul_nonneg (hw _ (Finset.mem_powerset.mp ‹_› ‹_›))
        (Real.rpow_nonneg (Nat.cast_nonneg _) _))

/-- `∏ (1 + f i) ≤ exp(∑ f i)` for nonneg `f`. -/
lemma prod_one_add_le_exp_sum (S : Finset ℕ) (f : ℕ → ℝ)
    (hf : ∀ i ∈ S, 0 ≤ f i) :
    ∏ i ∈ S, (1 + f i) ≤ Real.exp (∑ i ∈ S, f i) := by
  rw [Real.exp_sum]
  exact Finset.prod_le_prod (fun _ _ => add_nonneg zero_le_one (hf _ ‹_›))
    fun _ _ => by rw [add_comm]; exact Real.add_one_le_exp _

/-- **Tail-sum decay.**
The sum over nonempty subsets `T ⊆ q.primeFactors` with `∏ T > s` of the
combined Euler weight decays as `O(s^{−ε/2})`. This is the classic Rankin
trick applied to the deviation Euler product.

The constant `K = exp(k · ζ(1+ε/2))` is independent of `q` and `s`.
The proof uses:
1. Rankin's trick to introduce the factor `s^{−ε/2}`.
2. The bound `1 + x ≤ exp(x)` to convert the Euler product to `exp(sum)`.
3. The spacing hypothesis to bound `tailEulerWeight ≤ k · p^{−(1+ε/2)}`.
4. Summability of `p^{−(1+ε/2)}` (since `1 + ε/2 > 1`). -/
public lemma tail_sum_decay (ε : ℝ) (hε : 0 < ε) (k : ℕ) (hk : 2 ≤ k)
    (Ω : ∀ p : ℕ, Finset (ZMod p))
    (hrp : ∀ p, p.Prime → 1 - (Ω p).card / (p : ℝ) ≤ k / (p : ℝ)) :
    ∃ K : ℝ, 0 < K ∧ ∀ (q : ℕ) [NeZero q] (s : ℝ) (_ : 1 ≤ s),
      ∑ T ∈ (q.primeFactors.powerset.filter (· ≠ ∅)).filter
            (fun (T : Finset ℕ) => ¬((∏ p ∈ T, (p : ℝ)) ≤ s)),
        ∏ p ∈ T, combinedEulerWeight ε k Ω p ≤
        K * s ^ (-(ε / 2)) := by
  refine ⟨Real.exp (k * ∑' n : ℕ, (n : ℝ) ^ (-(1 + ε / 2))), ?_, ?_⟩
  · positivity
  · intro q hq s hs
    have h_rankin : ∑ T ∈ (q.primeFactors.powerset.filter
        (fun (T : Finset ℕ) => ¬(∏ p ∈ T, (p : ℝ) ≤ s))),
        ∏ p ∈ T, combinedEulerWeight ε k Ω p ≤
        s ^ (-(ε / 2)) * ∏ p ∈ q.primeFactors,
          (1 + combinedEulerWeight ε k Ω p * (p : ℝ) ^ (ε / 2)) := by
      convert rankin_powerset_bound q.primeFactors
        (fun p => combinedEulerWeight ε k Ω p) _ s (by positivity) (ε / 2)
        (by positivity) using 1
      exact fun p hp => combinedEulerWeight_nonneg ε k Ω p (Nat.prime_of_mem_primeFactors hp)
    have h_exp : ∏ p ∈ q.primeFactors,
        (1 + combinedEulerWeight ε k Ω p * (p : ℝ) ^ (ε / 2)) ≤
        Real.exp (∑ p ∈ q.primeFactors,
          combinedEulerWeight ε k Ω p * (p : ℝ) ^ (ε / 2)) := by
      convert prod_one_add_le_exp_sum q.primeFactors _ _ using 1
      exact fun p hp => mul_nonneg
        (combinedEulerWeight_nonneg ε k Ω p (Nat.prime_of_mem_primeFactors hp))
        (Real.rpow_nonneg (Nat.cast_nonneg _) _)
    have h_combined : ∑ p ∈ q.primeFactors,
        combinedEulerWeight ε k Ω p * (p : ℝ) ^ (ε / 2) ≤
        k * ∑' n : ℕ, (n : ℝ) ^ (-(1 + ε / 2)) := by
      have h_combined : ∑ p ∈ q.primeFactors,
          combinedEulerWeight ε k Ω p * (p : ℝ) ^ (ε / 2) ≤
          ∑ p ∈ q.primeFactors, k * (p : ℝ) ^ (-(1 + ε / 2)) := by
        apply Finset.sum_le_sum
        intro p hp
        convert mul_le_mul_of_nonneg_right
          (combinedEulerWeight_le ε hε k Ω hrp p (Nat.prime_of_mem_primeFactors hp))
          (Real.rpow_nonneg (Nat.cast_nonneg p) (ε / 2)) using 1 ; ring_nf
        rw [mul_assoc,
          ← Real.rpow_add (Nat.cast_pos.mpr <| Nat.pos_of_mem_primeFactors hp)]
        ring_nf
      refine le_trans h_combined ?_
      rw [← Finset.mul_sum _ _ _]
      exact mul_le_mul_of_nonneg_left
        (Summable.sum_le_tsum (q.primeFactors)
          (fun _ _ => Real.rpow_nonneg (Nat.cast_nonneg _) _)
          (by exact Real.summable_nat_rpow.2 (by linarith)))
        (Nat.cast_nonneg _)
    refine le_trans ?_ (h_rankin.trans ?_)
    · refine Finset.sum_le_sum_of_subset_of_nonneg ?_ ?_ <;> grind
    · rw [mul_comm]; gcongr
      exact h_exp.trans (Real.exp_le_exp.mpr h_combined)

end PoissonCRT
