/-
Copyright (c) 2026 Fernando Portela. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Fernando Portela
-/

/-
Portions of this file were generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.29.0
Mathlib version: 8a178386ffc0f5fef0b77738bb5449d50efeea95

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

import PoissonViaCRT.Defs
import PoissonViaCRT.CRTMultiplicativity
import PoissonViaCRT.DeviationBoundHelper
import Mathlib.Algebra.Star.Basic
import Mathlib.Analysis.Complex.Exponential
import Mathlib.Analysis.Normed.Group.Defs
import Mathlib.Analysis.SpecialFunctions.Trigonometric.Basic
import Mathlib.Analysis.SpecialFunctions.Trigonometric.Bounds
import Mathlib.Data.Finset.Defs
import Mathlib.Data.Matrix.Mul
import Mathlib.Data.Nat.Prime.Defs
import Mathlib.Data.ZMod.Defs
import Mathlib.Logic.Basic

set_option linter.unusedVariables false

/-!
# Fourier ANOVA for the Deviation Bound

This file scaffolds the **Fourier ANOVA** (Analysis of Variance) machinery for proving
the uniform deviation bound in Proposition 3.6 of Granville–Kurlberg
(arXiv:math/0412135v2, §3.2).

Instead of the combinatorial Gamma-structure decomposition, we expand the deviation
$N_k(h, \Omega_q) - \mu$ in terms of the discrete Fourier transform on the finite
abelian group $G = (\mathbb{Z}/q\mathbb{Z})^{k-1}$, factor the Fourier coefficients
via CRT, and bound the resulting sum using exponential-sum estimates from the
`WellDistributed` hypothesis.

## Main Definitions

* `PoissonCRT.rootOfUnity`: The primitive $q$-th root of unity $e^{2\pi i / q}$.
* `PoissonCRT.character`: The additive character
  $\chi_\xi(x) = e^{2\pi i \langle \xi, x \rangle / q}$.
* `PoissonCRT.dft`: The discrete Fourier transform on $(\mathbb{Z}/q\mathbb{Z})^m$.
* `PoissonCRT.fourierLocalDeviation`: The local deviation function
  $\operatorname{dev}_p(h) = N_k(h, \Omega_p) - \mu_p$.
* `PoissonCRT.boxIndicator`: The indicator function of the scaled box $s \cdot X$
  in $(\mathbb{Z}/q\mathbb{Z})^m$.

## Main Results (stubbed)

* `PoissonCRT.character_orthogonality`: Orthogonality of additive characters.
* `PoissonCRT.plancherel_identity`: Plancherel / Parseval identity on $G$.
* `PoissonCRT.dft_inversion`: Fourier inversion formula.
* `PoissonCRT.fourierLocalDeviation_dft_zero`: The Fourier transform of the local deviation
  vanishes at the zero frequency.
* `PoissonCRT.local_deviation_fourier_bound`: $L^\infty$ bound on the local
  deviation Fourier coefficients using `WellDistributed`.
* `PoissonCRT.box_fourier_l1_bound`: The $L^1$-norm of the box indicator Fourier
  transform is $O((\log q)^{k-1})$.

## References

* [A. Granville, P. Kurlberg, *Poisson statistics via the Chinese remainder theorem*]
  [arXiv:math/0412135v2], §3.2
* See `docs/fourier_anova_blueprint.md` for the full mathematical blueprint.
-/

open Finset BigOperators Classical Complex

namespace PoissonCRT
/-! ### Additive characters on `ZMod q` -/

/-- The primitive `q`-th root of unity $\omega_q = e^{2\pi i / q}$. -/
noncomputable def rootOfUnity (q : ℕ) [NeZero q] : ℂ :=
  Complex.exp (2 * Real.pi * Complex.I / (q : ℂ))

/-- The additive character $\chi_a(x) = \omega_q^{a \cdot x}$ on `ZMod q`.
Here `a` and `x` are elements of `ZMod q`, and we lift the product `a * x` to `ℤ`
via `ZMod.val` before exponentiating. -/
@[expose]
public noncomputable def additiveChar (q : ℕ) [NeZero q] (a : ZMod q) (x : ZMod q) : ℂ :=
  Complex.exp (2 * Real.pi * Complex.I * ((a * x).val : ℂ) / (q : ℂ))

/-- The product character on `(ZMod q)^m`. Given a frequency vector `ξ : Fin m → ZMod q`
and a point `x : Fin m → ZMod q`, the character is
$\chi_\xi(x) = \prod_j \chi_{\xi_j}(x_j) = e^{2\pi i \langle \xi, x \rangle / q}$. -/
@[expose]
public noncomputable def character (q : ℕ) [NeZero q] (m : ℕ)
    (ξ x : Fin m → ZMod q) : ℂ :=
  ∏ j : Fin m, additiveChar q (ξ j) (x j)

/-! ### Discrete Fourier Transform -/

/-- The **discrete Fourier transform** of `f : (ZMod q)^m → ℂ`.

$$\widehat{f}(\xi) = \frac{1}{q^m} \sum_{x \in (\mathbb{Z}/q\mathbb{Z})^m}
  f(x) \cdot \overline{\chi_\xi(x)}.$$ -/
@[expose]
public noncomputable def dft (q : ℕ) [NeZero q] (m : ℕ)
    (f : (Fin m → ZMod q) → ℂ) (ξ : Fin m → ZMod q) : ℂ :=
  (1 / (q : ℂ) ^ m) * ∑ x : Fin m → ZMod q, f x * starRingEnd ℂ (character q m ξ x)

/-! ### Character properties -/

/-
`additiveChar q a x` can be written as a power of the primitive root
`exp(2πi·a.val/q)` raised to `x.val`.
-/
public lemma additiveChar_eq_exp_pow (q : ℕ) [NeZero q] (a x : ZMod q) :
    additiveChar q a x =
      Complex.exp (2 * Real.pi * Complex.I * (a.val : ℂ) / (q : ℂ)) ^ x.val := by
  rw [ ← Complex.exp_nat_mul ] ; ring_nf;
  convert Complex.exp_eq_exp_iff_exists_int.mpr ?_ using 2 ; ring_nf;
  use -((a.val * x.val) / q);
  rw [ ZMod.val_mul ];
  rw [ Nat.mod_def ] ; ring_nf;
  rw [ Nat.cast_sub ( Nat.mul_div_le _ _ ) ] ; push_cast ; ring_nf;
  norm_cast ; simp +decide [ mul_assoc, mul_comm, mul_left_comm, NeZero.ne ]

/-
The `additiveChar` at `a = 0` is identically `1`.
-/
@[simp]
public lemma additiveChar_zero (q : ℕ) [NeZero q] (x : ZMod q) :
    additiveChar q 0 x = 1 := by
  -- By definition of additiveChar, we have additiveChar q 0 x = Complex.exp (2 * Real.pi * Complex.I * (0 * x).val / (q : ℂ)).
  simp [additiveChar]

/-
The primitive `q`-th root of unity raised to `q` equals `1`.
-/
lemma exp_two_pi_I_val_pow_eq_one (q : ℕ) [NeZero q] (a : ZMod q) :
    Complex.exp (2 * Real.pi * Complex.I * (a.val : ℂ) / (q : ℂ)) ^ q = 1 := by
  rw [ ← Complex.exp_nat_mul, mul_comm, Complex.exp_eq_one_iff ];
  exact ⟨ a.val, by rw [ div_mul_cancel₀ _ ( NeZero.ne _ ) ] ; push_cast; ring ⟩

/-
For `a ≠ 0` in `ZMod q`, the primitive root `exp(2πi·a.val/q) ≠ 1`.
-/
lemma exp_two_pi_I_val_ne_one (q : ℕ) [NeZero q] (a : ZMod q) (ha : a ≠ 0) :
    Complex.exp (2 * Real.pi * Complex.I * (a.val : ℂ) / (q : ℂ)) ≠ 1 := by
  contrapose! ha;
  rw [ Complex.exp_eq_one_iff ] at ha;
  -- By simplifying, we can see that this implies $a.val = nq$ for some integer $n$.
  obtain ⟨n, hn⟩ := ha
  have h_eq : a.val = n * q := by
    rw [ div_eq_iff ] at hn;
    · exact_mod_cast ( mul_left_cancel₀ ( Complex.two_pi_I_ne_zero ) <| by linear_combination' hn : ( a.val : ℂ ) = n * q );
    · exact Nat.cast_ne_zero.mpr <| NeZero.ne q;
  replace h_eq := congr_arg ( ( ↑ ) : ℤ → ZMod q ) h_eq ; simp_all +decide

/-
**1D orthogonality of additive characters.**
$$\sum_{x \in \mathbb{Z}/q\mathbb{Z}} \chi_a(x) =
  \begin{cases} q & \text{if } a = 0, \\ 0 & \text{if } a \neq 0. \end{cases}$$
-/
lemma additiveChar_sum_eq_ite (q : ℕ) [NeZero q] (a : ZMod q) :
    ∑ x : ZMod q, additiveChar q a x = if a = 0 then (q : ℂ) else 0 := by
  split_ifs with ha;
  · aesop;
  · -- Rewrite each term using `additiveChar_eq_exp_pow` to get `∑ x, r^(x.val)` where `r = exp(2πi a.val/q)`.
    have h_exp : ∑ x : ZMod q, additiveChar q a x = ∑ x ∈ Finset.range q, (Complex.exp (2 * Real.pi * Complex.I * (a.val : ℂ) / (q : ℂ))) ^ x := by
      refine' Finset.sum_bij ( fun x _ => x.val ) _ _ _ _ <;> simp +decide [ additiveChar_eq_exp_pow ];
      · exact fun x => ZMod.val_lt x;
      · exact fun x y h => by simpa [ ZMod.natCast_zmod_val ] using congr_arg ( fun x : ℕ => x : ℕ → ZMod q ) h;
      · exact fun b hb => ⟨ b, ZMod.val_cast_of_lt hb ⟩;
    rw [ h_exp, geom_sum_eq ] <;> norm_num [ ha ];
    · exact Or.inl ( by rw [ sub_eq_zero, ← Complex.exp_nat_mul, mul_comm, Complex.exp_eq_one_iff ] ; use a.val; push_cast; ring_nf; norm_num [ NeZero.ne ] );
    · convert exp_two_pi_I_val_ne_one q a ha using 1;
      cases q <;> aesop

/-
The conjugate of `additiveChar q a x` equals `additiveChar q (-a) x`.
-/
public lemma starRingEnd_additiveChar (q : ℕ) [NeZero q] (a x : ZMod q) :
    starRingEnd ℂ (additiveChar q a x) = additiveChar q (-a) x := by
  -- Apply the property of the conjugate of the exponential.
  have h_conj_exp : (starRingEnd ℂ) (Complex.exp (2 * Real.pi * Complex.I * ((a * x).val : ℂ) / (q : ℂ))) = Complex.exp (2 * Real.pi * Complex.I * (q - (a * x).val : ℤ) / (q : ℂ)) := by
    norm_num [ Complex.ext_iff, Complex.exp_re, Complex.exp_im ];
    norm_num [ sub_div, mul_sub, NeZero.ne ];
    erw [ ZMod.cast_eq_val ] ; norm_cast ; aesop;
  unfold additiveChar;
  cases eq_or_ne ( a * x ) 0 <;> simp_all +decide [ ZMod.neg_val ];
  rw [ Nat.cast_sub ];
  · cases q <;> aesop;
  · exact Nat.le_of_lt ( ZMod.val_lt _ )

/-
The product of characters satisfies `χ_ξ(x) · conj(χ_η(x)) = χ_{ξ-η}(x)`.
-/
lemma character_mul_conj (q : ℕ) [NeZero q] (m : ℕ)
    (ξ η x : Fin m → ZMod q) :
    character q m ξ x * starRingEnd ℂ (character q m η x) =
      character q m (ξ - η) x := by
  unfold character;
  rw [ map_prod, ← Finset.prod_mul_distrib ];
  refine' Finset.prod_congr rfl fun j _ => _;
  rw [ starRingEnd_additiveChar ];
  unfold additiveChar;
  rw [ ← Complex.exp_add ];
  rw [ Complex.exp_eq_exp_iff_exists_int ];
  use ((ξ j * x j).val + (-η j * x j).val - ((ξ j - η j) * x j).val) / q;
  rw [ Int.cast_div ] <;> norm_num;
  · ring;
  · simp +decide [ sub_mul, ← ZMod.intCast_zmod_eq_zero_iff_dvd ];
  · exact NeZero.ne q

/-
**Orthogonality of additive characters.** The sum of a non-trivial character over the
full group vanishes, and the sum of the trivial character is the group order:

$$\sum_{x \in G} \chi_\xi(x) \overline{\chi_\eta(x)} = |G| \cdot \delta_{\xi, \eta}.$$
-/
public theorem character_orthogonality (q : ℕ) [NeZero q] (m : ℕ)
    (ξ η : Fin m → ZMod q) :
    ∑ x : Fin m → ZMod q, character q m ξ x * starRingEnd ℂ (character q m η x) =
      if ξ = η then ((q : ℂ) ^ m) else 0 := by
  -- By Fubini's theorem, we can interchange the order of summation.
  have h_fubini : ∑ x : Fin m → ZMod q, character q m (ξ - η) x = ∏ j : Fin m, ∑ x : ZMod q, additiveChar q ((ξ - η) j) x := by
    rw [ Finset.prod_sum ];
    refine' Finset.sum_bij ( fun x _ => fun i _ => x i ) _ _ _ _ <;> simp +decide [ character ];
    · simp +decide [ funext_iff ];
    · exact fun b => ⟨ fun i => b i ( Finset.mem_univ i ), funext fun i => funext fun _ => rfl ⟩;
  split_ifs with h <;> simp_all +decide [ character_mul_conj ];
  exact Finset.prod_eq_zero ( Finset.mem_univ ( Classical.choose ( Function.ne_iff.mp h ) ) ) ( by rw [ additiveChar_sum_eq_ite ] ; simp +decide [ sub_eq_zero, Classical.choose_spec ( Function.ne_iff.mp h ) ] )

/-
**Fourier inversion formula.**
$f(x) = \sum_{\xi \in G} \widehat{f}(\xi) \cdot \chi_\xi(x)$.
-/
public theorem dft_inversion (q : ℕ) [NeZero q] (m : ℕ)
    (f : (Fin m → ZMod q) → ℂ) (x : Fin m → ZMod q) :
    f x = ∑ ξ : Fin m → ZMod q, dft q m f ξ * character q m ξ x := by
  simp +decide [ dft, Finset.mul_sum _ _ _, mul_comm, mul_left_comm ];
  -- By the orthogonality of the characters, the inner sum over ξ is q^m if x = y and 0 otherwise.
  have h_orthogonality : ∀ y : Fin m → ZMod q, ∑ ξ : Fin m → ZMod q, (character q m ξ x) * (starRingEnd ℂ (character q m ξ y)) = if x = y then (q : ℂ) ^ m else 0 := by
    convert character_orthogonality q m x using 1;
    unfold character; ring_nf;
    unfold additiveChar; simp +decide [ mul_comm ] ;
  rw [ Finset.sum_comm ];
  simp_all +decide [ ← Finset.mul_sum _ _ _ ]

/-! ### Plancherel / Parseval identity -/

/-
**Plancherel identity** on $(\mathbb{Z}/q\mathbb{Z})^m$:

$$\frac{1}{q^m} \sum_{x \in G} f(x) \cdot \overline{g(x)}
  = \sum_{\xi \in G} \widehat{f}(\xi) \cdot \overline{\widehat{g}(\xi)}.$$
-/
theorem plancherel_identity (q : ℕ) [NeZero q] (m : ℕ)
    (f g : (Fin m → ZMod q) → ℂ) :
    (1 / (q : ℂ) ^ m) * ∑ x : Fin m → ZMod q, f x * starRingEnd ℂ (g x) =
      ∑ ξ : Fin m → ZMod q, dft q m f ξ * starRingEnd ℂ (dft q m g ξ) := by
  unfold dft; simp +decide [ mul_assoc, Finset.mul_sum _ _ _, Finset.sum_mul ] ;
  -- By the orthogonality of the characters, the inner sum over ξ is zero unless x = y.
  have h_inner : ∀ x y : Fin m → ZMod q, ∑ ξ : Fin m → ZMod q, character q m ξ x * starRingEnd ℂ (character q m ξ y) = if x = y then (q : ℂ) ^ m else 0 := by
    intro x y;
    have := character_orthogonality q m;
    convert this x y using 1;
    unfold character; simp +decide
    unfold additiveChar; simp +decide [ mul_comm ] ;
  simp +decide only [mul_left_comm];
  rw [ Finset.sum_comm, Finset.sum_congr rfl ] ; intros ; rw [ Finset.sum_comm ] ; simp +decide [ ← Finset.mul_sum _ _ _ ] ; ring_nf;
  simp_all +decide [ mul_assoc, mul_comm, mul_left_comm, pow_mul ];
  simp +decide [ sq, mul_assoc, NeZero.ne ]

/-! ### Local deviation function -/

/-- The **local deviation function** at prime `p`:
$\operatorname{dev}_p(h) = N_k((0, h_1, \ldots, h_{k-1}), \Omega_p) - \mu_p$,
where $\mu_p = |\Omega_p|^k / p^{k-1}$ is the local expected value. -/
@[expose]
public noncomputable def fourierLocalDeviation (k : ℕ) (Ω : ∀ p : ℕ, Finset (ZMod p))
    (p : ℕ) [NeZero p] (h : Fin (k - 1) → ZMod p) : ℂ :=
  (tupleCount (Ω p) (Fin.cons 0 h) : ℂ) - (((Ω p).card : ℝ) ^ k / (p : ℝ) ^ (k - 1) : ℝ)

/-
For any `t : ZMod p` and `S : Finset (ZMod p)`, the number of `h : ZMod p` with
`t + h ∈ S` equals `|S|`. This is because `h ↦ t + h` is a bijection on `ZMod p`.
-/
lemma card_filter_add_mem (p : ℕ) [NeZero p] (t : ZMod p) (S : Finset (ZMod p)) :
    (Finset.univ.filter fun h : ZMod p => t + h ∈ S).card = S.card := by
  -- The function h ↦ t + h is a bijection from ZMod p to ZMod p, so the cardinality of the preimage of S under this function is equal to the cardinality of S.
  have h_bij : Finset.image (fun h => t + h) (Finset.univ.filter (fun h => t + h ∈ S)) = S := by
    ext x; aesop;
  rw [ ← h_bij, Finset.card_image_of_injective _ ( add_right_injective t ) ];
  aesop

/-
Summing `tupleCount (Ω p) (Fin.cons 0 h)` over all `h` in `ℕ` form:
`∑ h, tupleCount (Ω p) (Fin.cons 0 h) = (Ω p).card ^ k`.
-/
theorem sum_tupleCount_eq_card_pow_nat (k : ℕ) (hk : 1 ≤ k) (p : ℕ) [NeZero p]
    (Ω : ∀ p : ℕ, Finset (ZMod p)) :
    (∑ h : Fin (k - 1) → ZMod p, tupleCount (Ω p) (Fin.cons 0 h)) =
      (Ω p).card ^ k := by
  unfold tupleCount
  rcases k with ( _ | k ) <;> simp_all +decide [ Fin.forall_fin_succ ]
  -- Goal: ∑ x, #{t | t ∈ Ω p ∧ ∀ i, t + x i ∈ Ω p} = (Ω p).card ^ (k + 1)
  have h_count : ∀ t ∈ Ω p, (Finset.univ.filter fun h : Fin k → ZMod p => ∀ i, t + h i ∈ Ω p).card = (Ω p).card ^ k := by
    intro t _
    rw [show (Finset.univ.filter fun h : Fin k → ZMod p => ∀ i, t + h i ∈ Ω p) =
      Finset.image (fun y : Fin k → ↑(Ω p) => fun i => (y i : ZMod p) - t) Finset.univ from ?_]
    · rw [Finset.card_image_of_injective]
      · simp [Finset.card_univ, Fintype.card_coe]
      · exact fun y z h => funext fun i => Subtype.ext <| by simpa using congr_fun h i
    · ext y; simp [Finset.mem_image]
      exact ⟨fun hy => ⟨fun i => ⟨t + y i, hy i⟩, by ext i; simp⟩,
             by rintro ⟨a, rfl⟩ i; simp⟩
  -- Fubini: swap sum and filter, then use h_count
  simp_rw [Finset.card_filter]
  rw [Finset.sum_comm]
  have : ∀ y : ZMod p,
      (∑ x : Fin k → ZMod p, if y ∈ Ω p ∧ ∀ (i : Fin k), y + x i ∈ Ω p then 1 else 0) =
      if y ∈ Ω p then (Ω p).card ^ k else 0 := by
    intro y
    split_ifs with hy
    · simp only [hy, true_and]
      rw [← Finset.card_filter]
      exact h_count y hy
    · apply Finset.sum_eq_zero; intro x _; simp [hy]
  have step1 : (∑ y : ZMod p, ∑ x : Fin k → ZMod p,
      if (y ∈ Ω p ∧ ∀ (i : Fin k), y + x i ∈ Ω p) then (1 : ℕ) else 0) =
    ∑ y : ZMod p, if y ∈ Ω p then (Ω p).card ^ k else 0 :=
    Finset.sum_congr rfl (fun y _ => this y)
  have step2 : (∑ y : ZMod p, if y ∈ Ω p then (Ω p).card ^ k else 0) = (Ω p).card ^ (k + 1) := by
    simp only [Finset.sum_ite, Finset.sum_const_zero, Finset.sum_const, smul_eq_mul]
    simp [mul_comm, pow_succ]
  exact step1.trans step2

/-- Summing `tupleCount (Ω p) (Fin.cons 0 h)` over all `h : Fin (k-1) → ZMod p`
yields `(Ω p).card ^ k`. The key idea: swap the sum over `h` and `t`, then for
each fixed `t ∈ Ω p`, the sum over each coordinate `h_i` of the indicator
`[t + h_i ∈ Ω p]` equals `|Ω p|` (as `h_i` ranges over all of `ZMod p`). -/
public theorem sum_tupleCount_eq_card_pow (k : ℕ) (hk : 1 ≤ k) (p : ℕ) [NeZero p]
    (Ω : ∀ p : ℕ, Finset (ZMod p)) :
    (∑ h : Fin (k - 1) → ZMod p, (tupleCount (Ω p) (Fin.cons 0 h) : ℂ)) =
      ((Ω p).card : ℂ) ^ k := by
  exact_mod_cast sum_tupleCount_eq_card_pow_nat k hk p Ω

/-- The sum of the local deviation over all elements of $(\mathbb{Z}/p\mathbb{Z})^{k-1}$
is zero (the deviations from the mean cancel). -/
theorem fourierLocalDeviation_sum_zero (k : ℕ) (hk : 1 ≤ k) (p : ℕ) [NeZero p]
    (Ω : ∀ p : ℕ, Finset (ZMod p)) :
    ∑ h : Fin (k - 1) → ZMod p, fourierLocalDeviation k Ω p h = 0 := by
  unfold fourierLocalDeviation
  simp +decide [Finset.sum_sub_distrib]
  rw [mul_div_cancel₀]
  · exact sub_eq_zero_of_eq <| mod_cast sum_tupleCount_eq_card_pow k hk p Ω
  · exact pow_ne_zero _ (Nat.cast_ne_zero.mpr <| NeZero.ne p)

/-- The Fourier transform of the local deviation vanishes at the zero frequency:
$\widehat{\operatorname{dev}}_p(0) = 0$. This is immediate from `fourierLocalDeviation_sum_zero`
and the definition of `dft`. -/
theorem fourierLocalDeviation_dft_zero (k : ℕ) (hk : 1 ≤ k) (p : ℕ) [NeZero p]
    (Ω : ∀ p : ℕ, Finset (ZMod p)) :
    dft p (k - 1) (fourierLocalDeviation k Ω p) 0 = 0 := by
  unfold dft; simp +decide
  unfold character; simp +decide [additiveChar_zero]
  exact Or.inr (fourierLocalDeviation_sum_zero k hk p Ω)

/-! ### Box indicator function -/

/-- The **box indicator function** on $(\mathbb{Z}/q\mathbb{Z})^m$. Given a box `B`
with side lengths $b_1, \ldots, b_m$ and a scaling parameter `s > 0`, the indicator
$I_S(x) = 1$ if $x$ lies in the scaled box $\{1, \ldots, \lfloor s b_j \rfloor\}^m$
(identified with elements of `ZMod q` via their canonical representatives), and
$I_S(x) = 0$ otherwise. -/
@[expose]
public noncomputable def boxIndicator (q : ℕ) [NeZero q] (m : ℕ)
    (B : Box m) (s : ℝ) (x : Fin m → ZMod q) : ℂ :=
  if ∀ j : Fin m, (x j).val ∈ Finset.Icc 1 ⌊s * B.sides j⌋₊ then 1 else 0

/-! ### Exponential sum bounds from `WellDistributed` -/

/-- The Fourier-analytic analogue of `WellDistributed` from §3.2.
This hypothesis directly asserts the necessary $L^\\infty$ decay on the non-zero Fourier
coefficients of the local deviation function, including the crucial
$(1 - |\Omega_p|/p)$ factor that mirrors the spatial `WellDistributed` hypothesis.
Specifically, for $\xi \neq 0$:
$$\|\widehat{N}_p(\xi)\| \le (1 - |\Omega_p|/p) \cdot p^{-\varepsilon} \cdot \mu_p$$
where $\mu_p = |\Omega_p|^k / p^{k-1}$. The factor $(1 - |\Omega_p|/p)$ is essential:
it ensures that when $\Omega_p$ is nearly full, the Fourier coefficients are
near-zero, making the divisor sum in the Möbius synthesis absolutely convergent. -/
@[expose]
public def WellDistributedFourier (ε : ℝ) (p : ℕ) [Fact p.Prime] (Ω : Finset (ZMod p)) (k : ℕ) : Prop :=
  ∀ (ξ : Fin (k - 1) → ZMod p), ξ ≠ 0 →
    ‖dft p (k - 1) (fun h => (tupleCount Ω (Fin.cons 0 h) : ℂ)) ξ‖ ≤
    (1 - (Ω.card : ℝ) / p) * (p : ℝ) ^ (-ε) * ((Ω.card : ℝ) ^ k / (p : ℝ) ^ (k - 1))

/-! ### Helper lemmas for the WD → WDF bridge -/

/-- The norm of `additiveChar q a x` is 1. -/
public lemma norm_additiveChar (q : ℕ) [NeZero q] (a x : ZMod q) :
    ‖additiveChar q a x‖ = 1 := by
  unfold additiveChar
  have h : 2 * ↑Real.pi * I * ↑(a * x).val / (↑q : ℂ) =
      ↑(2 * Real.pi * ↑(a * x).val / (↑q : ℝ)) * I := by
    push_cast; ring
  rw [h, Complex.norm_exp_ofReal_mul_I]

/-- The norm of `character q m ξ x` is 1. -/
lemma norm_character (q : ℕ) [NeZero q] (m : ℕ) (ξ x : Fin m → ZMod q) :
    ‖character q m ξ x‖ = 1 := by
  unfold character
  induction m with
  | zero => simp
  | succ n ih =>
    rw [Fin.prod_univ_castSucc, norm_mul]
    rw [ih (fun j => ξ j.castSucc) (fun j => x j.castSucc)]
    rw [norm_additiveChar]
    ring

/-- For ξ ≠ 0, the sum of conjugate characters vanishes. -/
public lemma sum_star_character_eq_zero (q : ℕ) [NeZero q] (m : ℕ)
    (ξ : Fin m → ZMod q) (hξ : ξ ≠ 0) :
    ∑ x : Fin m → ZMod q, starRingEnd ℂ (character q m ξ x) = 0 := by
  have h := character_orthogonality q m 0 ξ
  simp only [character, Pi.zero_apply, additiveChar_zero, Finset.prod_const_one, one_mul] at h
  rw [if_neg (Ne.symm hξ)] at h
  convert h using 1

lemma WellDistributed_implies_WellDistributedFourier
    (ε : ℝ) (p : ℕ) [Fact p.Prime] (Ω : Finset (ZMod p)) (k : ℕ)
    (hWD : WellDistributed ε p Ω k) :
    WellDistributedFourier ε p Ω k := by
  intro ξξ hξ_ne_zero
  have h_sum_zero : ∑ r : Fin (k - 1) → ZMod p, starRingEnd ℂ (character p (k - 1) ξξ r) = 0 := by
    convert sum_star_character_eq_zero p ( k - 1 ) ξξ hξ_ne_zero using 1;
  -- Apply the triangle inequality to the sum.
  have h_triangle : ‖(1 / (p : ℂ) ^ (k - 1)) * ∑ r : Fin (k - 1) → ZMod p, (tupleCount Ω (Fin.cons 0 r) - ((Ω.card : ℂ) ^ k / (p : ℂ) ^ (k - 1))) * starRingEnd ℂ (character p (k - 1) ξξ r)‖ ≤ (1 / (p : ℝ) ^ (k - 1)) * ∑ r : Fin (k - 1) → ZMod p, |(tupleCount Ω (Fin.cons 0 r) : ℝ) - ((Ω.card : ℝ) ^ k / (p : ℝ) ^ (k - 1))| := by
    have h_triangle : ∀ r : Fin (k - 1) → ZMod p, ‖(tupleCount Ω (Fin.cons 0 r) - ((Ω.card : ℂ) ^ k / (p : ℂ) ^ (k - 1))) * starRingEnd ℂ (character p (k - 1) ξξ r)‖ ≤ |(tupleCount Ω (Fin.cons 0 r) : ℝ) - ((Ω.card : ℝ) ^ k / (p : ℝ) ^ (k - 1))| := by
      intro r
      simp [norm_character];
      convert Complex.norm_real _ |> le_of_eq using 1;
      norm_num [ Complex.normSq, Complex.norm_def ];
    rw [ norm_mul, norm_div ];
    gcongr;
    · exact_mod_cast pow_pos ( Nat.Prime.pos Fact.out ) _;
    · norm_num;
    · norm_num [ Complex.norm_pow ];
    · exact le_trans ( norm_sum_le _ _ ) ( Finset.sum_le_sum fun _ _ => h_triangle _ );
  refine le_trans ?_ ( h_triangle.trans ?_ );
  · unfold dft; simp +decide [ sub_mul ] ;
    simp_all +decide [ ← Finset.mul_sum _ _ _ ];
  · have := hWD.2;
    rw [ div_mul_eq_mul_div, div_le_iff₀ ] <;> norm_cast at * <;> simp_all +decide only [Nat.cast_pow,
      one_div, Complex.norm_mul, norm_inv, norm_pow, RCLike.norm_natCast, one_mul];
    · nlinarith;
    · exact pow_pos ( Nat.Prime.pos Fact.out ) _

/-! ### Box Fourier transform decay -/

/-
The box indicator factors as a product of coordinate-wise 1D indicators:
`boxIndicator q m B s x = ∏ j, if (x j).val ∈ Icc 1 ⌊s * B.sides j⌋₊ then 1 else 0`.
This follows from the equivalence of `∀ j, P j` with the product of `if P j then 1 else 0`.
-/
lemma boxIndicator_eq_prod (q : ℕ) [NeZero q] (m : ℕ)
    (B : Box m) (s : ℝ) (x : Fin m → ZMod q) :
    boxIndicator q m B s x = ∏ j : Fin m,
      if (x j).val ∈ Finset.Icc 1 ⌊s * B.sides j⌋₊ then (1 : ℂ) else 0 := by
  unfold boxIndicator; split_ifs <;> simp_all +decide [ Finset.prod_ite ] ;

/-
The DFT of the box indicator factors as a product of 1D DFTs.
This relies on `boxIndicator_eq_prod` to factor the function and the fact that
`character q m ξ x = ∏ j, additiveChar q (ξ j) (x j)` factors over coordinates.
The sum over `x : Fin m → ZMod q` of the product then splits via `Fintype.prod_sum`.
-/
public lemma dft_boxIndicator_eq_prod (q : ℕ) [NeZero q] (m : ℕ)
    (B : Box m) (s : ℝ) (ξ : Fin m → ZMod q) :
    dft q m (boxIndicator q m B s) ξ =
      ∏ j : Fin m, dft q 1
        (fun x => if (x 0).val ∈ Finset.Icc 1 ⌊s * B.sides j⌋₊ then (1 : ℂ) else 0)
        (fun _ => ξ j) := by
  unfold dft;
  nontriviality;
  simp +decide [ boxIndicator_eq_prod, Finset.prod_mul_distrib, Finset.prod_const ];
  rw [ Finset.prod_sum ];
  refine' Or.inl ( Finset.sum_bij ( fun x _ => fun i _ => fun _ => x i ) _ _ _ _ ) <;> simp +decide [ character ];
  · simp +decide [ funext_iff ];
  · exact fun b => ⟨ fun i => b i ( Finset.mem_univ i ) 0, funext fun i => funext fun _ => funext fun _ => by simp +decide [ Fin.eq_zero ] ⟩;
  · exact fun a => by rw [ ← Finset.prod_mul_distrib ] ; exact Finset.prod_congr rfl fun _ _ => by split_ifs <;> ring;

/-! ### CRT frequency equivalence -/

/-
For squarefree `q` and prime factor `p ∣ q`, the cofactor `q / p` is nonzero in `ZMod p`.
This holds because `q` is squarefree, so `p ∤ q / p`, hence `(q / p : ℕ)` has nonzero
image in `ZMod p`.
-/
lemma natCast_div_prime_ne_zero (q : ℕ) [NeZero q] (hq : Squarefree q)
    (p : q.primeFactors) :
    ((q / p : ℕ) : ZMod p) ≠ 0 := by
  rw [ Ne.eq_def, ZMod.natCast_eq_zero_iff ];
  rw [ Nat.dvd_div_iff_mul_dvd ] <;> norm_num [ Nat.mem_primeFactors.mp p.2 ];
  exact fun h => absurd ( hq.squarefree_of_dvd h ) ( by rw [ Nat.squarefree_mul_iff ] ; aesop )

/-- The **CRT frequency equivalence**: maps a global frequency `ξ ∈ ZMod q` to its
local frequency components for the additive character splitting.

For each prime factor `p ∣ q`, the local frequency is
`(ξ mod p) · (q/p)⁻¹ mod p`, where `(q/p)⁻¹` is the modular inverse of the cofactor
`q/p` in `ZMod p`. This correction factor arises from the CRT idempotents:
if `eₚ` is the idempotent satisfying `eₚ ≡ 1 (mod p)` and `eₚ ≡ 0 (mod p')`
for `p' ≠ p`, then `eₚ = (q/p) · (q/p)⁻¹`, and the additive character
`exp(2πi a/q)` decomposes as `∏ₚ exp(2πi (a mod p · (q/p)⁻¹) / p)`. -/
@[expose]
public noncomputable def crtFrequencyEquiv (q : ℕ) [NeZero q] (hq : Squarefree q) :
    ZMod q ≃ ((p : q.primeFactors) → ZMod (p : ℕ)) where
  toFun ξ p :=
    haveI : NeZero p.val := ⟨(Nat.mem_primeFactors.mp p.prop).1.ne_zero⟩
    crtRingEquiv q hq ξ p * ((q / p : ℕ) : ZMod p)⁻¹
  invFun f :=
    (crtRingEquiv q hq).symm fun p =>
      haveI : NeZero p.val := ⟨(Nat.mem_primeFactors.mp p.prop).1.ne_zero⟩
      f p * ((q / p : ℕ) : ZMod p)
  left_inv ξ := by
    simp only
    conv_rhs => rw [← (crtRingEquiv q hq).symm_apply_apply ξ]
    congr 1; funext p
    haveI : NeZero p.val := ⟨(Nat.mem_primeFactors.mp p.prop).1.ne_zero⟩
    haveI : Fact p.val.Prime := ⟨(Nat.mem_primeFactors.mp p.prop).1⟩
    rw [mul_assoc, inv_mul_cancel₀ (natCast_div_prime_ne_zero q hq p), mul_one]
  right_inv f := by
    funext p; simp only
    haveI : NeZero p.val := ⟨(Nat.mem_primeFactors.mp p.prop).1.ne_zero⟩
    haveI : Fact p.val.Prime := ⟨(Nat.mem_primeFactors.mp p.prop).1⟩
    rw [(crtRingEquiv q hq).apply_symm_apply]
    rw [mul_assoc, mul_inv_cancel₀ (natCast_div_prime_ne_zero q hq p), mul_one]

/-
**Additive character CRT splitting.** For squarefree `q`, the additive character
`exp(2πi (ξ · x).val / q)` decomposes as a product over the prime factors of `q`:
$\chi_\xi(x) = \prod_{p \mid q} \chi_{\xi_p}(x_p),$
where `ξ_p = crtFrequencyEquiv q hq ξ p` is the corrected local frequency and
`x_p = crtRingEquiv q hq x p` is the CRT projection of `x`.
-/
set_option maxHeartbeats 1600000 in
public lemma additiveChar_crt_split (q : ℕ) [NeZero q] (hq : Squarefree q)
    (ξ x : ZMod q) :
    additiveChar q ξ x =
      ∏ p ∈ q.primeFactors.attach, (
        haveI : NeZero p.val := ⟨(Nat.mem_primeFactors.mp p.prop).1.ne_zero⟩
        additiveChar p.val
          (crtFrequencyEquiv q hq ξ p)
          (crtRingEquiv q hq x p)
      ) := by
  unfold additiveChar; simp +decide [ mul_comm ] ;
  rw [ ← Complex.exp_sum ];
  -- By the properties of the exponential function and the definition of `crtFrequencyEquiv`, we can rewrite the right-hand side of the equation.
  have h_exp : (ξ * x).cast / (q : ℂ) - ∑ p ∈ q.primeFactors.attach, ((crtFrequencyEquiv q hq) ξ p * (crtRingEquiv q hq) x p).val / (p : ℂ) ∈ Set.range (fun n : ℤ => (n : ℂ)) := by
    -- By the properties of the Chinese Remainder Theorem, we know that
    have h_crt : (ξ * x).val ≡ ∑ p ∈ q.primeFactors.attach, ((crtFrequencyEquiv q hq) ξ p * (crtRingEquiv q hq) x p).val * (q / p : ℕ) [MOD q] := by
      have h_crt : ∀ p ∈ q.primeFactors.attach, (ξ * x).val ≡ ((crtFrequencyEquiv q hq ξ p) * (crtRingEquiv q hq x p)).val * (q / p : ℕ) [MOD p] := by
        intro p hp
        have h_crt : (ξ * x).val ≡ ((crtRingEquiv q hq (ξ * x) p).val) * (q / p : ℕ) * ((q / p : ℕ)⁻¹ : ZMod p).val [MOD p] := by
          have h_crt : (q / p : ℕ) * ((q / p : ℕ)⁻¹ : ZMod p).val ≡ 1 [MOD p] := by
            haveI := Fact.mk ( Nat.prime_of_mem_primeFactors p.2 ) ; simp +decide [ ← ZMod.natCast_eq_natCast_iff ] ;
            rw [ ZMod.mul_inv_of_unit ];
            rw [ isUnit_iff_ne_zero ];
            rw [ Ne.eq_def, ZMod.natCast_eq_zero_iff ];
            rw [ Nat.dvd_div_iff_mul_dvd ];
            · exact fun h => absurd ( hq.squarefree_of_dvd h ) ( by rw [ Nat.squarefree_mul_iff ] ; aesop );
            · exact Nat.dvd_of_mem_primeFactors p.2;
          simp_all +decide [ ← ZMod.natCast_eq_natCast_iff, mul_assoc ];
          have h_crt : (ξ * x).cast = ((crtRingEquiv q hq (ξ * x) p).val : ZMod p) := by
            convert rfl;
            convert ZMod.natCast_zmod_val _;
            · convert rfl;
              convert crtRingEquiv_apply_eq_castHom q hq ( ξ * x ) p using 1;
            · exact ⟨ Nat.ne_of_gt ( Nat.pos_of_mem_primeFactors p.2 ) ⟩;
          aesop;
        simp_all +decide [ ← ZMod.natCast_eq_natCast_iff, mul_assoc ];
        simp +decide [ mul_assoc, mul_comm, mul_left_comm, crtFrequencyEquiv ];
        haveI := Fact.mk ( Nat.prime_of_mem_primeFactors p.2 ) ; simp +decide [ ← mul_assoc ] ;
      have h_crt : ∀ p ∈ q.primeFactors.attach, (ξ * x).val ≡ ∑ p ∈ q.primeFactors.attach, ((crtFrequencyEquiv q hq ξ p) * (crtRingEquiv q hq x p)).val * (q / p : ℕ) [MOD p] := by
        intro p hp
        have h_crt : ∑ p ∈ q.primeFactors.attach, ((crtFrequencyEquiv q hq ξ p) * (crtRingEquiv q hq x p)).val * (q / p : ℕ) ≡ ((crtFrequencyEquiv q hq ξ p) * (crtRingEquiv q hq x p)).val * (q / p : ℕ) [MOD p] := by
          simp +decide [ ← ZMod.natCast_eq_natCast_iff ];
          rw [ Finset.sum_eq_single p ] <;> simp_all +decide [ Nat.ModEq ];
          intro a ha ha' ha'' ha'''; have := Nat.dvd_div_of_mul_dvd ( show a * p.val ∣ q from Nat.Coprime.mul_dvd_of_dvd_of_dvd ( by have := Nat.coprime_primes ha ( Nat.prime_of_mem_primeFactors p.2 ) ; aesop ) ha' ( Nat.dvd_of_mem_primeFactors p.2 ) ) ; simp_all +decide [ Nat.dvd_iff_mod_eq_zero ] ;
          simp_all +decide [ ← ZMod.val_natCast, Nat.dvd_iff_mod_eq_zero ];
        exact Eq.trans ( by solve_by_elim ) h_crt.symm;
      rw [ Nat.modEq_iff_dvd ] at *;
      have h_crt : (∏ p ∈ q.primeFactors.attach, (p : ℤ)) ∣ (∑ p ∈ q.primeFactors.attach, ((crtFrequencyEquiv q hq ξ p) * (crtRingEquiv q hq x p)).val * (q / p : ℕ)) - (ξ * x).val := by
        convert Finset.prod_dvd_of_coprime _ _;
        · intros p hp q hq hpq; exact (by
          have := Nat.coprime_primes ( Nat.prime_of_mem_primeFactors p.2 ) ( Nat.prime_of_mem_primeFactors q.2 ) ; aesop;);
        · exact fun p hp => by simpa using h_crt p hp |> Nat.ModEq.dvd;
      convert h_crt using 1;
      rw [ ← Nat.cast_prod ] ; norm_cast ; rw [ ← Nat.prod_primeFactors_of_squarefree hq ] ;
      refine' Finset.prod_bij ( fun p hp => ⟨ p, _ ⟩ ) _ _ _ _ <;> simp_all +decide [ Nat.primeFactors_prod ];
    obtain ⟨ k, hk ⟩ := h_crt.symm.dvd;
    use k;
    simp_all +decide [ ← @Int.cast_inj ℂ ];
    rw [ div_sub', eq_div_iff ] <;> norm_cast at * <;> simp_all +decide [ NeZero.ne ];
    convert hk.symm using 1 ; ring;
    rw [ Finset.mul_sum _ _ _ ] ; refine' congr_arg _ ( Finset.sum_congr rfl fun p hp => _ ) ; rw [ Nat.cast_div ( Nat.dvd_of_mem_primeFactors p.2 ) ( Nat.cast_ne_zero.mpr <| Nat.ne_of_gt <| Nat.pos_of_mem_primeFactors p.2 ) ] ; ring;
  obtain ⟨ n, hn ⟩ := h_exp; simp_all +decide [ Complex.exp_eq_exp_iff_exists_int, mul_div_assoc, mul_assoc, mul_comm, mul_left_comm ] ;
  exact ⟨ n, by rw [ hn ] ; simp [ Finset.mul_sum _ _ _, mul_sub, mul_comm ] ⟩

/-! ### Fourier synthesis helper lemmas -/

/-
The sum of `‖dft I_S (-ξ)‖` over all `ξ` equals the sum of `‖dft I_S ξ‖` by reindexing
(`ξ ↦ -ξ` is a bijection on the group).
-/
lemma sum_norm_dft_neg_eq (q : ℕ) [NeZero q] (m : ℕ) (f : (Fin m → ZMod q) → ℂ) :
    ∑ ξ : Fin m → ZMod q, ‖dft q m f (-ξ)‖ =
    ∑ ξ : Fin m → ZMod q, ‖dft q m f ξ‖ := by
  apply Finset.sum_bij (fun ξ _ => -ξ);
  · exact fun _ _ => Finset.mem_univ _;
  · aesop;
  · exact fun b _ => ⟨ -b, Finset.mem_univ _, neg_neg b ⟩;
  · grind

/-
**Spatial → Frequency swap.** Using DFT inversion on `f_dev` and swapping sums
(Fubini), we obtain
`∑ h, I_S(h) * f(h) = ∑ ξ, q^m * dft(f)(ξ) * dft(I_S)(-ξ)`.
-/
public lemma spatial_to_frequency_swap (q : ℕ) [NeZero q] (m : ℕ)
    (f g : (Fin m → ZMod q) → ℂ) :
    ∑ h, g h * f h =
      ∑ ξ : Fin m → ZMod q,
        ((q : ℂ) ^ m) * dft q m f ξ * dft q m g (-ξ) := by
  -- By Fubini's theorem, we can interchange the order of summation.
  have h_fubini : ∑ h : Fin m → ZMod q, g h * (∑ ξ : Fin m → ZMod q, dft q m f ξ * character q m ξ h) = ∑ ξ : Fin m → ZMod q, dft q m f ξ * (∑ h : Fin m → ZMod q, g h * character q m ξ h) := by
    simpa only [ mul_assoc, mul_left_comm, Finset.mul_sum _ _ _ ] using Finset.sum_comm;
  convert h_fubini using 2;
  · exact congrArg _ ( dft_inversion q m f _ );
  · unfold dft;
    field_simp;
    unfold character; congr! 2; simp +decide [ starRingEnd_additiveChar ] ;



/-- The cumulative sum map on `Fin m → ZMod q`. -/
@[expose]
public noncomputable def cumSum (q : ℕ) [NeZero q] (m : ℕ) (x : Fin m → ZMod q) :
    Fin m → ZMod q :=
  fun j => ∑ i ∈ Finset.Iic j, x i

/-- The difference map on `Fin m → ZMod q` (inverse of cumulative sum). -/
@[expose]
public noncomputable def diffMap (q : ℕ) [NeZero q] (m : ℕ) (y : Fin m → ZMod q) :
    Fin m → ZMod q :=
  fun j => y j - if h : (j : ℕ) = 0 then 0 else y ⟨j - 1, by omega⟩

/-
`diffMap` is a left inverse of `cumSum`.
-/
public lemma diffMap_cumSum (q : ℕ) [NeZero q] (m : ℕ) (x : Fin m → ZMod q) :
    diffMap q m (cumSum q m x) = x := by
  unfold cumSum diffMap; ext j; induction j ; simp +decide [*] ;
  induction' ‹ℕ› with n ih <;> simp_all +decide;
  · rw [ show ( Iic ⟨ 0, by assumption ⟩ : Finset ( Fin m ) ) = { ⟨ 0, by assumption ⟩ } by ext ⟨ i, hi ⟩ ; aesop ] ; norm_num;
  · rw [ show ( Iic ⟨ n + 1, by linarith ⟩ : Finset ( Fin m ) ) = Iic ⟨ n, by linarith ⟩ ∪ { ⟨ n + 1, by linarith ⟩ } from ?_, Finset.sum_union ] <;> norm_num [ Finset.sum_singleton, Finset.sum_union, Finset.disjoint_singleton_right ];
    grind +locals

/-
`cumSum` is a left inverse of `diffMap`.
-/
public lemma cumSum_diffMap (q : ℕ) [NeZero q] (m : ℕ) (y : Fin m → ZMod q) :
    cumSum q m (diffMap q m y) = y := by
  funext j;
  induction' j with j ih;
  induction' j with j ih;
  · unfold cumSum diffMap; simp +decide ;
    rw [ show ( Iic ⟨ 0, ih ⟩ : Finset ( Fin m ) ) = { ⟨ 0, ih ⟩ } by ext ⟨ i, hi ⟩ ; aesop ] ; aesop;
  · unfold cumSum diffMap at *;
    rw [ show ( Iic ⟨ j + 1, ih ⟩ : Finset ( Fin m ) ) = Finset.Iic ⟨ j, by linarith ⟩ ∪ { ⟨ j + 1, ih ⟩ } from ?_, Finset.sum_union ] <;> norm_num;
    · rename_i h; specialize h ( Nat.lt_of_succ_lt ih ) ; simp_all +decide [ Finset.sum_sub_distrib ] ;
    · grind

/-- The cumulative sum map is an equivalence. -/
@[expose]
public noncomputable def cumSumEquiv (q : ℕ) [NeZero q] (m : ℕ) :
    (Fin m → ZMod q) ≃ (Fin m → ZMod q) where
  toFun := cumSum q m
  invFun := diffMap q m
  left_inv := diffMap_cumSum q m
  right_inv := cumSum_diffMap q m

/-- The frequency differencing operator. -/
private noncomputable def freqDiff (q : ℕ) [NeZero q] (m : ℕ) (ξ : Fin m → ZMod q) :
    Fin m → ZMod q :=
  fun j => ξ j - if h_lt : (j : ℕ) + 1 < m then ξ ⟨(j : ℕ) + 1, h_lt⟩ else 0

/-
Character identity: the character at frequency ξ evaluated at x equals the character
at frequency `freqDiff ξ` evaluated at `cumSum x`. This is Abel summation by parts.
-/
private lemma character_cumSum_eq (q : ℕ) [NeZero q] (m : ℕ)
    (ξ x : Fin m → ZMod q) :
    character q m ξ x = character q m (freqDiff q m ξ) (cumSum q m x) := by
  -- By Abel summation by parts, we can rewrite the sum of the products of ξ and x as the sum of the products of the frequency differences and the cumulative sums.
  have h_abel : ∑ j : Fin m, (ξ j) * (x j) = ∑ j : Fin m, (freqDiff q m ξ j) * (cumSum q m x j) := by
    induction' m with m ih;
    · rfl;
    · simp +decide [ Fin.sum_univ_castSucc, freqDiff, cumSum ] at *;
      rw [ show ( Finset.Iic ( Fin.last m ) : Finset ( Fin ( m + 1 ) ) ) = Finset.univ from Finset.eq_univ_of_forall fun i => Finset.mem_Iic.mpr ( Fin.le_last _ ) ] ; simp +decide [Fin.sum_univ_castSucc] ; ring_nf;
      rw [ add_comm, Finset.sum_sub_distrib ];
      simp +decide [add_assoc, Finset.mul_sum _ _ _, ih];
      rw [ ← Finset.sum_sub_distrib ] ; rw [ ← Finset.sum_add_distrib ] ; congr ; ext i ; split_ifs <;> simp_all +decide [add_comm] ; ring_nf;
      · rw [ ← Finset.sum_sub_distrib ];
        refine Finset.sum_bij (fun a _ => a.castSucc) ?_ ?_ ?_ ?_
        · intro a ha; simp [Finset.mem_Iic] at ha ⊢; exact Fin.castSucc_le_castSucc_iff.mpr ha
        · intro a₁ _ a₂ _ h; exact Fin.castSucc_injective _ h
        · intro b hb
          simp [Finset.mem_Iic] at hb
          have hb_lt : (b : ℕ) < m := Fin.lt_def.mp (lt_of_le_of_lt hb (Fin.castSucc_lt_last i))
          exact ⟨⟨(b : ℕ), hb_lt⟩, Finset.mem_Iic.mpr (by simp [Fin.le_iff_val_le_val] at hb ⊢; exact hb), by simp⟩
        · intro a _; rfl;
      · cases ‹m ≤ i + 1›.eq_or_lt <;> simp_all +decide [Fin.last];
        · repeat rw [ show ( Iic i.castSucc : Finset ( Fin ( m + 1 ) ) ) = Finset.image ( Fin.castSucc ) ( Iic i ) from ?_, Finset.sum_image ] <;> norm_num [ Fin.ext_iff ];
        · linarith [ Fin.is_lt i ];
  unfold character;
  unfold additiveChar; simp_all +decide ;
  convert Complex.exp_eq_exp_iff_exists_int.mpr _ using 1;
  rw [ ← Complex.exp_sum ];
  rw [ ← Complex.exp_sum ];
  use ( ∑ j : Fin m, ( ξ j * x j |> ZMod.val ) - ∑ j : Fin m, ( freqDiff q m ξ j * cumSum q m x j |> ZMod.val ) ) / q;
  rw [ Int.cast_div ] <;> norm_num [ ← Finset.sum_div _ _ _, h_abel ];
  · simp +decide [← Finset.mul_sum _ _ _] ; ring;
  · simp_all +decide [ ← ZMod.intCast_zmod_eq_zero_iff_dvd ];
  · exact NeZero.out

public lemma dft_sum_transform (q : ℕ) [NeZero q] (m : ℕ)
    (g : (Fin m → ZMod q) → ℂ) (ξ : Fin m → ZMod q) :
    dft q m (fun x => g (fun j => ∑ i ∈ Finset.Iic j, x i)) ξ =
    dft q m g (fun j => ξ j - if h_lt : (j : ℕ) + 1 < m then ξ ⟨(j : ℕ) + 1, h_lt⟩ else 0) := by
  -- By changing variables using the equivalence between the sum over x and the sum over y, we can rewrite the left-hand side.
  have h_change_var : ∑ x : Fin m → ZMod q, g (cumSum q m x) * starRingEnd ℂ (character q m ξ x) = ∑ y : Fin m → ZMod q, g y * starRingEnd ℂ (character q m (freqDiff q m ξ) y) := by
    apply Finset.sum_bij (fun x _ => cumSum q m x);
    · grind;
    · intro a₁ _ a₂ _ h; have := diffMap_cumSum q m a₁; have := diffMap_cumSum q m a₂; aesop;
    · exact fun b _ => ⟨ diffMap q m b, Finset.mem_univ _, cumSum_diffMap q m b ⟩;
    · exact fun x _ => by rw [ character_cumSum_eq ] ;
  unfold dft; aesop;

/-
The integer-to-ZMod map is injective on {1, ..., n} when n < q.
-/
private lemma intCast_injective_on_range (q : ℕ) [NeZero q] {n : ℕ} (hn : n < q)
    {a b : ℤ} (ha : a ∈ Finset.Icc 1 (n : ℤ)) (hb : b ∈ Finset.Icc 1 (n : ℤ))
    (heq : (a : ZMod q) = (b : ZMod q)) : a = b := by
  rw [ ZMod.intCast_eq_intCast_iff ] at heq;
  rw [ Int.ModEq ] at heq ; rw [ Int.emod_eq_of_lt, Int.emod_eq_of_lt ] at heq <;> linarith [ Finset.mem_Icc.mp ha, Finset.mem_Icc.mp hb ] ;

/-
The difference map from cumulative h to increments d_j = h_j - h_{j-1} relates
    `inScaledBox X s 0 h` to the product condition `∀ j, d_j ∈ {1,...,⌊s*b_j⌋}`,
    which is exactly `boxIndicator`.
-/
private lemma inScaledBox_iff_boxIndicator_diffs (q : ℕ) [NeZero q] (k : ℕ) (hk : 2 ≤ k)
    (X : Box (k - 1)) (s : ℝ) (hs : 0 ≤ s)
    (h : Fin (k - 1) → ℤ)
    (hrange : h ∈ (Fintype.piFinset fun _ => Finset.Icc (1 : ℤ) ⌈s * ∑ i, X.sides i⌉)) :
    inScaledBox X s (fun _ => 0) h ↔
    ∀ j : Fin (k - 1),
      let d_j : ℤ := h j - if (j : ℕ) = 0 then 0 else h ⟨j - 1, by omega⟩
      1 ≤ d_j ∧ d_j ≤ ⌊s * X.sides j⌋ := by
  constructor <;> intro H <;> simp_all +decide [ inScaledBox ];
  · intro j; specialize H j; split_ifs at H ⊢ <;> norm_cast at *;
    · exact ⟨ by linarith, Int.le_of_lt_add_one <| by rw [ ← @Int.cast_lt ℝ ] ; push_cast; linarith [ Int.lt_floor_add_one ( s * X.sides j ) ] ⟩;
    · exact ⟨ by linarith, Int.le_of_lt_add_one <| by rw [ ← @Int.cast_lt ℝ ] ; push_cast; linarith [ Int.lt_floor_add_one ( s * X.sides j ) ] ⟩;
  · intro i; specialize H i; split_ifs at * <;> norm_cast at * ;
    · exact ⟨ by linarith, by linarith [ Int.floor_le ( s * X.sides i ), ( by norm_cast; linarith : ( h i : ℝ ) ≤ ⌊s * X.sides i⌋ ) ] ⟩;
    · exact ⟨ by linarith, by linarith [ Int.floor_le ( s * X.sides i ), show ( h i : ℝ ) ≤ ⌊s * X.sides i⌋ + h ⟨ i - 1, Nat.lt_of_le_of_lt ( Nat.sub_le _ _ ) i.2 ⟩ by exact_mod_cast H.2 ] ⟩

/-
Step 1: Change variables from cumulative h to differences d.
The map `h → d` where `d_j = h_j - h_{j-1}` is a bijection from
`inScaledBox` lattice points to the product interval `∏_j {1,...,⌊s*b_j⌋}`.
-/
set_option maxHeartbeats 800000 in
public lemma inScaledBox_sum_eq_diff_sum (k : ℕ) (hk : 2 ≤ k)
    (q : ℕ) [NeZero q] (X : Box (k - 1)) (s : ℝ) (hs : 0 ≤ s)
    (f : (Fin (k - 1) → ℤ) → ℂ) :
    ∑ h ∈ (Fintype.piFinset fun _ => Finset.Icc (1 : ℤ) ⌈s * ∑ i, X.sides i⌉).filter
        (fun h => inScaledBox X s (fun _ => 0) h),
      f h =
    ∑ d ∈ Fintype.piFinset (fun j : Fin (k - 1) => Finset.Icc 1 ⌊s * X.sides j⌋),
      f (fun j => ∑ i ∈ Finset.Iic j, d i) := by
  apply Finset.sum_bij (fun h _ => fun j => h j - if j.val = 0 then 0 else h ⟨j.val - 1, by omega⟩) _ _ _ _ <;> simp_all +decide [Finset.mem_filter];
  · intro a ha hX a_3; specialize hX a_3; split_ifs at * <;> simp_all +decide ;
    · exact Int.le_floor.2 hX.2;
    · exact ⟨ by linarith, Int.le_of_lt_add_one <| by rw [ ← @Int.cast_lt ℝ ] ; push_cast; linarith [ Int.lt_floor_add_one ( s * X.sides a_3 ) ] ⟩;
  · intro a₁ ha₁ ha₂ a₂ ha₃ ha₄ h; ext j; induction' j with j ih; simp_all +decide [ funext_iff ] ;
    induction' j with j ih <;> simp_all +decide [ Fin.forall_iff ];
    · simpa using h 0 ih;
    · grind;
  · intro b hb
    use fun j => ∑ i ∈ Finset.Iic j, b i
    constructor
    all_goals generalize_proofs at *;
    · refine' ⟨ _, _ ⟩
      all_goals generalize_proofs at *;
      · intro a
        have h_sum_le : ∑ i ∈ Finset.Iic a, b i ≤ ∑ i, ⌊s * X.sides i⌋ := by
          exact le_trans ( Finset.sum_le_sum fun _ _ => hb _ |>.2 ) ( Finset.sum_le_sum_of_subset_of_nonneg ( Finset.subset_univ _ ) fun _ _ _ => Int.floor_nonneg.mpr ( mul_nonneg hs ( X.sides_pos _ |> le_of_lt ) ) )
        have h_sum_ge : 1 ≤ ∑ i ∈ Finset.Iic a, b i := by
          exact le_trans ( hb a |>.1 ) ( Finset.single_le_sum ( fun i _ => by linarith [ hb i ] ) ( by simp ) )
        exact ⟨h_sum_ge, by
          exact le_trans h_sum_le ( Int.le_of_lt_add_one <| by rw [ ← @Int.cast_lt ℝ ] ; push_cast; nlinarith [ Int.le_ceil ( s * ∑ i, X.sides i ), show ( ∑ i : Fin ( k - 1 ), ⌊s * X.sides i⌋ : ℝ ) ≤ s * ∑ i : Fin ( k - 1 ), X.sides i from by rw [ Finset.mul_sum _ _ _ ] ; exact Finset.sum_le_sum fun i _ => Int.floor_le _ ] ) ;⟩;
      · intro j; specialize hb j; rcases j with ⟨ _ | j, hj ⟩ <;> simp_all +decide ;
        · rw [ show ( Iic ⟨ 0, hj ⟩ : Finset ( Fin ( k - 1 ) ) ) = { ⟨ 0, hj ⟩ } by ext ⟨ i, hi ⟩ ; aesop ] ; norm_num ; exact ⟨ by norm_cast; linarith, by exact Int.le_floor.mp hb.2 ⟩ ;
        · rw [ show ( Iic ⟨ j + 1, hj ⟩ : Finset ( Fin ( k - 1 ) ) ) = Iic ⟨ j, by omega ⟩ ∪ { ⟨ j + 1, hj ⟩ } from ?_, Finset.sum_union ] <;> norm_num [ Finset.sum_singleton, Finset.sum_Ioc_succ_top, (Nat.succ_eq_succ ▸ Finset.Icc_succ_left_eq_Ioc) ] at *;
          · exact ⟨ by linarith, by linarith [ show ( b ⟨ j + 1, hj ⟩ : ℝ ) ≤ s * X.sides ⟨ j + 1, hj ⟩ from le_trans ( mod_cast hb.2 ) ( Int.floor_le _ ) ] ⟩;
          · grind;
    · ext j; rcases j with ⟨ _ | j, hj ⟩ <;> simp +decide ; ring_nf;
      · rw [ show ( Iic ⟨ 0, hj ⟩ : Finset ( Fin ( k - 1 ) ) ) = { ⟨ 0, hj ⟩ } by ext ⟨ i, hi ⟩ ; aesop ] ; norm_num;
      · rw [ show ( Iic ⟨ j + 1, hj ⟩ : Finset ( Fin ( k - 1 ) ) ) = Iic ⟨ j, by omega ⟩ ∪ { ⟨ j + 1, hj ⟩ } from ?_, Finset.sum_union ] <;> norm_num [ Finset.sum_singleton, Finset.mem_Iic ];
        ext ⟨ i, hi ⟩ ; simp +decide [le_iff_lt_or_eq] ; omega;
  · intro a ha h; congr; ext j; rw [ show ( ∑ x ∈ Iic j, a x ) = ∑ x ∈ Iic j, ( if x.val = 0 then 0 else a ⟨ x.val - 1, by omega ⟩ ) + a j from ?_ ] ; ring;
    induction' j with j ih;
    induction' j with j ih <;> simp_all +decide [Finset.sum_ite];
    · rw [ show ( Iic ⟨ 0, ih ⟩ : Finset ( Fin ( k - 1 ) ) ) = { ⟨ 0, ih ⟩ } by ext ⟨ x, hx ⟩ ; aesop ] ; aesop;
    · rw [ show ( Iic ⟨ j + 1, by linarith ⟩ : Finset ( Fin ( k - 1 ) ) ) = Finset.Iic ⟨ j, by linarith ⟩ ∪ { ⟨ j + 1, by linarith ⟩ } from ?_, Finset.sum_union ] <;> norm_num [ Finset.sum_singleton, Finset.sum_union, Finset.sum_Ioc_succ_top, (Nat.succ_eq_succ ▸ Finset.Icc_succ_left_eq_Ioc) ];
      · rw [ Finset.sum_filter, Finset.sum_insert ] <;> norm_num [ ih ( by linarith ) ];
        rw [ add_comm, Finset.sum_ite ] ; aesop;
      · ext ⟨ x, hx ⟩ ; simp +decide [ Fin.le_iff_val_le_val ] ; omega;

/-
Step 2: Map integer differences to ZMod q. Under `hbox` (⌊s*b_j⌋₊ < q),
the map `d_j → (d_j : ZMod q)` is a bijection from the integer interval `{1,...,⌊s*b_j⌋}`
to ZMod q elements with `val ∈ {1,...,⌊s*b_j⌋₊}`, which is the support of `boxIndicator`.
-/
private lemma diff_sum_eq_zmod_sum (k : ℕ) (hk : 2 ≤ k)
    (q : ℕ) [NeZero q] (X : Box (k - 1)) (s : ℝ) (hs : 0 ≤ s)
    (hbox : ∀ j : Fin (k - 1), ⌊s * X.sides j⌋₊ < q)
    (g : (Fin (k - 1) → ZMod q) → ℂ) :
    ∑ d ∈ Fintype.piFinset (fun j : Fin (k - 1) => Finset.Icc 1 ⌊s * X.sides j⌋),
      g (fun i => (∑ j ∈ Finset.Iic i, d j : ZMod q)) =
    ∑ x : Fin (k - 1) → ZMod q,
      boxIndicator q (k - 1) X s x * g (cumSum q (k - 1) x) := by
  -- The set of `x : Fin (k - 1) → ZMod q` where `boxIndicator X s x ≠ 0` is exactly the image of `piFinset (fun j => Icc 1 ⌊s * X.sides j⌋)` under the standard map `d ↦ (fun j => (d j : ZMod q))`.
  have h_image : {x : Fin (k - 1) → ZMod q | boxIndicator q (k - 1) X s x ≠ 0} =
    Set.image (fun d : Fin (k - 1) → ℤ => fun j => (d j : ZMod q)) (Fintype.piFinset fun j => Icc 1 ⌊s * X.sides j⌋) := by
      ext x; simp [boxIndicator];
      constructor <;> intro h;
      · use fun j => (x j).val;
        simp_all +decide [Pi.le_def];
        constructor <;> intro i <;> specialize h i;
        · rcases q with ( _ | _ | q ) <;> norm_cast;
          · grind;
          · grind;
          · exact Nat.one_le_cast.mpr h.1;
        · convert Int.ofNat_le.mpr h.2 using 1;
          · cases q <;> aesop;
          · exact Eq.symm <| Int.toNat_of_nonneg <| Int.floor_nonneg.2 <| mul_nonneg hs <| le_of_lt <| X.sides_pos i;
      · rcases h with ⟨ d, ⟨ hd₁, hd₂ ⟩, rfl ⟩ ; simp_all +decide [ Pi.le_def ] ;
        intro i; specialize hd₁ i; specialize hd₂ i; rcases d_i : d i with ( _ | _ | d_i ) <;> simp_all +decide ;
        · rw [ Int.le_floor ] at hd₂ ; norm_cast at *;
          rw [ Nat.mod_eq_of_lt ];
          · exact ⟨ hd₁, Nat.le_floor <| mod_cast hd₂ ⟩;
          · exact lt_of_le_of_lt ( Nat.le_floor <| mod_cast hd₂ ) ( hbox i );
        · tauto;
  -- By definition of `boxIndicator`, we can restrict the sum to the image of `piFinset (fun j => Icc 1 ⌊s * X.sides j⌋)`.
  have h_sum_image : ∑ x, boxIndicator q (k - 1) X s x * g (cumSum q (k - 1) x) =
      ∑ x ∈ Finset.image (fun d : Fin (k - 1) → ℤ => fun j => (d j : ZMod q)) (Fintype.piFinset fun j => Icc 1 ⌊s * X.sides j⌋), g (cumSum q (k - 1) x) := by
        rw [ ← Finset.sum_subset ];
        any_goals exact Finset.univ.filter fun x => boxIndicator q ( k - 1 ) X s x ≠ 0;
        · refine' Finset.sum_bij ( fun x hx => x ) _ _ _ _ <;> simp_all +decide [ Set.ext_iff ];
          · exact fun a x hx₁ hx₂ hx₃ => ⟨ x, fun i => ⟨ hx₁ i, hx₂ i ⟩, hx₃ ⟩;
          · exact fun a ha => ⟨ a, ⟨ fun i => ha i |>.1, fun i => ha i |>.2 ⟩, rfl ⟩;
          · grind +locals;
        · exact filter_subset (fun x => boxIndicator q (k - 1) X s x ≠ 0) univ;
        · aesop;
  rw [ h_sum_image, Finset.sum_image ];
  · unfold cumSum; aesop;
  · intros d hd d' hd' h_eq;
    ext j; specialize h_eq; replace h_eq := congr_fun h_eq j; simp_all +decide [ ZMod.intCast_eq_intCast_iff ] ;
    rw [ Int.ModEq ] at h_eq;
    rw [ Int.emod_eq_of_lt, Int.emod_eq_of_lt ] at h_eq;
    · exact h_eq;
    · exact le_trans ( by norm_num ) ( hd'.1 j );
    · exact lt_of_le_of_lt ( hd'.2 j ) ( Int.floor_lt.mpr ( Nat.lt_of_floor_lt ( hbox j ) ) );
    · exact le_trans ( by norm_num ) ( hd.1 j );
    · exact lt_of_le_of_lt ( hd.2 j ) ( Int.floor_lt.mpr ( Nat.lt_of_floor_lt ( hbox j ) ) )

/-- The sum over integer lattice points in the scaled box equals the `ZMod q` sum
weighted by `boxIndicator`, under the change of variables from cumulative
positions to differences. -/
public lemma inScaledBox_sum_eq_zmod_sum (k : ℕ) (hk : 2 ≤ k)
    (q : ℕ) [NeZero q] (X : Box (k - 1)) (s : ℝ) (hs : 0 ≤ s)
    (hbox : ∀ j : Fin (k - 1), ⌊s * X.sides j⌋₊ < q)
    (g : (Fin (k - 1) → ZMod q) → ℂ) :
    ∑ h ∈ (Fintype.piFinset fun _ => Finset.Icc (1 : ℤ) ⌈s * ∑ i, X.sides i⌉).filter
        (fun h => inScaledBox X s (fun _ => 0) h),
      g (fun i => (h i : ZMod q)) =
    ∑ x : Fin (k - 1) → ZMod q,
      boxIndicator q (k - 1) X s x * g (cumSum q (k - 1) x) := by
  rw [inScaledBox_sum_eq_diff_sum k hk q X s hs
    (fun h => g (fun i => (h i : ZMod q)))]
  convert diff_sum_eq_zmod_sum k hk q X s hs hbox g using 1
  congr 1; ext d; congr 1; ext i
  simp only [Int.cast_sum]


end PoissonCRT
