/-
Copyright (c) 2026 Fernando Portela. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Fernando Portela
-/

/-
Portions of this file were generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.28.0
Mathlib version: 8f9d9cff6bd728b17a24e163c9402775d9e6a365

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
PROVIDED SOLUTION

# Task: Prove `local_deviation_fourier_bound` and `deviation_fourier_synthesis`

**Target File:** `PoissonViaCRT/FourierANOVA.lean`

## Task 1: Prove `local_deviation_fourier_bound`

This lemma states that under the `WellDistributedFourier` hypothesis, the Fourier transform of the local deviation function `fourierLocalDeviation` is bounded pointwise by `p^{-ε} · |Ω_p| / p^{k-1}`.

### Proof Strategy

Split on whether `ξ = 0` or `ξ ≠ 0`:

1. **Case `ξ = 0`:** Use the already-proved `fourierLocalDeviation_dft_zero` (which shows `dft(fourierLocalDeviation)(0) = 0`). The norm of zero is zero, which is `≤` the RHS (since the RHS is non-negative by `positivity`).

2. **Case `ξ ≠ 0`:** The DFT of `fourierLocalDeviation` at `ξ ≠ 0` equals the DFT of `tupleCount` at `ξ` minus the DFT of the constant `μ_p` at `ξ`. But the DFT of a constant at `ξ ≠ 0` vanishes (by `dft_const_nonzero`, already proved in this file). So `dft(fourierLocalDeviation)(ξ) = dft(tupleCount)(ξ)`, and the `WellDistributedFourier` hypothesis `hwd` directly gives the bound.

### Key Lemmas Available
- `fourierLocalDeviation_dft_zero` — proved, gives `dft(dev)(0) = 0`
- `dft_const_nonzero` — proved, gives `dft(const)(ξ) = 0` for `ξ ≠ 0`
- `fourierLocalDeviation` — defined as `tupleCount - μ` (complex-valued)
- The hypothesis `hwd : WellDistributedFourier ε p (Ω p) k` directly bounds the DFT of `tupleCount`

### Important Details
- `fourierLocalDeviation k Ω p h = (tupleCount (Ω p) (Fin.cons 0 h) : ℂ) - (((Ω p).card : ℝ) ^ k / (p : ℝ) ^ (k - 1) : ℝ)`
- The DFT is **linear**, so `dft(f - g) = dft(f) - dft(g)`.
- You may need to show linearity of `dft` explicitly or use `Finset.sum_sub_distrib` after unfolding.

## Task 2: Close the inner `sorry` in `deviation_fourier_synthesis`

The proof skeleton is already in place with:
- `hlem1`: The spatial→frequency swap identity
- `hlem2`: The `L∞` bound on `dft(f_dev)(ξ)` (calls `deviation_dft_linf_bound`, currently sorry'd — but it's available as a hypothesis in scope)
- `hC_bound`: The box `L¹` bound (from `box_fourier_l1_bound`, also sorry'd but available)

### Proof Strategy for `hlem3`

Starting from `hlem1`:
```
∑ h, I_S(h) · f_dev(h) = ∑ ξ, q^{k-1} · dft(f_dev)(ξ) · dft(I_S)(-ξ)
```

1. **Take norms** of both sides: `‖LHS‖ = ‖RHS‖`.
2. **Triangle inequality** on the RHS: `‖∑ ξ ...‖ ≤ ∑ ξ ‖...‖`.
3. **Factor each term**: `‖q^{k-1} · dft(f_dev)(ξ) · dft(I_S)(-ξ)‖ = q^{k-1} · ‖dft(f_dev)(ξ)‖ · ‖dft(I_S)(-ξ)‖`.
4. **Apply `hlem2`** to bound `‖dft(f_dev)(ξ)‖ ≤ q^{-ε} · |Ω_q| / q^{k-1}`.
5. **Factor out** the constant `q^{k-1} · q^{-ε} · |Ω_q| / q^{k-1} = q^{-ε} · |Ω_q|`.
6. **Sum** `∑ ξ ‖dft(I_S)(-ξ)‖ = ∑ ξ ‖dft(I_S)(ξ)‖` (by `sum_norm_dft_neg_eq`).
7. **Apply `hC_bound`**: `∑ ξ ‖dft(I_S)(ξ)‖ ≤ C · (log q)^{k-1}`.
8. **Multiply**: `q^{-ε} · |Ω_q| · C · (log q)^{k-1} = C · (log q)^{k-1} · q^{-ε} · |Ω_q|`.

### Key Lemmas Available
- `sum_norm_dft_neg_eq` — already proved in the file
- `norm_mul` — from Mathlib
- `Finset.sum_le_sum` — from Mathlib
- `norm_sum_le` (or `Finset.norm_sum_le`) — triangle inequality for norms
- `hC_bound` from `box_fourier_l1_bound` — in scope via the outer `obtain`

## Build Verification
After completing both proofs, the file should build successfully. The `sorry` count in `FourierANOVA.lean` should drop from 5 to 3 (the remaining 3 being `WellDistributed_implies_WellDistributedFourier`, `box_fourier_1d_bound`, and `deviation_dft_linf_bound`).

-/

import PoissonViaCRT.Defs
import PoissonViaCRT.CRTMultiplicativity
import PoissonViaCRT.DeviationBoundHelper

set_option linter.unusedVariables false

/-!
# Fourier ANOVA for the Deviation Bound

This file scaffolds the **Fourier ANOVA** (Analysis of Variance) machinery for proving
the uniform deviation bound in Proposition 3.6 of Granville–Kurlberg
(arXiv:math/0412135v2, §3.2).

Instead of the combinatorial Gamma-structure decomposition, we expand the deviation
$N_k(h, \Omega_q) - \mu$ in terms of the discrete Fourier transform on the finite
abelian group $G = (\mathbb{Z}/q\mathbb{Z})^{k-1}$, factor the Fourier coefficients
via CRT, and bound the resulting sum using exponential-sum estimates from the
`WellDistributed` hypothesis.

## Main Definitions

* `PoissonCRT.rootOfUnity`: The primitive $q$-th root of unity $e^{2\pi i / q}$.
* `PoissonCRT.character`: The additive character
  $\chi_\xi(x) = e^{2\pi i \langle \xi, x \rangle / q}$.
* `PoissonCRT.dft`: The discrete Fourier transform on $(\mathbb{Z}/q\mathbb{Z})^m$.
* `PoissonCRT.fourierLocalDeviation`: The local deviation function
  $\operatorname{dev}_p(h) = N_k(h, \Omega_p) - \mu_p$.
* `PoissonCRT.boxIndicator`: The indicator function of the scaled box $s \cdot X$
  in $(\mathbb{Z}/q\mathbb{Z})^m$.

## Main Results (stubbed)

* `PoissonCRT.character_orthogonality`: Orthogonality of additive characters.
* `PoissonCRT.plancherel_identity`: Plancherel / Parseval identity on $G$.
* `PoissonCRT.dft_inversion`: Fourier inversion formula.
* `PoissonCRT.fourierLocalDeviation_dft_zero`: The Fourier transform of the local deviation
  vanishes at the zero frequency.
* `PoissonCRT.local_deviation_fourier_bound`: $L^\infty$ bound on the local
  deviation Fourier coefficients using `WellDistributed`.
* `PoissonCRT.box_fourier_l1_bound`: The $L^1$-norm of the box indicator Fourier
  transform is $O((\log q)^{k-1})$.

## References

* [A. Granville, P. Kurlberg, *Poisson statistics via the Chinese remainder theorem*]
  [arXiv:math/0412135v2], §3.2
* See `docs/fourier_anova_blueprint.md` for the full mathematical blueprint.
-/

open Finset BigOperators Classical Complex

namespace PoissonCRT

/-! ### Additive characters on `ZMod q` -/

/-- The primitive `q`-th root of unity $\omega_q = e^{2\pi i / q}$. -/
noncomputable def rootOfUnity (q : ℕ) [NeZero q] : ℂ :=
  Complex.exp (2 * Real.pi * Complex.I / (q : ℂ))

/-- The additive character $\chi_a(x) = \omega_q^{a \cdot x}$ on `ZMod q`.
Here `a` and `x` are elements of `ZMod q`, and we lift the product `a * x` to `ℤ`
via `ZMod.val` before exponentiating. -/
noncomputable def additiveChar (q : ℕ) [NeZero q] (a : ZMod q) (x : ZMod q) : ℂ :=
  Complex.exp (2 * Real.pi * Complex.I * ((a * x).val : ℂ) / (q : ℂ))

/-- The product character on `(ZMod q)^m`. Given a frequency vector `ξ : Fin m → ZMod q`
and a point `x : Fin m → ZMod q`, the character is
$\chi_\xi(x) = \prod_j \chi_{\xi_j}(x_j) = e^{2\pi i \langle \xi, x \rangle / q}$. -/
noncomputable def character (q : ℕ) [NeZero q] (m : ℕ)
    (ξ x : Fin m → ZMod q) : ℂ :=
  ∏ j : Fin m, additiveChar q (ξ j) (x j)

/-! ### Discrete Fourier Transform -/

/-- The **discrete Fourier transform** of `f : (ZMod q)^m → ℂ`.

$$\widehat{f}(\xi) = \frac{1}{q^m} \sum_{x \in (\mathbb{Z}/q\mathbb{Z})^m}
  f(x) \cdot \overline{\chi_\xi(x)}.$$ -/
noncomputable def dft (q : ℕ) [NeZero q] (m : ℕ)
    (f : (Fin m → ZMod q) → ℂ) (ξ : Fin m → ZMod q) : ℂ :=
  (1 / (q : ℂ) ^ m) * ∑ x : Fin m → ZMod q, f x * starRingEnd ℂ (character q m ξ x)

/-! ### Character properties -/

/-
`additiveChar q a x` can be written as a power of the primitive root
`exp(2πi·a.val/q)` raised to `x.val`.
-/
lemma additiveChar_eq_exp_pow (q : ℕ) [NeZero q] (a x : ZMod q) :
    additiveChar q a x =
      Complex.exp (2 * Real.pi * Complex.I * (a.val : ℂ) / (q : ℂ)) ^ x.val := by
  rw [ ← Complex.exp_nat_mul ] ; ring_nf;
  convert Complex.exp_eq_exp_iff_exists_int.mpr ?_ using 2 ; ring_nf;
  use -((a.val * x.val) / q);
  rw [ ZMod.val_mul ];
  rw [ Nat.mod_def ] ; ring_nf;
  rw [ Nat.cast_sub ( Nat.mul_div_le _ _ ) ] ; push_cast ; ring_nf;
  norm_cast ; simp +decide [ mul_assoc, mul_comm, mul_left_comm, NeZero.ne ]

/-
The `additiveChar` at `a = 0` is identically `1`.
-/
@[simp]
lemma additiveChar_zero (q : ℕ) [NeZero q] (x : ZMod q) :
    additiveChar q 0 x = 1 := by
  -- By definition of additiveChar, we have additiveChar q 0 x = Complex.exp (2 * Real.pi * Complex.I * (0 * x).val / (q : ℂ)).
  simp [additiveChar]

/-
The primitive `q`-th root of unity raised to `q` equals `1`.
-/
lemma exp_two_pi_I_val_pow_eq_one (q : ℕ) [NeZero q] (a : ZMod q) :
    Complex.exp (2 * Real.pi * Complex.I * (a.val : ℂ) / (q : ℂ)) ^ q = 1 := by
  rw [ ← Complex.exp_nat_mul, mul_comm, Complex.exp_eq_one_iff ];
  exact ⟨ a.val, by rw [ div_mul_cancel₀ _ ( NeZero.ne _ ) ] ; push_cast; ring ⟩

/-
For `a ≠ 0` in `ZMod q`, the primitive root `exp(2πi·a.val/q) ≠ 1`.
-/
lemma exp_two_pi_I_val_ne_one (q : ℕ) [NeZero q] (a : ZMod q) (ha : a ≠ 0) :
    Complex.exp (2 * Real.pi * Complex.I * (a.val : ℂ) / (q : ℂ)) ≠ 1 := by
  contrapose! ha;
  rw [ Complex.exp_eq_one_iff ] at ha;
  -- By simplifying, we can see that this implies $a.val = nq$ for some integer $n$.
  obtain ⟨n, hn⟩ := ha
  have h_eq : a.val = n * q := by
    rw [ div_eq_iff ] at hn;
    · exact_mod_cast ( mul_left_cancel₀ ( Complex.two_pi_I_ne_zero ) <| by linear_combination' hn : ( a.val : ℂ ) = n * q );
    · exact Nat.cast_ne_zero.mpr <| NeZero.ne q;
  replace h_eq := congr_arg ( ( ↑ ) : ℤ → ZMod q ) h_eq ; simp_all +decide

/-
**1D orthogonality of additive characters.**
$$\sum_{x \in \mathbb{Z}/q\mathbb{Z}} \chi_a(x) =
  \begin{cases} q & \text{if } a = 0, \\ 0 & \text{if } a \neq 0. \end{cases}$$
-/
lemma additiveChar_sum_eq_ite (q : ℕ) [NeZero q] (a : ZMod q) :
    ∑ x : ZMod q, additiveChar q a x = if a = 0 then (q : ℂ) else 0 := by
  split_ifs with ha;
  · aesop;
  · -- Rewrite each term using `additiveChar_eq_exp_pow` to get `∑ x, r^(x.val)` where `r = exp(2πi a.val/q)`.
    have h_exp : ∑ x : ZMod q, additiveChar q a x = ∑ x ∈ Finset.range q, (Complex.exp (2 * Real.pi * Complex.I * (a.val : ℂ) / (q : ℂ))) ^ x := by
      refine' Finset.sum_bij ( fun x _ => x.val ) _ _ _ _ <;> simp +decide [ additiveChar_eq_exp_pow ];
      · exact fun x => ZMod.val_lt x;
      · exact fun x y h => by simpa [ ZMod.natCast_zmod_val ] using congr_arg ( fun x : ℕ => x : ℕ → ZMod q ) h;
      · exact fun b hb => ⟨ b, ZMod.val_cast_of_lt hb ⟩;
    rw [ h_exp, geom_sum_eq ] <;> norm_num [ ha ];
    · exact Or.inl ( by rw [ sub_eq_zero, ← Complex.exp_nat_mul, mul_comm, Complex.exp_eq_one_iff ] ; use a.val; push_cast; ring_nf; norm_num [ NeZero.ne ] );
    · convert exp_two_pi_I_val_ne_one q a ha using 1;
      cases q <;> aesop

/-
The conjugate of `additiveChar q a x` equals `additiveChar q (-a) x`.
-/
lemma starRingEnd_additiveChar (q : ℕ) [NeZero q] (a x : ZMod q) :
    starRingEnd ℂ (additiveChar q a x) = additiveChar q (-a) x := by
  -- Apply the property of the conjugate of the exponential.
  have h_conj_exp : (starRingEnd ℂ) (Complex.exp (2 * Real.pi * Complex.I * ((a * x).val : ℂ) / (q : ℂ))) = Complex.exp (2 * Real.pi * Complex.I * (q - (a * x).val : ℤ) / (q : ℂ)) := by
    norm_num [ Complex.ext_iff, Complex.exp_re, Complex.exp_im ];
    norm_num [ sub_div, mul_sub, NeZero.ne ];
    erw [ ZMod.cast_eq_val ] ; norm_cast ; aesop;
  unfold additiveChar;
  cases eq_or_ne ( a * x ) 0 <;> simp_all +decide [ ZMod.neg_val ];
  rw [ Nat.cast_sub ];
  · cases q <;> aesop;
  · exact Nat.le_of_lt ( ZMod.val_lt _ )

/-
The product of characters satisfies `χ_ξ(x) · conj(χ_η(x)) = χ_{ξ-η}(x)`.
-/
lemma character_mul_conj (q : ℕ) [NeZero q] (m : ℕ)
    (ξ η x : Fin m → ZMod q) :
    character q m ξ x * starRingEnd ℂ (character q m η x) =
      character q m (ξ - η) x := by
  unfold character;
  rw [ map_prod, ← Finset.prod_mul_distrib ];
  refine' Finset.prod_congr rfl fun j _ => _;
  rw [ starRingEnd_additiveChar ];
  unfold additiveChar;
  rw [ ← Complex.exp_add ];
  rw [ Complex.exp_eq_exp_iff_exists_int ];
  use ((ξ j * x j).val + (-η j * x j).val - ((ξ j - η j) * x j).val) / q;
  rw [ Int.cast_div ] <;> norm_num;
  · ring;
  · simp +decide [ sub_mul, ← ZMod.intCast_zmod_eq_zero_iff_dvd ];
  · exact NeZero.ne q

/-
**Orthogonality of additive characters.** The sum of a non-trivial character over the
full group vanishes, and the sum of the trivial character is the group order:

$$\sum_{x \in G} \chi_\xi(x) \overline{\chi_\eta(x)} = |G| \cdot \delta_{\xi, \eta}.$$
-/
theorem character_orthogonality (q : ℕ) [NeZero q] (m : ℕ)
    (ξ η : Fin m → ZMod q) :
    ∑ x : Fin m → ZMod q, character q m ξ x * starRingEnd ℂ (character q m η x) =
      if ξ = η then ((q : ℂ) ^ m) else 0 := by
  -- By Fubini's theorem, we can interchange the order of summation.
  have h_fubini : ∑ x : Fin m → ZMod q, character q m (ξ - η) x = ∏ j : Fin m, ∑ x : ZMod q, additiveChar q ((ξ - η) j) x := by
    rw [ Finset.prod_sum ];
    refine' Finset.sum_bij ( fun x _ => fun i _ => x i ) _ _ _ _ <;> simp +decide [ character ];
    · simp +decide [ funext_iff ];
    · exact fun b => ⟨ fun i => b i ( Finset.mem_univ i ), funext fun i => funext fun _ => rfl ⟩;
  split_ifs with h <;> simp_all +decide [ character_mul_conj ];
  exact Finset.prod_eq_zero ( Finset.mem_univ ( Classical.choose ( Function.ne_iff.mp h ) ) ) ( by rw [ additiveChar_sum_eq_ite ] ; simp +decide [ sub_eq_zero, Classical.choose_spec ( Function.ne_iff.mp h ) ] )

/-
**Fourier inversion formula.**
$f(x) = \sum_{\xi \in G} \widehat{f}(\xi) \cdot \chi_\xi(x)$.
-/
theorem dft_inversion (q : ℕ) [NeZero q] (m : ℕ)
    (f : (Fin m → ZMod q) → ℂ) (x : Fin m → ZMod q) :
    f x = ∑ ξ : Fin m → ZMod q, dft q m f ξ * character q m ξ x := by
  simp +decide [ dft, Finset.mul_sum _ _ _, mul_comm, mul_left_comm ];
  -- By the orthogonality of the characters, the inner sum over ξ is q^m if x = y and 0 otherwise.
  have h_orthogonality : ∀ y : Fin m → ZMod q, ∑ ξ : Fin m → ZMod q, (character q m ξ x) * (starRingEnd ℂ (character q m ξ y)) = if x = y then (q : ℂ) ^ m else 0 := by
    convert character_orthogonality q m x using 1;
    unfold character; ring_nf;
    unfold additiveChar; simp +decide [ mul_comm ] ;
  rw [ Finset.sum_comm ];
  simp_all +decide [ ← Finset.mul_sum _ _ _ ]

/-! ### Plancherel / Parseval identity -/

/-
**Plancherel identity** on $(\mathbb{Z}/q\mathbb{Z})^m$:

$$\frac{1}{q^m} \sum_{x \in G} f(x) \cdot \overline{g(x)}
  = \sum_{\xi \in G} \widehat{f}(\xi) \cdot \overline{\widehat{g}(\xi)}.$$
-/
theorem plancherel_identity (q : ℕ) [NeZero q] (m : ℕ)
    (f g : (Fin m → ZMod q) → ℂ) :
    (1 / (q : ℂ) ^ m) * ∑ x : Fin m → ZMod q, f x * starRingEnd ℂ (g x) =
      ∑ ξ : Fin m → ZMod q, dft q m f ξ * starRingEnd ℂ (dft q m g ξ) := by
  unfold dft; simp +decide [ mul_assoc, Finset.mul_sum _ _ _, Finset.sum_mul ] ;
  -- By the orthogonality of the characters, the inner sum over ξ is zero unless x = y.
  have h_inner : ∀ x y : Fin m → ZMod q, ∑ ξ : Fin m → ZMod q, character q m ξ x * starRingEnd ℂ (character q m ξ y) = if x = y then (q : ℂ) ^ m else 0 := by
    intro x y;
    have := character_orthogonality q m;
    convert this x y using 1;
    unfold character; simp +decide
    unfold additiveChar; simp +decide [ mul_comm ] ;
  simp +decide only [mul_left_comm];
  rw [ Finset.sum_comm, Finset.sum_congr rfl ] ; intros ; rw [ Finset.sum_comm ] ; simp +decide [ ← Finset.mul_sum _ _ _ ] ; ring_nf;
  simp_all +decide [ mul_assoc, mul_comm, mul_left_comm, pow_mul ];
  simp +decide [ sq, mul_assoc, NeZero.ne ]

/-! ### Local deviation function -/

/-- The **local deviation function** at prime `p`:
$\operatorname{dev}_p(h) = N_k((0, h_1, \ldots, h_{k-1}), \Omega_p) - \mu_p$,
where $\mu_p = |\Omega_p|^k / p^{k-1}$ is the local expected value. -/
noncomputable def fourierLocalDeviation (k : ℕ) (Ω : ∀ p : ℕ, Finset (ZMod p))
    (p : ℕ) [NeZero p] (h : Fin (k - 1) → ZMod p) : ℂ :=
  (tupleCount (Ω p) (Fin.cons 0 h) : ℂ) - (((Ω p).card : ℝ) ^ k / (p : ℝ) ^ (k - 1) : ℝ)

/-
For any `t : ZMod p` and `S : Finset (ZMod p)`, the number of `h : ZMod p` with
`t + h ∈ S` equals `|S|`. This is because `h ↦ t + h` is a bijection on `ZMod p`.
-/
lemma card_filter_add_mem (p : ℕ) [NeZero p] (t : ZMod p) (S : Finset (ZMod p)) :
    (Finset.univ.filter fun h : ZMod p => t + h ∈ S).card = S.card := by
  -- The function h ↦ t + h is a bijection from ZMod p to ZMod p, so the cardinality of the preimage of S under this function is equal to the cardinality of S.
  have h_bij : Finset.image (fun h => t + h) (Finset.univ.filter (fun h => t + h ∈ S)) = S := by
    ext x; aesop;
  rw [ ← h_bij, Finset.card_image_of_injective _ ( add_right_injective t ) ];
  aesop

/-
Summing `tupleCount (Ω p) (Fin.cons 0 h)` over all `h` in `ℕ` form:
`∑ h, tupleCount (Ω p) (Fin.cons 0 h) = (Ω p).card ^ k`.
-/
theorem sum_tupleCount_eq_card_pow_nat (k : ℕ) (hk : 1 ≤ k) (p : ℕ) [NeZero p]
    (Ω : ∀ p : ℕ, Finset (ZMod p)) :
    (∑ h : Fin (k - 1) → ZMod p, tupleCount (Ω p) (Fin.cons 0 h)) =
      (Ω p).card ^ k := by
  unfold tupleCount;
  rcases k with ( _ | k ) <;> simp_all +decide [ Fin.forall_fin_succ ];
  -- For each fixed t ∈ Ω p, the number of h such that ∀ i, t + h i ∈ Ω p is exactly |Ω p|^k.
  have h_count : ∀ t ∈ Ω p, (Finset.univ.filter fun h : Fin k → ZMod p => ∀ i, t + h i ∈ Ω p).card = (Ω p).card ^ k := by
    intro t ht
    have h_count : (Finset.univ.filter fun h : Fin k → ZMod p => ∀ i, t + h i ∈ Ω p).card = (Finset.pi Finset.univ fun _ : Fin k => Finset.univ.filter fun h : ZMod p => t + h ∈ Ω p).card := by
      refine' Finset.card_bij ( fun h hh => fun i _ => h i ) _ _ _ <;> simp +decide [ funext_iff ];
      exact fun b hb => ⟨ fun i => b i ( Finset.mem_univ i ), hb, fun i => rfl ⟩;
    simp_all +decide [ Finset.card_univ ];
    exact congr_arg ( · ^ k ) ( by rw [ show Finset.filter ( fun h => t + h ∈ Ω p ) Finset.univ = Finset.image ( fun h => h - t ) ( Ω p ) by ext; aesop ] ; rw [ Finset.card_image_of_injective _ ( sub_left_injective ) ] );
  -- By Fubini's theorem, we can interchange the order of summation.
  have h_fubini : ∑ x : Fin k → ZMod p, (Finset.univ.filter fun t : ZMod p => t ∈ Ω p ∧ ∀ i, t + x i ∈ Ω p).card = ∑ t ∈ Ω p, (Finset.univ.filter fun x : Fin k → ZMod p => ∀ i, t + x i ∈ Ω p).card := by
    simp +decide only [card_filter];
    rw [ Finset.sum_comm ];
    rw [ ← Finset.sum_subset ( Finset.subset_univ ( Ω p ) ) ] <;> aesop;
  rw [ h_fubini, Finset.sum_congr rfl h_count, Finset.sum_const, Finset.card_eq_sum_ones, smul_eq_mul, mul_comm ] ; ring

/-- Summing `tupleCount (Ω p) (Fin.cons 0 h)` over all `h : Fin (k-1) → ZMod p`
yields `(Ω p).card ^ k`. The key idea: swap the sum over `h` and `t`, then for
each fixed `t ∈ Ω p`, the sum over each coordinate `h_i` of the indicator
`[t + h_i ∈ Ω p]` equals `|Ω p|` (as `h_i` ranges over all of `ZMod p`). -/
theorem sum_tupleCount_eq_card_pow (k : ℕ) (hk : 1 ≤ k) (p : ℕ) [NeZero p]
    (Ω : ∀ p : ℕ, Finset (ZMod p)) :
    (∑ h : Fin (k - 1) → ZMod p, (tupleCount (Ω p) (Fin.cons 0 h) : ℂ)) =
      ((Ω p).card : ℂ) ^ k := by
  exact_mod_cast sum_tupleCount_eq_card_pow_nat k hk p Ω

/- The original statement of `fourierLocalDeviation_sum_zero` omitted the hypothesis `1 ≤ k`.
   It is false when `k = 0`: ℕ subtraction gives `k - 1 = 0`, so `Fin.cons 0 h` has type
   `Fin 1 → ZMod p`, making the tuple count equal to `|Ω p|` while the mean term is
   `|Ω p|^0 / p^0 = 1`.  The corrected version below adds `(hk : 1 ≤ k)`. -/
-- theorem fourierLocalDeviation_sum_zero (k : ℕ) (p : ℕ) [NeZero p]
--     (Ω : ∀ p : ℕ, Finset (ZMod p)) :
--     ∑ h : Fin (k - 1) → ZMod p, fourierLocalDeviation k Ω p h = 0 := by
--   sorry

/-- The sum of the local deviation over all elements of $(\mathbb{Z}/p\mathbb{Z})^{k-1}$
is zero (the deviations from the mean cancel).

*Corrected*: requires `1 ≤ k`; the original statement is false for `k = 0`. -/
theorem fourierLocalDeviation_sum_zero (k : ℕ) (hk : 1 ≤ k) (p : ℕ) [NeZero p]
    (Ω : ∀ p : ℕ, Finset (ZMod p)) :
    ∑ h : Fin (k - 1) → ZMod p, fourierLocalDeviation k Ω p h = 0 := by
  unfold fourierLocalDeviation
  simp +decide [Finset.sum_sub_distrib]
  rw [mul_div_cancel₀]
  · exact sub_eq_zero_of_eq <| mod_cast sum_tupleCount_eq_card_pow k hk p Ω
  · exact pow_ne_zero _ (Nat.cast_ne_zero.mpr <| NeZero.ne p)

/- The original statement of `fourierLocalDeviation_dft_zero` omitted `1 ≤ k`; it inherits
   the same issue from `fourierLocalDeviation_sum_zero`. -/
-- theorem fourierLocalDeviation_dft_zero (k : ℕ) (p : ℕ) [NeZero p]
--     (Ω : ∀ p : ℕ, Finset (ZMod p)) :
--     dft p (k - 1) (fourierLocalDeviation k Ω p) 0 = 0 := by
--   sorry

/-- The Fourier transform of the local deviation vanishes at the zero frequency:
$\widehat{\operatorname{dev}}_p(0) = 0$. This is immediate from `fourierLocalDeviation_sum_zero`
and the definition of `dft`.

*Corrected*: requires `1 ≤ k`; see `fourierLocalDeviation_sum_zero`. -/
theorem fourierLocalDeviation_dft_zero (k : ℕ) (hk : 1 ≤ k) (p : ℕ) [NeZero p]
    (Ω : ∀ p : ℕ, Finset (ZMod p)) :
    dft p (k - 1) (fourierLocalDeviation k Ω p) 0 = 0 := by
  unfold dft; simp +decide
  unfold character; simp +decide [additiveChar_zero]
  exact Or.inr (fourierLocalDeviation_sum_zero k hk p Ω)

/-! ### Box indicator function -/

/-- The **box indicator function** on $(\mathbb{Z}/q\mathbb{Z})^m$. Given a box `B`
with side lengths $b_1, \ldots, b_m$ and a scaling parameter `s > 0`, the indicator
$I_S(x) = 1$ if $x$ lies in the scaled box $\{1, \ldots, \lfloor s b_j \rfloor\}^m$
(identified with elements of `ZMod q` via their canonical representatives), and
$I_S(x) = 0$ otherwise. -/
noncomputable def boxIndicator (q : ℕ) [NeZero q] (m : ℕ)
    (B : Box m) (s : ℝ) (x : Fin m → ZMod q) : ℂ :=
  if ∀ j : Fin m, (x j).val ∈ Finset.Icc 1 ⌊s * B.sides j⌋₊ then 1 else 0

/-! ### Exponential sum bounds from `WellDistributed` -/

/-- The Fourier-analytic analogue of `WellDistributed` from §3.2.
This hypothesis directly asserts the necessary $L^\\infty$ decay on the non-zero Fourier
coefficients of the local deviation function, bypassing the lossy spatial bound.
Specifically, it asserts that for $\\xi \\neq 0$, the Fourier coefficient is bounded by
$p^{-\\varepsilon} |\\Omega_p| / p^{k-1}$, which is necessary to offset the dual group volume. -/
def WellDistributedFourier (ε : ℝ) (p : ℕ) [Fact p.Prime] (Ω : Finset (ZMod p)) (k : ℕ) : Prop :=
  ∀ (ξ : Fin (k - 1) → ZMod p), ξ ≠ 0 →
    ‖dft p (k - 1) (fun h => (tupleCount Ω (Fin.cons 0 h) : ℂ)) ξ‖ ≤
    (p : ℝ) ^ (-ε) * ((Ω.card : ℝ) / (p : ℝ) ^ (k - 1))

/-- **Bridge: spatial → Fourier well-distribution.**
The paper's spatial hypothesis `WellDistributed` (pointwise bound on `|N_k - μ|` for
injective tuples) implies the Fourier hypothesis `WellDistributedFourier` (pointwise
bound on non-zero DFT coefficients of the counting function).

The proof uses the standard bound: each DFT coefficient is a weighted average of
`N_k(h) - μ` against characters, so the triangle inequality + the spatial bound gives
the Fourier bound up to a volume factor that is absorbed by the normalization. -/
lemma WellDistributed_implies_WellDistributedFourier
    (ε : ℝ) (p : ℕ) [Fact p.Prime] (Ω : Finset (ZMod p)) (k : ℕ)
    (hWD : WellDistributed ε p Ω k) :
    WellDistributedFourier ε p Ω k := by
  sorry

/--
**$L^\\infty$ bound on local deviation Fourier coefficients.** Under the `WellDistributedFourier`
hypothesis (which encodes the Weil bound cancellation from the convolution structure),
the Fourier transform of the local deviation function is bounded pointwise.

Note: by definition, `dft(deviation)(0) = 0`. For $\\xi \\neq 0$, the deviation FT equals
the FT of `tupleCount`, which is bounded by `WellDistributedFourier`.
-/
theorem local_deviation_fourier_bound (ε : ℝ) (_hε : 0 < ε)
    (p : ℕ) [hp : Fact p.Prime] (Ω : ∀ p : ℕ, Finset (ZMod p))
    (k : ℕ) (hk : 1 ≤ k)
    (hwd : WellDistributedFourier ε p (Ω p) k)
    (ξ : Fin (k - 1) → ZMod p) :
    ‖dft p (k - 1) (fourierLocalDeviation k Ω p) ξ‖ ≤
      (p : ℝ) ^ (-ε) * ((Ω p).card : ℝ) / (p : ℝ) ^ (k - 1) := by
  sorry

/-! ### Box Fourier transform decay -/

/-
The box indicator factors as a product of coordinate-wise 1D indicators:
`boxIndicator q m B s x = ∏ j, if (x j).val ∈ Icc 1 ⌊s * B.sides j⌋₊ then 1 else 0`.
This follows from the equivalence of `∀ j, P j` with the product of `if P j then 1 else 0`.
-/
lemma boxIndicator_eq_prod (q : ℕ) [NeZero q] (m : ℕ)
    (B : Box m) (s : ℝ) (x : Fin m → ZMod q) :
    boxIndicator q m B s x = ∏ j : Fin m,
      if (x j).val ∈ Finset.Icc 1 ⌊s * B.sides j⌋₊ then (1 : ℂ) else 0 := by
  unfold boxIndicator; split_ifs <;> simp_all +decide [ Finset.prod_ite ] ;

/-- The 1D analogue of the box Fourier L¹ bound: the sum of norms of 1D DFT
coefficients of a 1D box indicator is `O(log q)`, with a **universal** constant `C`
independent of `q` and `N`. Proof deferred (analytic hurdle). -/
lemma box_fourier_1d_bound :
    ∃ C : ℝ, 0 < C ∧ ∀ (q : ℕ) [NeZero q] (N : ℕ),
      ∑ ξ : ZMod q,
        ‖dft q 1 (fun x => if (x 0).val ∈ Finset.Icc 1 N then (1 : ℂ) else 0)
          (fun _ => ξ)‖ ≤
      C * Real.log q := by
  sorry

/-
The DFT of the box indicator factors as a product of 1D DFTs.
This relies on `boxIndicator_eq_prod` to factor the function and the fact that
`character q m ξ x = ∏ j, additiveChar q (ξ j) (x j)` factors over coordinates.
The sum over `x : Fin m → ZMod q` of the product then splits via `Fintype.prod_sum`.
-/
lemma dft_boxIndicator_eq_prod (q : ℕ) [NeZero q] (m : ℕ)
    (B : Box m) (s : ℝ) (ξ : Fin m → ZMod q) :
    dft q m (boxIndicator q m B s) ξ =
      ∏ j : Fin m, dft q 1
        (fun x => if (x 0).val ∈ Finset.Icc 1 ⌊s * B.sides j⌋₊ then (1 : ℂ) else 0)
        (fun _ => ξ j) := by
  unfold dft;
  nontriviality;
  simp +decide [ boxIndicator_eq_prod, Finset.prod_mul_distrib, Finset.prod_const ];
  rw [ Finset.prod_sum ];
  refine' Or.inl ( Finset.sum_bij ( fun x _ => fun i _ => fun _ => x i ) _ _ _ _ ) <;> simp +decide [ character ];
  · simp +decide [ funext_iff ];
  · exact fun b => ⟨ fun i => b i ( Finset.mem_univ i ) 0, funext fun i => funext fun _ => funext fun _ => by simp +decide [ Fin.eq_zero ] ⟩;
  · exact fun a => by rw [ ← Finset.prod_mul_distrib ] ; exact Finset.prod_congr rfl fun _ _ => by split_ifs <;> ring;

/-
**$L^1$-norm bound for the box Fourier transform.** The sum of norms
of the Fourier coefficients of the box indicator is $O((\log q)^m)$:

$\sum_{\xi \in (\mathbb{Z}/q\mathbb{Z})^m} \|\widehat{I}_S(\xi)\|
  \leq C_{\mathrm{box}} \cdot (\log q)^m,$

where $C_{\mathrm{box}}$ depends only on the box $X$ (not on $q$).
-/
theorem box_fourier_l1_bound (k : ℕ) (_hk : 2 ≤ k) (B : Box (k - 1)) :
    ∃ C : ℝ, 0 < C ∧ ∀ (q : ℕ) [NeZero q] (s : ℝ) (_hs : 0 < s),
      ∑ ξ : Fin (k - 1) → ZMod q,
        ‖dft q (k - 1) (boxIndicator q (k - 1) B s) ξ‖ ≤
      C * (Real.log q) ^ (k - 1 : ℕ) := by
  obtain ⟨ C₁D, hC₁D_pos, hC₁D_bound ⟩ := box_fourier_1d_bound;
  refine' ⟨ C₁D ^ ( k - 1 ), pow_pos hC₁D_pos _, fun q _ s hs => _ ⟩;
  -- Apply the bound for each component of the product.
  have h_prod_bound : ∑ ξ : Fin (k - 1) → ZMod q, ∏ j : Fin (k - 1), ‖dft q 1 (fun x => if (x 0).val ∈ Finset.Icc 1 ⌊s * B.sides j⌋₊ then (1 : ℂ) else 0) (fun _ => ξ j)‖ ≤ (∏ j : Fin (k - 1), C₁D * Real.log q) := by
    have h_prod_bound : ∀ (f : Fin (k - 1) → ZMod q → ℝ), (∀ j, 0 ≤ f j) → (∑ ξ : Fin (k - 1) → ZMod q, ∏ j, f j (ξ j)) ≤ ∏ j, (∑ ξ : ZMod q, f j ξ) := by
      intro f hf; rw [ Finset.prod_sum ] ;
      refine' le_of_eq _;
      refine' Finset.sum_bij ( fun ξ _ => fun j _ => ξ j ) _ _ _ _ <;> simp +decide;
      · simp +decide [ funext_iff ];
      · exact fun b => ⟨ fun j => b j ( Finset.mem_univ j ), funext fun j => funext fun _ => rfl ⟩;
    refine' le_trans _ ( Finset.prod_le_prod _ fun j _ => hC₁D_bound q ⌊s * B.sides j⌋₊ );
    · convert h_prod_bound _ _ using 1;
      · convert rfl;
      · exact fun _ => fun _ => norm_nonneg _;
    · exact fun _ _ => Finset.sum_nonneg fun _ _ => norm_nonneg _;
  refine le_trans ?_ ( h_prod_bound.trans ?_ );
  · exact Finset.sum_le_sum fun _ _ => by rw [ dft_boxIndicator_eq_prod ] ; norm_num;
  · norm_num [ Finset.prod_mul_distrib ];
    rw [ mul_pow ]

/-! ### CRT frequency equivalence -/

/-
For squarefree `q` and prime factor `p ∣ q`, the cofactor `q / p` is nonzero in `ZMod p`.
This holds because `q` is squarefree, so `p ∤ q / p`, hence `(q / p : ℕ)` has nonzero
image in `ZMod p`.
-/
lemma natCast_div_prime_ne_zero (q : ℕ) [NeZero q] (hq : Squarefree q)
    (p : q.primeFactors) :
    ((q / p : ℕ) : ZMod p) ≠ 0 := by
  rw [ Ne.eq_def, ZMod.natCast_eq_zero_iff ];
  rw [ Nat.dvd_div_iff_mul_dvd ] <;> norm_num [ Nat.mem_primeFactors.mp p.2 ];
  exact fun h => absurd ( hq.squarefree_of_dvd h ) ( by rw [ Nat.squarefree_mul_iff ] ; aesop )

/-- The **CRT frequency equivalence**: maps a global frequency `ξ ∈ ZMod q` to its
local frequency components for the additive character splitting.

For each prime factor `p ∣ q`, the local frequency is
`(ξ mod p) · (q/p)⁻¹ mod p`, where `(q/p)⁻¹` is the modular inverse of the cofactor
`q/p` in `ZMod p`. This correction factor arises from the CRT idempotents:
if `eₚ` is the idempotent satisfying `eₚ ≡ 1 (mod p)` and `eₚ ≡ 0 (mod p')`
for `p' ≠ p`, then `eₚ = (q/p) · (q/p)⁻¹`, and the additive character
`exp(2πi a/q)` decomposes as `∏ₚ exp(2πi (a mod p · (q/p)⁻¹) / p)`. -/
noncomputable def crtFrequencyEquiv (q : ℕ) [NeZero q] (hq : Squarefree q) :
    ZMod q ≃ ((p : q.primeFactors) → ZMod (p : ℕ)) where
  toFun ξ p :=
    haveI : NeZero p.val := ⟨(Nat.mem_primeFactors.mp p.prop).1.ne_zero⟩
    crtRingEquiv q hq ξ p * ((q / p : ℕ) : ZMod p)⁻¹
  invFun f :=
    (crtRingEquiv q hq).symm fun p =>
      haveI : NeZero p.val := ⟨(Nat.mem_primeFactors.mp p.prop).1.ne_zero⟩
      f p * ((q / p : ℕ) : ZMod p)
  left_inv ξ := by
    simp only
    conv_rhs => rw [← (crtRingEquiv q hq).symm_apply_apply ξ]
    congr 1; funext p
    haveI : NeZero p.val := ⟨(Nat.mem_primeFactors.mp p.prop).1.ne_zero⟩
    haveI : Fact p.val.Prime := ⟨(Nat.mem_primeFactors.mp p.prop).1⟩
    rw [mul_assoc, inv_mul_cancel₀ (natCast_div_prime_ne_zero q hq p), mul_one]
  right_inv f := by
    funext p; simp only
    haveI : NeZero p.val := ⟨(Nat.mem_primeFactors.mp p.prop).1.ne_zero⟩
    haveI : Fact p.val.Prime := ⟨(Nat.mem_primeFactors.mp p.prop).1⟩
    rw [(crtRingEquiv q hq).apply_symm_apply]
    rw [mul_assoc, mul_inv_cancel₀ (natCast_div_prime_ne_zero q hq p), mul_one]

/-
**Additive character CRT splitting.** For squarefree `q`, the additive character
`exp(2πi (ξ · x).val / q)` decomposes as a product over the prime factors of `q`:
$\chi_\xi(x) = \prod_{p \mid q} \chi_{\xi_p}(x_p),$
where `ξ_p = crtFrequencyEquiv q hq ξ p` is the corrected local frequency and
`x_p = crtRingEquiv q hq x p` is the CRT projection of `x`.
-/
set_option maxHeartbeats 1600000 in
lemma additiveChar_crt_split (q : ℕ) [NeZero q] (hq : Squarefree q)
    (ξ x : ZMod q) :
    additiveChar q ξ x =
      ∏ p ∈ q.primeFactors.attach, (
        haveI : NeZero p.val := ⟨(Nat.mem_primeFactors.mp p.prop).1.ne_zero⟩
        additiveChar p.val
          (crtFrequencyEquiv q hq ξ p)
          (crtRingEquiv q hq x p)
      ) := by
  unfold additiveChar; simp +decide [ mul_comm ] ;
  rw [ ← Complex.exp_sum ];
  -- By the properties of the exponential function and the definition of `crtFrequencyEquiv`, we can rewrite the right-hand side of the equation.
  have h_exp : (ξ * x).cast / (q : ℂ) - ∑ p ∈ q.primeFactors.attach, ((crtFrequencyEquiv q hq) ξ p * (crtRingEquiv q hq) x p).val / (p : ℂ) ∈ Set.range (fun n : ℤ => (n : ℂ)) := by
    -- By the properties of the Chinese Remainder Theorem, we know that
    have h_crt : (ξ * x).val ≡ ∑ p ∈ q.primeFactors.attach, ((crtFrequencyEquiv q hq) ξ p * (crtRingEquiv q hq) x p).val * (q / p : ℕ) [MOD q] := by
      have h_crt : ∀ p ∈ q.primeFactors.attach, (ξ * x).val ≡ ((crtFrequencyEquiv q hq ξ p) * (crtRingEquiv q hq x p)).val * (q / p : ℕ) [MOD p] := by
        intro p hp
        have h_crt : (ξ * x).val ≡ ((crtRingEquiv q hq (ξ * x) p).val) * (q / p : ℕ) * ((q / p : ℕ)⁻¹ : ZMod p).val [MOD p] := by
          have h_crt : (q / p : ℕ) * ((q / p : ℕ)⁻¹ : ZMod p).val ≡ 1 [MOD p] := by
            haveI := Fact.mk ( Nat.prime_of_mem_primeFactors p.2 ) ; simp +decide [ ← ZMod.natCast_eq_natCast_iff ] ;
            rw [ ZMod.mul_inv_of_unit ];
            rw [ isUnit_iff_ne_zero ];
            rw [ Ne.eq_def, ZMod.natCast_eq_zero_iff ];
            rw [ Nat.dvd_div_iff_mul_dvd ];
            · exact fun h => absurd ( hq.squarefree_of_dvd h ) ( by rw [ Nat.squarefree_mul_iff ] ; aesop );
            · exact Nat.dvd_of_mem_primeFactors p.2;
          simp_all +decide [ ← ZMod.natCast_eq_natCast_iff, mul_assoc ];
          have h_crt : (ξ * x).cast = ((crtRingEquiv q hq (ξ * x) p).val : ZMod p) := by
            convert rfl;
            convert ZMod.natCast_zmod_val _;
            · convert rfl;
              convert crtRingEquiv_apply_eq_castHom q hq ( ξ * x ) p using 1;
            · exact ⟨ Nat.ne_of_gt ( Nat.pos_of_mem_primeFactors p.2 ) ⟩;
          aesop;
        simp_all +decide [ ← ZMod.natCast_eq_natCast_iff, mul_assoc ];
        simp +decide [ mul_assoc, mul_comm, mul_left_comm, crtFrequencyEquiv ];
        haveI := Fact.mk ( Nat.prime_of_mem_primeFactors p.2 ) ; simp +decide [ ← mul_assoc ] ;
      have h_crt : ∀ p ∈ q.primeFactors.attach, (ξ * x).val ≡ ∑ p ∈ q.primeFactors.attach, ((crtFrequencyEquiv q hq ξ p) * (crtRingEquiv q hq x p)).val * (q / p : ℕ) [MOD p] := by
        intro p hp
        have h_crt : ∑ p ∈ q.primeFactors.attach, ((crtFrequencyEquiv q hq ξ p) * (crtRingEquiv q hq x p)).val * (q / p : ℕ) ≡ ((crtFrequencyEquiv q hq ξ p) * (crtRingEquiv q hq x p)).val * (q / p : ℕ) [MOD p] := by
          simp +decide [ ← ZMod.natCast_eq_natCast_iff ];
          rw [ Finset.sum_eq_single p ] <;> simp_all +decide [ Nat.ModEq ];
          intro a ha ha' ha'' ha'''; have := Nat.dvd_div_of_mul_dvd ( show a * p.val ∣ q from Nat.Coprime.mul_dvd_of_dvd_of_dvd ( by have := Nat.coprime_primes ha ( Nat.prime_of_mem_primeFactors p.2 ) ; aesop ) ha' ( Nat.dvd_of_mem_primeFactors p.2 ) ) ; simp_all +decide [ Nat.dvd_iff_mod_eq_zero ] ;
          simp_all +decide [ ← ZMod.val_natCast, Nat.dvd_iff_mod_eq_zero ];
        exact Eq.trans ( by solve_by_elim ) h_crt.symm;
      rw [ Nat.modEq_iff_dvd ] at *;
      have h_crt : (∏ p ∈ q.primeFactors.attach, (p : ℤ)) ∣ (∑ p ∈ q.primeFactors.attach, ((crtFrequencyEquiv q hq ξ p) * (crtRingEquiv q hq x p)).val * (q / p : ℕ)) - (ξ * x).val := by
        convert Finset.prod_dvd_of_coprime _ _;
        · intros p hp q hq hpq; exact (by
          have := Nat.coprime_primes ( Nat.prime_of_mem_primeFactors p.2 ) ( Nat.prime_of_mem_primeFactors q.2 ) ; aesop;);
        · exact fun p hp => by simpa using h_crt p hp |> Nat.ModEq.dvd;
      convert h_crt using 1;
      rw [ ← Nat.cast_prod ] ; norm_cast ; rw [ ← Nat.prod_primeFactors_of_squarefree hq ] ;
      refine' Finset.prod_bij ( fun p hp => ⟨ p, _ ⟩ ) _ _ _ _ <;> simp_all +decide [ Nat.primeFactors_prod ];
    obtain ⟨ k, hk ⟩ := h_crt.symm.dvd;
    use k;
    simp_all +decide [ ← @Int.cast_inj ℂ ];
    rw [ div_sub', eq_div_iff ] <;> norm_cast at * <;> simp_all +decide [ NeZero.ne ];
    convert hk.symm using 1 ; ring;
    rw [ Finset.mul_sum _ _ _ ] ; refine' congr_arg _ ( Finset.sum_congr rfl fun p hp => _ ) ; rw [ Nat.cast_div ( Nat.dvd_of_mem_primeFactors p.2 ) ( Nat.cast_ne_zero.mpr <| Nat.ne_of_gt <| Nat.pos_of_mem_primeFactors p.2 ) ] ; ring;
  obtain ⟨ n, hn ⟩ := h_exp; simp_all +decide [ Complex.exp_eq_exp_iff_exists_int, mul_div_assoc, mul_assoc, mul_comm, mul_left_comm ] ;
  exact ⟨ n, by rw [ hn ] ; simp [ Finset.mul_sum _ _ _, mul_sub, mul_comm ] ⟩

/-! ### CRT factorization of Fourier coefficients -/

/-
**CRT factorization of the deviation DFT.** For squarefree `q`, the Fourier transform
of the global counting function factors as a product of local Fourier transforms over
the prime factors of `q`. This is the frequency-domain manifestation of
`counting_function_multiplicative`.
-/
theorem dft_crt_factorization (q : ℕ) [NeZero q] (hq : Squarefree q)
    (Ω : ∀ p : ℕ, Finset (ZMod p)) (k : ℕ) (hk : 2 ≤ k)
    (ξ : Fin (k - 1) → ZMod q) :
    dft q (k - 1) (fun h => (tupleCount (crtSubset q Ω) (Fin.cons 0 h) : ℂ)) ξ =
      ∏ p ∈ q.primeFactors.attach, (
        haveI : NeZero p.val := ⟨(Nat.mem_primeFactors.mp p.prop).1.ne_zero⟩
        dft p.val (k - 1) (fun h_p => (tupleCount (Ω p.val) (Fin.cons 0 h_p) : ℂ))
          (fun j => crtFrequencyEquiv q hq (ξ j) p)) := by
  -- `hk` is not used in the proof but is retained for specification purposes.
  unfold dft; simp +decide [ Finset.prod_mul_distrib ] ;
  rw [ Finset.prod_sum ];
  refine' congrArg₂ _ _ _;
  · rw [ Finset.prod_pow, ← Nat.cast_prod ];
    convert rfl;
    convert prod_primeFactors_eq q hq |> Eq.symm;
  · refine' Finset.sum_bij _ _ _ _ _;
    use fun a _ p _ j => crtRingEquiv q hq ( a j ) p;
    · aesop;
    · simp +decide [funext_iff];
      intro a₁ a₂ h x; exact (crtRingEquiv q hq).injective (by
      ext p; specialize h p.val ( Nat.prime_of_mem_primeFactors p.prop ) ( Nat.dvd_of_mem_primeFactors p.prop ) ( NeZero.ne q ) x; aesop;);
    · intro b hb; use fun j => (crtRingEquiv q hq).symm (fun p => b p (by
      exact Finset.mem_attach _ p) j); simp +decide;
    · intro a ha; rw [ Finset.prod_mul_distrib ] ; simp +decide [ character ] ;
      congr! 1;
      · convert congr_arg ( ( ↑ ) : ℕ → ℂ ) ( counting_function_multiplicative q hq Ω ( Fin.cons 0 a ) ) using 1;
        simp +decide [ crtRingEquiv_apply_eq_castHom ];
        refine' Finset.prod_bij ( fun x _ => x.val ) _ _ _ _ <;> simp +decide [ Fin.cons ];
        intro p hp hp' hq; congr; ext i; induction i using Fin.inductionOn <;> aesop;
      · rw [ Finset.prod_comm ];
        refine' Finset.prod_congr rfl fun x _ => _;
        rw [ additiveChar_crt_split q hq ];
        rw [ map_prod ];
        refine' Finset.prod_bij ( fun p hp => ⟨ p, hp ⟩ ) _ _ _ _ <;> aesop

/-! ### Fourier synthesis helper lemmas -/

/-
The sum of `‖dft I_S (-ξ)‖` over all `ξ` equals the sum of `‖dft I_S ξ‖` by reindexing
(`ξ ↦ -ξ` is a bijection on the group).
-/
lemma sum_norm_dft_neg_eq (q : ℕ) [NeZero q] (m : ℕ) (f : (Fin m → ZMod q) → ℂ) :
    ∑ ξ : Fin m → ZMod q, ‖dft q m f (-ξ)‖ =
    ∑ ξ : Fin m → ZMod q, ‖dft q m f ξ‖ := by
  apply Finset.sum_bij (fun ξ _ => -ξ);
  · exact fun _ _ => Finset.mem_univ _;
  · aesop;
  · exact fun b _ => ⟨ -b, Finset.mem_univ _, neg_neg b ⟩;
  · grind

/-
**Spatial → Frequency swap.** Using DFT inversion on `f_dev` and swapping sums
(Fubini), we obtain
`∑ h, I_S(h) * f(h) = ∑ ξ, q^m * dft(f)(ξ) * dft(I_S)(-ξ)`.
-/
lemma spatial_to_frequency_swap (q : ℕ) [NeZero q] (m : ℕ)
    (f g : (Fin m → ZMod q) → ℂ) :
    ∑ h, g h * f h =
      ∑ ξ : Fin m → ZMod q,
        ((q : ℂ) ^ m) * dft q m f ξ * dft q m g (-ξ) := by
  -- By Fubini's theorem, we can interchange the order of summation.
  have h_fubini : ∑ h : Fin m → ZMod q, g h * (∑ ξ : Fin m → ZMod q, dft q m f ξ * character q m ξ h) = ∑ ξ : Fin m → ZMod q, dft q m f ξ * (∑ h : Fin m → ZMod q, g h * character q m ξ h) := by
    simpa only [ mul_assoc, mul_left_comm, Finset.mul_sum _ _ _ ] using Finset.sum_comm;
  convert h_fubini using 2;
  · exact congrArg _ ( dft_inversion q m f _ );
  · unfold dft;
    field_simp;
    unfold character; congr! 2; simp +decide [ starRingEnd_additiveChar ] ;

/-
The sum of the global counting function over all `h` equals
`q^(k-1) * ∏_p μ_p` (or equivalently, `∏_p |Ω_p|^k`).
-/
lemma sum_global_tupleCount (k : ℕ) (hk : 2 ≤ k)
    (q : ℕ) [NeZero q] (hq : Squarefree q)
    (Ω : ∀ p : ℕ, Finset (ZMod p)) :
    (∑ h : Fin (k - 1) → ZMod q,
      (tupleCount (crtSubset q Ω) (Fin.cons 0 h) : ℂ)) =
      ↑(q : ℝ) ^ (k - 1 : ℕ) * ↑(∏ p ∈ q.primeFactors, localMean k Ω p) := by
  have := @dft_crt_factorization;
  specialize this q hq Ω k hk 0;
  convert congr_arg ( fun x : ℂ => ( q : ℂ ) ^ ( k - 1 ) * x ) this using 1;
  · unfold dft; norm_num;
    unfold character; norm_num [ NeZero.ne ] ;
  · simp +decide [ localMean, dft ];
    rw [ ← Finset.prod_div_distrib ];
    rw [ ← Finset.prod_attach ];
    refine Or.inl <| Finset.prod_congr rfl fun p hp => ?_;
    rw [ show ( crtFrequencyEquiv q hq ) 0 p = 0 from _ ];
    · simp +decide [ character, additiveChar ];
      rw [ inv_mul_eq_div, sum_tupleCount_eq_card_pow ];
      linarith;
    · simp +decide [ crtFrequencyEquiv ]

/-
The DFT of the global counting function at `ξ = 0` equals `μ_q = ∏_p μ_p`.
This is a consequence of the definition of `dft`, `sum_tupleCount_eq_card_pow`,
and `counting_function_multiplicative`.
-/
lemma dft_tupleCount_zero (k : ℕ) (hk : 2 ≤ k)
    (q : ℕ) [NeZero q] (hq : Squarefree q)
    (Ω : ∀ p : ℕ, Finset (ZMod p)) :
    dft q (k - 1) (fun h => (tupleCount (crtSubset q Ω) (Fin.cons 0 h) : ℂ)) 0 =
      ↑(∏ p ∈ q.primeFactors, localMean k Ω p) := by
  unfold dft;
  -- The sum of the counting function over the entire domain is independent of the phase factor `e^(iθ)`. It is equal to the product of the means times `q^(k-1)` by `sum_global_tupleCount`.
  have h_sum_nonzero : ∑ h : Fin (k - 1) → ZMod q, (tupleCount (crtSubset q Ω) (Fin.cons 0 h) : ℂ) = (q : ℝ) ^ (k - 1 : ℕ) * (∏ p ∈ q.primeFactors, localMean k Ω p) := by
    exact sum_global_tupleCount k hk q hq Ω;
  simp_all +decide [ character ];
  rw [ ← mul_assoc, inv_mul_cancel₀ ( pow_ne_zero _ ( Nat.cast_ne_zero.mpr <| NeZero.ne q ) ), one_mul ]

/-
The DFT of a constant function at `ξ ≠ 0` vanishes.
This follows from character orthogonality.
-/
lemma dft_const_nonzero (q : ℕ) [NeZero q] (m : ℕ) (c : ℂ)
    (ξ : Fin m → ZMod q) (hξ : ξ ≠ 0) :
    dft q m (fun _ => c) ξ = 0 := by
  unfold dft;
  have := character_orthogonality q m ξ 0; simp_all +decide [ Finset.mul_sum _ _ _, mul_left_comm ] ;
  convert congr_arg ( fun x : ℂ => c * ( ( q ^ m : ℂ ) ⁻¹ * starRingEnd ℂ x ) ) this using 1 ; simp +decide [ Finset.mul_sum _ _ _, character ] ; ring_nf;
  norm_num

/-
**L∞ Frequency Bound on the deviation DFT.** For squarefree `q` and well-distributed
`Ω`, each Fourier coefficient of `f_dev = N_q - μ_q` is bounded by
`(∏_p μ_p) * ∏_p (1 + (1 - r_p) p^{-ε})`.
-/
lemma deviation_dft_linf_bound (k : ℕ) (hk : 2 ≤ k) (ε : ℝ) (_hε : 0 < ε)
    (q : ℕ) [NeZero q] (hq : Squarefree q)
    (Ω : ∀ p : ℕ, Finset (ZMod p))
    (hwd : ∀ p, (hp : p ∈ q.primeFactors) → haveI : Fact p.Prime :=
      ⟨(Nat.mem_primeFactors.mp hp).1⟩;
      WellDistributedFourier ε p (Ω p) k)
    (ξ : Fin (k - 1) → ZMod q) :
    ‖dft q (k - 1) (fun h => (tupleCount (crtSubset q Ω) (Fin.cons 0 h) : ℂ) -
      ↑(∏ p ∈ q.primeFactors, localMean k Ω p)) ξ‖ ≤
      (q : ℝ) ^ (-ε) * ((crtSubset q Ω).card : ℝ) / (q : ℝ) ^ (k - 1) := by
  sorry

/-! ### Fourier synthesis: the uniform deviation bound -/

/-
**Fourier ANOVA synthesis.** Combining Plancherel, CRT factorization, the primitive
character sieve ($\widehat{\operatorname{dev}}_p(0) = 0$), exponential sum bounds, and
box transform decay, we obtain the uniform deviation bound:

$$\Bigl|\sum_{h \in s_q X} \bigl(N_k(h, \Omega_q) - \mu\bigr)\Bigr|
  \leq C \cdot (\log q)^{k-1} \cdot
    \prod_{p \mid q} \bigl(1 + (1 - r_p)\, p^{-\varepsilon}\bigr),$$
-/
theorem deviation_fourier_synthesis (k : ℕ) (hk : 2 ≤ k) (B : Box (k - 1)) :
    ∃ C : ℝ, 0 < C ∧
      ∀ (ε : ℝ) (_hε : 0 < ε) (q : ℕ) [NeZero q] (_hq : Squarefree q)
      (Ω : ∀ p : ℕ, Finset (ZMod p))
      (_hwd : ∀ p, (hp : p ∈ q.primeFactors) → haveI : Fact p.Prime :=
        ⟨(Nat.mem_primeFactors.mp hp).1⟩;
        WellDistributedFourier ε p (Ω p) k)
      (s : ℝ) (_hs : 0 < s),
      ‖∑ h : Fin (k - 1) → ZMod q,
        (boxIndicator q (k - 1) B s h) *
        ((tupleCount (crtSubset q Ω) (Fin.cons 0 h) : ℂ) -
          ↑(∏ p ∈ q.primeFactors, localMean k Ω p))‖ ≤
      C * (Real.log q) ^ (k - 1 : ℕ) *
        (q : ℝ) ^ (-ε) * ((crtSubset q Ω).card : ℝ) := by
  obtain ⟨C, hC_pos, hC_bound⟩ := box_fourier_l1_bound k hk B
  exact ⟨C, hC_pos, fun ε hε q _ hq Ω hwd s hs => by
    -- Abbreviations for readability
    set f_dev : (Fin (k - 1) → ZMod q) → ℂ :=
      fun h => (tupleCount (crtSubset q Ω) (Fin.cons 0 h) : ℂ) -
        ↑(∏ p ∈ q.primeFactors, localMean k Ω p)
    set I_S := boxIndicator q (k - 1) B s

    -- **Lemma 1 (Spatial → Frequency swap):**
    have hlem1 : ∑ h, I_S h * f_dev h =
        ∑ ξ : Fin (k - 1) → ZMod q,
          ((q : ℂ) ^ (k - 1 : ℕ)) * dft q (k - 1) f_dev ξ *
            dft q (k - 1) I_S (-ξ) :=
      spatial_to_frequency_swap q (k - 1) f_dev I_S

    -- **Lemma 2 (L∞ Frequency Bound):**
    have hlem2 : ∀ ξ : Fin (k - 1) → ZMod q,
        ‖dft q (k - 1) f_dev ξ‖ ≤ (q : ℝ) ^ (-ε) * ((crtSubset q Ω).card : ℝ) / (q : ℝ) ^ (k - 1) :=
      fun ξ => deviation_dft_linf_bound k hk ε hε q hq Ω hwd ξ

    -- **Lemma 3 (Assembly):**
    -- The spatial→frequency identity (hlem1) gives us:
    --   ∑ h, I_S h * f_dev h = ∑ ξ, q^(k-1) * dft(f_dev)(ξ) * dft(I_S)(-ξ)
    -- Taking norms and applying triangle inequality + L∞ bound (hlem2):
    have hlem3 : ‖∑ h, I_S h * f_dev h‖ ≤
        C * (Real.log q) ^ (k - 1 : ℕ) *
        (q : ℝ) ^ (-ε) * ((crtSubset q Ω).card : ℝ) := by
      sorry
    exact hlem3⟩


end PoissonCRT
