/-
Copyright (c) 2026 Fernando Portela. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Fernando Portela
-/

/-
Portions of this file were generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.28.0
Mathlib version: 8f9d9cff6bd728b17a24e163c9402775d9e6a365

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

import PoissonViaCRT.Defs
import PoissonViaCRT.Combinatorics
import Mathlib.Algebra.Order.Floor.Extended
import Mathlib.Algebra.Order.Floor.Semifield
import Mathlib.Algebra.Order.Interval.Basic
import Mathlib.Algebra.Order.Ring.Star
import Mathlib.Analysis.Complex.UpperHalfPlane.Basic
import Mathlib.Analysis.SpecialFunctions.Bernstein
import Mathlib.Analysis.SpecialFunctions.Gamma.Basic
import Mathlib.Analysis.SpecialFunctions.Trigonometric.DerivHyp
import Mathlib.Combinatorics.Enumerative.DyckWord
import Mathlib.Combinatorics.SimpleGraph.Triangle.Removal
import Mathlib.Data.Int.Star
import Mathlib.Data.NNRat.Floor
import Mathlib.Data.Nat.Factorial.DoubleFactorial
import Mathlib.Geometry.Euclidean.Altitude
import Mathlib.NumberTheory.Height.Basic
import Mathlib.NumberTheory.LucasLehmer
import Mathlib.NumberTheory.SelbergSieve
import Mathlib.RingTheory.WittVector.IsPoly
import Mathlib.Topology.Sheaves.Presheaf

set_option linter.unusedVariables false

/-!
# Helper lemmas for GammaDeviationSynthesis

Decomposed lemmas needed to prove `gammaProdOfBoxPoint_mem_Icc`
and `fiber_card_le_countTuplesWithGammaProd`.
-/

open Finset BigOperators Classical

namespace PoissonCRT

/-! ## Squarefreeness of product of distinct primes -/

/-- The product of primes from `q.primeFactors` (where `q` is squarefree) is squarefree. -/
public lemma prod_primes_squarefree (T : Finset ℕ) (q : ℕ) [NeZero q]
    (hq : Squarefree q) (hT : T ⊆ q.primeFactors) :
    Squarefree (∏ p ∈ T, p) := by
  have h_distinct_primes : ∀ p ∈ T, Nat.Prime p :=
    fun p hp => Nat.prime_of_mem_primeFactors <| hT hp
  have h_prod_squarefree : ∀ {S : Finset ℕ}, (∀ p ∈ S, Nat.Prime p) → Squarefree (∏ p ∈ S, p) := by
    intros S hS; induction S using Finset.induction <;> simp_all +decide [ Nat.squarefree_mul_iff ]
    exact ⟨ Nat.Coprime.prod_right fun p hp => hS.1.coprime_iff_not_dvd.mpr fun h => ‹¬_› <| by
      have := Nat.prime_dvd_prime_iff_eq hS.1 ( hS.2 p hp ) ; aesop, hS.1.squarefree ⟩
  exact h_prod_squarefree h_distinct_primes

/-! ## Lower bound: gammaProdOfBoxPoint ≥ 1 -/

/-- `gammaProdOfBoxPoint T h ≥ 1` for nonempty T of primes. -/
public lemma gammaProdOfBoxPoint_pos {n : ℕ}
    (T : Finset ℕ) (hT_ne : T.Nonempty)
    (q : ℕ) [NeZero q] (hT : T ⊆ q.primeFactors)
    (h : Fin n → ℤ) :
    0 < gammaProdOfBoxPoint T h := by
  refine Finset.prod_pos fun j _ => ?_
  apply Nat.pos_of_ne_zero _
  simp_all +decide [ Finset.lcm_eq_zero_iff ]
  exact fun i hij h => absurd h <| Finset.prod_ne_zero_iff.mpr fun p hp =>
    Nat.ne_of_gt <| Nat.pos_of_mem_primeFactors <| hT hp

/-! ## Upper bound helpers -/

/-- `Finset.lcm S f ∣ ∏ i ∈ S, f i` for natural numbers. -/
lemma lcm_dvd_prod {ι : Type*} [DecidableEq ι] (S : Finset ι) (f : ι → ℕ) :
    S.lcm f ∣ ∏ i ∈ S, f i :=
  Finset.lcm_dvd fun b hb => Finset.dvd_prod_of_mem f hb

/-- All entries of `Fin.cons 0 h` are in `[0, H]` when each `h i ∈ [1, H]`. -/
public lemma fin_cons_zero_range {n : ℕ} (H : ℕ)
    (h : Fin n → ℤ)
    (hh : h ∈ Fintype.piFinset (fun _ : Fin n => Finset.Icc (1 : ℤ) (H : ℤ))) :
    let h' : Fin (n + 1) → ℤ := Fin.cons (0 : ℤ) h
    ∀ i : Fin (n + 1), (0 : ℤ) ≤ h' i ∧ h' i ≤ (H : ℤ) := by
  simp_all +decide [ Fin.forall_fin_succ, Fintype.mem_piFinset ]
  exact fun i => by linarith [ hh i ]

/-- The natAbs of differences of `Fin.cons 0 h` entries is ≤ H. -/
public lemma natAbs_diff_le_H {n : ℕ} (H : ℕ)
    (h : Fin n → ℤ)
    (hh : h ∈ Fintype.piFinset (fun _ : Fin n => Finset.Icc (1 : ℤ) (H : ℤ))) :
    let h' : Fin (n + 1) → ℤ := Fin.cons (0 : ℤ) h
    ∀ i j : Fin (n + 1), Int.natAbs (h' j - h' i) ≤ H := by
  simp_all +decide [ Fin.forall_fin_succ ]
  grind +qlia

/--
When all values are bounded by H and positive, lcm ≤ product ≤ H^|S|.
    More precisely, `S.lcm f ≤ H ^ S.card` when `0 < H` and each `f i ≤ H`.
-/
lemma lcm_le_pow_card {ι : Type*} [DecidableEq ι]
    (S : Finset ι) (f : ι → ℕ) (H : ℕ) (hH : 0 < H)
    (hf : ∀ i ∈ S, f i ≤ H) :
    S.lcm f ≤ H ^ S.card := by
  by_cases h : ∏ i ∈ S, f i = 0
  · simp_all +decide [ Finset.prod_eq_zero_iff ]
    obtain ⟨ a, ha, ha' ⟩ := h
    exact le_trans ( Finset.lcm_eq_zero_iff.mpr ⟨ a, ha, ha' ⟩ |> le_of_eq ) ( Nat.zero_le _ )
  · exact le_trans ( Nat.le_of_dvd ( Nat.pos_of_ne_zero h ) ( lcm_dvd_prod _ _ ) )
      ( Finset.prod_le_pow_card _ _ _ hf )

/--
`gammaProdOfBoxPoint T h ≤ H^((n+1)*(n+1))` when all pairwise
    differences of `Fin.cons 0 h` are nonzero (e.g., from inScaledBox).
    Requires `H > 0` and differences ≤ H.
-/
public lemma gammaProdOfBoxPoint_le {n : ℕ}
    (T : Finset ℕ) (H : ℕ) (hH : 0 < H)
    (h : Fin n → ℤ)
    (h_diff_le : let h' : Fin (n + 1) → ℤ := Fin.cons (0 : ℤ) h
      ∀ i j : Fin (n + 1), Int.natAbs (h' j - h' i) ≤ H)
    (h_diff_pos : let h' : Fin (n + 1) → ℤ := Fin.cons (0 : ℤ) h
      ∀ i j : Fin (n + 1), i ≠ j → 0 < Int.natAbs (h' j - h' i)) :
    gammaProdOfBoxPoint T h ≤ H ^ ((n + 1) * (n + 1)) := by
  apply le_trans ( Finset.prod_le_prod' _ ) _
  use fun i => H ^ ( Finset.card ( Finset.Iio i ) )
  · intro i hi; apply lcm_le_pow_card; aesop
    exact fun j hj =>
      Nat.le_trans ( Nat.le_of_dvd ( h_diff_pos _ _ ( ne_of_lt ( Finset.mem_Iio.mp hj ) ) )
        ( Nat.gcd_dvd_right _ _ ) ) ( h_diff_le _ _ )
  · rw [ Finset.prod_pow_eq_pow_sum ]
    exact pow_le_pow_right₀ hH ( le_trans ( Finset.sum_le_sum fun _ _ =>
      show # ( Finset.Iio _ ) ≤ n + 1 from by simp +arith +decide ) ( by simp +arith +decide ) )

/-! ## Fiber cardinality helpers -/

/-- When h is in the scaled box with offset 0, `Fin.cons 0 h` has distinct entries. -/
public lemma fin_cons_zero_injective {n : ℕ} (hn : 1 ≤ n)
    (X : Box n) (s : ℝ)
    (h : Fin n → ℤ)
    (hbox : inScaledBox X s (fun _ => 0) h) :
    let h' : Fin (n + 1) → ℤ := Fin.cons (0 : ℤ) h
    ∀ i j : Fin (n + 1), i ≠ j → h' i ≠ h' j := by
  simp +decide [ Fin.forall_fin_succ ]
  have h_mono : StrictMono h := by
    have h_diff_pos : ∀ i : Fin n, 0 < h i - (if i.val = 0 then 0 else h (Fin.mk (i.val - 1) (by
    exact lt_of_le_of_lt ( Nat.pred_le _ ) i.2))) := by
      intro i; specialize hbox i; aesop
    generalize_proofs at *
    intro i j hij
    obtain ⟨j, hj⟩ := j
    obtain ⟨i, hi⟩ := i
    simp_all +decide [ Nat.add_one_le_iff ]
    induction hij <;> simp_all +decide
    · specialize h_diff_pos ⟨ i + 1, hj ⟩ ; aesop
    · grind
  have h_pos : ∀ i : Fin n, 0 < h i := by
    intro i
    have := hbox ⟨0, by omega⟩
    simp at this
    exact lt_of_lt_of_le this.1 ( h_mono.monotone ( Nat.zero_le _ ) )
  exact ⟨ fun i hi => ne_of_lt ( h_pos i ),
    fun i => ⟨ ne_of_gt ( h_pos i ), fun j hij => h_mono.injective.ne hij ⟩ ⟩

/--
Positive differences from distinct Fin.cons 0 h entries.
-/
public lemma fin_cons_zero_diff_pos {n : ℕ} (hn : 1 ≤ n)
    (X : Box n) (s : ℝ)
    (h : Fin n → ℤ)
    (hbox : inScaledBox X s (fun _ => 0) h) :
    let h' : Fin (n + 1) → ℤ := Fin.cons (0 : ℤ) h
    ∀ i j : Fin (n + 1), i ≠ j → 0 < Int.natAbs (h' j - h' i) := by
  exact fun i j hij => Int.natAbs_pos.mpr ( sub_ne_zero.mpr <| by
    simpa [ Fin.ext_iff ] using fin_cons_zero_injective hn X s h hbox i j hij |> fun h =>
      Ne.symm h )

/-- The `GammaStructure.ofTuple` constructed from `c = ∏ T` has
    `gammaProd` equal to `gammaProdOfBoxPoint T h`. -/
public lemma gammaProd_ofTuple_eq {n : ℕ}
    (T : Finset ℕ) (c : ℕ) (hc : Squarefree c) (hc_def : c = ∏ p ∈ T, p)
    (h : Fin n → ℤ)
    (h_dist : ∀ i j : Fin (n + 1), i ≠ j →
      (Fin.cons (0 : ℤ) h : Fin (n + 1) → ℤ) i ≠ (Fin.cons (0 : ℤ) h : Fin (n + 1) → ℤ) j) :
    (GammaStructure.ofTuple c hc (Fin.cons (0 : ℤ) h) h_dist).gammaProd =
      gammaProdOfBoxPoint T h := by
  subst hc_def
  unfold GammaStructure.gammaProd GammaStructure.gammaRow gammaProdOfBoxPoint
  congr 1; ext j
  apply Finset.lcm_congr rfl
  intro i hi
  exact gammaOfTuple_of_ne _ _ (ne_of_lt (Finset.mem_Iio.mp hi))

/--
For `GammaStructure.ofTuple`, gamma i j divides sqfreepart.
    Since gamma i j is squarefree and divides gammaProd, it divides radical(gammaProd).
-/
lemma ofTuple_gamma_dvd_sqfreepart {k : ℕ}
    (c : ℕ) (hc : Squarefree c)
    (h' : Fin k → ℤ)
    (h_dist : ∀ i j : Fin k, i ≠ j → h' i ≠ h' j)
    (i j : Fin k) (hij : i ≠ j) :
    (GammaStructure.ofTuple c hc h' h_dist).gamma i j ∣
      (GammaStructure.ofTuple c hc h' h_dist).sqfreepart := by
  have h_gamma_div_gammaProd :
      (GammaStructure.ofTuple c hc h' h_dist).gamma i j ∣
        (GammaStructure.ofTuple c hc h' h_dist).gammaProd := by
    have h_gamma_div_gammaRow :
        (GammaStructure.ofTuple c hc h' h_dist).gamma i j ∣
          (GammaStructure.ofTuple c hc h' h_dist).gammaRow (max i j) := by
      cases le_total i j <;> simp_all +decide [ GammaStructure.gammaRow ]
      · exact Finset.dvd_lcm ( Finset.mem_Iio.mpr ( lt_of_le_of_ne ‹_› hij ) )
      · convert Finset.dvd_lcm ( Finset.mem_Iio.mpr ( show j < i from
          lt_of_le_of_ne ‹_› ( Ne.symm hij ) ) ) using 1
        congr! 1
        exact funext fun x => GammaStructure.symm _ _ _
    exact dvd_trans h_gamma_div_gammaRow ( Finset.dvd_prod_of_mem _ ( Finset.mem_univ _ ) )
  -- Since $\gamma_{ij}$ is squarefree and divides $\gammaProd$, it must divide the radical
  -- of $\gammaProd$.
  have h_gamma_div_radical :
      ∀ {d : ℕ}, Squarefree d → d ∣ (GammaStructure.ofTuple c hc h' h_dist).gammaProd →
        d ∣ (GammaStructure.ofTuple c hc h' h_dist).sqfreepart := by
    intros d hd hd_div_gammaProd
    have h_prime_factors :
        ∀ p ∈ d.primeFactors,
          p ∈ (GammaStructure.ofTuple c hc h' h_dist).gammaProd.primeFactors := by
      simp +zetaDelta at *
      exact fun p pp dp _ =>
          ⟨ pp, dvd_trans dp hd_div_gammaProd, Nat.ne_of_gt <| Nat.pos_of_ne_zero <| by
        exact Nat.ne_of_gt <| GammaStructure.gammaProd_pos _ ⟩
    have h_prime_factors :
        d ∣ ∏ p ∈ (GammaStructure.ofTuple c hc h' h_dist).gammaProd.primeFactors, p := by
      rw [ ← Finset.prod_sdiff <|
        show d.primeFactors ⊆ ( GammaStructure.ofTuple c hc h' h_dist ).gammaProd.primeFactors from
          fun p hp => h_prime_factors p hp ]
      rw [ Nat.prod_primeFactors_of_squarefree hd ]
      exact dvd_mul_left _ _
    convert h_prime_factors using 1
  exact h_gamma_div_radical ( by
    exact ( GammaStructure.ofTuple c hc h' h_dist ).sqfree i j hij ) h_gamma_div_gammaProd

/-- For `GammaStructure.ofTuple`, the sqfreepart divides c.
    Every prime dividing gammaProd must divide some gcd(c, d), hence c. -/
lemma ofTuple_sqfreepart_dvd {k : ℕ}
    (c : ℕ) (hc : Squarefree c)
    (h' : Fin k → ℤ)
    (h_dist : ∀ i j : Fin k, i ≠ j → h' i ≠ h' j) :
    (GammaStructure.ofTuple c hc h' h_dist).sqfreepart ∣ c := by
  unfold GammaStructure.sqfreepart radical
  show ∏ p ∈ (GammaStructure.ofTuple c hc h' h_dist).gammaProd.primeFactors, p ∣ c
  conv_rhs => rw [← Nat.prod_primeFactors_of_squarefree hc]
  apply Finset.prod_dvd_prod_of_subset
  intro p hp
  rw [Nat.mem_primeFactors] at hp ⊢
  refine ⟨hp.1, ?_, hc.ne_zero⟩
  have hp_prime : Prime p := irreducible_iff_prime.mp hp.1
  obtain ⟨j, _, hj⟩ := (hp_prime.dvd_finset_prod_iff _).mp hp.2.1
  have h1 : p ∣ ∏ i ∈ Iio j, (GammaStructure.ofTuple c hc h' h_dist).gamma i j :=
    dvd_trans hj (lcm_dvd_prod _ _)
  obtain ⟨i, hi, h2⟩ := (hp_prime.dvd_finset_prod_iff _).mp h1
  have hij : i ≠ j := ne_of_lt (Finset.mem_Iio.mp hi)
  have hg : (GammaStructure.ofTuple c hc h' h_dist).gamma i j =
      Nat.gcd c (Int.natAbs (h' j - h' i)) := by
    unfold GammaStructure.ofTuple; exact gammaOfTuple_of_ne _ _ hij
  rw [hg] at h2
  exact dvd_trans h2 (Nat.gcd_dvd_left _ _)

/-- For `GammaStructure.ofTuple c hc h' h_dist`, the sqfreepart-gcd identity holds:
    `gcd(sqfreepart, |h'_j - h'_i|) = gamma i j` for `i ≠ j`. -/
public lemma ofTuple_gcd_eq {k : ℕ}
    (c : ℕ) (hc : Squarefree c)
    (h' : Fin k → ℤ)
    (h_dist : ∀ i j : Fin k, i ≠ j → h' i ≠ h' j)
    (i j : Fin k) (hij : i ≠ j) :
    Nat.gcd (GammaStructure.ofTuple c hc h' h_dist).sqfreepart
      (Int.natAbs (h' j - h' i)) =
    (GammaStructure.ofTuple c hc h' h_dist).gamma i j := by
  have h_sqf_dvd := ofTuple_sqfreepart_dvd c hc h' h_dist
  have h_gamma_dvd := ofTuple_gamma_dvd_sqfreepart c hc h' h_dist i j hij
  have hg : (GammaStructure.ofTuple c hc h' h_dist).gamma i j =
      Nat.gcd c (Int.natAbs (h' j - h' i)) := by
    unfold GammaStructure.ofTuple; exact gammaOfTuple_of_ne _ _ hij
  apply Nat.dvd_antisymm
  · rw [hg]; exact Nat.dvd_gcd (dvd_trans (Nat.gcd_dvd_left _ _) h_sqf_dvd) (Nat.gcd_dvd_right _ _)
  · exact Nat.dvd_gcd h_gamma_dvd (by rw [hg]; exact Nat.gcd_dvd_right _ _)

end PoissonCRT
