/-
Copyright (c) 2026 Fernando Portela. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Fernando Portela
-/

/-
Portions of this file were generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.28.0
Mathlib version: 8f9d9cff6bd728b17a24e163c9402775d9e6a365

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

import PoissonViaCRT.Combinatorics

/-!
# Gamma-Range Summation Bounds (§3.1 Integration)

This file builds on the combinatorial bounds in `Combinatorics.lean` to prove
integrated summation bounds on `M_γ(H)` over ranges of `γ`. These are needed
for the large-divisor regime in the deviation bound (Proposition 3.7).

## Main Results

* `countTuplesWithGammaProd_le_sum`: For any finite set `S` of Gamma structures
  with `γ(Γ) = γ` that covers all tuples, `M_γ(H) ≤ ∑_{Γ ∈ S} M_Γ(H)`.
* `countTuplesWithGamma_bound_of_gammaProd_le`: Per-Γ bound:
  `M_Γ(H) ≤ 2^k · H^k / γ` when `γ(Γ) ≤ H`.
* `countTuplesWithGammaProd_small_gamma`: Combined small-γ bound:
  `M_γ(H) ≤ C(k+1,2)^{ω(γ)} · 2^k · H^k / γ` when `γ ≤ H`.

## References

* Granville–Kurlberg §3.1, equations (★3)–(★4)
-/

open Finset BigOperators Nat

namespace PoissonCRT

variable {k : ℕ}

/-! ### Helper lemmas -/

/-- Each `gammaRow` value divides `gammaProd`. -/
lemma gammaRow_dvd_gammaProd (Γ : GammaStructure (k + 1)) (j : Fin (k + 1)) :
    Γ.gammaRow j ∣ Γ.gammaProd :=
  Finset.dvd_prod_of_mem _ (Finset.mem_univ j)

/-- Each `gammaRow` value is at most `gammaProd`. -/
lemma gammaRow_le_gammaProd (Γ : GammaStructure (k + 1)) (j : Fin (k + 1)) :
    Γ.gammaRow j ≤ Γ.gammaProd :=
  Nat.le_of_dvd (GammaStructure.gammaProd_pos Γ) (gammaRow_dvd_gammaProd Γ j)

/-- When `gammaProd ≤ H`, all `gammaRow` values are `≤ H`. -/
lemma gammaRow_le_of_gammaProd_le (Γ : GammaStructure (k + 1)) (H : ℕ)
    (h : Γ.gammaProd ≤ H) (i : Fin k) :
    Γ.gammaRow i.succ ≤ H :=
  le_trans (gammaRow_le_gammaProd Γ i.succ) h

/-! ### Per-Γ small gamma bound -/

/-- For any Γ with `gammaProd = γ ≤ H`, `M_Γ(H) ≤ 2^k · H^k / γ`. This is
a direct corollary of `countTuples_bound_small_gamma` combined with
`gammaRow_le_of_gammaProd_le`. -/
theorem countTuplesWithGamma_bound_of_gammaProd_le
    (Γ : GammaStructure (k + 1)) (γ H : ℕ) (hΓ : Γ.gammaProd = γ)
    (hγ_le : γ ≤ H) :
    (countTuplesWithGamma Γ H : ℝ) ≤ 2 ^ k * (H : ℝ) ^ k / γ := by
  convert countTuples_bound_small_gamma Γ H _
  · grind
  · exact fun i => le_trans ( gammaRow_le_of_gammaProd_le Γ H ( by linarith ) i ) ( by linarith )

/-! ### Decomposition of M_γ(H) -/

/-- **Decomposition lemma (reformulated)**: `M_γ(H)` is bounded by the sum of
`M_Γ(H)` over any finite set `S` of Gamma structures with `γ(Γ) = γ` that
covers all tuples in the counting set. The formulation using
`Finset.univ` is not available since `GammaStructure` is not `Fintype`
(diagonal entries are unconstrained). -/
theorem countTuplesWithGammaProd_le_sum (γ H : ℕ) (_hγ : 0 < γ) (_hH : 0 < H)
    (S : Finset (GammaStructure (k + 1)))
    (_hS_prod : ∀ Γ ∈ S, Γ.gammaProd = γ)
    (hS_cover : ∀ h : Fin (k + 1) → ℤ,
      h 0 = 0 →
      (∀ i j, i ≠ j → h i ≠ h j) →
      (∀ i, 0 ≤ h i ∧ h i ≤ H) →
      (∃ Γ : GammaStructure (k + 1), Γ.gammaProd = γ ∧
        ∀ i j, i ≠ j →
          Nat.gcd Γ.sqfreepart (Int.natAbs (h j - h i)) = Γ.gamma i j) →
      ∃ Γ ∈ S, ∀ i j, i ≠ j →
        Nat.gcd Γ.sqfreepart (Int.natAbs (h j - h i)) = Γ.gamma i j) :
    (countTuplesWithGammaProd k γ H : ℝ) ≤
      ∑ Γ ∈ S, (countTuplesWithGamma Γ H : ℝ) := by
  norm_cast
  refine le_trans ?_ ( Finset.card_biUnion_le )
  refine' le_trans _ ( Finset.card_mono _ )
  rotate_left
  exact Finset.filter ( fun h => h 0 = 0 ∧ ( ∀ i j, ¬i = j → h i ≠ h j )
      ∧ ( ∀ i, 0 ≤ h i ∧ h i ≤ H )
      ∧ ∃ Γ ∈ S, ∀ i j, ¬i = j → Γ.sqfreepart.gcd ( h j - h i |> Int.natAbs ) = Γ.gamma i j )
    ( Fintype.piFinset fun _ => Finset.Icc 0 H )
  · simp +contextual [ Finset.subset_iff ]
  · rw [ ← Set.ncard_coe_finset ]
    apply_rules [ Set.ncard_le_ncard ]
    · intro h hh; specialize hS_cover h; aesop
    · exact Set.toFinite _

/-! ### Small-γ bound on M_γ(H) -/

/-- **Small-γ bound**: `M_γ(H) ≤ (2^C(k+1,2))^{ω(γ)} · 2^k · H^k / γ` when `γ ≤ H`.
Combines `countTuplesWithGammaProd_le_sum` (decomposition over Gamma structures),
`countTuplesWithGamma_bound_of_gammaProd_le` (per-structure bound), and
`countGammaStructures_le` (structure-counting bound). -/
theorem countTuplesWithGammaProd_small_gamma (γ H : ℕ)
    (hγ : 0 < γ) (hH : 0 < H) (hγ_le : γ ≤ H) :
    (countTuplesWithGammaProd k γ H : ℝ) ≤
      ((2 ^ (k + 1).choose 2) : ℝ) ^ γ.primeFactors.card *
        2 ^ k * (H : ℝ) ^ k / γ := by
  refine le_trans (countTuplesWithGammaProd_le_sum γ H hγ hH ?_ ?_ ?_) ?_
  exact finsetGammaStructures γ
  · exact fun Γ hΓ => by simpa using hΓ
  · exact fun h hh₁ hh₂ hh₃ hh₄ =>
      ⟨hh₄.choose, mem_finsetGammaStructures.mpr hh₄.choose_spec.1, hh₄.choose_spec.2⟩
  · refine le_trans (Finset.sum_le_sum fun Γ hΓ =>
      show (countTuplesWithGamma Γ H : ℝ) ≤ 2 ^ k * H ^ k / γ from ?_) ?_
    · convert countTuplesWithGamma_bound_of_gammaProd_le Γ γ H _ _ using 1 <;> aesop
    · norm_num [mul_assoc, mul_div_assoc]
      gcongr
      exact_mod_cast countGammaStructures_le γ hγ

/-! ### Large-γ bounds on M_γ(H) (GK Corollary 5) -/

/-- The threshold `w(τ)` for the piecewise bounds on `M_γ(H)` in the large-γ regime.
Following GK Corollary 5, for `n` (which corresponds to $k-1$ in GK when counting $k$ tuples),
the threshold is $w(τ) = n + 1 - 9/8 + (τ - 1/2)^2 / 2$.
We leave this uncomputable/abstracted since we will only use it via its stated properties. -/
noncomputable def tupleBoundWeight (n : ℕ) (τ : ℕ) : ℝ :=
  (n : ℝ) + 1 - 9/8 + ((τ : ℝ) - 1/2)^2 / 2

/-- The value $\tau_1 = \lfloor \sqrt{2(n+1) + 1/4} - 1/2 \rfloor$ defining the intermediate regime. -/
noncomputable def tauOne (n : ℕ) : ℕ :=
  ⌊Real.sqrt (2 * (n : ℝ) + 2 + 1/4) - 1/2⌋₊

/-- **Intermediate-γ bound**: `M_γ(H) ≤ C^ω(γ) · H^{n+1.5-\sqrt{2n+2.25}}` when `H^{w(0)} < γ ≤ H^{w(τ_1)}`.
This is left as an honest `sorry`, reflecting the lattice-counting bounds from GK Corollary 5. -/
theorem countTuplesWithGammaProd_med_gamma (n γ H : ℕ)
    (hγ : 0 < γ) (hH : 0 < H)
    (h_gt : (H : ℝ) ^ tupleBoundWeight n 0 < (γ : ℝ))
    (h_le : (γ : ℝ) ≤ (H : ℝ) ^ tupleBoundWeight n (tauOne n)) :
    (countTuplesWithGammaProd n γ H : ℝ) ≤
      ((2 ^ (n + 1).choose 2) : ℝ) ^ γ.primeFactors.card *
        (H : ℝ) ^ ((n : ℝ) + 1.5 - Real.sqrt (2 * (n : ℝ) + 2.25)) := by
  sorry

/-- **Large-γ piecewise bound**: `M_γ(H) ≤ C^ω(γ) · H^{n+1-τ}` when `H^{w(τ-1)} < γ ≤ H^{w(τ)}`.
This is left as an honest `sorry`, reflecting the lattice-counting bounds from GK Corollary 5. -/
theorem countTuplesWithGammaProd_large_gamma (n γ H τ : ℕ)
    (hγ : 0 < γ) (hH : 0 < H) (hτ_lower : tauOne n + 1 ≤ τ) (hτ_upper : τ ≤ n)
    (h_gt : (H : ℝ) ^ tupleBoundWeight n (τ - 1) < (γ : ℝ))
    (h_le : (γ : ℝ) ≤ (H : ℝ) ^ tupleBoundWeight n τ) :
    (countTuplesWithGammaProd n γ H : ℝ) ≤
      ((2 ^ (n + 1).choose 2) : ℝ) ^ γ.primeFactors.card *
        (H : ℝ) ^ (n + 1 - τ) := by
  sorry

end PoissonCRT
