/-
Copyright (c) 2026 Fernando Portela. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Fernando Portela, Antigravity (Google DeepMind)
-/

/-
Portions of this file were generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.28.0
Mathlib version: 8f9d9cff6bd728b17a24e163c9402775d9e6a365

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

import PoissonViaCRT.Defs
import PoissonViaCRT.AnalyticInputs
import PoissonViaCRT.SmallDivisorHelpers
import PoissonViaCRT.EulerWeights
import PoissonViaCRT.GammaDeviationHelpers
import PoissonViaCRT.GammaRangeSum
import PoissonViaCRT.GammaEulerSumHelpers
import PoissonViaCRT.L1DeviationSynthesis
import Mathlib.Algebra.Order.Floor.Extended
import Mathlib.Algebra.Order.Floor.Semifield
import Mathlib.Algebra.Order.Interval.Basic
import Mathlib.Algebra.Order.Ring.Star
import Mathlib.Analysis.Complex.UpperHalfPlane.Basic
import Mathlib.Analysis.PSeries
import Mathlib.Analysis.SpecialFunctions.Bernstein
import Mathlib.Analysis.SpecialFunctions.Gamma.Basic
import Mathlib.Analysis.SpecialFunctions.Trigonometric.DerivHyp
import Mathlib.Combinatorics.Enumerative.DyckWord
import Mathlib.Combinatorics.SimpleGraph.Triangle.Removal
import Mathlib.Data.Int.Star
import Mathlib.Data.NNRat.Floor
import Mathlib.Data.Nat.Factorial.DoubleFactorial
import Mathlib.Geometry.Euclidean.Altitude
import Mathlib.NumberTheory.ArithmeticFunction.Defs
import Mathlib.NumberTheory.Chebyshev
import Mathlib.NumberTheory.LSeries.Dirichlet
import Mathlib.NumberTheory.LSeries.Nonvanishing
import Mathlib.NumberTheory.Height.Basic
import Mathlib.NumberTheory.LucasLehmer
import Mathlib.NumberTheory.SelbergSieve
import Mathlib.RingTheory.WittVector.IsPoly
import Mathlib.Topology.Sheaves.Presheaf

set_option linter.unusedVariables false

/-!
# Gamma-Deviation Synthesis

This file bridges the algebraic product-difference decomposition
(`MobiusSynthesis.lean`) with the combinatorial `M_γ(H)` tuple-counting bounds
(`Combinatorics.lean`, `GammaRangeSum.lean`).

## Overview

In the Granville–Kurlberg proof (§3.1), the sum over lattice points `h`
of the deviation product `∏_{p ∈ T} |N_p(h) − μ_p|` is reorganised by
fibering over the *gamma value* `γ` of each tuple. The gamma value is
defined via `gammaProdOfBoxPoint`: for `c = ∏_{p ∈ T} p` and a lattice
point `h` in the scaled box, the gamma product
`γ(h) = ∏_j lcm_{i<j} gcd(c, |h'_j − h'_i|)` (where `h' = (0, h)`)
encodes the collision structure.

The summation rearrangement uses `Finset.sum_fiberwise_of_maps_to` to
partition the box lattice points by their gamma value, then bounds the
per-fiber deviation product and counts the fiber cardinality using
`countTuplesWithGammaProd`.

## Main Results

* `deviation_prod_le_perGammaWeight` — Pointwise bound: for each box point `h`,
  `|∏_{p ∈ T} (N_p − μ_p)| ≤ perGammaDeviationWeight ε k Ω T γ(h)`.
* `fiber_card_le_countTuplesWithGammaProd` — Fiber cardinality: the number of
  box points with gamma value `γ` is at most `countTuplesWithGammaProd (k−1) γ H`.
* `deviation_sum_le_gamma_sum` — Synthesis: the total deviation sum is bounded
  by `∑_γ w(γ) · M_γ(H)`.

## References

* [A. Granville, P. Kurlberg, *Poisson statistics via the Chinese remainder theorem*]
  [arXiv:math/0412135v2], §3.1
-/

open Nat Finset BigOperators Classical

open ArithmeticFunction

open scoped zeta sigma

namespace PoissonCRT

-- The PNT+ ground-truth facts (`MediumPNT`, `d`, `d_apply_prime_pow`) and the
-- intermediate analytic lemmas (`divisor_bound`, `euler_product_converges`) now
-- live in `PoissonViaCRT.AnalyticInputs`.


/-! ## 1. Per-gamma deviation weight -/

/-- The per-gamma deviation weight for a subset `T` of primes.
For a gamma value `γ` (representing a collision structure), the weight
is the product over primes `p ∈ T` of:
- `p` (trivial bound) if `p ∣ radical γ` (collision prime),
- `(1 − |Ω_p|/p) · p^{−ε} · μ_p` (Weil-type bound) if `p ∤ radical γ`
  (well-distributed prime). -/
noncomputable def perGammaDeviationWeight (ε : ℝ) (k : ℕ)
    (Ω : ∀ p : ℕ, Finset (ZMod p)) (T : Finset ℕ) (γ : ℕ) : ℝ :=
  (∏ p ∈ T.filter (fun p => p ∣ radical γ),
    (k : ℝ) * (p : ℝ) * (1 - (Ω p).card / (p : ℝ))) *
  (∏ p ∈ T.filter (fun p => ¬(p ∣ radical γ)),
    (1 - (Ω p).card / (p : ℝ)) * (p : ℝ) ^ (-ε) * localMean k Ω p)

/-! ## 2. Auxiliary lemmas for the deviation-sum bound -/

/--
The `perGammaDeviationWeight` is nonneg for primes `T ⊆ q.primeFactors`.
-/
lemma perGammaDeviationWeight_nonneg (ε : ℝ) (k : ℕ)
    (Ω : ∀ p : ℕ, Finset (ZMod p)) (q : ℕ) [NeZero q]
    (T : Finset ℕ) (hT : T ⊆ q.primeFactors) (γ : ℕ) :
    0 ≤ perGammaDeviationWeight ε k Ω T γ := by
  refine mul_nonneg
      ( Finset.prod_nonneg fun p hp => mul_nonneg ( mul_nonneg (Nat.cast_nonneg _) (Nat.cast_nonneg _) ) ?_ )
      ( Finset.prod_nonneg fun p hp => mul_nonneg ( mul_nonneg ?_ ?_ ) ?_ )
  · apply sub_nonneg_of_le _
    apply div_le_one_of_le₀ _ ( Nat.cast_nonneg _ )
    haveI := Fact.mk ( Nat.prime_of_mem_primeFactors ( hT ( Finset.mem_filter.mp hp |>.1 ) ) )
    exact_mod_cast le_trans ( Finset.card_le_univ _ ) ( by norm_num )
  · apply sub_nonneg_of_le _
    apply div_le_one_of_le₀ _ ( Nat.cast_nonneg _ )
    haveI := Fact.mk ( Nat.prime_of_mem_primeFactors ( hT ( Finset.mem_filter.mp hp |>.1 ) ) )
    exact_mod_cast le_trans ( Finset.card_le_univ _ ) ( by norm_num )
  · positivity
  · exact div_nonneg ( pow_nonneg ( Nat.cast_nonneg _ ) _ ) ( pow_nonneg ( Nat.cast_nonneg _ ) _ )

/--
When `p ∈ T`, `p` is prime, and `p ∤ radical(γ(h))`, the projected
tuple `Fin.cons 0 h` is injective modulo `p`. This is because `p ∣ ∏ T`
and `p ∤ radical(γ)` together imply `p` does not divide any pairwise
difference `|h'_j − h'_i|`, where `h' = Fin.cons 0 h`.
-/
lemma not_dvd_radical_gammaProd_imp_injective {n : ℕ} (hn : 1 ≤ n)
    (T : Finset ℕ) (q : ℕ) [NeZero q]
    (hT : T ⊆ q.primeFactors)
    (p : ℕ) (hp_prime : Nat.Prime p) (hp_T : p ∈ T)
    (h : Fin n → ℤ)
    (hp_not : ¬(p ∣ radical (gammaProdOfBoxPoint T h))) :
    let g : Fin (n + 1) → ZMod q :=
      Fin.cons (0 : ZMod q) (fun j : Fin n => ((h j : ℤ) : ZMod q))
    haveI : NeZero p := ⟨hp_prime.ne_zero⟩
    Function.Injective (fun i : Fin (n + 1) =>
      ZMod.castHom (Nat.dvd_of_mem_primeFactors (hT hp_T)) (ZMod p) (g i)) := by
  intro i j hij
  generalize_proofs at *
  intro h_eq
  generalize_proofs at *
  contrapose! hp_not
  simp_all +decide only [ZMod.castHom_apply, ne_eq, radical]
  apply dvd_trans _ ( Finset.dvd_prod_of_mem _ <|
    Nat.mem_primeFactors.mpr ⟨ hp_prime, _, _ ⟩ ) <;>
      norm_num [ gammaProdOfBoxPoint ]
  · apply dvd_trans _ ( Finset.dvd_prod_of_mem _ ( Finset.mem_univ ( Max.max j hij ) ) )
    cases max_choice j hij <;> simp_all +decide only [sup_eq_left, sup_of_le_left, sup_eq_right,
      sup_of_le_right]
    · apply dvd_trans _ ( Finset.dvd_lcm ( Finset.mem_Iio.mpr <| show hij < j from
        lt_of_le_of_ne ‹_› <| Ne.symm hp_not ) ) ; simp_all +decide only [Fin.cons]
      apply Nat.dvd_gcd ( Finset.dvd_prod_of_mem _ hp_T ) _
      rw [ ← Int.natCast_dvd ]
      haveI := Fact.mk hp_prime; simp_all +decide [← ZMod.intCast_zmod_eq_zero_iff_dvd]
      cases j using Fin.inductionOn <;> cases hij using Fin.inductionOn <;> aesop
    · apply dvd_trans _ ( Finset.dvd_lcm ( Finset.mem_Iio.mpr ( lt_of_le_of_ne ‹_› hp_not ) ) )
      simp_all +decide only [Fin.cons]
      apply Nat.dvd_gcd ( Finset.dvd_prod_of_mem _ hp_T ) _
      rw [ ← Int.natCast_dvd ]
      simp_all +decide only [← ZMod.intCast_zmod_eq_zero_iff_dvd, Int.cast_sub, sub_eq_iff_eq_add,
        zero_add]
      convert h_eq.symm using 1
      · cases hij using Fin.inductionOn <;> aesop
      · cases j using Fin.inductionOn <;> aesop
  · simp +decide only [prod_eq_zero_iff, mem_univ, Finset.lcm_eq_zero_iff, mem_Iio,
    Nat.gcd_eq_zero_iff, ↓existsAndEq, and_true, Int.natAbs_eq_zero, true_and, not_exists, not_and]
    intro i j hij h0; have := hT h0; simp_all +decide

/--
Weil-type bound on `|localCount − localMean|` when the tuple is
injective modulo `p` (without requiring `p > ⌈s * ∑ sides⌉`).
-/
lemma localCount_deviation_of_injective {ε : ℝ} {n : ℕ} (hn : 1 ≤ n)
    (Ω : ∀ p : ℕ, Finset (ZMod p)) (q : ℕ) [NeZero q]
    (p : ℕ) (hp_prime : Nat.Prime p) (hp_factor : p ∈ q.primeFactors)
    (hWD : @WellDistributed ε p ⟨hp_prime⟩ (Ω p) (n + 1))
    (h : Fin n → ℤ)
    (h_inj :
      let g : Fin (n + 1) → ZMod q :=
        Fin.cons (0 : ZMod q) (fun j : Fin n => ((h j : ℤ) : ZMod q))
      haveI : NeZero p := ⟨hp_prime.ne_zero⟩
      Function.Injective (fun i : Fin (n + 1) =>
        ZMod.castHom (Nat.dvd_of_mem_primeFactors hp_factor) (ZMod p) (g i))) :
    |localCount Ω q (Fin.cons (0 : ZMod q) (fun i => ((h i : ℤ) : ZMod q))) p -
      localMean (n + 1) Ω p| ≤
    (1 - (Ω p).card / (p : ℝ)) * (p : ℝ) ^ (-ε) * localMean (n + 1) Ω p := by
  unfold localCount localMean
  simp +decide only [↓reduceDIte, Fin.cons, ZMod.castHom_apply, add_tsub_cancel_right, hp_factor]
  convert hWD.1 _ _ using 1
  convert h_inj using 1

/--
**Pointwise Weight Bound.** For a single lattice point `h` in the box,
the absolute deviation product `|∏_{p ∈ T} (localCount − localMean)|` is
bounded by `perGammaDeviationWeight ε k Ω T γ`, where `γ` is the gamma
product `gammaProdOfBoxPoint T h`.

The proof splits `T` into collision primes (`p ∣ radical γ`) and
well-distributed primes (`p ∤ radical γ`):
- Collision primes get the trivial bound `|localCount − localMean| ≤ p`
  via `abs_localCount_sub_localMean_le_p`.
- Well-distributed primes: since `p ∤ radical γ` and `p ∣ ∏ T`, the
  tuple `Fin.cons 0 h` is injective mod `p`, so the `WellDistributed`
  hypothesis gives `|localCount − localMean| ≤ (1−|Ω|/p)·p^{−ε}·μ_p`.

Uses `not_dvd_radical_gammaProd_imp_injective` and
`localCount_deviation_of_injective` as sub-lemmas.
-/
lemma deviation_prod_le_perGammaWeight (ε : ℝ) (hε : 0 < ε) (k : ℕ) (hk : 2 ≤ k)
    (Ω : ∀ p : ℕ, Finset (ZMod p)) (q : ℕ) [NeZero q] (hq : Squarefree q)
    (hΩ : ∀ p, p.Prime → (Ω p).Nonempty)
    (hWD : ∀ (p : ℕ) [Fact p.Prime], WellDistributed ε p (Ω p) k)
    (X : Box (k - 1)) (s : ℝ) (hs : 1 ≤ s)
    (T : Finset ℕ) (hT : T ⊆ q.primeFactors) (hT_ne : T.Nonempty)
    (h : Fin (k - 1) → ℤ)
    (hh_mem : h ∈ (Fintype.piFinset fun _ : Fin (k - 1) =>
        Finset.Icc (1 : ℤ) ↑(⌈s * ∑ i, X.sides i⌉₊)))
    (hbox : inScaledBox X s (fun _ => 0) h) :
    |∏ p ∈ T, (localCount Ω q
        (Fin.cons (0 : ZMod q) fun i => (h i : ZMod q)) p -
        localMean k Ω p)| ≤
    perGammaDeviationWeight ε k Ω T (gammaProdOfBoxPoint T h) := by
  -- For each prime $p \in T$, we can split the product into two parts: one where $p$ divides
  -- the radical of $\gamma$ and one where it does not.
  have h_split : ∀ p ∈ T,
      |localCount Ω q (Fin.cons 0 (fun i => ((h i : ℤ) : ZMod q))) p - localMean k Ω p|
      ≤ if p ∣ radical (gammaProdOfBoxPoint T h) then
          (k : ℝ) * (p : ℝ) * (1 - (Ω p).card / (p : ℝ))
      else (1 - (Ω p).card / (p : ℝ)) * (p : ℝ) ^ (-ε) * localMean k Ω p := by
    intro p hp
    split_ifs
    · -- Collision prime: sharp union bound `|N_p − μ_p| ≤ k·p·(1 − r_p)`.
      have hp_prime := Nat.prime_of_mem_primeFactors (hT hp)
      have hp_pos : (0 : ℝ) < (p : ℝ) := by exact_mod_cast hp_prime.pos
      have h_collision := localCount_sub_localMean_abs_le_collision k hk Ω q p (hT hp) h
      refine h_collision.trans (le_of_eq ?_)
      field_simp
    · convert localCount_deviation_of_injective ( show 1 ≤ k - 1 from
        Nat.le_sub_one_of_lt hk ) Ω q p ( Nat.prime_of_mem_primeFactors ( hT hp ) )
          ( hT hp ) _ h _ using 1
      any_goals rw [ Nat.sub_add_cancel ( by linarith ) ]
      · grind
      · convert hWD p using 1
      · convert not_dvd_radical_gammaProd_imp_injective
          ( show 1 ≤ k - 1 from Nat.le_sub_one_of_lt hk ) T q hT p
          ( Nat.prime_of_mem_primeFactors ( hT hp ) ) hp h ‹_› using 1
  convert Finset.prod_le_prod ?_ h_split using 1
  · rw [ Finset.abs_prod ]
  · unfold perGammaDeviationWeight; simp +decide [ Finset.prod_ite ]
  · exact fun _ _ => abs_nonneg _

/-- **Fiber Cardinality Bound.** For any fixed `γ`, the number of box
lattice points `h` that map to `γ` via `gammaProdOfBoxPoint` is bounded
by `countTuplesWithGammaProd (k − 1) γ H`.

The proof shows that each `h` in the fiber corresponds to a tuple
`Fin.cons 0 h` satisfying the conditions in `countTuplesWithGammaProd`:
- `(Fin.cons 0 h) 0 = 0`
- distinct entries (from `inScaledBox_strictMono`)
- `0 ≤ (Fin.cons 0 h) i ≤ H`
- existence of a matching `GammaStructure` (via `GammaStructure.ofTuple`) -/
/- TODO: The proof requires:
   1. Showing each h in the fiber maps to a tuple Fin.cons 0 h satisfying
      the conditions in countTuplesWithGammaProd (h' 0 = 0, distinct entries,
      0 ≤ h' i ≤ H, and existence of a matching GammaStructure).
   2. The key difficulty is proving that
      gcd(radical(γ), |h'_j - h'_i|) = gcd(∏ T, |h'_j - h'_i|)
      which is needed for the GammaStructure matching condition.
   3. Using injectivity of Fin.cons 0 to bound the fiber cardinality. -/

lemma fiber_card_le_countTuplesWithGammaProd (k : ℕ) (hk : 2 ≤ k)
    (T : Finset ℕ) (q : ℕ) [NeZero q] (hq : Squarefree q) (hT : T ⊆ q.primeFactors)
    (X : Box (k - 1)) (s : ℝ) (hs : 1 ≤ s) (γ : ℕ) :
    let H := ⌈s * ∑ i, X.sides i⌉₊
    (((Fintype.piFinset fun _ : Fin (k - 1) => Finset.Icc (1 : ℤ) ↑H).filter
      (fun h => inScaledBox X s (fun _ => 0) h)).filter
      (fun h => gammaProdOfBoxPoint T h = γ)).card ≤
    countTuplesWithGammaProd (k - 1) γ H := by
  intro H
  -- The fiber is a finset of h : Fin (k-1) → ℤ
  -- Map each h to Fin.cons 0 h : Fin k → ℤ and show it's in the counting set
  set S := ((Fintype.piFinset fun _ : Fin (k - 1) => Finset.Icc (1 : ℤ) ↑H).filter
    (fun h => inScaledBox X s (fun _ => 0) h)).filter
    (fun h => gammaProdOfBoxPoint T h = γ) with S_def
  -- countTuplesWithGammaProd is Set.ncard of a set
  unfold countTuplesWithGammaProd
  -- Map h to h' = Fin.cons 0 h
  have h_inj : ∀ a ∈ S, ∀ b ∈ S,
      (Fin.cons (0 : ℤ) a : Fin (k - 1 + 1) → ℤ) = Fin.cons (0 : ℤ) b → a = b := by
    intro a _ b _ hab
    funext i; have := congr_fun hab (Fin.succ i)
    simp only [Fin.cons, Fin.cases_succ] at this; exact this
  set F : (Fin (k - 1) → ℤ) → (Fin (k - 1 + 1) → ℤ) := fun h => Fin.cons (0 : ℤ) h
  have h_card : S.card = (S.image F).card :=
    (Finset.card_image_of_injOn (fun a ha b hb => h_inj a ha b hb)).symm
  rw [h_card, ← Set.ncard_coe_finset]
  apply Set.ncard_le_ncard
  · intro h' hh'
    simp only [Finset.coe_image, Set.mem_image, Finset.mem_coe] at hh'
    obtain ⟨h, hh, rfl⟩ := hh'
    simp only [S_def, Finset.mem_filter] at hh
    obtain ⟨⟨hh_pi, hh_box⟩, hh_gamma⟩ := hh
    -- Show h' = Fin.cons 0 h is in the counting set
    refine ⟨?_, ?_, ?_, ?_⟩
    · -- h' 0 = 0
      rfl
    · -- distinct entries
      exact fin_cons_zero_injective (by omega) X s h hh_box
    · -- 0 ≤ h' i ≤ H
      exact fin_cons_zero_range H h hh_pi
    · -- ∃ Γ with matching structure
      have h_dist := fin_cons_zero_injective (by omega) X s h hh_box
      have hc_sq := prod_primes_squarefree T q hq hT
      refine ⟨GammaStructure.ofTuple (∏ p ∈ T, p) hc_sq (Fin.cons 0 h) h_dist, ?_, ?_⟩
      · -- gammaProd = γ
        rw [gammaProd_ofTuple_eq T _ hc_sq rfl h h_dist]
        exact hh_gamma
      · -- matching gcd condition
        exact ofTuple_gcd_eq _ hc_sq _ h_dist
  · apply Set.Finite.subset (Finset.finite_toSet
      (Fintype.piFinset (fun _ : Fin (k - 1 + 1) => Finset.Icc (0 : ℤ) H)))
    intro h' ⟨_, _, hh_range, _⟩
    simp only [Fintype.mem_piFinset, Finset.mem_Icc, Finset.mem_coe]
    exact fun i => hh_range i

/-- The gamma product of a box point is in `[1, H ^ k]`. The lower bound
follows from `gammaProd_pos` (the tuple has distinct entries, giving at least
one nontrivial gcd). The upper bound follows from each `gammaRow j` dividing
`∏_{i<j} |h'_j − h'_i| ≤ H^j`, so `γ ≤ H^{k(k−1)/2} ≤ H^k` when `k ≤ 3`,
and from `countTuplesWithGammaProd = 0` for out-of-range `γ` otherwise. -/
/- TODO: The lower bound (γ ≥ 1) is straightforward since each lcm factor
   is ≥ 1 (Finset.lcm starts from 1, and gcd(c, d) ≥ 1 for c ≥ 1 and d ≥ 1).
   The upper bound (γ ≤ H^k) holds for k ≤ 3 by the estimate
   gammaRow_j ≤ H^j and k(k-1)/2 ≤ k. For k ≥ 4, the bound may need
   strengthening to H^{k(k-1)/2} or ∏ T^{k-1}, depending on the
   application context. -/
lemma gammaProdOfBoxPoint_mem_Icc (k : ℕ) (hk : 2 ≤ k)
    (T : Finset ℕ) (hT_ne : T.Nonempty)
    (q : ℕ) [NeZero q] (hq : Squarefree q) (hT : T ⊆ q.primeFactors)
    (X : Box (k - 1)) (s : ℝ) (hs : 1 ≤ s)
    (h : Fin (k - 1) → ℤ)
    (hh_mem : h ∈ (Fintype.piFinset fun _ : Fin (k - 1) =>
        Finset.Icc (1 : ℤ) ↑(⌈s * ∑ i, X.sides i⌉₊)))
    (hbox : inScaledBox X s (fun _ => 0) h) :
    gammaProdOfBoxPoint T h ∈ Finset.Icc 1 (⌈s * ∑ i, X.sides i⌉₊ ^ (k * k)) := by
  simp only [Finset.mem_Icc]
  set H := ⌈s * ∑ i, X.sides i⌉₊ with H_def
  constructor
  · -- Lower bound: γ ≥ 1
    exact gammaProdOfBoxPoint_pos T hT_ne q hT h
  · -- Upper bound: γ ≤ H^(k*k)
    -- k * k ≥ (k-1+1)*(k-1+1) = k*k, so H^(k*k) ≥ H^((k-1+1)*(k-1+1))
    have hH_pos : 0 < H := by
      apply Nat.ceil_pos.mpr
      exact mul_pos (by linarith) (Finset.sum_pos (fun _ _ => X.sides_pos _)
        ⟨⟨0, by omega⟩, Finset.mem_univ _⟩)
    have hkk : (k - 1 + 1) * (k - 1 + 1) ≤ k * k := by
      rw [Nat.sub_add_cancel (by omega : 1 ≤ k)]
    calc gammaProdOfBoxPoint T h
        ≤ H ^ ((k - 1 + 1) * (k - 1 + 1)) := by
          apply gammaProdOfBoxPoint_le T H hH_pos h
          · exact natAbs_diff_le_H H h hh_mem
          · exact fin_cons_zero_diff_pos (by omega) X s h hbox
      _ ≤ H ^ (k * k) := Nat.pow_le_pow_right hH_pos hkk

/-
**Prime factors of a gamma product are in `T`.** Every prime dividing
`gammaProdOfBoxPoint T h` lies in `T`. This is because `gammaProdOfBoxPoint T h`
is a product of `lcm`s of values `gcd(∏_{p∈T} p, ·)`, each of which divides
`∏_{p∈T} p`; hence the whole product divides a power of `∏_{p∈T} p`, whose
prime factors are exactly `T` (when `T` consists of primes).

This justifies restricting the gamma summation domain to those `γ` with
`γ.primeFactors ⊆ T`: the box-point fibres are empty outside this set.
-/
lemma gammaProdOfBoxPoint_primeFactors_subset {n : ℕ} (T : Finset ℕ)
    (hT_prime : ∀ p ∈ T, Nat.Prime p) (h : Fin n → ℤ) :
    (gammaProdOfBoxPoint T h).primeFactors ⊆ T := by
  -- By definition of gammaProdOfBoxPoint, we know that every prime factor of gammaProdOfBoxPoint T h divides c.
  have h_divides_c : gammaProdOfBoxPoint T h ∣ (∏ p ∈ T, p) ^ (n + 1) := by
    convert Finset.prod_dvd_prod_of_dvd _ _ _;
    rotate_left;
    exact fun _ => ∏ p ∈ T, p;
    · exact fun i _ => Finset.lcm_dvd fun j hj => Nat.gcd_dvd_left _ _;
    · norm_num;
  grind +suggestions

/-! ## 3. Deviation sum bounded by gamma sum -/

/-- **Deviation-sum ≤ gamma-sum (per-T bound).**

For a nonempty subset `T ⊆ q.primeFactors`, the sum over box lattice
points `h` of the absolute deviation product `|∏_{p ∈ T} (N_p(h) − μ_p)|`
is bounded by a sum over gamma values `γ ∈ [1, H^{k^2}]` of the per-gamma
deviation weight times the tuple count `M_γ(H)`.

The proof proceeds by:
1. Applying `Finset.sum_fiberwise_of_maps_to` with the fibering function
   `gammaProdOfBoxPoint T` to partition the sum by gamma value.
2. Bounding each fiber sum using the pointwise bound
   `deviation_prod_le_perGammaWeight`.
3. Bounding each fiber cardinality using
   `fiber_card_le_countTuplesWithGammaProd`. -/
lemma deviation_sum_le_gamma_sum (ε : ℝ) (hε : 0 < ε) (k : ℕ) (hk : 2 ≤ k)
    (Ω : ∀ p : ℕ, Finset (ZMod p)) (q : ℕ) [NeZero q] (hq : Squarefree q)
    (hΩ : ∀ p, p.Prime → (Ω p).Nonempty)
    (hWD : ∀ (p : ℕ) [Fact p.Prime], WellDistributed ε p (Ω p) k)
    (X : Box (k - 1)) (s : ℝ) (hs : 1 ≤ s)
    (T : Finset ℕ) (hT : T ⊆ q.primeFactors) (hT_ne : T.Nonempty) :
    let H := ⌈s * ∑ i, X.sides i⌉₊
    ∑ h ∈ ((Fintype.piFinset fun _ : Fin (k - 1) =>
        Finset.Icc (1 : ℤ) ↑H).filter
      (fun h => inScaledBox X s (fun _ => 0) h)),
      |∏ p ∈ T, (localCount Ω q
          (Fin.cons (0 : ZMod q) fun i => (h i : ZMod q)) p -
          localMean k Ω p)| ≤
    ∑ γ ∈ (Finset.Icc 1 (H ^ (k * k))).filter (fun γ => γ.primeFactors ⊆ T),
      perGammaDeviationWeight ε k Ω T γ *
        (countTuplesWithGammaProd (k - 1) γ H : ℝ) := by
  -- Introduce the let-binding and set up notation
  set H := ⌈s * ∑ i, X.sides i⌉₊ with H_def
  -- Eliminate the trivial let-binding left in the goal
  change ∑ h ∈ ((Fintype.piFinset fun _ : Fin (k - 1) =>
      Finset.Icc (1 : ℤ) ↑H).filter
    (fun h => inScaledBox X s (fun _ => 0) h)),
    |∏ p ∈ T, (localCount Ω q
        (Fin.cons (0 : ZMod q) fun i => (h i : ZMod q)) p -
        localMean k Ω p)| ≤
    ∑ γ ∈ (Finset.Icc 1 (H ^ (k * k))).filter (fun γ => γ.primeFactors ⊆ T),
      perGammaDeviationWeight ε k Ω T γ *
        (countTuplesWithGammaProd (k - 1) γ H : ℝ)
  set S := ((Fintype.piFinset fun _ : Fin (k - 1) =>
      Finset.Icc (1 : ℤ) ↑H).filter
    (fun h => inScaledBox X s (fun _ => 0) h)) with S_def
  set f := fun h : Fin (k - 1) → ℤ =>
    |∏ p ∈ T, (localCount Ω q
        (Fin.cons (0 : ZMod q) fun i => (h i : ZMod q)) p -
        localMean k Ω p)| with f_def
  set g := fun h : Fin (k - 1) → ℤ => gammaProdOfBoxPoint T h with g_def
  set w := fun γ => perGammaDeviationWeight ε k Ω T γ with w_def
  -- Step 1: Show g maps S into Icc 1 (H^k)
  have hg : ∀ h ∈ S, g h ∈ (Finset.Icc 1 (H ^ (k * k))).filter (fun γ => γ.primeFactors ⊆ T) := by
    intro h hh
    simp only [S_def, Finset.mem_filter] at hh
    refine Finset.mem_filter.mpr ⟨gammaProdOfBoxPoint_mem_Icc k hk T hT_ne q hq hT X s hs h hh.1 hh.2,
      gammaProdOfBoxPoint_primeFactors_subset T
        (fun p hp => Nat.prime_of_mem_primeFactors (hT hp)) h⟩
  -- Step 2: Apply fiberwise decomposition (rewrite LHS into grouped form)
  have fiber_eq : ∑ h ∈ S, f h =
      ∑ γ ∈ (Finset.Icc 1 (H ^ (k * k))).filter (fun γ => γ.primeFactors ⊆ T), ∑ h ∈ S.filter (fun h => g h = γ), f h :=
    (Finset.sum_fiberwise_of_maps_to hg f).symm
  rw [show ∑ h ∈ S, f h
           = ∑ γ ∈ (Finset.Icc 1 (H ^ (k * k))).filter (fun γ => γ.primeFactors ⊆ T), ∑ h ∈ S.filter (fun h => g h = γ), f h from fiber_eq]
  -- Step 3: Bound each fiber sum
  apply Finset.sum_le_sum
  intro γ _hγ
  -- Step 3a: Pointwise bound on each summand in the fiber
  have h_pointwise : ∀ h ∈ S.filter (fun h => g h = γ), f h ≤ w γ := by
    intro h hh
    have hh_S : h ∈ S := (Finset.mem_filter.mp hh).1
    have hh_γ : g h = γ := (Finset.mem_filter.mp hh).2
    have hh_pi : h ∈ Fintype.piFinset fun _ : Fin (k - 1) => Finset.Icc (1 : ℤ) ↑H :=
      (Finset.mem_filter.mp hh_S).1
    have hh_box : inScaledBox X s (fun _ => 0) h := (Finset.mem_filter.mp hh_S).2
    have h_bound := deviation_prod_le_perGammaWeight ε hε k hk Ω q hq hΩ hWD X s hs T hT hT_ne h
      hh_pi hh_box
    simp only [f_def, w_def, g_def] at *
    rw [← hh_γ]
    exact h_bound
  -- Step 3b: Bound fiber sum by w(γ) * |fiber|
  have h_fiber_sum : ∑ h ∈ S.filter (fun h => g h = γ), f h ≤
      w γ * ((S.filter (fun h => g h = γ)).card : ℝ) := by
    have h_le := Finset.sum_le_card_nsmul _ _ (w γ) h_pointwise
    rw [nsmul_eq_mul] at h_le
    linarith
  -- Step 3c: Bound fiber cardinality
  have h_fiber_card : ((S.filter (fun h => g h = γ)).card : ℝ) ≤
      (countTuplesWithGammaProd (k - 1) γ H : ℝ) := by
    exact_mod_cast fiber_card_le_countTuplesWithGammaProd k hk T q hq hT X s hs γ
  -- Step 3d: Combine
  calc ∑ h ∈ S.filter (fun h => g h = γ), f h
      ≤ w γ * ((S.filter (fun h => g h = γ)).card : ℝ) := h_fiber_sum
    _ ≤ w γ * (countTuplesWithGammaProd (k - 1) γ H : ℝ) := by
        exact mul_le_mul_of_nonneg_left h_fiber_card
          (perGammaDeviationWeight_nonneg ε k Ω q T hT γ)

/-! ## 4. Auxiliary lemmas for the gamma-weighted series bound -/

/--
**Euler product expansion.** The product `∏_{p ∈ S} (1 + 1/p)` equals
the sum over all subsets `A ⊆ S` of `∏_{p ∈ A} (1/p)`. This follows
from `Finset.prod_add` with `f = 1/p`, `g = 1`.
-/
lemma euler_product_one_add_inv (S : Finset ℕ) :
    ∏ p ∈ S, (1 + 1 / (p : ℝ)) =
    ∑ A ∈ S.powerset, ∏ p ∈ A, (1 / (p : ℝ)) := by
  simp +decide [ add_comm, Finset.prod_add ]

/--
For squarefree `γ` divisible by `d = ∏ T` (where `T` consists of primes),
we have `T ⊆ γ.primeFactors` and
`γ = (∏ p ∈ T, p) * ∏ p ∈ γ.primeFactors \ T, p`.
-/
lemma squarefree_prod_primeFactors_sdiff (T : Finset ℕ) (hT : ∀ p ∈ T, Nat.Prime p)
    (γ : ℕ) (hγ : Squarefree γ) (hdvd : (∏ p ∈ T, p) ∣ γ) :
    γ = (∏ p ∈ T, p) * ∏ p ∈ γ.primeFactors \ T, p := by
  convert Nat.prod_primeFactors_of_squarefree hγ |> Eq.symm |> Eq.trans <| ?_ using 1
  rw [ ← Finset.prod_union ( Finset.disjoint_sdiff ), Finset.union_sdiff_of_subset ]
  have h_prime_factors : T ⊆ γ.primeFactors := by
    have h_div : ∏ p ∈ T, p ∣ γ := hdvd
    have h_prime : ∀ p ∈ T, Nat.Prime p := hT
    exact fun p hp =>
      Nat.mem_primeFactors.mpr ⟨ h_prime p hp, Nat.dvd_trans ( Finset.dvd_prod_of_mem _ hp ) h_div,
        by aesop ⟩
  assumption

/--
For squarefree `γ ∈ [1, N]`, the set `γ.primeFactors \ T` lies in
the powerset of `S = {primes p ∈ [2,N], p ∉ T}`.
-/
lemma primeFactors_sdiff_mem_powerset (T : Finset ℕ) (hT : ∀ p ∈ T, Nat.Prime p)
    (N γ : ℕ) (hγ_sq : Squarefree γ) (hγ_range : γ ∈ Finset.Icc 1 N) :
    γ.primeFactors \ T ∈
      ((Finset.Icc 2 N).filter (fun p => Nat.Prime p ∧ p ∉ T)).powerset := by
  simp +zetaDelta only [mem_Icc, mem_powerset] at *
  intro p hp
  simp_all +decide only [mem_sdiff, Nat.mem_primeFactors, ne_eq, mem_filter, mem_Icc,
    not_false_eq_true, and_self, and_true]
  exact ⟨ hp.1.1.two_le, Nat.le_trans ( Nat.le_of_dvd hγ_range.1 hp.1.2.1 ) hγ_range.2 ⟩

/--
The map `γ ↦ γ.primeFactors \ T` is injective on squarefree multiples
of `d = ∏ T`. This is because squarefree `γ` is determined by its prime
factors, and `T ⊆ γ.primeFactors` (so the sdiff determines all of
`γ.primeFactors`).
-/
lemma primeFactors_sdiff_injOn (T : Finset ℕ) (hT : ∀ p ∈ T, Nat.Prime p) (N : ℕ) :
    Set.InjOn (fun γ : ℕ => γ.primeFactors \ T)
      ((Finset.Icc 1 N).filter (fun γ => Squarefree γ ∧ (∏ p ∈ T, p) ∣ γ) : Finset ℕ) := by
  intros γ₁ hγ₁ γ₂ hγ₂ h_eq
  simp_all +decide only [coe_filter, mem_Icc, Set.mem_setOf_eq, Finset.ext_iff, mem_sdiff,
    Nat.mem_primeFactors, ne_eq, and_congr_left_iff, and_congr_right_iff]
  -- Since γ₁ and γ₂ are squarefree and divisible by d, their prime factors are exactly T and
  -- the prime factors of γ₁ and γ₂ that are not in T.
  have h_prime_factors :
      γ₁.primeFactors = T ∪ (γ₁.primeFactors \ T)
      ∧ γ₂.primeFactors = T ∪ (γ₂.primeFactors \ T) := by
    have h_prime_factors : T ⊆ γ₁.primeFactors ∧ T ⊆ γ₂.primeFactors := by
      exact ⟨ fun p hp => Nat.mem_primeFactors.mpr ⟨ hT p hp,
          Nat.dvd_trans ( Finset.dvd_prod_of_mem _ hp ) hγ₁.2.2, by linarith ⟩,
        fun p hp => Nat.mem_primeFactors.mpr ⟨ hT p hp,
          Nat.dvd_trans ( Finset.dvd_prod_of_mem _ hp ) hγ₂.2.2, by linarith ⟩ ⟩
    generalize_proofs at *; (
    exact ⟨ by rw [ Finset.union_sdiff_of_subset h_prime_factors.1 ],
      by rw [ Finset.union_sdiff_of_subset h_prime_factors.2 ] ⟩)
  generalize_proofs at *; (
  -- Since γ₁ and γ₂ are squarefree and have the same prime factors, they must be equal.
  have h_eq_prime_factors : γ₁.primeFactors = γ₂.primeFactors := by
    grind +ring
  generalize_proofs at *; (
  exact Nat.prod_primeFactors_of_squarefree hγ₁.2.1 ▸ Nat.prod_primeFactors_of_squarefree hγ₂.2.1 ▸
    by rw [ h_eq_prime_factors ] ))



/-- **Tail Euler weight.** The combined Euler weight multiplied by `p^{ε/2}`,
used in the Rankin trick. With the spacing hypothesis, this is
`O(k · p^{-1-ε/2})`, which is summable. -/
noncomputable def tailEulerWeight (ε : ℝ) (k : ℕ) (Ω : ∀ p : ℕ, Finset (ZMod p)) (p : ℕ) : ℝ :=
  combinedEulerWeight ε k Ω p * (p : ℝ) ^ (ε / 2)



/-! ## 5. Gamma-weighted series bound -/

/--
If `p` is prime and divides `radical γ`, then `p ≤ γ`.
-/
lemma prime_dvd_radical_le_self (p γ : ℕ) (hp : p.Prime) (h : p ∣ radical γ) : p ≤ γ := by
  by_cases hg : γ = 0 <;> simp_all +decide only [radical, Nat.primeFactors_zero, prod_empty,
    Nat.dvd_one, nonpos_iff_eq_zero]
  simp_all +decide only [Nat.Prime.dvd_iff_not_coprime hp, Nat.coprime_prod_right_iff,
    Nat.mem_primeFactors, ne_eq, not_false_eq_true, and_true, and_imp, not_forall]
  obtain ⟨ q, hq₁, hq₂, hq₃ ⟩ := h
  have := Nat.gcd_dvd_left p q
  have := Nat.gcd_dvd_right p q
  simp_all +decide only [Nat.dvd_prime, false_or, ge_iff_le, Nat.gcd_self]
  exact Nat.le_of_dvd ( Nat.pos_of_ne_zero hg ) hq₂

/--
The Weil weight `(1 − |Ω_p|/p) · p^{−ε} · localMean k Ω p` is at most `p`
for any prime `p` and `ε ≥ 0`.
-/
lemma weil_weight_le_prime (ε : ℝ) (hε : 0 ≤ ε) (k : ℕ) (hk : 1 ≤ k)
    (Ω : ∀ p : ℕ, Finset (ZMod p)) (p : ℕ) (hp : p.Prime) :
    (1 - (Ω p).card / (p : ℝ)) * (p : ℝ) ^ (-ε) * localMean k Ω p ≤ (p : ℝ) := by
  have h_weil_weight_le_p :
      (1 - (Ω p).card / (p : ℝ)) * (p : ℝ) ^ (-ε) * localMean k Ω p
      ≤ (1 : ℝ) * (p : ℝ) ^ (-ε) * p := by
    gcongr <;> norm_num [ localMean ]
    · positivity
    · positivity
    · have h_card_le_p : (Ω p).card ≤ p := by
        haveI := Fact.mk hp
        exact le_trans ( Finset.card_le_univ _ ) ( by norm_num )
      generalize_proofs at *; (
      rcases k with ( _ | k ) <;> simp_all +decide only [le_add_iff_nonneg_left, zero_le, pow_succ,
        add_tsub_cancel_right, ge_iff_le]
      exact div_le_of_le_mul₀ ( by positivity ) ( by positivity ) ( by
        norm_cast
        nlinarith [ pow_pos ( Nat.pos_of_ne_zero hp.ne_zero ) k,
          pow_le_pow_left' h_card_le_p k ] ))
  exact h_weil_weight_le_p.trans ( by
    rw [ one_mul ]
    exact mul_le_of_le_one_left ( Nat.cast_nonneg _ ) ( by
      simpa using Real.rpow_le_rpow_of_exponent_le ( Nat.one_le_cast.mpr hp.pos )
        ( neg_nonpos.mpr hε ) ) )

/--
**Prefactor absorption inequality.**
`(1/|Ω_q|) · ∏_{q.pf ∖ T} μ_p ≤ ∏_T μ_p⁻¹`.
-/
private lemma prefactor_le_inv_prod_localMean (k : ℕ) (hk : 2 ≤ k)
    (Ω : ∀ p : ℕ, Finset (ZMod p))
    (q : ℕ) [NeZero q] (hq : Squarefree q)
    (hΩ : ∀ p, p.Prime → (Ω p).Nonempty)
    (T : Finset ℕ) (hT : T ⊆ q.primeFactors) :
    (1 / (crtSubset q Ω).card : ℝ) *
      ∏ p ∈ q.primeFactors \ T, localMean k Ω p ≤
    ∏ p ∈ T, (localMean k Ω p)⁻¹ := by
  -- By definition of cardinality, we know that
  -- $(crtSubset q).card � =� \prod_{p \in q.primeFactors} (Ω p).card$.
  have h_card : ((crtSubset q Ω).card : ℝ) = (∏ p ∈ q.primeFactors, (Ω p).card : ℝ) := by
    convert globalMean_eq_prod_localMean 1 q hq Ω using 1
    · norm_num
    · unfold localMean; norm_num
  rw [ h_card, div_mul_eq_mul_div, div_le_iff₀ ]
  · rw [ ← Finset.prod_sdiff hT ]
    simp +decide [localMean, mul_assoc, mul_comm]
    field_simp
    rw [ div_le_div_iff₀ ] <;> norm_cast <;> norm_num [ Finset.prod_eq_zero_iff, Nat.Prime.ne_zero ]
    · have h_prod_le : ∀ p ∈ q.primeFactors, (Ω p).card ^ k ≤ p ^ (k - 1) * (Ω p).card := by
        intro p hp
        have h_card_le : (Ω p).card ≤ p := by
          haveI := Fact.mk ( Nat.prime_of_mem_primeFactors hp )
          exact le_trans ( Finset.card_le_univ _ ) ( by norm_num )
        exact le_trans ( by rw [ ← pow_succ, Nat.sub_add_cancel ( by linarith ) ] )
          ( Nat.mul_le_mul_right _ ( Nat.pow_le_pow_left h_card_le _ ) )
      apply le_trans ( Nat.mul_le_mul ( Finset.prod_le_prod' fun p hp =>
          h_prod_le p <| Finset.mem_sdiff.mp hp |>.1 )
        ( Finset.prod_le_prod' fun p hp => h_prod_le p <| hT hp ) ) _
      simp +decide [ mul_assoc, mul_comm, mul_left_comm, Finset.prod_mul_distrib ]
    · exact fun p hp _ _ _ => pow_pos hp.pos _
    · exact fun p hp =>
        pow_pos ( Finset.card_pos.mpr ( hΩ p ( Nat.prime_of_mem_primeFactors ( hT hp ) ) ) ) _
  · exact Finset.prod_pos fun p hp =>
      Nat.cast_pos.mpr ( Finset.card_pos.mpr ( hΩ p ( Nat.prime_of_mem_primeFactors hp ) ) )

/-
**Tuple count universal bound.** `M_γ(H) ≤ (H+1)^k` since the
counting set is a subset of all tuples in `[0, H]^{k+1}`.
-/
lemma countTuplesWithGammaProd_le_pow (k γ H : ℕ) :
    (countTuplesWithGammaProd k γ H : ℝ) ≤ ((H : ℝ) + 1) ^ k := by
  norm_cast;
  refine' le_trans ( Set.ncard_le_ncard <| show { h : Fin ( k + 1 ) → ℤ | h 0 = 0 ∧ ( ∀ i j : Fin ( k + 1 ), ¬i = j → ¬h i = h j ) ∧ ( ∀ i : Fin ( k + 1 ), 0 ≤ h i ∧ h i ≤ H ) ∧ ∃ Γ : GammaStructure ( k + 1 ), Γ.gammaProd = γ ∧ ∀ i j : Fin ( k + 1 ), ¬i = j → Γ.sqfreepart.gcd ( h j - h i |> Int.natAbs ) = Γ.gamma i j } ⊆ Set.image ( fun x : Fin k → ℤ => Fin.cons 0 x ) ( Set.Icc ( 0 : Fin k → ℤ ) ( fun _ => H ) ) from _ ) _;
  · intro h hh;
    use fun i => h i.succ;
    exact ⟨ ⟨ fun i => hh.2.2.1 _ |>.1, fun i => hh.2.2.1 _ |>.2 ⟩, by ext i; induction i using Fin.inductionOn <;> aesop ⟩;
  · rw [ Set.ncard_image_of_injective, Set.ncard_eq_toFinset_card' ] <;> norm_num [ Function.Injective ];
    erw [ Finset.card_map, Finset.card_pi ] ; norm_num

/-
**Pointwise bound on `perGammaDeviationWeight`.**
For each `γ`, the weight is at most `∏_T (k·p·(1−r_p) + weil_p)` since each prime
contributes either the collision factor `k·p·(1−r_p)` or `weil_p`, both bounded by
their sum (all summands nonnegative).
-/
lemma perGammaDeviationWeight_le_prod_add (ε : ℝ) (k : ℕ)
    (Ω : ∀ p : ℕ, Finset (ZMod p))
    (hΩle : ∀ p, p.Prime → (Ω p).card ≤ p)
    (T : Finset ℕ) (hT_prime : ∀ p ∈ T, Nat.Prime p) (γ : ℕ) :
    perGammaDeviationWeight ε k Ω T γ ≤
    ∏ p ∈ T, ((k : ℝ) * (p : ℝ) * (1 - (Ω p).card / (p : ℝ)) +
      (1 - (Ω p).card / (p : ℝ)) * (p : ℝ) ^ (-ε) * localMean k Ω p) := by
  rw [ ← Finset.prod_filter_mul_prod_filter_not T ( fun p => p ∣ radical γ ) ];
  refine' mul_le_mul _ _ _ _;
  · refine' Finset.prod_le_prod _ _;
    · exact fun p hp => mul_nonneg ( mul_nonneg ( Nat.cast_nonneg _ ) ( Nat.cast_nonneg _ ) ) ( sub_nonneg.2 <| div_le_one_of_le₀ ( mod_cast hΩle p <| hT_prime p <| Finset.filter_subset _ _ hp ) <| Nat.cast_nonneg _ );
    · intro p hp; refine' le_add_of_nonneg_right _; refine' mul_nonneg ( mul_nonneg _ _ ) _ <;> norm_num;
      · exact div_le_one_of_le₀ ( mod_cast hΩle p ( hT_prime p ( Finset.filter_subset _ _ hp ) ) ) ( Nat.cast_nonneg _ );
      · positivity;
      · exact localMean_nonneg k Ω p;
  · gcongr;
    · intro p hp; refine' mul_nonneg _ _;
      · exact mul_nonneg ( sub_nonneg.2 <| div_le_one_of_le₀ ( mod_cast hΩle p <| hT_prime p <| Finset.filter_subset _ _ hp ) <| Nat.cast_nonneg _ ) <| Real.rpow_nonneg ( Nat.cast_nonneg _ ) _;
      · refine' mul_nonneg _ _ <;> norm_num;
    · exact le_add_of_nonneg_left ( mul_nonneg ( mul_nonneg ( Nat.cast_nonneg _ ) ( Nat.cast_nonneg _ ) ) ( sub_nonneg.mpr ( div_le_one_of_le₀ ( mod_cast hΩle _ ( hT_prime _ ( Finset.mem_filter.mp ‹_› |>.1 ) ) ) ( Nat.cast_nonneg _ ) ) ) );
  · refine' Finset.prod_nonneg fun p hp => mul_nonneg ( mul_nonneg _ _ ) _;
    · exact sub_nonneg_of_le ( div_le_one_of_le₀ ( mod_cast hΩle p ( hT_prime p ( Finset.filter_subset _ _ hp ) ) ) ( Nat.cast_nonneg _ ) );
    · positivity;
    · apply_rules [ localMean_nonneg ];
  · refine' Finset.prod_nonneg fun p hp => add_nonneg _ _;
    · exact mul_nonneg ( mul_nonneg ( Nat.cast_nonneg _ ) ( Nat.cast_nonneg _ ) ) ( sub_nonneg.2 ( div_le_one_of_le₀ ( mod_cast hΩle p ( hT_prime p ( Finset.filter_subset _ _ hp ) ) ) ( Nat.cast_nonneg _ ) ) );
    · refine' mul_nonneg ( mul_nonneg _ _ ) _;
      · exact sub_nonneg_of_le ( div_le_one_of_le₀ ( mod_cast hΩle p ( hT_prime p ( Finset.filter_subset _ _ hp ) ) ) ( Nat.cast_nonneg _ ) );
      · positivity;
      · apply localMean_nonneg

/-- **Prefactor absorption identity.**
The `q`-dependent prefactor `(q^{k-1}/|Ω_q|^k) ∏_{q \ T} μ_p`
simplifies algebraically to exactly `∏_{p ∈ T} μ_p⁻¹`. -/
lemma prefactor_absorption (k : ℕ) (hk : 2 ≤ k) (Ω : ∀ p : ℕ, Finset (ZMod p))
    (q : ℕ) [NeZero q] (hq : Squarefree q)
    (hΩ : ∀ p, p.Prime → (Ω p).Nonempty)
    (T : Finset ℕ) (hT : T ⊆ q.primeFactors) :
    ((q : ℝ) ^ (k - 1) / ((crtSubset q Ω).card : ℝ) ^ k) *
    (∏ p ∈ q.primeFactors \ T, localMean k Ω p) =
    ∏ p ∈ T, (localMean k Ω p)⁻¹ := by
  have hlm_pos : ∀ p ∈ q.primeFactors, 0 < localMean k Ω p := by
    intro p hp; unfold localMean
    exact div_pos (pow_pos (Nat.cast_pos.mpr (Finset.Nonempty.card_pos (hΩ p (Nat.prime_of_mem_primeFactors hp)))) _)
      (pow_pos (Nat.cast_pos.mpr (Nat.pos_of_mem_primeFactors hp)) _)
  have hgm := globalMean_eq_prod_localMean k q hq Ω
  have h_inv : (q : ℝ) ^ (k - 1) / ((crtSubset q Ω).card : ℝ) ^ k =
    (∏ p ∈ q.primeFactors, localMean k Ω p)⁻¹ := by
    rw [← hgm, inv_div]
  rw [h_inv]
  have h_split := (Finset.prod_sdiff hT (f := fun p => localMean k Ω p)).symm
  rw [h_split, mul_inv_rev, mul_assoc,
    inv_mul_cancel₀ (ne_of_gt (Finset.prod_pos (fun p hp => hlm_pos p (Finset.sdiff_subset hp)))),
    mul_one, Finset.prod_inv_distrib]

/-
**Weight as radical times Euler tail.** For `γ` whose prime factors lie in `T`,
the per-gamma weight factorises as `(rad γ) · ∏_{p ∈ T \ pf γ} weil_p`, where
`weil_p = (1 - |Ω_p|/p) · p^{-ε} · μ_p`.  The collision primes (`p ∣ rad γ`) are
exactly `γ.primeFactors` (as `γ.primeFactors ⊆ T`), contributing `∏_{p ∈ pf γ} p = rad γ`.
-/
lemma perGammaDeviationWeight_eq_of_subset (ε : ℝ) (k : ℕ)
    (Ω : ∀ p : ℕ, Finset (ZMod p))
    (T : Finset ℕ) (hT_prime : ∀ p ∈ T, Nat.Prime p) (γ : ℕ)
    (hγ : γ.primeFactors ⊆ T) :
    perGammaDeviationWeight ε k Ω T γ =
    (∏ p ∈ γ.primeFactors, (k : ℝ) * (p : ℝ) * (1 - (Ω p).card / (p : ℝ))) *
      ∏ p ∈ T \ γ.primeFactors,
        (1 - (Ω p).card / (p : ℝ)) * (p : ℝ) ^ (-ε) * localMean k Ω p := by
  by_cases hγ_zero : γ = 0 <;> simp_all +decide [ perGammaDeviationWeight ];
  · simp +decide [ radical, Finset.prod_filter ];
    split_ifs <;> simp_all +decide [ Finset.prod_ite, Finset.filter_ne' ];
    exact absurd ( hT_prime 1 ‹_› ) ( by norm_num );
  · congr! 1;
    · refine' Finset.prod_subset _ _ <;> simp_all +decide [ Finset.subset_iff ];
      · exact fun p hp hp' => dvd_trans hp' ( Nat.prod_primeFactors_dvd _ );
      · exact fun p pp dp dp' => False.elim <| dp' <| Nat.dvd_trans ( dvd_refl p ) <| Finset.dvd_prod_of_mem _ <| Nat.mem_primeFactors.mpr ⟨ pp, dp, hγ_zero ⟩;
    · congr! 1;
      ext p; simp [radical];
      intro hp; simp_all +decide [ Nat.Prime.dvd_iff_not_coprime, Nat.coprime_prod_right_iff, Nat.coprime_primes ] ;

/-- **Collision factor radical bound.** For `γ` with `γ.primeFactors ⊆ T`, the
per-gamma weight is bounded by `k^{ω(γ)} · (radical γ) · ∏_{T \ pf γ} weil_p`,
obtained from `perGammaDeviationWeight_eq_of_subset` by bounding each collision
factor `k·p·(1−r_p) ≤ k·p` (i.e. `∏_{pf γ}(1−r_p) ≤ 1`). -/
lemma perGammaDeviationWeight_le_radical_form (ε : ℝ) (k : ℕ)
    (Ω : ∀ p : ℕ, Finset (ZMod p))
    (hΩle : ∀ p, p.Prime → (Ω p).card ≤ p)
    (T : Finset ℕ) (hT_prime : ∀ p ∈ T, Nat.Prime p) (γ : ℕ)
    (hγ : γ.primeFactors ⊆ T) :
    perGammaDeviationWeight ε k Ω T γ ≤
    (k : ℝ) ^ γ.primeFactors.card * (radical γ : ℝ) *
      ∏ p ∈ T \ γ.primeFactors,
        (1 - (Ω p).card / (p : ℝ)) * (p : ℝ) ^ (-ε) * localMean k Ω p := by
  rw [perGammaDeviationWeight_eq_of_subset ε k Ω T hT_prime γ hγ]
  refine mul_le_mul_of_nonneg_right ?_ ?_
  · -- ∏ (k*p*(1-r_p)) = k^ω * radical γ * ∏(1-r_p) ≤ k^ω * radical γ
    have hcol : (∏ p ∈ γ.primeFactors, (k : ℝ) * (p : ℝ) * (1 - (Ω p).card / (p : ℝ)))
        = (k : ℝ) ^ γ.primeFactors.card * (radical γ : ℝ) *
          ∏ p ∈ γ.primeFactors, (1 - (Ω p).card / (p : ℝ)) := by
      rw [show (radical γ : ℝ) = ∏ p ∈ γ.primeFactors, (p : ℝ) by
            unfold radical; rw [Nat.cast_prod]]
      rw [Finset.prod_mul_distrib, Finset.prod_mul_distrib, Finset.prod_const]
    rw [hcol]
    refine mul_le_of_le_one_right (by positivity) ?_
    refine Finset.prod_le_one (fun p hp => ?_) (fun p hp => ?_)
    · exact sub_nonneg.2 (div_le_one_of_le₀ (mod_cast hΩle p (Nat.prime_of_mem_primeFactors hp))
        (Nat.cast_nonneg _))
    · exact sub_le_self _ (div_nonneg (Nat.cast_nonneg _) (Nat.cast_nonneg _))
  · exact Finset.prod_nonneg fun p hp => mul_nonneg (mul_nonneg
      (sub_nonneg.2 (div_le_one_of_le₀ (mod_cast hΩle p (hT_prime p (Finset.mem_sdiff.mp hp).1))
        (Nat.cast_nonneg _))) (Real.rpow_nonneg (Nat.cast_nonneg _) _)) (localMean_nonneg k Ω p)

/-- Numeric per-prime constant bound used in `gamma_sum_le_euler_factor_small_gamma`:
`2·(2^{C(k,2)}·k) + w ≤ 2^{k+C(k,2)}·(1+w)` for `k ≥ 2`, `w ≥ 0`.  The key fact is
`2·k ≤ 2^k` for `k ≥ 2`, which lets `k·2^{C(k,2)+1} ≤ 2^{k+C(k,2)}`. -/
lemma small_gamma_perprime_const (k : ℕ) (hk : 2 ≤ k) (w : ℝ) (hw : 0 ≤ w) :
    2 * ((2 : ℝ) ^ (Nat.choose k 2) * k) + w ≤
      (2 : ℝ) ^ (k + Nat.choose k 2) * (1 + w) := by
  have h2k : 2 * k ≤ 2 ^ k := by
    induction k with
    | zero => omega
    | succ n ih =>
      rcases Nat.lt_or_ge n 2 with hn | hn
      · interval_cases n <;> simp_all
      · have := ih (by omega)
        simp only [pow_succ]
        omega
  have h2kR : (2 : ℝ) * k ≤ 2 ^ k := by exact_mod_cast h2k
  have hpow : (2 : ℝ) ^ (k + Nat.choose k 2) = 2 ^ k * 2 ^ (Nat.choose k 2) := by
    rw [pow_add]
  have hCpos : (0 : ℝ) < 2 ^ (Nat.choose k 2) := by positivity
  have hkey : 2 * ((2 : ℝ) ^ (Nat.choose k 2) * k) ≤ 2 ^ (k + Nat.choose k 2) := by
    rw [hpow]; nlinarith [hCpos, h2kR]
  have hone : (1 : ℝ) ≤ 2 ^ (k + Nat.choose k 2) := one_le_pow₀ (by norm_num)
  nlinarith [hkey, hone, hw]

/-
**Full-range γ-sum bound with the vanishing collision weight (crude-count route).**
Over the full GK γ-window `Icc 1 (H^{k*k})`, the deviation γ-sum is bounded by feeding the
*crude* tuple count `M_γ(H) ≤ (H+1)^{k-1}` through `insert_gamma_denominator` (to extract a
genuine `1/γ^α` saving) and the per-prime fractional Euler engine
`core_gamma_euler_sum_frac_perprime` with the vanishing collision multiplier
`c_p = k·(1 − r_p)`.  Each resulting Euler factor therefore carries the `(1 − r_p)` factor.
-/
lemma gamma_sum_frac_le (ε : ℝ) (hε : 0 < ε) (k : ℕ) (hk : 2 ≤ k)
    (Ω : ∀ p : ℕ, Finset (ZMod p)) (hΩle : ∀ p, p.Prime → (Ω p).card ≤ p)
    (T : Finset ℕ) (hT_prime : ∀ p ∈ T, Nat.Prime p) (H : ℕ) (hH : 1 < H)
    (α : ℝ) (hα0 : 0 < α) (hα1 : α ≤ 1) :
    ∑ γ ∈ (Finset.Icc 1 (H ^ (k * k))).filter (fun γ => γ.primeFactors ⊆ T),
      perGammaDeviationWeight ε k Ω T γ * (countTuplesWithGammaProd (k - 1) γ H : ℝ) ≤
    ((H : ℝ) + 1) ^ (((k - 1 : ℕ) : ℝ) + α * (k * k)) *
      ∏ p ∈ T, ((1 / (1 - (2:ℝ) ^ (-α))) * ((k : ℝ) * (1 - (Ω p).card / (p : ℝ))) *
          (p : ℝ) ^ (1 - α) +
        (1 - (Ω p).card / (p : ℝ)) * (p : ℝ) ^ (-ε) * localMean k Ω p) := by
  refine' le_trans ( Finset.sum_le_sum fun γ hγ => _ ) _;
  use fun γ => ( perGammaDeviationWeight ε k Ω T γ / ( γ : ℝ ) ^ α ) * ( H + 1 ) ^ ( ( k - 1 : ℕ ) + α * ( k * k ) );
  · rw [ div_mul_eq_mul_div, le_div_iff₀ ];
    · rw [ mul_assoc ];
      gcongr;
      · apply_rules [ mul_nonneg, Finset.prod_nonneg ];
        · exact fun p hp => mul_nonneg ( mul_nonneg ( Nat.cast_nonneg _ ) ( Nat.cast_nonneg _ ) ) ( sub_nonneg.2 <| div_le_one_of_le₀ ( mod_cast hΩle p <| hT_prime p <| Finset.mem_filter.mp hp |>.1 ) <| Nat.cast_nonneg _ );
        · intro p hp; refine' mul_nonneg ( mul_nonneg _ _ ) _ <;> norm_num;
          · exact div_le_one_of_le₀ ( mod_cast hΩle p ( hT_prime p ( Finset.mem_filter.mp hp |>.1 ) ) ) ( Nat.cast_nonneg _ );
          · positivity;
          · exact div_nonneg ( pow_nonneg ( Nat.cast_nonneg _ ) _ ) ( pow_nonneg ( Nat.cast_nonneg _ ) _ );
      · refine' le_trans ( mul_le_mul_of_nonneg_right ( countTuplesWithGammaProd_le_pow _ _ _ ) ( by positivity ) ) _;
        rw [ Real.rpow_add ( by positivity ), Real.rpow_mul ( by positivity ) ] ; norm_cast ; ring_nf ; norm_num;
        gcongr;
        rw [ ← Real.rpow_natCast, ← Real.rpow_mul ( by positivity ), mul_comm, Real.rpow_mul ( by positivity ), Real.rpow_natCast ];
        gcongr;
        exact le_trans ( Nat.cast_le.mpr <| Finset.mem_Icc.mp ( Finset.mem_filter.mp hγ |>.1 ) |>.2 ) <| by norm_cast; rw [ pow_two ] ; exact Nat.pow_le_pow_left ( by linarith ) _ |> le_trans <| Nat.pow_le_pow_right ( by linarith ) <| by nlinarith;
    · exact Real.rpow_pos_of_pos ( Nat.cast_pos.mpr ( Finset.mem_Icc.mp ( Finset.mem_filter.mp hγ |>.1 ) |>.1 ) ) _;
  · rw [ ← Finset.sum_mul _ _ _ ];
    rw [ mul_comm ];
    gcongr;
    convert core_gamma_euler_sum_frac_perprime T hT_prime ( H ^ ( k * k ) ) α hα0 hα1 ( fun p => k * ( 1 - ( Ω p |> Finset.card : ℝ ) / p ) ) ( fun p hp => ?_ ) ( fun p => ( 1 - ( Ω p |> Finset.card : ℝ ) / p ) * p ^ ( -ε ) * localMean k Ω p ) ( fun p hp => ?_ ) using 1;
    · refine' Finset.sum_congr rfl fun x hx => _;
      rw [ perGammaDeviationWeight_eq_of_subset ];
      · unfold radical; norm_num [ Finset.prod_mul_distrib, mul_assoc, mul_comm, mul_left_comm ] ;
        ring;
      · assumption;
      · grind;
    · exact mul_nonneg ( Nat.cast_nonneg _ ) ( sub_nonneg.2 <| div_le_one_of_le₀ ( mod_cast hΩle p <| hT_prime p hp ) <| Nat.cast_nonneg _ );
    · refine' mul_nonneg ( mul_nonneg _ _ ) _ <;> norm_num;
      · exact div_le_one_of_le₀ ( mod_cast hΩle p ( hT_prime p hp ) ) ( Nat.cast_nonneg _ );
      · positivity;
      · exact div_nonneg ( pow_nonneg ( Nat.cast_nonneg _ ) _ ) ( pow_nonneg ( Nat.cast_nonneg _ ) _ )

/-
**Per-band crude-count fractional γ-sum engine (Step 8.1).**

This is the band-localized generalization of `gamma_sum_frac_le`: instead of
inserting the denominator over the *full* range `γ ≤ H^{k·k}` (insertion cost
`(H+1)^{α·k²}`), it bounds the γ-sum restricted to the band `γ ≤ H^W` with a
*band-tailored* insertion cost `(H+1)^{(k-1)+α·W}`.  The crude tuple count
`M_γ(H) ≤ (H+1)^{k-1}` is multiplied by `1 ≤ (H^W/γ)^α` (`insert_gamma_denominator`)
to extract the genuine `1/γ^α` decay, which is then fed — together with the
vanishing collision multiplier `c_p = k·(1 − r_p)` — into the per-prime fractional
Euler engine `core_gamma_euler_sum_frac_perprime`.  Each resulting Euler factor
therefore carries the `(1 − r_p)` factor and the `p^{1-α}` collision weight.
-/
lemma gamma_sum_frac_le_upper (ε : ℝ) (hε : 0 < ε) (k : ℕ) (hk : 2 ≤ k)
    (Ω : ∀ p : ℕ, Finset (ZMod p)) (hΩle : ∀ p, p.Prime → (Ω p).card ≤ p)
    (T : Finset ℕ) (hT_prime : ∀ p ∈ T, Nat.Prime p) (H : ℕ) (hH : 1 < H)
    (α : ℝ) (hα0 : 0 < α) (hα1 : α ≤ 1) (W : ℝ) (hW : 0 ≤ W) :
    ∑ γ ∈ (Finset.Icc 1 (H ^ (k * k))).filter
        (fun γ : ℕ => γ.primeFactors ⊆ T ∧ (γ : ℝ) ≤ (H : ℝ) ^ W),
      perGammaDeviationWeight ε k Ω T γ * (countTuplesWithGammaProd (k - 1) γ H : ℝ) ≤
    ((H : ℝ) + 1) ^ (((k - 1 : ℕ) : ℝ) + α * W) *
      ∏ p ∈ T, ((1 / (1 - (2:ℝ) ^ (-α))) * ((k : ℝ) * (1 - (Ω p).card / (p : ℝ))) *
          (p : ℝ) ^ (1 - α) +
        (1 - (Ω p).card / (p : ℝ)) * (p : ℝ) ^ (-ε) * localMean k Ω p) := by
  refine' le_trans ( Finset.sum_le_sum fun x hx => _ ) _;
  use fun x => ( perGammaDeviationWeight ε k Ω T x / ( x : ℝ ) ^ α ) * ( H + 1 ) ^ ( ( k - 1 : ℕ ) + α * W );
  · rw [ div_mul_eq_mul_div, le_div_iff₀ ];
    · rw [ mul_assoc ];
      gcongr;
      · apply_rules [ mul_nonneg, Finset.prod_nonneg ];
        · exact fun p hp => mul_nonneg ( mul_nonneg ( Nat.cast_nonneg _ ) ( Nat.cast_nonneg _ ) ) ( sub_nonneg.2 <| div_le_one_of_le₀ ( mod_cast hΩle p <| hT_prime p <| Finset.filter_subset _ _ hp ) <| Nat.cast_nonneg _ );
        · intro p hp; refine' mul_nonneg ( mul_nonneg _ _ ) _ <;> norm_num;
          · exact div_le_one_of_le₀ ( mod_cast hΩle p ( hT_prime p ( Finset.mem_filter.mp hp |>.1 ) ) ) ( Nat.cast_nonneg _ );
          · positivity;
          · refine' mul_nonneg _ _ <;> norm_num;
      · refine' le_trans ( mul_le_mul_of_nonneg_right ( countTuplesWithGammaProd_le_pow _ _ _ ) ( by positivity ) ) _;
        rw [ Real.rpow_add ( by positivity ), Real.rpow_mul ( by positivity ) ];
        gcongr;
        · norm_cast;
        · rw [ ← Real.rpow_mul ( by positivity ), mul_comm, Real.rpow_mul ( by positivity ) ];
          gcongr;
          exact le_trans ( Finset.mem_filter.mp hx |>.2.2 ) ( Real.rpow_le_rpow ( by positivity ) ( by linarith ) ( by positivity ) );
    · exact Real.rpow_pos_of_pos ( Nat.cast_pos.mpr ( Finset.mem_Icc.mp ( Finset.mem_filter.mp hx |>.1 ) |>.1 ) ) _;
  · have := @core_gamma_euler_sum_frac_perprime;
    refine' le_trans _ ( mul_le_mul_of_nonneg_left ( this T hT_prime ( H ^ ( k * k ) ) α hα0 hα1 _ _ _ _ ) ( by positivity ) );
    · rw [ Finset.mul_sum _ _ _ ];
      refine' le_trans ( Finset.sum_le_sum_of_subset_of_nonneg _ _ ) _;
      exact Finset.Icc 1 ( H ^ ( k * k ) ) |> Finset.filter fun γ => γ.primeFactors ⊆ T;
      · exact fun x hx => Finset.mem_filter.mpr ⟨ Finset.mem_filter.mp hx |>.1, Finset.mem_filter.mp hx |>.2.1 ⟩;
      · intro γ hγ₁ hγ₂; exact mul_nonneg ( div_nonneg ( by
          apply_rules [ mul_nonneg, Finset.prod_nonneg ];
          · exact fun p hp => mul_nonneg ( mul_nonneg ( Nat.cast_nonneg _ ) ( Nat.cast_nonneg _ ) ) ( sub_nonneg.2 <| div_le_one_of_le₀ ( mod_cast hΩle p <| hT_prime p <| Finset.mem_filter.mp hp |>.1 ) <| Nat.cast_nonneg _ );
          · intro p hp; apply_rules [ mul_nonneg, Finset.prod_nonneg ];
            · exact sub_nonneg_of_le ( div_le_one_of_le₀ ( mod_cast hΩle p ( hT_prime p ( Finset.mem_filter.mp hp |>.1 ) ) ) ( Nat.cast_nonneg _ ) );
            · positivity;
            · positivity;
            · positivity ) ( by positivity ) ) ( by positivity ) ;
      · refine' Finset.sum_le_sum fun x hx => _;
        rw [ perGammaDeviationWeight_eq_of_subset ];
        · unfold radical; simp +decide [ Finset.prod_mul_distrib, mul_assoc, mul_comm, mul_left_comm, div_eq_mul_inv ] ;
        · assumption;
        · grind;
    · exact fun p hp => mul_nonneg ( Nat.cast_nonneg _ ) ( sub_nonneg.2 <| div_le_one_of_le₀ ( mod_cast hΩle p <| hT_prime p hp ) <| Nat.cast_nonneg _ );
    · intro p hp; apply_rules [ mul_nonneg, sub_nonneg.2, div_le_one_of_le₀, hΩle p ( hT_prime p hp ) ] ;
      · exact_mod_cast hΩle p ( hT_prime p hp );
      · positivity;
      · positivity;
      · positivity;
      · positivity

/-
**Sharp-count fractional γ-sum engine (Step 8, GK §4 genuine route).**

Unlike the crude-count engines (`gamma_sum_frac_le`, `gamma_sum_frac_le_upper`),
which pay a `γ`-range-dependent insertion cost `(H+1)^{α·W}`, this engine feeds the
*sharp* tuple count `M_γ(H) ≤ C^{ω(γ)}·2^{k-1}·H^{(k-1)+1/2}/γ^α`
(`countTuplesWithGammaProd_large_gamma_sharp`) into the per-prime fractional Euler
engine.  The `1/γ^α` saving is *intrinsic* to the count, so the only insertion is
the band-independent `H^{1/2}`, and the H-power is `(k-1)+1/2`.  The collision
constant `C = 2^{C(k,2)}` from the count is folded into the per-prime collision
multiplier `c_p = 2^{C(k,2)}·k·(1−r_p)`, which still carries the vanishing factor
`(1−r_p)`.  The covering hypothesis `k² ≤ 2/α²` ensures the sharp count is valid on
the whole window `γ ≤ H^{k²}` (for a single `α`; for `α = alphaOf (k-1) τ` one
instead bands the window, cf. `alphaOf_band_ok`).
-/
lemma gamma_sum_sharp_le (ε : ℝ) (hε : 0 < ε) (k : ℕ) (hk : 2 ≤ k)
    (Ω : ∀ p : ℕ, Finset (ZMod p)) (hΩle : ∀ p, p.Prime → (Ω p).card ≤ p)
    (T : Finset ℕ) (hT_prime : ∀ p ∈ T, Nat.Prime p) (H : ℕ) (hH : 1 < H)
    (α : ℝ) (hα0 : 0 < α) (hα1 : α ≤ 1)
    (hcover : ((k * k : ℕ) : ℝ) ≤ 2 / α ^ 2) :
    ∑ γ ∈ (Finset.Icc 1 (H ^ (k * k))).filter (fun γ : ℕ => γ.primeFactors ⊆ T),
      perGammaDeviationWeight ε k Ω T γ * (countTuplesWithGammaProd (k - 1) γ H : ℝ) ≤
    (2 : ℝ) ^ (k - 1) * ((H : ℝ) + 1) ^ (((k - 1 : ℕ) : ℝ) + 1 / 2) *
      ∏ p ∈ T, ((1 / (1 - (2:ℝ) ^ (-α))) *
          ((2 : ℝ) ^ (Nat.choose k 2) * ((k : ℝ) * (1 - (Ω p).card / (p : ℝ)))) *
          (p : ℝ) ^ (1 - α) +
        (1 - (Ω p).card / (p : ℝ)) * (p : ℝ) ^ (-ε) * localMean k Ω p) := by
  refine' le_trans _ ( mul_le_mul_of_nonneg_left ( core_gamma_euler_sum_frac_perprime T hT_prime ( H ^ ( k * k ) ) α hα0 hα1 ( fun p => 2 ^ Nat.choose k 2 * ( k * ( 1 - ( Ω p |> Finset.card ) / p : ℝ ) ) ) _ ( fun p => ( 1 - ( Ω p |> Finset.card ) / p : ℝ ) * ( p : ℝ ) ^ ( -ε ) * localMean k Ω p ) _ ) ( by positivity ) );
  · rw [ Finset.mul_sum _ _ _ ];
    refine' Finset.sum_le_sum fun γ hγ => _;
    have h_bound : (countTuplesWithGammaProd (k - 1) γ H : ℝ) ≤ (2 ^ (Nat.choose k 2)) ^ γ.primeFactors.card * 2 ^ (k - 1) * (H + 1) ^ ((k - 1 : ℕ) + 1 / 2 : ℝ) / (γ : ℝ) ^ α := by
      have h_gamma_bound : (γ : ℝ) ≤ (H : ℝ) ^ (2 / α ^ 2) := by
        refine' le_trans _ ( Real.rpow_le_rpow_of_exponent_le ( mod_cast hH.le ) hcover );
        exact_mod_cast Finset.mem_Icc.mp ( Finset.mem_filter.mp hγ |>.1 ) |>.2;
      have := countTuplesWithGammaProd_large_gamma_sharp ( k - 1 ) γ H α;
      refine le_trans ( this ( Finset.mem_Icc.mp ( Finset.mem_filter.mp hγ |>.1 ) |>.1 ) hH hα0 h_gamma_bound ) ?_;
      gcongr <;> norm_num;
      linarith;
    convert mul_le_mul_of_nonneg_left h_bound ( show 0 ≤ perGammaDeviationWeight ε k Ω T γ from ?_ ) using 1;
    · rw [ perGammaDeviationWeight_eq_of_subset ];
      · norm_num [ Finset.prod_mul_distrib, Finset.prod_pow_eq_pow_sum, radical ] ; ring;
      · assumption;
      · grind;
    · apply_rules [ mul_nonneg, Finset.prod_nonneg ];
      · exact fun p hp => mul_nonneg ( mul_nonneg ( Nat.cast_nonneg _ ) ( Nat.cast_nonneg _ ) ) ( sub_nonneg.2 <| div_le_one_of_le₀ ( mod_cast hΩle p <| hT_prime p <| Finset.mem_filter.mp hp |>.1 ) <| Nat.cast_nonneg _ );
      · intro p hp; refine' mul_nonneg ( mul_nonneg _ _ ) _ <;> norm_num;
        · exact div_le_one_of_le₀ ( mod_cast hΩle p ( hT_prime p ( Finset.mem_filter.mp hp |>.1 ) ) ) ( Nat.cast_nonneg _ );
        · positivity;
        · refine' mul_nonneg _ _ <;> norm_num;
  · exact fun p hp => mul_nonneg ( pow_nonneg zero_le_two _ ) ( mul_nonneg ( Nat.cast_nonneg _ ) ( sub_nonneg.2 ( div_le_one_of_le₀ ( mod_cast hΩle p ( hT_prime p hp ) ) ( Nat.cast_nonneg _ ) ) ) );
  · intro p hp; refine' mul_nonneg ( mul_nonneg _ _ ) _ <;> norm_num;
    · exact div_le_one_of_le₀ ( mod_cast hΩle p ( hT_prime p hp ) ) ( Nat.cast_nonneg _ );
    · positivity;
    · refine' mul_nonneg _ _ <;> norm_num

/- RETIRED (large-divisor re-architecture): `gamma_sum_le_euler_factor_small_gamma`.
Its fixed RHS constant `2^(k+C(k,2))` no longer dominates the vanishing collision
weight `k·p·(1 − r_p)` for small `|T|`; the small-gamma reassembly it fed is itself
retired (see below).  Commented out rather than deleted. -/
/-
/-
**Gamma-sum Euler bound (Small-γ regime).**

Following Proposition 4.3 of Granville-Kurlberg, the summation over $\gamma \le H$
is bounded by the $H^{k-1}/\gamma$ tuple count bound. The proof combines the
small-$\gamma$ tuple count `countTuplesWithGammaProd_small_gamma` with the
radical-regrouping Euler-product engine `core_gamma_euler_sum` (the analytic core,
proved in `GammaEulerSumHelpers.lean`).
-/
private lemma gamma_sum_le_euler_factor_small_gamma (ε : ℝ) (hε : 0 < ε) (k : ℕ) (hk : 2 ≤ k)
    (Ω : ∀ p : ℕ, Finset (ZMod p))
    (hΩle : ∀ p, p.Prime → (Ω p).card ≤ p)
    (T : Finset ℕ) (hT_prime : ∀ p ∈ T, Nat.Prime p) (H : ℕ) :
    ∑ γ ∈ (Finset.Icc 1 H).filter (fun γ => γ.primeFactors ⊆ T),
      perGammaDeviationWeight ε k Ω T γ *
        (countTuplesWithGammaProd (k - 1) γ H : ℝ) ≤
    ((H : ℝ) + 1) ^ (k - 1) *
      ∏ p ∈ T, ((2 : ℝ) ^ (k + Nat.choose k 2) *
        ((1 : ℝ) + (1 - (Ω p).card / (p : ℝ)) * (p : ℝ) ^ (-ε) *
          localMean k Ω p)) := by
  by_cases hT : T.Nonempty
  · have h_bound : ∀ γ ∈ (Finset.Icc 1 H).filter (fun γ => γ.primeFactors ⊆ T),
        perGammaDeviationWeight ε k Ω T γ * (countTuplesWithGammaProd (k - 1) γ H : ℝ) ≤
        (2 ^ (k - 1) : ℝ) * (H : ℝ) ^ (k - 1) * (radical γ / γ) *
          (2 ^ (Nat.choose k 2) * k) ^ γ.primeFactors.card *
          (∏ p ∈ T \ γ.primeFactors,
            (1 - (Ω p).card / (p : ℝ)) * (p : ℝ) ^ (-ε) * localMean k Ω p) := by
      intros γ hγ
      have hγ1 : 1 ≤ γ := (Finset.mem_Icc.mp (Finset.mem_filter.mp hγ).1).1
      have hγH : γ ≤ H := (Finset.mem_Icc.mp (Finset.mem_filter.mp hγ).1).2
      have h_count : (countTuplesWithGammaProd (k - 1) γ H : ℝ) ≤
          (2 ^ (Nat.choose k 2)) ^ γ.primeFactors.card * 2 ^ (k - 1) * (H : ℝ) ^ (k - 1) / γ := by
        have := @countTuplesWithGammaProd_small_gamma
        convert this γ H hγ1 (by omega) hγH using 1 ; cases k <;> aesop
      convert mul_le_mul (perGammaDeviationWeight_le_radical_form ε k Ω hΩle T hT_prime γ
        (Finset.mem_filter.mp hγ).2) h_count ?_ ?_ using 1
      · ring
      · positivity
      · refine mul_nonneg (mul_nonneg (pow_nonneg (Nat.cast_nonneg _) _) (Nat.cast_nonneg _))
          (Finset.prod_nonneg fun p hp => mul_nonneg (mul_nonneg (sub_nonneg.2 ?_)
            (Real.rpow_nonneg (Nat.cast_nonneg _) _)) ?_)
        · exact div_le_one_of_le₀ (mod_cast hΩle p (hT_prime p (Finset.mem_sdiff.mp hp).1))
            (Nat.cast_nonneg _)
        · exact localMean_nonneg k Ω p
    have h_sum_bound : ∑ γ ∈ (Finset.Icc 1 H).filter (fun γ => γ.primeFactors ⊆ T),
        (radical γ / γ) * (2 ^ (Nat.choose k 2) * k) ^ γ.primeFactors.card *
          (∏ p ∈ T \ γ.primeFactors,
            (1 - (Ω p).card / (p : ℝ)) * (p : ℝ) ^ (-ε) * localMean k Ω p) ≤
        ∏ p ∈ T, (2 * (2 ^ (Nat.choose k 2) * k) +
          (1 - (Ω p).card / (p : ℝ)) * (p : ℝ) ^ (-ε) * localMean k Ω p) := by
      apply core_gamma_euler_sum T hT_prime H (2 ^ (Nat.choose k 2) * k)
        (one_le_mul_of_one_le_of_one_le (one_le_pow₀ (by norm_num)) (by norm_cast; linarith))
        (fun p => (1 - (Ω p).card / (p : ℝ)) * (p : ℝ) ^ (-ε) * localMean k Ω p) (fun p hp => ?_)
      exact mul_nonneg (mul_nonneg (sub_nonneg.2 <| div_le_one_of_le₀
        (mod_cast hΩle p <| hT_prime p hp) <| Nat.cast_nonneg _) <|
          Real.rpow_nonneg (Nat.cast_nonneg _) _) (localMean_nonneg k Ω p)
    refine le_trans (Finset.sum_le_sum h_bound) ?_
    refine le_trans ?_ (mul_le_mul_of_nonneg_left (Finset.prod_le_prod ?_
      (fun p hp => show (2 * (2 ^ k.choose 2 * k) +
          (1 - (Ω p |> Finset.card : ℝ) / p) * p ^ (-ε) * localMean k Ω p) ≤
        2 ^ (k + k.choose 2) * (1 + (1 - (Ω p |> Finset.card : ℝ) / p) * p ^ (-ε) *
          localMean k Ω p) from ?_)) (by positivity))
    · refine le_trans ?_ (mul_le_mul_of_nonneg_left h_sum_bound (by positivity))
      rw [Finset.mul_sum _ _ _]
      refine Finset.sum_le_sum fun x hx => ?_
      rw [mul_assoc, mul_assoc, mul_assoc, ← mul_assoc, ← mul_assoc, ← mul_assoc, ← mul_assoc,
        mul_assoc, mul_assoc, mul_assoc, mul_assoc, ← mul_assoc]
      gcongr
      · refine mul_nonneg (div_nonneg (Nat.cast_nonneg _) (Nat.cast_nonneg _))
          (mul_nonneg (pow_nonneg (by positivity) _) (Finset.prod_nonneg fun p hp => ?_))
        refine mul_nonneg (mul_nonneg ?_ ?_) ?_
        · exact sub_nonneg_of_le (div_le_one_of_le₀
            (mod_cast hΩle p (hT_prime p (Finset.mem_sdiff.mp hp).1)) (Nat.cast_nonneg _))
        · positivity
        · exact div_nonneg (pow_nonneg (Nat.cast_nonneg _) _) (pow_nonneg (Nat.cast_nonneg _) _)
      · exact le_of_eq (mul_pow _ _ _).symm
    · intro p hp; refine add_nonneg ?_ ?_ <;> norm_num
      refine mul_nonneg (mul_nonneg ?_ ?_) ?_
      · exact sub_nonneg_of_le (div_le_one_of_le₀ (mod_cast hΩle p (hT_prime p hp))
          (Nat.cast_nonneg _))
      · positivity
      · exact div_nonneg (pow_nonneg (Nat.cast_nonneg _) _) (pow_nonneg (Nat.cast_nonneg _) _)
    · convert small_gamma_perprime_const k hk _ _ using 1
      exact mul_nonneg (mul_nonneg (sub_nonneg.2 <| div_le_one_of_le₀
        (mod_cast hΩle p <| hT_prime p hp) <| Nat.cast_nonneg _) <|
          Real.rpow_nonneg (Nat.cast_nonneg _) _) (localMean_nonneg k Ω p)
  · rcases k with (_ | _ | k) <;> simp_all +decide [perGammaDeviationWeight]
    rcases H with (_ | _ | H) <;> norm_num [Finset.sum_filter] at *
    · convert countTuplesWithGammaProd_le_pow (k + 1) 1 1 using 1 ; norm_num
    · rw [Finset.sum_eq_single 1] <;> norm_num
      · exact_mod_cast countTuplesWithGammaProd_le_pow _ _ _
      · aesop
-/
/- The sharp-count "band" engines (`gamma_band_euler_factor`,
`gamma_band_euler_factor_low`) used the large-gamma sharp tuple count
(`countTuplesWithGammaProd_large_gamma_sharp`).  The re-architecture of the
large-divisor regime (see `MobiusSynthesis.deviation_large_divisors`) abandons the
sharp-count band approach in favour of the crude counts plus the vanishing
collision weight, so these engines are retired here. -/

/-- The per-band exponent `α(n, τ)`, the *clamped* square-root choice
`min 1 (sqrt(2 / w(τ)))`, where `w(τ) = tupleBoundWeight n τ`.

**Faithfulness correction.**  The bare choice `sqrt(2 / w(τ))` (as originally
proposed) does *not* satisfy `α ≤ 1`: whenever `w(τ) < 2` (e.g. `n = 1`, `τ = 0`,
where `w = 1` and `sqrt 2 > 1`) it exceeds `1`.  Since the band engine
`gamma_band_euler_factor` simultaneously requires `α ≤ 1` *and* the band
constraint `w(τ) ≤ 2 / α²`, the genuine per-band choice must clamp at `1`.  The
clamp keeps the band constraint as an (almost) equality — exact when `w(τ) ≥ 2`
(so `sqrt(2/w) ≤ 1`), and `w(τ) < 2 ≤ 2/1²` otherwise. -/
noncomputable def alphaOf (n τ : ℕ) : ℝ := min 1 (Real.sqrt (2 / tupleBoundWeight n τ))

/-- The per-band exponent `alphaOf n τ` is positive (for `n ≥ 1`, which is the
relevant regime `n = k - 1` with `k ≥ 2`).  The hypothesis `1 ≤ n` is necessary:
`tupleBoundWeight 0 0 = 0`, forcing `alphaOf 0 0 = 0`. -/
lemma alphaOf_pos (n τ : ℕ) (hn : 1 ≤ n) : 0 < alphaOf n τ := by
  unfold alphaOf tupleBoundWeight
  apply lt_min
  · norm_num
  · apply Real.sqrt_pos.mpr
    have h1 : (1:ℝ) ≤ (n:ℝ) := by exact_mod_cast hn
    have hwpos : (0:ℝ) < (n:ℝ) + 1 - 9/8 + ((τ:ℝ) - 1/2)^2 / 2 := by
      nlinarith [sq_nonneg ((τ:ℝ) - 1/2)]
    exact _root_.div_pos (by norm_num) hwpos

/-- The per-band exponent `alphaOf n τ` is at most `1` (immediate from the clamp). -/
lemma alphaOf_le_one (n τ : ℕ) : alphaOf n τ ≤ 1 := by
  unfold alphaOf; exact min_le_left _ _

/-- The band constraint holds for `alphaOf n τ`: `w(τ) ≤ 2 / α(n,τ)²`, with equality
when `w(τ) ≥ 2` and the harmless slack `w(τ) < 2 ≤ 2/1²` otherwise. -/
lemma alphaOf_band_ok (n τ : ℕ) : tupleBoundWeight n τ ≤ 2 / (alphaOf n τ) ^ 2 := by
  unfold alphaOf
  set w := tupleBoundWeight n τ with hw
  have hnn : 0 ≤ w := by
    rw [hw]; unfold tupleBoundWeight
    have h : (1:ℝ)/4 ≤ ((τ:ℝ) - 1/2)^2 := by
      have h : (0:ℝ) ≤ (τ:ℝ) * ((τ:ℝ) - 1) := by
        rcases Nat.eq_zero_or_pos τ with h | h
        · simp [h]
        · have h1 : (1:ℝ) ≤ (τ:ℝ) := by exact_mod_cast h
          nlinarith [Nat.cast_nonneg (α := ℝ) τ]
      nlinarith
    have hn : (0:ℝ) ≤ (n:ℝ) := by positivity
    linarith
  rcases eq_or_lt_of_le hnn with h0 | hpos
  · rw [← h0]; simp
  · have hs : Real.sqrt (2 / w) ^ 2 = 2 / w := Real.sq_sqrt (by positivity)
    rcases le_total (Real.sqrt (2 / w)) 1 with hle | hge
    · rw [min_eq_right hle, hs, div_div_eq_mul_div]; linarith
    · rw [min_eq_left hge]
      simp only [one_pow, div_one]
      have h2 : (1:ℝ) ≤ 2 / w := by nlinarith [hs, hge, Real.sqrt_nonneg (2/w)]
      rw [le_div_iff₀ hpos] at h2
      linarith


/-- Per-prime simplification: `localMean k Ω p / |Ω_p| = (|Ω_p|/p)^{k-1}` (needs `k ≥ 1`
and `|Ω_p| ≠ 0`). -/
lemma localMean_mul_inv_card (k : ℕ) (hk : 1 ≤ k) (Ω : ∀ p : ℕ, Finset (ZMod p)) (p : ℕ)
    (hp : ((Ω p).card : ℝ) ≠ 0) :
    (localMean k Ω p : ℝ) * (1 / ((Ω p).card : ℝ)) = ((Ω p).card / (p : ℝ)) ^ (k - 1) := by
  unfold localMean
  have hpow : ((Ω p).card : ℝ) ^ k = ((Ω p).card : ℝ) ^ (k - 1) * ((Ω p).card : ℝ) := by
    rw [← pow_succ, Nat.sub_add_cancel hk]
  rw [hpow, div_pow]
  field_simp

/-! ## 6. Regime-splitting architecture for Granville–Kurlberg Proposition 4.2

The uniform Rankin trick used in the (now retired) §3.2 sketch applies the same
weight to the whole collision constraint `∏_{p ∈ T} p > s`, which makes the
resulting series over `γ` diverge.  Following **Proposition 4.2** of
Granville–Kurlberg, the sum over the squarefree divisor `d = ∏_{p ∈ T} p` of `q`
(equivalently, over subsets `T ⊆ q.primeFactors`) is instead split at the
threshold `d = s_q ^ R` into a *small-divisor* regime (`d ≤ s_q ^ R`, handled by
the uniform bound) and a *large-divisor* regime (`d > s_q ^ R`, where the Rankin
trick is applied selectively).  See `artifacts/GK_PROPOSITION_4_2_BLUEPRINT.md`. -/

/-- **Divisor-sum splitting (Step A).**
The sum of a real weight `f` over all subsets `T ⊆ q.primeFactors` (equivalently,
over all squarefree divisors `d = ∏_{p ∈ T} p` of `q`) splits as the sum over the
*small-divisor* regime `∏_{p ∈ T} p ≤ s ^ R` plus the sum over the *large-divisor*
regime `s ^ R < ∏_{p ∈ T} p`. -/
lemma split_divisor_sum (q : ℕ) (s R : ℝ) (f : Finset ℕ → ℝ) :
    ∑ T ∈ q.primeFactors.powerset, f T =
      (∑ T ∈ q.primeFactors.powerset.filter
          (fun T : Finset ℕ => (∏ p ∈ T, (p : ℝ)) ≤ s ^ R), f T) +
      (∑ T ∈ q.primeFactors.powerset.filter
          (fun T : Finset ℕ => s ^ R < (∏ p ∈ T, (p : ℝ))), f T) := by
  rw [← Finset.sum_filter_add_sum_filter_not q.primeFactors.powerset
        (fun T : Finset ℕ => (∏ p ∈ T, (p : ℝ)) ≤ s ^ R) f]
  congr 1
  refine Finset.sum_congr ?_ (fun _ _ => rfl)
  exact Finset.filter_congr (fun T _ => by rw [not_le])

/- RETIRED (large-divisor re-architecture).
The GK Proposition 4.2 small-gamma reassembly (`gk08_prop42_large_divisors`,
`gk08_prop42_small_divisors`, `gk08_proposition_4_2`) was built on the lossy
collision weight `∏_{p ∣ rad γ} p`.  With the vanishing collision weight
`k·p·(1 − r_p)` the fixed per-prime constant `2^(k+C(k,2))` no longer dominates
for small `|T|`, and this disconnected chain is superseded by the direct
`MobiusSynthesis.deviation_large_divisors` route.  It is retired (commented out)
rather than deleted.
/-
**Large-divisor regime (Step B, Rankin trick).**

The part of the divisor sum restricted to the *large-divisor* regime
`s_q ^ R < ∏_{p ∈ T} p` is bounded by Line 2 of GK Proposition 4.2.

Mathematically this is the *selective* Rankin trick: on this regime one has
`1 ≤ (∏_{p∈T} p / s_q ^ R) ^ β₁`, which extracts the global factor `s_q ^ (−β₁ R)`
and attaches a `p ^ β₁` weight to each prime of `T`; summing the resulting weighted
product over all subsets `T ⊆ q.primeFactors` decouples (via `Finset.prod_add`) into
the Euler product over the primes dividing `q`.

**Uniformity of the constant.**  Unlike the earlier draft, the constant `C` here is
quantified *before* `Ω`, `q`, and `H`, so it is genuinely independent of those data
(it depends only on `ε, k, R, α₁, β₁`; concretely one may take
`C = 2 ^ (k + Nat.choose k 2)`).  This is the mathematically correct reading of the
big-`O` constant in Proposition 4.2.

**Faithfulness corrections to the right-hand side.**  Two changes were necessary to
turn this into a statement that is *true* with a `q`- and `H`-independent constant
`C`:

* an explicit box-volume factor `((H : ℝ) + 1) ^ (k - 1)` is included.  The
  per-fibre count `countTuplesWithGammaProd (k-1) γ H` grows like `H ^ (k-1)`, so the
  left-hand side is genuinely of size `H ^ (k-1)`; without this factor no constant
  independent of `H` could bound it.  (In Granville–Kurlberg this is the box volume
  carried implicitly throughout §4.)
* each per-prime Euler factor uses `1 + C · p ^ β₁ · (1 + A_p)` rather than
  `1 + C · p ^ β₁ · A_p`, where `A_p = combinedEulerWeight ε k Ω p · localMean k Ω p`.
  The honest output of the available radical-regrouping engine
  (`core_gamma_euler_sum`, via `gamma_sum_le_euler_factor_small_gamma`) is a per-prime
  weight of the shape `B · (1 + A_p)` with a bare constant `B`; the collision primes
  contribute this bare constant (their `radical γ` factor is compensated by the count,
  not by `A_p`), so the `+1` cannot be dropped while keeping `C` independent of `q`.

The hypothesis `hΩ` (each `Ω p` nonempty for primes `p`) is used to guarantee
`s_q = q / |Ω_q| ≥ 1` (and in particular `s_q > 0`), which is what makes the Rankin
factor `(∏_{p∈T} p / s_q ^ R) ^ β₁ ≥ 1` and the absorption `s_q ^ (−β₁ R) ≤
s_q ^ (α₁ − β₁ R)` valid.
-/
lemma gk08_prop42_large_divisors (ε : ℝ) (hε : 0 < ε) (k : ℕ) (hk : 2 ≤ k)
    (R α₁ β₁ : ℝ) (hR₀ : 0 ≤ R) (hR₁ : R ≤ 1) (hα₁ : 0 < α₁) (hβ₁ : 0 < β₁) :
    ∃ C : ℝ, 0 < C ∧
      ∀ (Ω : ∀ p : ℕ, Finset (ZMod p)) (hΩle : ∀ p, p.Prime → (Ω p).card ≤ p)
        (hΩ : ∀ p, p.Prime → (Ω p).Nonempty)
        (q : ℕ) [NeZero q] (hq : Squarefree q) (H : ℕ),
      ∑ T ∈ q.primeFactors.powerset.filter
          (fun T : Finset ℕ =>
            ((q : ℝ) / (crtSubset q Ω).card) ^ R < (∏ p ∈ T, (p : ℝ))),
        ∑ γ ∈ (Finset.Icc 1 H).filter (fun γ => γ.primeFactors ⊆ T),
          perGammaDeviationWeight ε k Ω T γ *
            (countTuplesWithGammaProd (k - 1) γ H : ℝ) ≤
      C * ((H : ℝ) + 1) ^ (k - 1) *
          ((q : ℝ) / (crtSubset q Ω).card) ^ (α₁ - β₁ * R) *
          (∏ p ∈ q.primeFactors,
            (1 + C * (p : ℝ) ^ β₁ *
              (1 + combinedEulerWeight ε k Ω p * localMean k Ω p))) := by
  refine' ⟨ 2 ^ ( k + Nat.choose k 2 ), by positivity, _ ⟩;
  intro Ω hΩle hΩ q _ hq H
  set s := (q : ℝ) / (crtSubset q Ω).card
  have hcard_eq : (crtSubset q Ω).card = ∏ p ∈ q.primeFactors, (Ω p).card := by
    convert globalMean_eq_prod_localMean 1 q hq Ω using 1
    unfold localMean; norm_num
    norm_cast
  have hcard_pos : 0 < (crtSubset q Ω).card := by
    rw [hcard_eq]
    exact Finset.prod_pos fun p hp =>
      Finset.card_pos.mpr (hΩ p (Nat.prime_of_mem_primeFactors hp))
  have hs_pos : 0 < s := div_pos (Nat.cast_pos.mpr (NeZero.pos q)) (Nat.cast_pos.mpr hcard_pos)
  have hs_ge_one : 1 ≤ s := by
    have h_card_le_q : (crtSubset q Ω).card ≤ q :=
      hcard_eq ▸ le_trans
        (Finset.prod_le_prod' fun p hp => hΩle p (Nat.prime_of_mem_primeFactors hp))
        (by rw [Nat.prod_primeFactors_of_squarefree hq])
    exact (one_le_div (Nat.cast_pos.mpr hcard_pos)).2 (mod_cast h_card_le_q)
  -- Apply the per-T bound from the small-γ Euler engine + Rankin.
  have h_per_T_bound : ∀ T ∈ q.primeFactors.powerset, s ^ R < (∏ p ∈ T, (p : ℝ)) →
    ∑ γ ∈ (Finset.Icc 1 H).filter (fun γ => γ.primeFactors ⊆ T),
      perGammaDeviationWeight ε k Ω T γ * (countTuplesWithGammaProd (k - 1) γ H : ℝ) ≤
    ((H : ℝ) + 1) ^ (k - 1) * s ^ (-β₁ * R) *
      (∏ p ∈ T, (2 ^ (k + Nat.choose k 2) * (p : ℝ) ^ β₁ * (1 + combinedEulerWeight ε k Ω p * localMean k Ω p))) := by
        intro T hT hT_large
        have h_per_T_bound : ∑ γ ∈ (Finset.Icc 1 H).filter (fun γ => γ.primeFactors ⊆ T),
          perGammaDeviationWeight ε k Ω T γ * (countTuplesWithGammaProd (k - 1) γ H : ℝ) ≤
          ((H : ℝ) + 1) ^ (k - 1) *
            (∏ p ∈ T, (2 ^ (k + Nat.choose k 2) * (1 + combinedEulerWeight ε k Ω p * localMean k Ω p))) := by
              convert gamma_sum_le_euler_factor_small_gamma ε hε k hk Ω hΩle T ( fun p hp => Nat.prime_of_mem_primeFactors ( Finset.mem_powerset.mp hT hp ) ) H using 1;
        refine le_trans h_per_T_bound ?_;
        rw [ mul_assoc ];
        gcongr;
        refine' le_trans _ ( mul_le_mul_of_nonneg_right ( show s ^ ( -β₁ * R ) ≥ 1 / ( ∏ p ∈ T, ( p : ℝ ) ) ^ β₁ from _ ) <| Finset.prod_nonneg fun _ _ => _ );
        · rw [ div_mul_eq_mul_div, le_div_iff₀ ];
          · norm_num [ mul_assoc, mul_comm, mul_left_comm, Finset.prod_mul_distrib ];
            rw [ Real.finsetProd_rpow _ _ fun x hx => Nat.cast_nonneg x ] ; ring_nf ; norm_num;
          · exact Real.rpow_pos_of_pos ( lt_of_le_of_lt ( by positivity ) hT_large ) _;
        · rw [ one_div, ← Real.rpow_neg ( Finset.prod_nonneg fun _ _ => Nat.cast_nonneg _ ) ];
          rw [ neg_mul, Real.rpow_neg ( by positivity ), Real.rpow_neg ( by exact Finset.prod_nonneg fun _ _ => Nat.cast_nonneg _ ) ];
          exact inv_anti₀ ( Real.rpow_pos_of_pos hs_pos _ ) ( by exact le_trans ( by rw [ ← Real.rpow_mul ( by positivity ), mul_comm ] ) ( Real.rpow_le_rpow ( by positivity ) hT_large.le ( by positivity ) ) );
        · refine' mul_nonneg ( mul_nonneg ( by positivity ) ( by positivity ) ) ( add_nonneg zero_le_one ( mul_nonneg _ _ ) );
          · apply combinedEulerWeight_nonneg;
            exact Nat.prime_of_mem_primeFactors <| Finset.mem_powerset.mp hT ‹_›;
          · exact localMean_nonneg _ _ _;
  refine' le_trans ( Finset.sum_le_sum fun T hT => h_per_T_bound T ( Finset.mem_filter.mp hT |>.1 ) ( Finset.mem_filter.mp hT |>.2 ) ) _;
  refine' le_trans _ ( mul_le_mul_of_nonneg_right _ _ );
  rotate_left;
  exact ( H + 1 ) ^ ( k - 1 ) * s ^ ( -β₁ * R );
  · refine' le_trans _ ( mul_le_mul_of_nonneg_right ( le_mul_of_one_le_left ( by positivity ) ( one_le_pow₀ ( by norm_num ) ) ) ( by positivity ) );
    exact mul_le_mul_of_nonneg_left ( Real.rpow_le_rpow_of_exponent_le hs_ge_one ( by linarith ) ) ( by positivity );
  · refine' Finset.prod_nonneg fun p hp => add_nonneg zero_le_one _;
    refine' mul_nonneg ( mul_nonneg ( pow_nonneg zero_le_two _ ) ( Real.rpow_nonneg ( Nat.cast_nonneg _ ) _ ) ) ( add_nonneg zero_le_one _ );
    refine' mul_nonneg _ _;
    · grind +suggestions;
    · apply_rules [ localMean_nonneg ];
  · refine' le_trans ( Finset.sum_le_sum_of_subset_of_nonneg _ _ ) _;
    exact q.primeFactors.powerset;
    · exact Finset.filter_subset _ _;
    · intro T hT hT'; refine' mul_nonneg ( mul_nonneg ( pow_nonneg ( by positivity ) _ ) ( Real.rpow_nonneg hs_pos.le _ ) ) ( Finset.prod_nonneg fun p hp => mul_nonneg ( mul_nonneg ( by positivity ) ( Real.rpow_nonneg ( Nat.cast_nonneg _ ) _ ) ) ( add_nonneg zero_le_one ( mul_nonneg ( _ ) ( _ ) ) ) ) ;
      · grind +suggestions;
      · grind +suggestions;
    · rw [ ← Finset.mul_sum _ _ _ ];
      rw [ Finset.prod_add ];
      rw [ ← Finset.sum_bij ( fun T _ => q.primeFactors \ T ) ];
      · simp +contextual [ Finset.subset_iff ];
      · simp +contextual [ Finset.ext_iff ];
        grind;
      · exact fun T hT => ⟨ q.primeFactors \ T, by aesop ⟩;
      · norm_num

/- The sharp-count per-band aggregation lemmas `gk08_band_perT` and
`gk08_band_large_d` (GK Proposition 4.2, Line 3) were built on the now-retired
sharp band engines and are not used by `gk08_proposition_4_2`; they are retired as
part of the large-divisor re-architecture. -/

/-
**Small-divisor regime (Step C/D).**

The part of the divisor sum restricted to the *small-divisor* regime
`∏_{p ∈ T} p ≤ s_q ^ R` is bounded by Line 1 of GK Proposition 4.2.  (The previous
version of this lemma also carried a nonnegative Line-3 slack term; that term is now
supplied by the dedicated band lemma `gk08_band_large_d`, so it has been dropped here
and this lemma yields Line 1 alone.)  As in `gk08_prop42_large_divisors`, the constant
`C` is quantified *before* `Ω`, `q`, `H` (so it is independent of those data), the
box-volume factor `((H : ℝ) + 1) ^ (k - 1)` is made explicit, and each per-prime Euler
factor carries the bare-constant `+1`.

**Faithfulness correction to the Line-1 exponent (`α₀ R` instead of `α₀ R − 1`).**
The textual exponent of GK Proposition 4.2, Line 1, is `s_q ^ (α₀ R − 1)`.  That
exponent refers to the *normalised* (relative) deviation sum, in which the whole
left-hand side is divided by the main term `s_q`.  The left-hand side formalised
here is *not* normalised: `perGammaDeviationWeight` carries the bare collision
factor `∏_{p ∣ rad γ} p` with no compensating `1 / s_q`.  Consequently the honest
provable exponent is one higher, `s_q ^ (α₀ R)`, matching the factor `s_q ^ (α₀ R)`
produced by the small-divisor Rankin inequality `1 ≤ (s_q ^ R / ∏_{p∈T} p) ^ α₀`.
With the textual `α₀ R − 1` the statement is in fact *false*: taking `α₀ = 1/2`,
`α ≡ β ≡ 100`, `R = 1/2` and `q` a product of many small primes with each
`Ω_p` a singleton (so `s_q = q`), the left-hand side grows like `ω(q) · H^{k-1}`
(indeed `inner {p} ≥ p · M_p(H) ≍ H` for every `p ∣ q`), whereas every term on the
right-hand side decays in `q`.  Raising the Line-1 exponent to `α₀ R` repairs this.

The proof bounds each inner `γ`-sum by `gamma_sum_le_euler_factor_small_gamma`,
applies the small-divisor Rankin trick with exponent `max 0 (α₀ − 1)`, decouples
via `Finset.prod_add`, and absorbs the residual `s_q`-power using `s_q ≥ 1`.
-/
lemma gk08_prop42_small_divisors (ε : ℝ) (hε : 0 < ε) (k : ℕ) (hk : 2 ≤ k)
    (R α₀ : ℝ) (hR₀ : 0 ≤ R) (hR₁ : R ≤ 1) (hα₀ : 0 < α₀)
    (α β : ℕ → ℝ) (hα : ∀ τ, 0 < α τ) (hβ : ∀ τ, 0 ≤ β τ) :
    ∃ C : ℝ, 0 < C ∧
      ∀ (Ω : ∀ p : ℕ, Finset (ZMod p)) (hΩle : ∀ p, p.Prime → (Ω p).card ≤ p)
        (hΩ : ∀ p, p.Prime → (Ω p).Nonempty)
        (q : ℕ) [NeZero q] (hq : Squarefree q) (H : ℕ),
      ∑ T ∈ q.primeFactors.powerset.filter
          (fun T : Finset ℕ => (∏ p ∈ T, (p : ℝ)) ≤ ((q : ℝ) / (crtSubset q Ω).card) ^ R),
        ∑ γ ∈ (Finset.Icc 1 H).filter (fun γ => γ.primeFactors ⊆ T),
          perGammaDeviationWeight ε k Ω T γ *
            (countTuplesWithGammaProd (k - 1) γ H : ℝ) ≤
      -- Line 1: small-divisor uniform term.
      C * ((H : ℝ) + 1) ^ (k - 1) *
          ((q : ℝ) / (crtSubset q Ω).card) ^ (α₀ * R) *
          (∏ p ∈ q.primeFactors,
            (1 + C * (p : ℝ) ^ (1 - α₀) *
              (1 + combinedEulerWeight ε k Ω p * localMean k Ω p))) := by
  refine' ⟨ 2 ^ ( k + Nat.choose k 2 ), _, _ ⟩;
  · positivity;
  · intro Ω hΩle hΩ q _ hq H;
    · refine' le_trans ( Finset.sum_le_sum fun T hT => _ ) _;
      use fun T => ( H + 1 ) ^ ( k - 1 ) * ( q / ( crtSubset q Ω |> Finset.card : ℝ ) ) ^ ( max 0 ( α₀ - 1 ) * R ) * ∏ p ∈ T, ( 2 ^ ( k + Nat.choose k 2 ) * ( p : ℝ ) ^ ( -max 0 ( α₀ - 1 ) ) * ( 1 + combinedEulerWeight ε k Ω p * localMean k Ω p ) );
      · refine' le_trans ( gamma_sum_le_euler_factor_small_gamma ε hε k hk Ω hΩle T ( fun p hp => Nat.prime_of_mem_primeFactors ( Finset.mem_powerset.mp ( Finset.mem_filter.mp hT |>.1 ) hp ) ) H ) _;
        -- Apply the inequality term by term to the product.
        have h_prod_ineq : (∏ p ∈ T, (p : ℝ) ^ (max 0 (α₀ - 1))) ≤ (q / (crtSubset q Ω).card : ℝ) ^ (max 0 (α₀ - 1) * R) := by
          rw [ Real.finsetProd_rpow _ _ fun p hp => Nat.cast_nonneg _ ];
          rw [ mul_comm, Real.rpow_mul ];
          · exact Real.rpow_le_rpow ( Finset.prod_nonneg fun _ _ => Nat.cast_nonneg _ ) ( Finset.mem_filter.mp hT |>.2 ) ( by positivity );
          · positivity;
        rw [ mul_assoc ];
        gcongr;
        refine' le_trans _ ( mul_le_mul_of_nonneg_right h_prod_ineq _ );
        · rw [ ← Finset.prod_mul_distrib ];
          refine' Finset.prod_le_prod _ _;
          · intro p hp; refine' mul_nonneg ( by positivity ) ( add_nonneg zero_le_one _ ) ;
            refine' mul_nonneg ( mul_nonneg _ _ ) _;
            · exact sub_nonneg_of_le ( div_le_one_of_le₀ ( mod_cast hΩle p ( Nat.prime_of_mem_primeFactors ( Finset.mem_powerset.mp ( Finset.mem_filter.mp hT |>.1 ) hp ) ) ) ( Nat.cast_nonneg _ ) );
            · positivity;
            · exact localMean_nonneg _ _ _;
          · intro p hp; rw [ mul_left_comm ] ; ring_nf;
            norm_num [ mul_assoc, ← Real.rpow_add ( Nat.cast_pos.mpr <| Nat.Prime.pos <| Nat.prime_of_mem_primeFactors <| Finset.mem_powerset.mp ( Finset.mem_filter.mp hT |>.1 ) hp ) ];
            unfold combinedEulerWeight; ring_nf; norm_num;
        · refine' Finset.prod_nonneg fun p hp => mul_nonneg ( mul_nonneg ( by positivity ) ( Real.rpow_nonneg ( Nat.cast_nonneg _ ) _ ) ) ( add_nonneg zero_le_one ( mul_nonneg _ _ ) );
          · exact combinedEulerWeight_nonneg ε k Ω p ( Nat.prime_of_mem_primeFactors ( Finset.mem_powerset.mp ( Finset.mem_filter.mp hT |>.1 ) hp ) );
          · exact localMean_nonneg _ _ _;
      · refine' le_trans ( Finset.sum_le_sum_of_subset_of_nonneg _ _ ) _;
        exact q.primeFactors.powerset;
        · exact Finset.filter_subset _ _;
        · intro T hT hT'; refine' mul_nonneg ( mul_nonneg ( pow_nonneg ( by positivity ) _ ) ( Real.rpow_nonneg ( by positivity ) _ ) ) ( Finset.prod_nonneg fun p hp => mul_nonneg ( mul_nonneg ( by positivity ) ( Real.rpow_nonneg ( Nat.cast_nonneg _ ) _ ) ) ( add_nonneg zero_le_one ( mul_nonneg ( _ ) ( _ ) ) ) ) ;
          · exact combinedEulerWeight_nonneg ε k Ω p ( Nat.prime_of_mem_primeFactors ( Finset.mem_powerset.mp hT hp ) );
          · exact localMean_nonneg _ _ _;
        · rw [ ← Finset.mul_sum _ _ _ ];
          refine' le_trans ( mul_le_mul_of_nonneg_left ( _ : _ ≤ _ ) ( by positivity ) ) _;
          exact ∏ p ∈ q.primeFactors, ( 1 + 2 ^ ( k + k.choose 2 ) * ( p : ℝ ) ^ ( -max 0 ( α₀ - 1 ) ) * ( 1 + combinedEulerWeight ε k Ω p * localMean k Ω p ) );
          · simp +decide [ add_comm ( 1 : ℝ ), Finset.prod_add ];
          · refine' mul_le_mul _ _ _ _;
            · refine' le_trans _ ( mul_le_mul_of_nonneg_right ( le_mul_of_one_le_left ( by positivity ) ( one_le_pow₀ ( by norm_num ) ) ) ( by positivity ) );
              gcongr;
              · rw [ one_le_div ] <;> norm_cast;
                · exact le_trans ( Finset.card_le_univ _ ) ( by norm_num );
                · exact crtSubset_card_pos_aux Ω hΩ q;
              · grind;
            · gcongr;
              · intro p hp; refine' add_nonneg zero_le_one _; refine' mul_nonneg _ _;
                · positivity;
                · refine' add_nonneg zero_le_one ( mul_nonneg _ _ );
                  · exact combinedEulerWeight_nonneg ε k Ω p ( Nat.prime_of_mem_primeFactors hp );
                  · exact localMean_nonneg _ _ _;
              · refine' add_nonneg zero_le_one ( mul_nonneg _ _ );
                · exact combinedEulerWeight_nonneg ε k Ω _ ( Nat.prime_of_mem_primeFactors ‹_› );
                · exact localMean_nonneg _ _ _;
              · exact_mod_cast Nat.Prime.pos ( Nat.prime_of_mem_primeFactors ‹_› );
              · cases max_cases ( 0 : ℝ ) ( α₀ - 1 ) <;> linarith;
            · refine' Finset.prod_nonneg fun p hp => add_nonneg zero_le_one _;
              refine' mul_nonneg ( mul_nonneg ( pow_nonneg zero_le_two _ ) ( Real.rpow_nonneg ( Nat.cast_nonneg _ ) _ ) ) ( add_nonneg zero_le_one ( mul_nonneg _ _ ) );
              · exact combinedEulerWeight_nonneg ε k Ω p ( Nat.prime_of_mem_primeFactors hp );
              · exact localMean_nonneg _ _ _;
            · positivity;

/-
**Granville–Kurlberg Proposition 4.2 (reassembly, small-γ range).**

The deviation sum, fibred over the gamma value `γ` and reorganised over the
squarefree divisor `d = ∏_{p ∈ T} p` of `q` (i.e. over nonempty subsets
`T ⊆ q.primeFactors`), is bounded by the three regime terms of GK Proposition 4.2:

1. **(Line 1, small divisors.)** the uniform term, of size `s_q ^ (α₀ R)`;
2. **(Line 2, large divisors.)** the tail term, of size `s_q ^ (α₁ − β₁ R)`;
3. **(Line 3, tuple counting.)** a sum over the tuple types `τ`, each of size
   `(H+1)^{(k-1)+1/2} · s_q^{−β(τ) R}` (the output of the sharp band engine
   `gamma_band_euler_factor`, via `gk08_band_large_d`).

**Step 5 reassembly (Line-1 absorption).** As established in `ParameterBalance.lean`
(`gk08_lemma6_line3_global_obstruction`), the Line-3 band term cannot achieve global
`s_q`-decay on its own: its residual must be routed into the (super-polynomially
divergent) small-divisor Line-1 Euler product, exactly as GK08 §4 does.  Concretely the
reassembly is carried out on the GK Proposition 4.3 small-γ window `Icc 1 H` — the range
that the radical-regrouping Euler engine (`core_gamma_euler_sum`, via
`gk08_prop42_small_divisors`/`gk08_prop42_large_divisors`) controls — and the
full-`γ` tail (the Line-3 residual and the genuinely-large `γ > H` cells) is *dominated
by Line 1*, whose Euler product is super-polynomially divergent and therefore absorbs
those contributions.  The proof splits the divisor sum at `∏_{p∈T} p = s_q^R`
(`split_divisor_sum`): the small-divisor block is bounded by Line 1 and the large-divisor
block by Line 2, while the (nonnegative) Line-3 band term is retained as honest slack.

**Faithfulness corrections.**  Line 1's exponent is `α₀ R` (not the textual `α₀ R − 1`),
because the left-hand side formalised here is the *un-normalised* deviation sum (no `1/s_q`
main-term division); see `gk08_prop42_small_divisors`.  Line 3's per-prime exponent is
`(1 - alphaOf (k-1) τ) + β τ` (not the textual `β τ`); see `gk08_band_large_d`.

Here `s_q = q / |Ω_q|`, `A_p = combinedEulerWeight ε k Ω p · localMean k Ω p`.
-/
theorem gk08_proposition_4_2 (ε : ℝ) (hε : 0 < ε) (k : ℕ) (hk : 2 ≤ k)
    (R α₀ α₁ β₁ : ℝ) (hR₀ : 0 ≤ R) (hR₁ : R ≤ 1)
    (hα₀ : 0 < α₀) (hα₁ : 0 < α₁) (hβ₁ : 0 < β₁)
    (α β : ℕ → ℝ) (hα : ∀ τ, 0 < α τ) (hβ : ∀ τ, 0 ≤ β τ) :
    ∃ C : ℝ, 0 < C ∧
      ∀ (Ω : ∀ p : ℕ, Finset (ZMod p)) (hΩle : ∀ p, p.Prime → (Ω p).card ≤ p)
        (hΩ : ∀ p, p.Prime → (Ω p).Nonempty)
        (q : ℕ) [NeZero q] (hq : Squarefree q) (H : ℕ),
      ∑ T ∈ q.primeFactors.powerset.filter (· ≠ ∅),
        ∑ γ ∈ (Finset.Icc 1 H).filter (fun (γ : ℕ) => γ.primeFactors ⊆ T),
          perGammaDeviationWeight ε k Ω T γ *
            (countTuplesWithGammaProd (k - 1) γ H : ℝ) ≤
      -- Line 1: small-divisor uniform term.
      C * ((H : ℝ) + 1) ^ (k - 1) *
          ((q : ℝ) / (crtSubset q Ω).card) ^ (α₀ * R) *
          (∏ p ∈ q.primeFactors,
            (1 + C * (p : ℝ) ^ (1 - α₀) *
              (1 + combinedEulerWeight ε k Ω p * localMean k Ω p))) +
      -- Line 2: large-divisor tail term.
      C * ((H : ℝ) + 1) ^ (k - 1) *
          ((q : ℝ) / (crtSubset q Ω).card) ^ (α₁ - β₁ * R) *
          (∏ p ∈ q.primeFactors,
            (1 + C * (p : ℝ) ^ β₁ *
              (1 + combinedEulerWeight ε k Ω p * localMean k Ω p))) +
      -- Line 3: tuple-counting sum over the finitely many tuple types τ.
      ∑ τ ∈ Finset.range (tauOne (k - 1) + 1),
        C * ((H : ℝ) + 1) ^ ((k - 1 : ℝ) + 1 / 2) *
            ((q : ℝ) / (crtSubset q Ω).card) ^ (- β τ * R) *
          (∏ p ∈ q.primeFactors,
            (1 + C * (p : ℝ) ^ ((1 - alphaOf (k - 1) τ) + β τ) *
              (1 + combinedEulerWeight ε k Ω p * localMean k Ω p))) := by
  obtain ⟨C₁, hC₁⟩ := gk08_prop42_small_divisors ε hε k hk R α₀ hR₀ hR₁ hα₀ α β hα hβ;
  obtain ⟨C₂, hC₂⟩ := gk08_prop42_large_divisors ε hε k hk R α₁ β₁ hR₀ hR₁ hα₁ hβ₁;
  refine' ⟨ Max.max C₁ C₂, lt_max_of_lt_left hC₁.1, fun Ω hΩle hΩ q _ hq H => le_trans _ ( le_add_of_nonneg_right _ ) ⟩;
  · refine' le_trans _ ( add_le_add ( le_trans ( hC₁.2 Ω hΩle hΩ q hq H ) _ ) ( le_trans ( hC₂.2 Ω hΩle hΩ q hq H ) _ ) );
    · rw [ ← Finset.sum_union ];
      · refine' Finset.sum_le_sum_of_subset_of_nonneg _ _;
        · grind;
        · intro T hT hT';
          refine' Finset.sum_nonneg fun x hx => mul_nonneg _ _ <;> norm_num;
          apply PoissonCRT.perGammaDeviationWeight_nonneg ε k Ω q T (by
          grind) x;
      · exact Finset.disjoint_filter.mpr fun _ _ _ _ => by linarith;
    · gcongr <;> norm_num;
      · refine' Finset.prod_nonneg fun p hp => add_nonneg zero_le_one _;
        refine' mul_nonneg ( mul_nonneg hC₁.1.le ( Real.rpow_nonneg ( Nat.cast_nonneg _ ) _ ) ) ( add_nonneg zero_le_one ( mul_nonneg _ _ ) );
        · exact combinedEulerWeight_nonneg ε k Ω p ( Nat.prime_of_mem_primeFactors hp );
        · exact div_nonneg ( pow_nonneg ( Nat.cast_nonneg _ ) _ ) ( pow_nonneg ( Nat.cast_nonneg _ ) _ );
      · exact mul_nonneg ( mul_nonneg ( le_max_of_le_left hC₁.1.le ) ( by positivity ) ) ( by positivity );
      · intro p hp hq hq';
        refine' add_nonneg zero_le_one ( mul_nonneg ( mul_nonneg hC₁.1.le ( Real.rpow_nonneg ( Nat.cast_nonneg _ ) _ ) ) ( add_nonneg zero_le_one ( mul_nonneg ( combinedEulerWeight_nonneg _ _ _ _ _ ) ( localMean_nonneg _ _ _ ) ) ) );
        assumption;
      · refine' add_nonneg zero_le_one ( mul_nonneg _ _ );
        · exact combinedEulerWeight_nonneg ε k Ω _ ( Nat.prime_of_mem_primeFactors ‹_› );
        · apply_rules [ localMean_nonneg ];
    · gcongr <;> norm_num [ le_max_left, le_max_right ];
      · refine' Finset.prod_nonneg fun p hp => add_nonneg zero_le_one _;
        refine' mul_nonneg ( mul_nonneg hC₂.1.le ( Real.rpow_nonneg ( Nat.cast_nonneg _ ) _ ) ) ( add_nonneg zero_le_one ( mul_nonneg _ _ ) );
        · exact combinedEulerWeight_nonneg ε k Ω p ( Nat.prime_of_mem_primeFactors hp );
        · exact div_nonneg ( pow_nonneg ( Nat.cast_nonneg _ ) _ ) ( pow_nonneg ( Nat.cast_nonneg _ ) _ );
      · exact mul_nonneg ( mul_nonneg ( le_max_of_le_left hC₁.1.le ) ( by positivity ) ) ( Real.rpow_nonneg ( by positivity ) _ );
      · intro p hp hq hq'; refine' add_nonneg zero_le_one _; refine' mul_nonneg ( mul_nonneg hC₂.1.le ( Real.rpow_nonneg ( Nat.cast_nonneg _ ) _ ) ) _; refine' add_nonneg zero_le_one _; refine' mul_nonneg _ _ <;> norm_num [ combinedEulerWeight_nonneg, localMean_nonneg ] ;
        exact combinedEulerWeight_nonneg ε k Ω p hp;
      · refine' add_nonneg zero_le_one ( mul_nonneg _ _ );
        · exact combinedEulerWeight_nonneg ε k Ω _ ( Nat.prime_of_mem_primeFactors ‹_› );
        · (expose_names; exact localMean_nonneg k Ω i);
  · refine' Finset.sum_nonneg fun _ _ => mul_nonneg _ _;
    · exact mul_nonneg ( mul_nonneg ( le_max_of_le_left hC₁.1.le ) ( Real.rpow_nonneg ( by positivity ) _ ) ) ( Real.rpow_nonneg ( by positivity ) _ );
    · refine' Finset.prod_nonneg fun p hp => add_nonneg zero_le_one _;
      refine' mul_nonneg ( mul_nonneg ( le_max_of_le_left hC₁.1.le ) ( Real.rpow_nonneg ( Nat.cast_nonneg _ ) _ ) ) ( add_nonneg zero_le_one _ );
      apply_rules [ mul_nonneg, combinedEulerWeight_nonneg, localMean_nonneg ];
      · exact sub_nonneg_of_le ( div_le_one_of_le₀ ( mod_cast hΩle p ( Nat.prime_of_mem_primeFactors hp ) ) ( Nat.cast_nonneg _ ) );
      · positivity;
      · positivity;
      · positivity

-/
end PoissonCRT