/-
Copyright (c) 2026 Fernando Portela. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Fernando Portela
-/

/-
Portions of this file were generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.28.0
Mathlib version: 8f9d9cff6bd728b17a24e163c9402775d9e6a365

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

-- import Mathlib
import PoissonViaCRT.TupleCount
import PoissonViaCRT.Combinatorics
import PoissonViaCRT.FluctuationHelpers
import PoissonViaCRT.LatticePointBound
import PoissonViaCRT.CancellationHelpers
import RiemannHypothesisCurves.RiemannHypothesisHEC

set_option linter.unusedVariables false

/-!
# Main Theorems (§1, §3.2)

This file contains the main theorem statements from "Poisson statistics via the Chinese
remainder theorem" by Granville–Kurlberg, together with the key lemmas from their proofs.

## Main Results

* `PoissonCRT.tupleCount_crt_mul`: Multiplicativity of `N_k` under CRT.
* `PoissonCRT.epsilonAvgZero`: **Lemma 3.5**: `∑_h ε_k(h, d) = 0` for `d > 1`.
* `PoissonCRT.epsilon_sum_vanishes`: The sum `∑_h ε_k(h, p) = 0` (Lemma 3.5 identity).
* `PoissonCRT.mainTheorem_precise`: **Theorem 3.7** (precise version of Theorem 1.1).
* `PoissonCRT.coprime_tupleCount`: Hooley's theorem base case.
* `PoissonCRT.lattice_point_box_bound`: Lattice point count in scaled boxes.
* `PoissonCRT.euler_product_convergence`: Euler product bound under WD.
* `PoissonCRT.complete_period_cancellation_apply`: CRT cancellation for box sums.

## References

* [A. Granville, P. Kurlberg, *Poisson statistics via the Chinese remainder theorem*]
  [arXiv:math/0412135v2]
-/

open Finset BigOperators Classical

namespace PoissonCRT

/-! ### CRT multiplicativity of `N_k` -/

/-- **CRT multiplicativity**: For coprime `q₁, q₂`, the counting function is multiplicative:
`N_k(h, Ω_{q₁q₂}) = N_k(h mod q₁, Ω_{q₁}) · N_k(h mod q₂, Ω_{q₂})`.
This follows from the Chinese Remainder Theorem: `ℤ/q₁q₂ℤ ≅ ℤ/q₁ℤ × ℤ/q₂ℤ`. -/
theorem tupleCount_crt_mul {q₁ q₂ : ℕ} [NeZero q₁] [NeZero q₂]
    [NeZero (q₁ * q₂)]
    (hcop : Nat.Coprime q₁ q₂)
    (Ω₁ : Finset (ZMod q₁)) (Ω₂ : Finset (ZMod q₂))
    (h : Fin k → ZMod (q₁ * q₂)) :
    tupleCount (Ω₁ ×ˢ Ω₂ |>.map (ZMod.chineseRemainder hcop).symm.toEmbedding) h =
    tupleCount Ω₁ (fun i => ZMod.castHom (dvd_mul_right q₁ q₂) (ZMod q₁) (h i)) *
    tupleCount Ω₂ (fun i => ZMod.castHom (dvd_mul_left q₂ q₁) (ZMod q₂) (h i)) := by
  generalize_proofs at *
  unfold tupleCount
  rw [← Finset.card_product]
  refine Finset.card_bij (fun a _ =>
    ((ZMod.chineseRemainder hcop a).1, (ZMod.chineseRemainder hcop a).2)) ?_ ?_ ?_
  · simp +zetaDelta at *
    intro a ha
    have := ha
    simp_all +decide [ZMod.chineseRemainder]
  · aesop
  · intro b hb
    obtain ⟨b₁, b₂⟩ := b
    generalize_proofs at *
    refine' ⟨(ZMod.chineseRemainder hcop).symm (b₁, b₂), _, _⟩ <;>
      simp_all +decide
    simp_all +decide [ZMod.chineseRemainder]

/-! ### Lemma 3.5: Average of ε_k is zero

For any prime `p` and set `Ω_p ⊆ ℤ/pℤ`,
$$\sum_{\mathbf{h} \in (\mathbb{Z}/p\mathbb{Z})^{k-1}} \varepsilon_k(\mathbf{h}, p) = 0.$$

This follows from `∑_h N_k(h, Ω) = |Ω|^k`, and is stated in its fundamental form.
-/

/-- **Lemma 3.5 (reformulation)**: With `h₀ = 0` fixed, the sum of `N_{k+1}(0 :: g, Ω)`
over all `g : (ℤ/qℤ)^k` equals `|Ω|^{k+1}`. -/
theorem epsilonAvgZero {q : ℕ} [NeZero q] (Ω : Finset (ZMod q)) :
    ∑ g : Fin k → ZMod q, tupleCount Ω (Fin.cons 0 g) = Ω.card ^ (k + 1) :=
  tupleCount_sum_cons_eq Ω

/-! ### The error decomposition (§3.2)

The key identity: for squarefree `q`,
$$N_k(\mathbf{h}, q) = r_q^{k-1} \cdot |\Omega_q| \cdot \sum_{d \mid q} e_k(\mathbf{h}, d)$$
where `e_k(h, 1) = 1` and `e_k(h, d) = ∏_{p|d} ε_k(h, p)` for `d > 1`.

The `k`-level correlation decomposes as:
$$R_k(X, \Omega_q) = \operatorname{vol}(X) + O(1/s_q) + \text{Error}$$
where
$$\text{Error} = r_q^{k-1} \sum_{\substack{d \mid q \\ d > 1}}
  \sum_{\mathbf{h} \in s_q X \cap \mathbb{Z}^{k-1}} e_k(\mathbf{h}, d).$$
-/

/-- **Equation (3.6)**: The sum of `ε_k(h, p)` over all `h ∈ (ℤ/pℤ)^k` vanishes for `k ≥ 1`.
This follows from `∑_h N_k(h, Ω) = p · |Ω|^k`. -/
theorem epsilon_sum_vanishes {p : ℕ} [NeZero p] (Ω : Finset (ZMod p)) (hΩ : Ω.card ≠ 0)
    (hk : 1 ≤ k) :
    ∑ h : Fin k → ZMod p, epsilonError Ω h = 0 := by
  simp only [epsilonError, hΩ, ite_false]
  have hc : (Ω.card : ℝ) ≠ 0 := Nat.cast_ne_zero.mpr hΩ
  have hp : (p : ℝ) ≠ 0 := Nat.cast_ne_zero.mpr (NeZero.ne p)
  have hdenom : (Ω.card : ℝ) ^ k / (p : ℝ) ^ (k - 1) ≠ 0 :=
    div_ne_zero (pow_ne_zero _ hc) (pow_ne_zero _ hp)
  simp_rw [div_sub_one hdenom]
  rw [← Finset.sum_div, div_eq_zero_iff]
  left
  rw [Finset.sum_sub_distrib]
  have h1 : (∑ x : Fin k → ZMod p, (tupleCount Ω x : ℝ)) = (p : ℝ) * (Ω.card : ℝ) ^ k :=
    mod_cast tupleCount_sum_eq (k := k) Ω
  have h2 : (∑ _ : Fin k → ZMod p, ((Ω.card : ℝ) ^ k / (p : ℝ) ^ (k - 1))) =
      (p : ℝ) ^ k * ((Ω.card : ℝ) ^ k / (p : ℝ) ^ (k - 1)) := by
    rw [Finset.sum_const, Finset.card_univ]
    simp [ZMod.card, nsmul_eq_mul]
  rw [h1, h2]
  obtain ⟨n, rfl⟩ : ∃ n, k = n + 1 := ⟨k - 1, by omega⟩
  simp only [Nat.add_sub_cancel]
  field_simp
  ring

/-! ### Proposition 3.6 (Messy error bound)

Suppose we are given `R ∈ [0,1]`, and parameters `α₀, α₁, β₁, α(τ), β(τ) > 0`.
Assume `|Ω_p| > p^{1 - α(τ)}` for all `τ` and all primes `p` (so `s_p ≤ p^{α(τ)}`). Then
the Error term is bounded by a sum of terms, each being a power of `s_q` times an
Euler product `∏_{p|q} (1 + O_k(…))`.

The proof splits the divisor sum into "small d" (`d ≤ s_q^R`) and "large d" (`d > s_q^R`).
For small `d`, Lemma 3.5 cancels interior contributions; only `O((s_q/d)^{k-2})` boundary
terms remain. For large `d`, the Gamma machinery bounds the contribution via `M_Γ(H)`.
-/

/-! ### Helper lemmas for Proposition 3.6 -/

/-
The CRT subset is nonempty when each local subset `Ω p` is nonempty for primes `p`.

The CRT subset is nonempty because for each prime p dividing q, Ω p is nonempty. By ZMod.ringHom_surjective, the cast homomorphism ZMod q → ZMod p is surjective, so for any target in Ω p there exists a preimage. The intersection over all primes is nonempty by induction on the number of prime factors, using the Chinese Remainder Theorem.

Alternative simpler approach: for q = 1, primeFactors is empty so crtSubset = univ which has card 1 > 0. For q > 1, note that crtSubset q Ω = univ.filter (condition). The condition only involves prime factors of q. We need to show the filter is nonempty.

Actually, the simplest approach: show Finset.card_pos from Finset.Nonempty. The set is nonempty because we can construct an element. For any q, we can pick 0 ∈ ZMod q and check if it satisfies all conditions. If not, use CRT.

Try: rw [Finset.card_pos], apply Finset.Nonempty, use some element, and verify conditions using ZMod.ringHom_surjective and the nonemptiness of each Ω p.
-/
private lemma crtSubset_card_pos (Ω : ∀ p : ℕ, Finset (ZMod p))
    (hΩ : ∀ p, p.Prime → (Ω p).Nonempty) (q : ℕ) [NeZero q] :
    0 < (crtSubset q Ω).card := by
  by_contra! h_contra;
  -- By the Chinese Remainder Theorem, there exists an integer $x$ such that $x \equiv a_p \pmod{p}$ for each prime $p$ dividing $q$.
  obtain ⟨x, hx⟩ : ∃ x : ℕ, ∀ p ∈ Nat.primeFactors q, (x : ZMod p) ∈ Ω p := by
    -- By the Chinese Remainder Theorem, there exists an integer $x$ such that $x \equiv a_p \pmod{p}$ for each prime $p$ dividing $q$. Use this fact.
    have h_crt : ∀ {ps : Finset ℕ}, (∀ p ∈ ps, Nat.Prime p) → (∀ p ∈ ps, (Ω p).Nonempty) → ∃ x : ℕ, ∀ p ∈ ps, (x : ZMod p) ∈ Ω p := by
      intros ps hps hΩps
      have h_crt : ∀ p ∈ ps, ∃ x_p : ℕ, (x_p : ZMod p) ∈ Ω p ∧ ∀ q ∈ ps, q ≠ p → x_p ≡ 0 [MOD q] := by
        intro p hp
        obtain ⟨a_p, ha_p⟩ : ∃ a_p : ℕ, (a_p : ZMod p) ∈ Ω p := by
          haveI := Fact.mk ( hps p hp ) ; exact Exists.elim ( hΩps p hp ) fun x hx => ⟨ x.val, by simpa using hx ⟩ ;
        obtain ⟨x_p, hx_p⟩ : ∃ x_p : ℕ, x_p ≡ a_p [MOD p] ∧ ∀ q ∈ ps, q ≠ p → x_p ≡ 0 [MOD q] := by
          -- By the Chinese Remainder Theorem, there exists an integer $x_p$ such that $x_p \equiv a_p \pmod{p}$ and $x_p \equiv 0 \pmod{q}$ for all $q \in ps$ with $q \neq p$.
          obtain ⟨x_p, hx_p⟩ : ∃ x_p : ℕ, x_p ≡ a_p [MOD p] ∧ x_p ≡ 0 [MOD (∏ q ∈ ps.erase p, q)] := by
            have h_crt : Nat.gcd p (∏ q ∈ ps.erase p, q) = 1 := by
              exact Nat.Coprime.prod_right fun q hq => by have := Nat.coprime_primes ( hps p hp ) ( hps q ( Finset.mem_of_mem_erase hq ) ) ; aesop;
            have := Nat.chineseRemainder h_crt;
            exact ⟨ _, this a_p 0 |>.2 ⟩;
          exact ⟨ x_p, hx_p.1, fun q hq hqp => hx_p.2.of_dvd <| Finset.dvd_prod_of_mem _ <| by aesop ⟩
        use x_p;
        simp_all +decide [ ← ZMod.natCast_eq_natCast_iff ];
      choose! x hx₁ hx₂ using h_crt;
      use ∑ p ∈ ps, x p; intro p hp; simp_all +decide [ ← ZMod.natCast_eq_natCast_iff ] ;
      rw [ Finset.sum_eq_single p ] <;> aesop;
    exact h_crt ( fun p hp => Nat.prime_of_mem_primeFactors hp ) ( fun p hp => hΩ p ( Nat.prime_of_mem_primeFactors hp ) );
  simp_all +decide [ Finset.ext_iff, crtSubset ];
  obtain ⟨ p, hp₁, hp₂, hp₃, hp₄ ⟩ := h_contra x; specialize hx p hp₁ hp₂ hp₃; aesop;

/-
The spacing `s_q = q / |Ω_q|` is at least 1.

The spacing s_q = q / |crtSubset q Ω| ≥ 1 because |crtSubset q Ω| ≤ q. This follows from crtSubset q Ω ⊆ univ (it's a finset of ZMod q), and card(univ : Finset (ZMod q)) = q (by ZMod.card). So card(crtSubset) ≤ q, hence q / card ≥ 1.

Use: Finset.card_le_univ, ZMod.card, one_le_div_of_le (with card > 0 from crtSubset_card_pos).
-/
private lemma spacing_ge_one (Ω : ∀ p : ℕ, Finset (ZMod p))
    (hΩ : ∀ p, p.Prime → (Ω p).Nonempty) (q : ℕ) [NeZero q] :
    1 ≤ (q : ℝ) / (crtSubset q Ω).card := by
  rw [ one_le_div ] <;> norm_cast;
  · exact le_trans ( Finset.card_le_univ _ ) ( by norm_num );
  · exact crtSubset_card_pos Ω hΩ q


/-! ### Intermediate lemmas for Proposition 3.6 -/

/-
**Lattice point box bound**: The number of lattice points in a scaled box `sX`
deviates from `s^m · vol(X)` by at most `C_X · s^{m-1}`, where `C_X` depends on the
box dimensions and `m` is the dimension. This is a standard lattice point counting result.

The lattice points satisfying inScaledBox can be parametrized by increments d_i = h_i - h_{i-1} (with h_{-1} = 0), where each d_i is a positive integer with d_i ≤ s * X.sides i. So d_i ranges over {1, 2, ..., ⌊s * X.sides i⌋}, and the count equals ∏_i ⌊s * X.sides i⌋.
The volume X.volume = ∏_i X.sides i, so s^m * X.volume = ∏_i (s * X.sides i).
The error |∏_i ⌊s * b_i⌋ - ∏_i (s * b_i)| is bounded by C * s^(m-1) using the telescoping product bound: ∏ a_i - ∏ n_i = ∑_j (a_j - n_j) * ∏_{i&lt;j} n_i * ∏_{i>j} a_i, where each |a_j - n_j| &lt; 1 and each factor is at most s * max(b_i).
Choose C = m * (max b_i)^(m-1) + 1 (or similar).
For m = 0: the box is 0-dimensional, the count is 1, the volume is 1 (empty product), and s^0 * 1 = 1, so the error is 0 and any C > 0 works.
-/
lemma lattice_point_box_bound (m : ℕ) (X : Box m) :
    ∃ C : ℝ, 0 < C ∧ ∀ (v : Fin m → ℝ), (∀ i, 0 ≤ v i ∧ v i ≤ 1) → ∀ (s : ℝ), 1 ≤ s →
      |(((Fintype.piFinset fun _ : Fin m =>
          Finset.Icc (1 : ℤ) ⌈s * ∑ i, X.sides i⌉).filter
        (fun h => inScaledBox X s v h)).card : ℝ) - s ^ m * X.volume| ≤
        C * s ^ ((m : ℤ) - 1) := by
  -- Step 1: Obtain the product-of-floors bound for v = 0
  obtain ⟨C₁, hC₁_pos, hC₁_bound⟩ := prod_floor_approx m X.sides X.sides_pos
  -- Step 2: Obtain the offset difference bound
  obtain ⟨D, hD_nn, hD_bound⟩ := inScaledBox_offset_card_diff m X
  -- Step 3: Use C = C₁ + D + 1, which is positive
  refine ⟨C₁ + D + 1, by linarith, fun v hv s hs => ?_⟩
  -- Triangle inequality: |card(v) - vol| ≤ |card(v) - card(0)| + |card(0) - vol|
  have h_v0 : |(((Fintype.piFinset fun _ : Fin m =>
      Finset.Icc (1 : ℤ) ⌈s * ∑ i, X.sides i⌉).filter
    (fun h => inScaledBox X s (fun _ => 0) h)).card : ℝ) - s ^ m * X.volume| ≤
      C₁ * s ^ ((m : ℤ) - 1) := by
    rw [count_inScaledBox_eq_prod_floor m X s hs, Box.volume]
    convert hC₁_bound s hs using 2
    push_cast
    rfl
  have h_diff := hD_bound v hv s hs
  -- Abbreviate the two cardinalities
  set cv := ((Fintype.piFinset fun _ : Fin m =>
      Finset.Icc (1 : ℤ) ⌈s * ∑ i, X.sides i⌉).filter
    (fun h => inScaledBox X s v h)).card with hcv_def
  set c0 := ((Fintype.piFinset fun _ : Fin m =>
      Finset.Icc (1 : ℤ) ⌈s * ∑ i, X.sides i⌉).filter
    (fun h => inScaledBox X s (fun _ => 0) h)).card with hc0_def
  have h_tri : |(cv : ℝ) - s ^ m * X.volume| ≤
      |(cv : ℝ) - (c0 : ℝ)| + |(c0 : ℝ) - s ^ m * X.volume| := by
    calc |(cv : ℝ) - s ^ m * X.volume|
        = |((cv : ℝ) - c0) + ((c0 : ℝ) - s ^ m * X.volume)| := by ring_nf
      _ ≤ |(cv : ℝ) - c0| + |(c0 : ℝ) - s ^ m * X.volume| := abs_add_le _ _
  calc |(cv : ℝ) - s ^ m * X.volume|
    _ ≤ |(cv : ℝ) - c0| + |(c0 : ℝ) - s ^ m * X.volume| := h_tri
    _ ≤ D * s ^ ((m : ℤ) - 1) + C₁ * s ^ ((m : ℤ) - 1) := add_le_add h_diff h_v0
    _ ≤ (C₁ + D + 1) * s ^ ((m : ℤ) - 1) := by
        have : 0 ≤ s ^ ((m : ℤ) - 1) := zpow_nonneg (by linarith) _
        nlinarith

/-
**Euler product convergence**: Under the WD hypothesis with parameter `ε`,
for any divisor `d > 1` of `q`, the product of local WD error factors is bounded
by a universal constant `C_k` (depending only on `k` and `ε`). This captures the fact
that the product `∏_{p|d} (1 + O_k(p^{-ε}))` converges absolutely.

Choose C = 1. The product ∏_{p ∈ d.primeFactors} ((1 - |Ω_p|/p) · p^(-ε)) has each factor with absolute value at most 1 · p^(-ε) ≤ 2^(-ε) < 1 (since 0 ≤ 1 - |Ω_p|/p ≤ 1 because |Ω_p| ≤ p for any Finset of ZMod p). So the absolute value of the product is at most ∏_{p ∈ d.primeFactors} p^(-ε) ≤ ∏_{p ∈ d.primeFactors} 1 = 1.

Actually, each factor (1 - |Ω_p|/p) satisfies 0 ≤ (1 - |Ω_p|/p) ≤ 1, and p^(-ε) ≤ 1 for p ≥ 1 and ε > 0. So each factor has absolute value at most 1, and the product has absolute value at most 1. So C = 1 works.

Detailed proof:
refine ⟨1, one_pos, fun q _ d hd hd1 => ?_⟩
Apply abs_prod and bound each factor:
Each factor = (1 - (Ω p).card / p) * p ^ (-ε)
- 0 ≤ 1 - (Ω p).card / p ≤ 1 since (Ω p).card ≤ p (Finset.card_le_univ + ZMod.card)
- 0 ≤ p^(-ε) ≤ 1 since p ≥ 2 (prime) and ε > 0
So 0 ≤ factor ≤ 1, hence |factor| ≤ 1.
Product of values in [0,1] is in [0,1], so |product| ≤ 1 = C.
-/
lemma euler_product_convergence
    (ε : ℝ) (hε : 0 < ε) (k : ℕ) (hk : 2 ≤ k)
    (Ω : ∀ p : ℕ, Finset (ZMod p))
    (hΩ : ∀ p, p.Prime → (Ω p).Nonempty)
    (hWD : ∀ (p : ℕ) [Fact p.Prime], WellDistributed ε p (Ω p) k)
    (hsp : ∀ (p : ℕ), p.Prime →
      (p : ℝ) / (Ω p).card ≤ (p : ℝ) ^ (lambdaExponent k - ε)) :
    ∃ C : ℝ, 0 < C ∧ ∀ (q : ℕ) [NeZero q],
      ∀ (d : ℕ), d ∣ q → 1 < d →
        |∏ p ∈ d.primeFactors,
          ((1 : ℝ) - (Ω p).card / p) * (p : ℝ) ^ (-ε)| ≤ C := by
  refine' ⟨ 1, zero_lt_one, fun q hq d hd hd' => _ ⟩;
  rw [ Finset.abs_prod ];
  refine Finset.prod_le_one ?_ ?_ <;> norm_num;
  · exact fun _ _ _ _ => by positivity;
  · intro p pp dp _; rw [ abs_of_nonneg ( Real.rpow_nonneg ( Nat.cast_nonneg _ ) _ ) ] ; rw [ abs_of_nonneg ] <;> norm_num;
    · exact le_trans ( mul_le_of_le_one_left ( by positivity ) ( sub_le_self _ ( by positivity ) ) ) ( by simpa using Real.rpow_le_rpow_of_exponent_le ( mod_cast pp.one_lt.le ) ( neg_nonpos.mpr hε.le ) );
    · rw [ div_le_iff₀ ] <;> norm_cast <;> haveI := Fact.mk pp <;> simp_all;
      · haveI := Fact.mk pp; exact le_trans ( Finset.card_le_univ _ ) ( by norm_num ) ;
      · exact pp.pos

/-
**Complete period cancellation application**: For a divisor `d > 1` of `q`,
the sum of the error product `e_k(h, d) = ∏_{p|d} ε_k(h, p)` over lattice
points `h` in the scaled box `sX` is bounded using the cancellation from
`tupleCount_cons_deviation_sum_zero`. The key insight is that complete periods
cancel, and only boundary terms of size `O(s^{k-2})` remain.

Combining the lattice point box bound, the Euler product convergence, and the
period cancellation, the overall error is bounded by `C / s_q`.

Decompose kCorrelation into main term + deviation:

kCorrelation Ω_q X = (1/|Ω_q|) * ∑_h tupleCount(0::h)

Split tupleCount into expected μ = |Ω_q|^k / q^{k-1} plus deviation:
= (1/|Ω_q|) * [|box| * μ + ∑_h (tupleCount - μ)]
= (μ/|Ω_q|) * |box| + deviation_sum
= s^{-(k-1)} * |box| + deviation_sum

where s^{-(k-1)} = (|Ω_q|/q)^{k-1} = μ/|Ω_q|.

By the triangle inequality:
|kCorrelation - vol(X)| ≤ |s^{-(k-1)} * |box| - vol(X)| + |deviation_sum|

For the first term: s^{-(k-1)} * ||box| - s^{k-1} * vol(X)| ≤ s^{-(k-1)} * C_lp * s^{(k-1)-1} = C_lp * s^{-1}.
This uses h_lp_q.

For the second term: |deviation_sum| ≤ C_dev * s^{-1}.
This is exactly h_dev_q.

So: |kCorrelation - vol| ≤ C_lp * s^{-1} + C_dev * s^{-1} = (C_lp + C_dev) * s^{-1} ≤ (C_lp + C_dev + 1) * s^{-1}.

Key steps: unfold kCorrelation, use Finset.sum_sub_distrib to split the sum, convert the main term to s^{-(k-1)} * |box| using algebra, apply the triangle inequality, use h_lp_q and h_dev_q, and combine.
-/
-- set_option maxHeartbeats 800000 in
lemma complete_period_cancellation_apply
    (ε : ℝ) (hε : 0 < ε) (k : ℕ) (hk : 2 ≤ k)
    (Ω : ∀ p : ℕ, Finset (ZMod p))
    (hΩ : ∀ p, p.Prime → (Ω p).Nonempty)
    (hWD : ∀ (p : ℕ) [Fact p.Prime], WellDistributed ε p (Ω p) k)
    (hsp : ∀ (p : ℕ), p.Prime →
      (p : ℝ) / (Ω p).card ≤ (p : ℝ) ^ (lambdaExponent k - ε))
    (h_lp : ∀ (X : Box (k - 1)), ∃ C : ℝ, 0 < C ∧ ∀ (v : Fin (k - 1) → ℝ), (∀ i, 0 ≤ v i ∧ v i ≤ 1) →
      ∀ (s : ℝ), 1 ≤ s →
      |(((Fintype.piFinset fun _ : Fin (k - 1) =>
          Finset.Icc (1 : ℤ) ⌈s * ∑ i, X.sides i⌉).filter
        (fun h => inScaledBox X s v h)).card : ℝ) - s ^ (k - 1 : ℕ) * X.volume| ≤
        C * s ^ (((k - 1 : ℕ) : ℤ) - 1))
    (h_ep : ∃ C : ℝ, 0 < C ∧ ∀ (q : ℕ) [NeZero q],
      ∀ (d : ℕ), d ∣ q → 1 < d →
        |∏ p ∈ d.primeFactors,
          ((1 : ℝ) - (Ω p).card / p) * (p : ℝ) ^ (-ε)| ≤ C) :
    ∃ δ : ℝ, 0 < δ ∧ ∀ (X : Box (k - 1)), ∃ C : ℝ, 0 < C ∧
      ∀ (q : ℕ) [NeZero q] (_hq_sq : Squarefree q),
        |kCorrelation (crtSubset q Ω) X - X.volume| ≤
          C * ((q : ℝ) / (crtSubset q Ω).card) ^ (-δ) := by
  -- The deviation synthesis now returns ∃ δ > 0, and we propagate this δ through
  -- the cancellation argument. The key change: the old bound was O(s^{-1}), now
  -- it is O(s^{-δ}) for some δ > 0 that may be < 1 when k = 2.
  -- TODO: Adapt the algebraic cancellation proof to the general s^{-δ} form.
  -- For now, this is sorry'd pending the k=2 Cauchy-Schwarz completion.
  sorry

/-- **Fluctuation bound** (core of Proposition 3.6): Under the well-distribution hypothesis,
the error `|R_k(X) - vol(X)|` is bounded by `C · s_q^{-δ}` for some `δ > 0`.

This is the core mathematical content of Proposition 3.6 from Granville–Kurlberg
(arXiv:math/0412135v2, §3.2). The proof combines:
1. **Lattice point box bound** (`lattice_point_box_bound`): approximation of lattice
   point counts in scaled boxes.
2. **Euler product convergence** (`euler_product_convergence`): boundedness of the
   multiplicative error product under WD.
3. **Complete period cancellation** (`complete_period_cancellation_apply`): cancellation
   from `tupleCount_cons_deviation_sum_zero` applied to box sums. -/
private lemma fluctuation_bound
    (ε : ℝ) (hε : 0 < ε) (k : ℕ) (hk : 2 ≤ k)
    (Ω : ∀ p : ℕ, Finset (ZMod p))
    (hΩ : ∀ p, p.Prime → (Ω p).Nonempty)
    (hWD : ∀ (p : ℕ) [Fact p.Prime], WellDistributed ε p (Ω p) k)
    (hsp : ∀ (p : ℕ), p.Prime →
      (p : ℝ) / (Ω p).card ≤ (p : ℝ) ^ (lambdaExponent k - ε)) :
    ∃ δ : ℝ, 0 < δ ∧ ∀ (X : Box (k - 1)), ∃ C : ℝ, 0 < C ∧
      ∀ (q : ℕ) [NeZero q] (_hq_sq : Squarefree q),
        |kCorrelation (crtSubset q Ω) X - X.volume| ≤
          C * ((q : ℝ) / (crtSubset q Ω).card) ^ (-δ) := by
  -- Step 1: Obtain the lattice point box bound
  have h_lp : ∀ (X : Box (k - 1)), _ := fun X => lattice_point_box_bound (k - 1) X
  -- Step 2: Obtain the Euler product convergence bound
  have h_ep := euler_product_convergence ε hε k hk Ω hΩ hWD hsp
  -- Step 3: Apply the complete period cancellation to combine these bounds.
  -- The δ now comes from the deviation synthesis, not hardcoded to 1.
  obtain ⟨δ, hδ_pos, h_cpc⟩ := complete_period_cancellation_apply ε hε k hk Ω hΩ hWD hsp h_lp h_ep
  exact ⟨δ, hδ_pos, h_cpc⟩

/-- **Proposition 3.6** (simplified form): Under the well-distribution hypothesis (1) with
parameter `ε`, the error in the `k`-level correlation is bounded by `C · s_q^{-δ}` for
some `δ > 0` depending on `ε`, and some constant `C > 0` depending on the box `X`.

Note: The original formalization had issues that have been corrected:
1. `kCorrelation` now filters by `inScaledBox` (matching the paper's definition)
2. The bound includes a box-dependent constant `C`
3. Non-emptiness of `Ω p` for primes `p` is explicitly required -/
theorem error_bound_simplified
    (ε : ℝ) (hε : 0 < ε) (k : ℕ) (hk : 2 ≤ k)
    (Ω : ∀ p : ℕ, Finset (ZMod p))
    (hΩ : ∀ p, p.Prime → (Ω p).Nonempty)
    (hWD : ∀ (p : ℕ) [Fact p.Prime], WellDistributed ε p (Ω p) k)
    (hsp : ∀ (p : ℕ), p.Prime →
      (p : ℝ) / (Ω p).card ≤ (p : ℝ) ^ (lambdaExponent k - ε)) :
    ∃ δ : ℝ, 0 < δ ∧ ∀ (X : Box (k - 1)), ∃ C : ℝ, 0 < C ∧
      ∀ (q : ℕ) [NeZero q] (_hq_sq : Squarefree q),
        |kCorrelation (crtSubset q Ω) X - X.volume| ≤
          C * ((q : ℝ) / (crtSubset q Ω).card) ^ (-δ) := by
  exact fluctuation_bound ε hε k hk Ω hΩ hWD hsp

/-! ### Theorem 3.7 (= Theorem 1.1, precise version) -/

/-
**Theorem 3.7** (Theorem 1.1, precise version): Fix `ε > 0` and integer `K`.
Suppose subsets `Ω_p ⊆ ℤ/pℤ` satisfy:
1. `s_p ≤ p^{λ_K - ε}` for all primes `p`,
2. Hypothesis (1) holds for all `k ≤ K` with distinct `h` mod `p`.

Then for `k ≤ K` and any box `X`, the `k`-level correlation satisfies
`R_k(X, Ω_q) = vol(X) + o_{X,k}(1)` as `s_q → ∞`.

This follows from Proposition 3.6 and the lemma below.
-/
theorem mainTheorem_precise
    (ε : ℝ) (hε : 0 < ε) (K : ℕ) (hK : 2 ≤ K)
    (Ω : ∀ p : ℕ, Finset (ZMod p))
    (hΩ : ∀ p, p.Prime → (Ω p).Nonempty)
    (hWD : ∀ (p : ℕ) [Fact p.Prime] (k : ℕ), k ≤ K →
      WellDistributed ε p (Ω p) k)
    (hsp : ∀ (p : ℕ), p.Prime →
      (p : ℝ) / (Ω p).card ≤ (p : ℝ) ^ (lambdaExponent K - ε)) :
    ∀ (k : ℕ), 2 ≤ k → k ≤ K → ∀ (X : Box (k - 1)),
      ∃ δ : ℝ, 0 < δ ∧ ∃ C : ℝ, 0 < C ∧ ∀ (q : ℕ) [NeZero q] (_hq_sq : Squarefree q),
        |kCorrelation (crtSubset q Ω) X - X.volume| ≤
          C * ((q : ℝ) / (crtSubset q Ω).card) ^ (-δ) := by
  intro k hk2 hk_le X
  have h_lam : lambdaExponent K ≤ lambdaExponent k := by
    unfold lambdaExponent; split_ifs ;
    any_goals linarith;
    any_goals rw [ div_le_div_iff₀ ] <;> nlinarith [ Real.sqrt_nonneg 17, Real.sq_sqrt ( show 0 ≤ 17 by norm_num ), show ( k : ℝ ) ≥ 2 by norm_cast, show ( K : ℝ ) ≥ k by norm_cast ];
    · omega;
    · omega;
    · rw [ div_le_div_iff₀ ] <;> nlinarith [ Real.sqrt_nonneg 17, Real.sq_sqrt ( show 0 ≤ 17 by norm_num ), show ( K : ℝ ) ≥ 4 by norm_cast; omega ];
    · rw [ div_le_div_iff₀ ] <;> linarith [ show ( K : ℝ ) ≥ 4 by norm_cast; omega ]
  have hsp_k : ∀ (p : ℕ), p.Prime → (p : ℝ) / (Ω p).card ≤ (p : ℝ) ^ (lambdaExponent k - ε) := by
    intro p hp
    have h_base := hsp p hp
    have h_pow : (p : ℝ) ^ (lambdaExponent K - ε) ≤ (p : ℝ) ^ (lambdaExponent k - ε) := by
      apply Real.rpow_le_rpow_of_exponent_le (by exact_mod_cast hp.one_le)
      linarith
    exact le_trans h_base h_pow
  have := error_bound_simplified ε hε k hk2 Ω hΩ (fun p _ => hWD p k hk_le) hsp_k
  exact ⟨this.choose, this.choose_spec.1, this.choose_spec.2 X⟩

/-
**Lemma following Theorem 3.7**: Under the well-distribution hypothesis with suitable
bounds on `s_p`, the `p`-th factor in each Euler product is `s_p^{o(1)}`, so each
Euler product is `s_q^{o(1)}` and `Error ≤ s_q^{-δ}` for some `δ > 0`.

Choose δ = ε (positive by hε). Then for any prime p, subset Ω, assuming WellDistributed ε p Ω k, the spacing bound, and given injective h:

Case 1: If Ω.card = 0, then epsilonError = 0 by the if-then-else in the definition, and |0| = 0 ≤ RHS (since RHS = (1 - 0) * p^(-ε) ≥ 0, because p^(-ε) ≥ 0).

Case 2: If Ω.card > 0: WellDistributed gives |tupleCount Ω h - expected| ≤ (1 - |Ω|/p) * p^(-ε) * expected, where expected = |Ω|^k / p^(k-1) > 0.

epsilonError = tupleCount/expected - 1, so |epsilonError| = |tupleCount/expected - 1| = |tupleCount - expected| / expected (using the fact that for b > 0, |a/b - 1| = |a - b| / b).

From WellDistributed: |tupleCount - expected| / expected ≤ (1 - |Ω|/p) * p^(-ε).

Key steps:
1. refine ⟨ε, hε, fun p _ Ω hWD _ h hInj => ?_⟩
2. Unfold epsilonError, split on Ω.card = 0.
3. If Ω.card = 0: simp.
4. If Ω.card ≠ 0: let E := expected, show E > 0, then rewrite |.../E - 1| as |... - E|/E, then apply div_le_iff and use WellDistributed.
-/
theorem error_from_euler_products
    (ε : ℝ) (hε : 0 < ε) (k : ℕ) (_ : 2 ≤ k) :
    ∃ δ : ℝ, 0 < δ ∧ ∀ (p : ℕ) [Fact p.Prime] (Ω : Finset (ZMod p)),
      WellDistributed ε p Ω k →
      (p : ℝ) / Ω.card ≤ (p : ℝ) ^ (lambdaExponent k - 2 * ε) →
        ∀ (h : Fin k → ZMod p), Function.Injective h →
          |epsilonError Ω h| ≤ (1 - Ω.card / p : ℝ) * (p : ℝ) ^ (-ε) := by
  refine' ⟨ ε, hε, _ ⟩;
  intro p hp Ω hWD hsp h hInj
  unfold epsilonError
  simp +decide;
  split_ifs <;> simp_all +decide [ WellDistributed ];
  · positivity;
  · convert div_le_div_of_nonneg_right ( hWD.1 h hInj ) ( show 0 ≤ ( ( Ω.card : ℝ ) ^ k / p ^ ( k - 1 ) ) by positivity ) using 1;
    · rw [ div_sub_one, abs_div ] <;> norm_num [ show ( Ω.card : ℝ ) ≠ 0 by exact Nat.cast_ne_zero.mpr <| ne_of_gt <| Finset.card_pos.mpr <| Finset.nonempty_iff_ne_empty.mpr ‹_› ];
      · rw [ abs_of_nonneg ( by positivity : 0 ≤ ( Ω.card : ℝ ) ^ k / p ^ ( k - 1 ) ) ];
      · exact fun h => absurd h hp.1.ne_zero;
    · rw [ mul_div_cancel_right₀ _ ( ne_of_gt ( div_pos ( pow_pos ( Nat.cast_pos.mpr ( Finset.card_pos.mpr ( Finset.nonempty_of_ne_empty ‹_› ) ) ) _ ) ( pow_pos ( Nat.cast_pos.mpr hp.1.pos ) _ ) ) ) ]

/- Corollary 1.2 (d-th powers well-distributed) has been removed from scope.
   The target applications (Krafft multi-residue sieve and n²+1 quadratic sieve)
   rely strictly on exact combinatorial bounds or quadratic characters, which are
   covered by the hyperelliptic curve machinery already formalized in RHC/. -/


/-! ### Special case: Hooley's theorem (integers coprime to q) -/

/-- **Hooley's theorem** (recovered from Theorem 1.1): For `Ω_p = {x ∈ ℤ/pℤ : x ≠ 0}`
(integers coprime to `p`), the tuple counting function satisfies
`N_k(h, Ω_p) = p - k` for injective `h`. -/
theorem coprime_tupleCount (p : ℕ) [hp : Fact p.Prime] (k : ℕ)
    (h : Fin k → ZMod p) (hh : Function.Injective h) :
    tupleCount (univ.filter (· ≠ (0 : ZMod p))) h = p - k := by
  by_contra h_contra
  have h_set : Finset.filter (fun t : ZMod p => ∀ i, t + h i ≠ 0) Finset.univ =
      Finset.univ \ Finset.image (fun i => -h i) Finset.univ := by
    grind
  unfold tupleCount at h_contra
  simp_all +decide [Finset.card_sdiff]
  exact h_contra (by
    rw [Finset.card_image_of_injective _ fun i j hij => by simpa [hh.eq_iff] using hij]
    simp +decide)

end PoissonCRT
