/-
Copyright (c) 2026 Fernando Portela. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Fernando Portela
-/

/-
Portions of this file were generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.28.0
Mathlib version: 8f9d9cff6bd728b17a24e163c9402775d9e6a365

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

module
public import PoissonViaCRT.Defs
import PoissonViaCRT.CRTMultiplicativity
import PoissonViaCRT.ProductDifference
import PoissonViaCRT.LargeDivisorHelpers
import PoissonViaCRT.SmallDivisorHelpers
import PoissonViaCRT.TupleCount
import PoissonViaCRT.EulerWeights
import PoissonViaCRT.L1DeviationSynthesis
import PoissonViaCRT.L2DeviationSynthesis
import PoissonViaCRT.FourierANOVA

set_option linter.unusedVariables false

/-!
# Möbius Synthesis

This file assembles the final deviation bound (Proposition 3.6)
using the spatial synthesis / inclusion-exclusion strategy.
The proof combines:
- CRT multiplicativity of the counting function
  (`counting_function_multiplicative`)
- Product-difference expansion (`prod_sub_prod_expansion`)
- Triangle inequality (`Finset.abs_sum_le_sum_abs`)
- Small-divisor bounds via residue multiplicity estimates
  (`deviation_small_divisors` in `SmallDivisorHelpers.lean`)
- Large-divisor bounds via pointwise deviation estimates
  (`deviation_large_divisors`)
- Euler weight bounds (`EulerWeights.lean`)

## Main results

* `deviation_product_difference` — algebraic identity
  expressing the per-element deviation as a sum over
  nonempty subsets of prime factors of `q`.
* `deviation_triangle_bound` — triangle inequality bound
  on the absolute deviation.
* `deviation_final_synthesis` — the `q`-independent uniform
  bound `|D(q)| ≤ K · s(q)^{−δ}`.
* `deviation_uniform_exponent` — variant where the decay
  exponent `δ` is chosen independently of the box.
-/

open Finset BigOperators Classical

namespace PoissonCRT

/-! ## Auxiliary definitions -/

-- `localMean` and `localCount` are defined in `DeviationBoundHelper.lean`.

/-! ## Helper lemmas -/

/-- The subtype product from `counting_function_multiplicative`
equals the `Finset` product of `localCount` over the prime
factors of squarefree `q`. This identity converts between
the CRT-based and the per-prime representations of the
counting function. -/
lemma tupleCount_eq_prod_localCount {k : ℕ} (q : ℕ) [NeZero q] (hq : Squarefree q)
    (Ω : ∀ p : ℕ, Finset (ZMod p)) (h : Fin k → ZMod q) :
    (tupleCount (crtSubset q Ω) h : ℝ) = ∏ p ∈ q.primeFactors, localCount Ω q h p := by
  rw [ counting_function_multiplicative, Nat.cast_prod ];
  · refine' Finset.prod_bij ( fun p hp => p.val ) _ _ _ _ <;> simp +decide [ localCount ];
  · assumption

-- `globalMean_eq_prod_localMean` is now in `SmallDivisorHelpers.lean`.

/-! ## 1. Product-Difference Decomposition -/

/-- **Product-difference decomposition of the counting function deviation (divisor formulation).**
For squarefree `q`, the deviation `N_k(h, Ω_q) - μ` at each element `h` decomposes
as a sum over squarefree divisors `d ∣ q` with `d > 1`:

$N_k(h) - \mu = \sum_{d \mid q,\, d > 1}
  \prod_{p \mid d} (N_k(h \bmod p) - \mu_p) \cdot \prod_{p \mid q,\, p \nmid d} \mu_p$

This is a strict algebraic rewrite combining `counting_function_multiplicative`
with `prod_sub_prod_expansion`, transported to divisor sums via
`sum_nonempty_powerset_eq_sum_nontrivial_divisors`. -/
theorem deviation_product_difference {k : ℕ} (q : ℕ) [NeZero q]
    (hq : Squarefree q)
    (Ω : ∀ p : ℕ, Finset (ZMod p))
    (h : Fin k → ZMod q) :
    (tupleCount (crtSubset q Ω) h : ℝ) -
      ∏ p ∈ q.primeFactors, localMean k Ω p =
    ∑ d ∈ q.divisors.filter (1 < ·),
      (∏ p ∈ d.primeFactors, (localCount Ω q h p - localMean k Ω p)) *
      ∏ p ∈ q.primeFactors \ d.primeFactors, localMean k Ω p := by
  rw [tupleCount_eq_prod_localCount q hq Ω h]
  rw [prod_sub_prod_expansion (localCount Ω q h) (localMean k Ω) q.primeFactors]
  exact sum_nonempty_powerset_eq_sum_nontrivial_divisors q hq _

/-! ## 2. Triangle Inequality Bound -/

/-- **Triangle inequality on the product-difference expansion (divisor formulation).**
The absolute value of the deviation is bounded by the sum of absolute values
of the individual divisor terms. -/
theorem deviation_triangle_bound {k : ℕ} (q : ℕ) [NeZero q]
    (hq : Squarefree q)
    (Ω : ∀ p : ℕ, Finset (ZMod p))
    (h : Fin k → ZMod q) :
    |(tupleCount (crtSubset q Ω) h : ℝ) -
      ∏ p ∈ q.primeFactors, localMean k Ω p| ≤
    ∑ d ∈ q.divisors.filter (1 < ·),
      |(∏ p ∈ d.primeFactors, (localCount Ω q h p - localMean k Ω p))| *
      |∏ p ∈ q.primeFactors \ d.primeFactors, localMean k Ω p| := by
  rw [deviation_product_difference q hq Ω h]
  exact le_trans (Finset.abs_sum_le_sum_abs _ _)
    (Finset.sum_le_sum fun T _ => le_of_eq (abs_mul _ _))

/-! ## 3. Final Möbius Synthesis -/

/-- When |Ω_q| = 0, the deviation expression is zero. -/
private lemma deviation_zero_of_card_zero {k : ℕ} (q : ℕ) [NeZero q]
    (Ω : ∀ p : ℕ, Finset (ZMod p)) (X : Box (k - 1))
    (h0 : (crtSubset q Ω).card = 0) :
    let Ω_q := crtSubset q Ω
    let s := (q : ℝ) / Ω_q.card
    |(1 / (Ω_q.card : ℝ)) *
      ∑ h ∈ ((Fintype.piFinset fun _ : Fin (k - 1) =>
          Finset.Icc (1 : ℤ) ⌈s * ∑ i, X.sides i⌉).filter
        (fun h => inScaledBox X s (fun _ => 0) h)),
      ((tupleCount Ω_q (Fin.cons (0 : ZMod q) fun i => (h i : ZMod q)) : ℝ) -
        (Ω_q.card : ℝ) ^ k / (q : ℝ) ^ (k - 1))| * s = 0 := by
  simp +decide [h0]

/-
When |Ω_q| = q (all of ZMod q), the deviation is zero.
-/
private lemma deviation_zero_of_card_eq_q {k : ℕ} (hk : 2 ≤ k) (q : ℕ) [NeZero q]
    (Ω : ∀ p : ℕ, Finset (ZMod p)) (X : Box (k - 1))
    (hfull : (crtSubset q Ω).card = q) :
    let Ω_q := crtSubset q Ω
    let s := (q : ℝ) / Ω_q.card
    |(1 / (Ω_q.card : ℝ)) *
      ∑ h ∈ ((Fintype.piFinset fun _ : Fin (k - 1) =>
          Finset.Icc (1 : ℤ) ⌈s * ∑ i, X.sides i⌉).filter
        (fun h => inScaledBox X s (fun _ => 0) h)),
      ((tupleCount Ω_q (Fin.cons (0 : ZMod q) fun i => (h i : ZMod q)) : ℝ) -
        (Ω_q.card : ℝ) ^ k / (q : ℝ) ^ (k - 1))| * s = 0 := by
  simp_all;
  rw [ Finset.sum_congr rfl fun x hx => by rw [ show tupleCount ( crtSubset q Ω ) ( Fin.cons 0 fun i => ( x i : ZMod q ) ) = q from by
                                                  convert tupleCount_univ ( Fin.cons 0 fun i => ( x i : ZMod q ) );
                                                  exact Finset.eq_of_subset_of_card_le ( Finset.subset_univ _ ) ( by aesop ) ] ];
  cases k <;> simp_all +decide [ pow_succ, mul_div_cancel_left₀, NeZero.ne ]

/-
For a single q with |Ω_q| > 0, the deviation expression is bounded by a
specific value (possibly depending on q).
-/
private lemma deviation_bound_single {k : ℕ} (hk : 2 ≤ k) (q : ℕ) [NeZero q]
    (Ω : ∀ p : ℕ, Finset (ZMod p)) (X : Box (k - 1))
    (hcard : 0 < (crtSubset q Ω).card)
    (hle : (crtSubset q Ω).card ≤ q) :
    let Ω_q := crtSubset q Ω
    let s := (q : ℝ) / Ω_q.card
    |(1 / (Ω_q.card : ℝ)) *
      ∑ h ∈ ((Fintype.piFinset fun _ : Fin (k - 1) =>
          Finset.Icc (1 : ℤ) ⌈s * ∑ i, X.sides i⌉).filter
        (fun h => inScaledBox X s (fun _ => 0) h)),
      ((tupleCount Ω_q (Fin.cons (0 : ZMod q) fun i => (h i : ZMod q)) : ℝ) -
        (Ω_q.card : ℝ) ^ k / (q : ℝ) ^ (k - 1))| * s ≤
    2 * ((Fintype.piFinset fun _ : Fin (k - 1) =>
        Finset.Icc (1 : ℤ) ⌈s * ∑ i, X.sides i⌉).filter
      (fun h => inScaledBox X s (fun _ => 0) h)).card * s := by
  refine' mul_le_mul_of_nonneg_right _ ( by positivity );
  rw [ abs_mul, abs_of_nonneg ( by positivity ) ];
  rw [ div_mul_eq_mul_div, div_le_iff₀ ] <;> norm_cast;
  refine' le_trans ( mul_le_mul_of_nonneg_left ( Finset.abs_sum_le_sum_abs _ _ ) zero_le_one ) _;
  refine' le_trans ( mul_le_mul_of_nonneg_left ( Finset.sum_le_sum fun x hx => _ ) zero_le_one ) _;
  use fun x => 2 * #(crtSubset q Ω);
  · convert individual_deviation_bound ( crtSubset q Ω ) ( k - 1 ) hcard ( mod_cast hle )
      ( fun i => x i ) using 1;
    cases k <;> aesop;
  · norm_num [ mul_assoc, mul_comm, mul_left_comm ]

/-! ### Helpers for deviation_final_synthesis -/

/-
The spacing hypothesis at p = 2 forces ε ≤ lambdaExponent k. When ε > lambdaExponent k,
the hypotheses are inconsistent.
-/
private lemma spacing_forces_eps_le_lambda (ε : ℝ) (hε : 0 < ε) (k : ℕ) (hk : 2 ≤ k)
    (Ω : ∀ p : ℕ, Finset (ZMod p))
    (hΩ : ∀ p, p.Prime → (Ω p).Nonempty)
    (hsp : ∀ (p : ℕ), p.Prime →
      (p : ℝ) / (Ω p).card ≤ (p : ℝ) ^ (lambdaExponent k - ε)) :
    ε ≤ lambdaExponent k := by
  have := hsp 2 Nat.prime_two;
  contrapose! this;
  refine lt_of_lt_of_le ( Real.rpow_lt_rpow_of_exponent_lt ( by norm_num ) ( sub_neg.mpr this ) ) ?_
  norm_num
  rw [ one_le_div ] <;> norm_cast;
  · exact le_trans ( Finset.card_le_univ _ ) ( by norm_num );
  · exact Finset.card_pos.mpr ( hΩ 2 Nat.prime_two )

/-
When ε = lambdaExponent k, all local subsets are full, so the deviation is zero.
-/
private lemma all_full_of_eps_eq_lambda (ε : ℝ) (k : ℕ) (hk : 2 ≤ k)
    (Ω : ∀ p : ℕ, Finset (ZMod p))
    (hΩ : ∀ p, p.Prime → (Ω p).Nonempty)
    (hsp : ∀ (p : ℕ), p.Prime →
      (p : ℝ) / (Ω p).card ≤ (p : ℝ) ^ (lambdaExponent k - ε))
    (heq : ε = lambdaExponent k) :
    ∀ (p : ℕ), p.Prime → (Ω p).card = p := by
  intro p pp; specialize hsp p pp; simp_all +decide [ div_le_iff₀ ] ;
  haveI := Fact.mk pp; exact le_antisymm ( le_trans ( Finset.card_le_univ _ ) ( by norm_num ) ) hsp;

/-
When all local subsets are full (Ω_p = ZMod p for all primes p), the CRT subset
is the full set ZMod q.
-/
private lemma crtSubset_full_of_all_full (q : ℕ) [NeZero q]
    (Ω : ∀ p : ℕ, Finset (ZMod p))
    (hall : ∀ (p : ℕ), p.Prime → (Ω p).card = p) :
    (crtSubset q Ω).card = q := by
  nontriviality;
  convert Finset.card_univ;
  all_goals try infer_instance;
  · ext x;
    simp +decide [ crtSubset ];
    intro p pp dp _; specialize hall p pp; haveI := Fact.mk pp
    rw [ Finset.eq_of_subset_of_card_le ( Finset.subset_univ ( Ω p ) ) ] ; simp_all only [mem_univ]
    simp +decide [ hall, ZMod.card ];
  · cases q <;> aesop

/-! ### Tuple-Gamma Bridge Lemmas -/

/-
When `(Ω p).card = p` and `p` is prime, `Ω p = Finset.univ`.
-/
private lemma omegaFull_eq_univ {p : ℕ} [Fact p.Prime] (Ω : Finset (ZMod p))
    (h_full : Ω.card = p) : Ω = Finset.univ := by
  exact Finset.eq_of_subset_of_card_le ( Finset.subset_univ Ω )
    ( by simp +decide [ h_full, Finset.card_univ ] )

/-
`tupleCount univ g = Fintype.card (ZMod p)` for any `g`.
-/
private lemma tupleCount_univ_eq {p : ℕ} [NeZero p] (g : Fin k → ZMod p) :
    tupleCount (Finset.univ : Finset (ZMod p)) g = Fintype.card (ZMod p) := by
  unfold tupleCount; aesop;

/-
`localMean k Ω p = p` when `(Ω p).card = p` and `k ≥ 1`.
-/
private lemma localMean_eq_cast_of_full {k : ℕ} (hk : 1 ≤ k) (p : ℕ)
    (Ω : ∀ p : ℕ, Finset (ZMod p)) (h_full : (Ω p).card = p) :
    localMean k Ω p = (p : ℝ) := by
  unfold localMean; by_cases hp : p = 0 <;> simp_all;
  · exact Or.inl ( by linarith );
  · rw [ div_eq_iff ( by positivity ), ← pow_succ', Nat.sub_add_cancel hk ]

/-- When `Ω p` is the full residue set `ZMod p` (i.e.,
`(Ω p).card = p`), the local deviation
`localCount − localMean` vanishes for any tuple `h`.
This is the trivial case in the inclusion-exclusion:
full local sets contribute zero deviation. -/
lemma localCount_sub_localMean_eq_zero_of_not_dvd {k : ℕ} (hk : 1 ≤ k) (q : ℕ) [NeZero q]
    (p : ℕ) (hp : p ∈ q.primeFactors) (Ω : ∀ p : ℕ, Finset (ZMod p))
    (h : Fin k → ℤ) (_h_dist : ∀ i j, i ≠ j → h i ≠ h j)
    (_h_no_col : ∀ i j, i ≠ j → ¬(p ∣ Int.natAbs (h i - h j)))
    (h_full : (Ω p).card = p) :
    localCount Ω q (fun i => (h i : ZMod q)) p - localMean k Ω p = 0 := by
  unfold localCount; simp +decide [ *, localMean_eq_cast_of_full ];
  haveI : Fact p.Prime := ⟨ Nat.prime_of_mem_primeFactors hp ⟩ ;
  rw [ show Ω p = Finset.univ from ?_ ];
  · rw [ sub_eq_zero, tupleCount_univ_eq ] ; norm_num [ ZMod.card ];
  · exact Finset.eq_of_subset_of_card_le ( Finset.subset_univ _ )
      ( by simp +decide [ h_full, Finset.card_univ ] )

/-- If the product of local deviations over `T ⊆ q.primeFactors` is nonzero and each
`Ω p` for `p ∈ T` is the full set, then every prime `p ∈ T` divides some pairwise
difference `|h i - h j|` with `i ≠ j`. -/
lemma prod_diff_ne_zero_implies_dvd {k : ℕ} (hk : 1 ≤ k) (q : ℕ) [NeZero q]
    (T : Finset ℕ) (hT : T ⊆ q.primeFactors)
    (Ω : ∀ p : ℕ, Finset (ZMod p))
    (hΩ_full : ∀ p ∈ T, (Ω p).card = p)
    (h : Fin k → ℤ) (h_dist : ∀ i j, i ≠ j → h i ≠ h j)
    (h_prod : ∏ p ∈ T, (localCount Ω q (fun i => (h i : ZMod q)) p -
      localMean k Ω p) ≠ 0) :
    ∀ p ∈ T, ∃ i j, i ≠ j ∧ p ∣ Int.natAbs (h i - h j) := by
  intro p hp
  by_contra h_no_col
  push_neg at h_no_col
  exact h_prod (Finset.prod_eq_zero hp
    (localCount_sub_localMean_eq_zero_of_not_dvd hk q p (hT hp) Ω h h_dist h_no_col
      (hΩ_full p hp)))

/-! ### Large-divisor bounds

  **Status:** `deviation_large_divisors` is now proved using the per-T L2 bound
  (`per_T_deviation_le_combinedEulerWeight` from `L1DeviationSynthesis.lean`)
  combined with `tail_sum_decay` (relocated to `EulerWeights.lean`).

  The per-T bound reduces each `|inner_T|` to `C · ∏_{p ∈ T} combinedEulerWeight`,
  after which the Rankin-trick tail sum gives the `O(s^{-ε/2})` decay.
-/

/-- **Combined Euler weight tail-sum bound (divisor formulation).**

The sum of `globalModifiedEulerWeight d` over squarefree divisors `d ∣ q` with `d > 1` and
`(d : ℝ) > s` is bounded by `K · s^{−ε/2}`. This is the divisor-sum reformulation of the
Rankin-trick tail-sum bound, using `modified_tail_sum_decay` from `EulerWeights.lean`.

**Note on the previous formulation:** An earlier version of this lemma attempted to bound a
more complex summand involving a `T_small / T_large` prime-factor split, the CRT prefactor
`q^{k−1} / |Ω_q|^k`, and the complement product `∏_{q ∖ T} localMean`. That formulation is
**mathematically false**: when `|Ω_p| = p` for all primes `p`, each summand equals 1 (after
prefactor absorption), but the number of contributing subsets grows as `2^{ω(q)}`, which
exceeds any fixed `K · s^{−ε/2}`. The correct approach uses `globalModifiedEulerWeight`
directly, which vanishes when `|Ω_p| = p` and is summable via the Rankin trick otherwise. -/
private lemma modified_large_divisor_series_bound (ε : ℝ) (hε : 0 < ε) (k : ℕ) (hk : 2 ≤ k)
    (hε_lt : ε < lambdaExponent k)
    (C_gamma : ℝ) (hC_gamma : 0 ≤ C_gamma)
    (Ω : ∀ p : ℕ, Finset (ZMod p))
    (hrp : ∀ (p : ℕ), p.Prime → 1 - (Ω p).card / (p : ℝ) ≤ k / (p : ℝ)) :
    ∃ K_large : ℝ, 0 < K_large ∧ ∀ (q : ℕ) [NeZero q] (_ : Squarefree q) (s : ℝ) (_ : 1 ≤ s),
      ∑ d ∈ (q.divisors.filter (1 < ·)).filter (fun (d : ℕ) => ¬((d : ℝ) ≤ s)),
        globalModifiedEulerWeight ε k C_gamma Ω d ≤
        K_large * s ^ (-(ε / 2)) := by
  have hε2 : ε ≤ 1 := hε_lt.le.trans (lambdaExponent_le_one k)
  simp only [globalModifiedEulerWeight]
  exact modified_tail_sum_decay ε hε hε2 k hk C_gamma hC_gamma Ω hrp

/-
Per-`T` pointwise bound for the large-divisor case.
-/
private lemma large_divisor_per_T_bound (ε : ℝ) (hε : 0 < ε) (k : ℕ) (hk : 2 ≤ k)
    (Ω : ∀ p : ℕ, Finset (ZMod p))
    (hΩ : ∀ p, p.Prime → (Ω p).Nonempty)
    (hWD : ∀ (p : ℕ) [Fact p.Prime], WellDistributed ε p (Ω p) k)
    (hsp : ∀ (p : ℕ), p.Prime →
      (p : ℝ) / (Ω p).card ≤ (p : ℝ) ^ (lambdaExponent k - ε))
    (hrp : ∀ (p : ℕ), p.Prime → 1 - (Ω p).card / (p : ℝ) ≤ k / (p : ℝ))
    (hε_lt : ε < lambdaExponent k)
    (X : Box (k - 1))
    (C_lp : ℝ) (hC_lp_pos : 0 < C_lp)
    (hC_lp : ∀ (v : Fin (k - 1) → ℝ), (∀ i, 0 ≤ v i ∧ v i ≤ 1) → ∀ (s : ℝ), 1 ≤ s →
      |(((Fintype.piFinset fun _ : Fin (k - 1) =>
          Finset.Icc (1 : ℤ) ⌈s * ∑ i, X.sides i⌉).filter
        (fun h => inScaledBox X s v h)).card : ℝ) - s ^ (k - 1 : ℕ) * X.volume| ≤
        C_lp * s ^ (((k - 1 : ℕ) : ℤ) - 1))
    (q : ℕ) [NeZero q] (_ : Squarefree q)
    (T : Finset ℕ)
    (_ : T ∈ (q.primeFactors.powerset.filter (· ≠ ∅)).filter
          (fun (T : Finset ℕ) => ¬((∏ p ∈ T, (p : ℝ)) ≤ (q : ℝ) / (crtSubset q Ω).card))) :
    let s := (q : ℝ) / (crtSubset q Ω).card
    let B_max := ⌈s * ∑ i, X.sides i⌉₊
    let T_small := T.filter (· ≤ B_max)
    let T_large := T.filter (B_max < ·)
    |∑ h ∈ ((Fintype.piFinset fun _ : Fin (k - 1) =>
          Finset.Icc (1 : ℤ) ⌈s * ∑ i, X.sides i⌉).filter
        (fun h => inScaledBox X s (fun _ => 0) h)),
      (1 / ((crtSubset q Ω).card : ℝ)) *
        ((∏ p ∈ T, (localCount Ω q
            (Fin.cons (0 : ZMod q) fun i => (h i : ZMod q)) p -
            localMean k Ω p)) *
          ∏ p ∈ q.primeFactors \ T, localMean k Ω p)| ≤
    (X.volume + C_lp) *
      (((q : ℝ) ^ (k - 1) / ((crtSubset q Ω).card : ℝ) ^ k) *
        ∏ p ∈ q.primeFactors \ T, localMean k Ω p) *
      (∏ p ∈ T_small, (p : ℝ)) *
      (∏ p ∈ T_large, (1 - (Ω p).card / (p : ℝ)) * (p : ℝ) ^ (-ε) * localMean k Ω p) := by
  rename_i hT hT';
  refine' le_trans ( Finset.abs_sum_le_sum_abs _ _ ) _;
  refine' le_trans ( Finset.sum_le_sum fun x hx => _ ) _;
  use fun x => ( 1 / ( # ( crtSubset q Ω ) : ℝ ) ) * ( ∏ p ∈ T.filter ( · ≤ ⌈ ( q : ℝ ) / ( # ( crtSubset q Ω ) : ℝ ) * ∑ i, X.sides i⌉₊ ), ( p : ℝ ) ) * ( ∏ p ∈ T.filter ( ⌈ ( q : ℝ ) / ( # ( crtSubset q Ω ) : ℝ ) * ∑ i, X.sides i⌉₊ < · ), ( 1 - ( # ( Ω p ) : ℝ ) / p ) * ( p : ℝ ) ^ ( -ε ) * localMean k Ω p ) * ( ∏ p ∈ q.primeFactors \ T, localMean k Ω p );
  · have := deviation_prod_pointwise_le ε ( by omega ) Ω q X ( ( q : ℝ ) / ( # ( crtSubset q Ω ) : ℝ ) ) ( by
      exact div_pos ( Nat.cast_pos.mpr ( NeZero.pos q ) ) ( Nat.cast_pos.mpr ( Finset.card_pos.mpr ( by
        exact Finset.card_pos.mp ( by exact crtSubset_card_pos_aux Ω hΩ q ) ) ) ) ) ( by
      exact fun p hp => by rw [ Nat.sub_add_cancel ( by linarith ) ] ; exact hWD p; ) T ( by
      grind ) ( ⌈ ( q : ℝ ) / ( # ( crtSubset q Ω ) : ℝ ) * ∑ i, X.sides i⌉₊ ) rfl x ( by
      exact Finset.mem_filter.mp hx |>.2 ) ; simp_all +decide [ abs_mul, abs_of_nonneg ] ;
    rcases k with ( _ | _ | k ) <;> simp_all;
    rw [ abs_of_nonneg ( show 0 ≤ ∏ p ∈ q.primeFactors \ T, localMean ( k + 1 + 1 ) Ω p from Finset.prod_nonneg fun p hp => ?_ ) ];
    · simpa only [ mul_assoc ] using mul_le_mul_of_nonneg_right ( mul_le_mul_of_nonneg_left this ( by positivity ) ) ( Finset.prod_nonneg fun p hp => by unfold localMean; positivity );
    · exact div_nonneg ( pow_nonneg ( Nat.cast_nonneg _ ) _ ) ( pow_nonneg ( Nat.cast_nonneg _ ) _ );
  · simp +zetaDelta at *;
    convert mul_le_mul_of_nonneg_right ( scaled_box_card_le ( show 2 ≤ k from hk ) X C_lp hC_lp_pos hC_lp ( q / ( # ( crtSubset q Ω ) : ℝ ) ) _ ) _ using 1;
    · rw [ show ( q : ℝ ) ^ ( k - 1 ) = ( q : ℝ ) ^ ( k - 1 ) by rfl, show ( # ( crtSubset q Ω ) : ℝ ) ^ k = ( # ( crtSubset q Ω ) : ℝ ) ^ ( k - 1 ) * ( # ( crtSubset q Ω ) : ℝ ) by rw [ ← pow_succ, Nat.sub_add_cancel ( by linarith ) ] ] ; ring;
    · rw [ one_le_div ] <;> norm_cast;
      · exact le_trans ( Finset.card_le_univ _ ) ( by norm_num );
      · exact crtSubset_card_pos_aux Ω hΩ q;
    · refine' mul_nonneg _ _;
      · refine' mul_nonneg _ _;
        · exact mul_nonneg ( inv_nonneg.2 ( Nat.cast_nonneg _ ) )
            ( Finset.prod_nonneg fun _ _ => Nat.cast_nonneg _ )
        · refine' Finset.prod_nonneg fun p hp => mul_nonneg _ _;
          · exact mul_nonneg ( sub_nonneg.2 <| div_le_one_of_le₀ ( mod_cast by
              haveI := Fact.mk ( Nat.prime_of_mem_primeFactors ( hT'.1.1 ( Finset.mem_filter.mp hp |>.1 ) ) )
              exact le_trans ( Finset.card_le_univ _ ) ( by norm_num ) ; ) <| Nat.cast_nonneg _ ) <|
              Real.rpow_nonneg ( Nat.cast_nonneg _ ) _;
          · exact div_nonneg ( pow_nonneg ( Nat.cast_nonneg _ ) _ )
              ( pow_nonneg ( Nat.cast_nonneg _ ) _ );
      · refine' Finset.prod_nonneg fun p hp => _;
        exact localMean_nonneg k Ω p

/-- **Large-divisor contribution bound (divisor formulation).**

The sum of per-divisor deviation contributions over squarefree divisors `d ∣ q`
with `d > 1` and `(d : ℝ) > s` is bounded by `K₂ · s^{−ε/2}`. This formulation
replaces the earlier powerset-based version, using `globalModifiedEulerWeight`
and the transport lemma `sum_powerset_nonempty_filtered_eq`. -/
private lemma deviation_large_divisors (ε : ℝ) (hε : 0 < ε) (k : ℕ) (hk : 2 ≤ k)
    (Ω : ∀ p : ℕ, Finset (ZMod p))
    (hΩ : ∀ p, p.Prime → (Ω p).Nonempty)
    (hWD : ∀ (p : ℕ) [Fact p.Prime], WellDistributed ε p (Ω p) k)
    (hsp : ∀ (p : ℕ), p.Prime →
      (p : ℝ) / (Ω p).card ≤ (p : ℝ) ^ (lambdaExponent k - ε))
    (hrp : ∀ (p : ℕ), p.Prime → 1 - (Ω p).card / (p : ℝ) ≤ k / (p : ℝ))
    (hε_lt : ε < lambdaExponent k)
    (X : Box (k - 1))
    (C_lp : ℝ) (hC_lp_pos : 0 < C_lp)
    (hC_lp : ∀ (v : Fin (k - 1) → ℝ), (∀ i, 0 ≤ v i ∧ v i ≤ 1) → ∀ (s : ℝ), 1 ≤ s →
      |(((Fintype.piFinset fun _ : Fin (k - 1) =>
          Finset.Icc (1 : ℤ) ⌈s * ∑ i, X.sides i⌉).filter
        (fun h => inScaledBox X s v h)).card : ℝ) - s ^ (k - 1 : ℕ) * X.volume| ≤
        C_lp * s ^ (((k - 1 : ℕ) : ℤ) - 1)) :
    ∃ K₂ : ℝ, 0 < K₂ ∧ ∀ (q : ℕ) [NeZero q] (hq_sq : Squarefree q),
      let Ω_q := crtSubset q Ω
      let s := (q : ℝ) / Ω_q.card
      ∑ d ∈ (q.divisors.filter (1 < ·)).filter
            (fun (d : ℕ) => ¬((d : ℝ) ≤ s)),
        |∑ h ∈ ((Fintype.piFinset fun _ : Fin (k - 1) =>
            Finset.Icc (1 : ℤ) ⌈s * ∑ i, X.sides i⌉).filter
          (fun h => inScaledBox X s (fun _ => 0) h)),
        (1 / (Ω_q.card : ℝ)) *
          ((∏ p ∈ d.primeFactors, (localCount Ω q
              (Fin.cons (0 : ZMod q) fun i => (h i : ZMod q)) p -
              localMean k Ω p)) *
            ∏ p ∈ q.primeFactors \ d.primeFactors, localMean k Ω p)| ≤ K₂ * s ^ (-(ε / 2)) := by
  -- Step 1: Obtain the per-T L2 bound from L2DeviationSynthesis.
  obtain ⟨C_T, hC_T_pos, hC_T⟩ :=
    per_T_deviation_le_combinedEulerWeight ε hε k hk Ω hΩ hWD hsp hrp hε_lt X C_lp hC_lp_pos hC_lp
  -- Let C_gamma be an arbitrary non-negative constant for the modified weight. 0 works.
  have hC_gamma : 0 ≤ (0 : ℝ) := le_refl _
  -- Step 2: Obtain the tail-sum decay bound on ∑_d globalModifiedEulerWeight d.
  obtain ⟨K_large, hK_large_pos, hK_large⟩ := modified_large_divisor_series_bound ε hε k hk hε_lt 0 hC_gamma Ω hrp
  -- Step 3: Combine: the total is bounded by C_T · K_large · s^{-ε/2}.
  refine ⟨C_T * K_large, mul_pos hC_T_pos hK_large_pos, fun q _ hq_sq => ?_⟩
  have hs_ge : 1 ≤ (q : ℝ) / (crtSubset q Ω).card := by
    rw [one_le_div (Nat.cast_pos.mpr (Nat.pos_of_ne_zero (by
      have := crtSubset_card_pos_aux Ω hΩ q; aesop)))]
    norm_cast; exact le_trans (Finset.card_le_univ _) (by norm_num)
  -- Transport the divisor sum to powerset sum, apply per-T bounds, transport back.
  dsimp only []
  rw [← sum_nonempty_powerset_filtered_not_le_eq q hq_sq
    (fun T => |∑ h ∈ ((Fintype.piFinset fun _ : Fin (k - 1) =>
            Finset.Icc (1 : ℤ) ⌈(q : ℝ) / (crtSubset q Ω).card * ∑ i, X.sides i⌉).filter
          (fun h => inScaledBox X ((q : ℝ) / (crtSubset q Ω).card) (fun _ => 0) h)),
        (1 / ((crtSubset q Ω).card : ℝ)) *
          ((∏ p ∈ T, (localCount Ω q
              (Fin.cons (0 : ZMod q) fun i => (h i : ZMod q)) p -
              localMean k Ω p)) *
            ∏ p ∈ q.primeFactors \ T, localMean k Ω p)|)
    ((q : ℝ) / (crtSubset q Ω).card)]
  calc ∑ T ∈ (q.primeFactors.powerset.filter (· ≠ ∅)).filter
            (fun (T : Finset ℕ) => ¬((∏ p ∈ T, (p : ℝ)) ≤ (q : ℝ) / (crtSubset q Ω).card)),
        |∑ h ∈ ((Fintype.piFinset fun _ : Fin (k - 1) =>
            Finset.Icc (1 : ℤ) ⌈(q : ℝ) / (crtSubset q Ω).card * ∑ i, X.sides i⌉).filter
          (fun h => inScaledBox X ((q : ℝ) / (crtSubset q Ω).card) (fun _ => 0) h)),
        (1 / ((crtSubset q Ω).card : ℝ)) *
          ((∏ p ∈ T, (localCount Ω q
              (Fin.cons (0 : ZMod q) fun i => (h i : ZMod q)) p -
              localMean k Ω p)) *
            ∏ p ∈ q.primeFactors \ T, localMean k Ω p)|
      ≤ ∑ T ∈ (q.primeFactors.powerset.filter (· ≠ ∅)).filter
            (fun (T : Finset ℕ) => ¬((∏ p ∈ T, (p : ℝ)) ≤ (q : ℝ) / (crtSubset q Ω).card)),
          C_T * ∏ p ∈ T, combinedEulerWeight ε k Ω p := by
        apply Finset.sum_le_sum
        intro T hT
        exact hC_T q hq_sq T (Finset.mem_filter.mp hT |>.1)
    _ ≤ ∑ T ∈ (q.primeFactors.powerset.filter (· ≠ ∅)).filter
            (fun (T : Finset ℕ) => ¬((∏ p ∈ T, (p : ℝ)) ≤ (q : ℝ) / (crtSubset q Ω).card)),
          C_T * ∏ p ∈ T, modifiedEulerWeight ε k 0 Ω p := by
        apply Finset.sum_le_sum
        intro T hT
        apply mul_le_mul_of_nonneg_left
        · apply Finset.prod_le_prod
          · intro p hp
            have hp_prime : p.Prime := Nat.prime_of_mem_primeFactors (Finset.mem_powerset.mp (Finset.mem_filter.mp (Finset.mem_filter.mp hT |>.1) |>.1) hp)
            exact combinedEulerWeight_nonneg ε k Ω p hp_prime
          · intro p hp
            have hp_prime : p.Prime := Nat.prime_of_mem_primeFactors (Finset.mem_powerset.mp (Finset.mem_filter.mp (Finset.mem_filter.mp hT |>.1) |>.1) hp)
            unfold modifiedEulerWeight
            have h1 := combinedEulerWeight_nonneg ε k Ω p hp_prime
            have h2 := sq_nonneg (k : ℝ)
            linarith
        · exact hC_T_pos.le
    _ = C_T * ∑ T ∈ (q.primeFactors.powerset.filter (· ≠ ∅)).filter
            (fun (T : Finset ℕ) => ¬((∏ p ∈ T, (p : ℝ)) ≤ (q : ℝ) / (crtSubset q Ω).card)),
          ∏ p ∈ T, modifiedEulerWeight ε k 0 Ω p := by
        rw [← Finset.mul_sum]
    _ = C_T * ∑ d ∈ (q.divisors.filter (1 < ·)).filter
            (fun (d : ℕ) => ¬((d : ℝ) ≤ (q : ℝ) / (crtSubset q Ω).card)),
          globalModifiedEulerWeight ε k 0 Ω d := by
        congr 1
        convert sum_powerset_nonempty_filtered_eq q hq_sq
          (fun p => modifiedEulerWeight ε k 0 Ω p)
          ((q : ℝ) / (crtSubset q Ω).card) using 1
    _ ≤ C_T * (K_large * ((q : ℝ) / (crtSubset q Ω).card) ^ (-(ε / 2))) := by
        gcongr; exact hK_large q hq_sq ((q : ℝ) / (crtSubset q Ω).card) hs_ge
    _ = C_T * K_large * ((q : ℝ) / (crtSubset q Ω).card) ^ (-(ε / 2)) := by ring

/-! ### Core deviation bound assembly -/

/-
**Core per-`q` deviation bound with fixed exponent `ε / 2`.**
-/
private lemma deviation_expression_fixed_delta (ε : ℝ) (hε : 0 < ε) (k : ℕ) (hk : 2 ≤ k)
    (Ω : ∀ p : ℕ, Finset (ZMod p))
    (hΩ : ∀ p, p.Prime → (Ω p).Nonempty)
    (hWD : ∀ (p : ℕ) [Fact p.Prime], WellDistributed ε p (Ω p) k)
    (hsp : ∀ (p : ℕ), p.Prime →
      (p : ℝ) / (Ω p).card ≤ (p : ℝ) ^ (lambdaExponent k - ε))
    (hrp : ∀ (p : ℕ), p.Prime → 1 - (Ω p).card / (p : ℝ) ≤ k / (p : ℝ))
    (hε_lt : ε < lambdaExponent k)
    (X : Box (k - 1))
    (C_lp : ℝ) (hC_lp_pos : 0 < C_lp)
    (hC_lp : ∀ (v : Fin (k - 1) → ℝ), (∀ i, 0 ≤ v i ∧ v i ≤ 1) → ∀ (s : ℝ), 1 ≤ s →
      |(((Fintype.piFinset fun _ : Fin (k - 1) =>
          Finset.Icc (1 : ℤ) ⌈s * ∑ i, X.sides i⌉).filter
        (fun h => inScaledBox X s v h)).card : ℝ) - s ^ (k - 1 : ℕ) * X.volume| ≤
        C_lp * s ^ (((k - 1 : ℕ) : ℤ) - 1)) :
    ∃ K : ℝ, 0 < K ∧ ∀ (q : ℕ) [NeZero q] (_ : Squarefree q),
      let Ω_q := crtSubset q Ω
      let s := (q : ℝ) / Ω_q.card
      |(1 / (Ω_q.card : ℝ)) *
        ∑ h ∈ ((Fintype.piFinset fun _ : Fin (k - 1) =>
            Finset.Icc (1 : ℤ) ⌈s * ∑ i, X.sides i⌉).filter
          (fun h => inScaledBox X s (fun _ => 0) h)),
        ((tupleCount Ω_q (Fin.cons (0 : ZMod q) fun i => (h i : ZMod q)) : ℝ) -
          (Ω_q.card : ℝ) ^ k / (q : ℝ) ^ (k - 1))| ≤ K * s ^ (-(ε / 2)) := by
  -- Let's first obtain \( K_1 \) and \( K_2 \) from the previous lemmas.
  obtain ⟨K₁, hK₁_pos, hK₁⟩ :=
    deviation_small_divisors ε hε k hk Ω hΩ hWD hsp hrp hε_lt X C_lp hC_lp_pos hC_lp
  obtain ⟨K₂, hK₂_pos, hK₂⟩ :=
    deviation_large_divisors ε hε k hk Ω hΩ hWD hsp hrp hε_lt X C_lp hC_lp_pos hC_lp;
  refine' ⟨ K₁ + K₂, add_pos hK₁_pos hK₂_pos, fun q _ hq ↦ _ ⟩;
  -- Apply the triangle inequality to the sum, using divisor sums directly.
  have h_triangle : |(1 / (crtSubset q Ω).card : ℝ) * ∑ h ∈ ((Fintype.piFinset fun _ : Fin (k - 1) => Finset.Icc (1 : ℤ) ⌈(q : ℝ) / (crtSubset q Ω).card * ∑ i, X.sides i⌉).filter (fun h => inScaledBox X ((q : ℝ) / (crtSubset q Ω).card) (fun _ => 0) h)), ((tupleCount (crtSubset q Ω) (Fin.cons (0 : ZMod q) fun i => (h i : ZMod q)) : ℝ) - ∏ p ∈ q.primeFactors, localMean k Ω p)| ≤ ∑ d ∈ q.divisors.filter (1 < ·), |∑ h ∈ ((Fintype.piFinset fun _ : Fin (k - 1) => Finset.Icc (1 : ℤ) ⌈(q : ℝ) / (crtSubset q Ω).card * ∑ i, X.sides i⌉).filter (fun h => inScaledBox X ((q : ℝ) / (crtSubset q Ω).card) (fun _ => 0) h)), (1 / (crtSubset q Ω).card : ℝ) * ((∏ p ∈ d.primeFactors, (localCount Ω q (Fin.cons (0 : ZMod q) fun i => (h i : ZMod q)) p - localMean k Ω p)) * ∏ p ∈ q.primeFactors \ d.primeFactors, localMean k Ω p)| := by
    have h_triangle : |∑ h ∈ ((Fintype.piFinset fun _ : Fin (k - 1) => Finset.Icc (1 : ℤ) ⌈(q : ℝ) / (crtSubset q Ω).card * ∑ i, X.sides i⌉).filter (fun h => inScaledBox X ((q : ℝ) / (crtSubset q Ω).card) (fun _ => 0) h)), ((tupleCount (crtSubset q Ω) (Fin.cons (0 : ZMod q) fun i => (h i : ZMod q)) : ℝ) - ∏ p ∈ q.primeFactors, localMean k Ω p)| ≤ ∑ d ∈ q.divisors.filter (1 < ·), |∑ h ∈ ((Fintype.piFinset fun _ : Fin (k - 1) => Finset.Icc (1 : ℤ) ⌈(q : ℝ) / (crtSubset q Ω).card * ∑ i, X.sides i⌉).filter (fun h => inScaledBox X ((q : ℝ) / (crtSubset q Ω).card) (fun _ => 0) h)), ((∏ p ∈ d.primeFactors, (localCount Ω q (Fin.cons (0 : ZMod q) fun i => (h i : ZMod q)) p - localMean k Ω p)) * ∏ p ∈ q.primeFactors \ d.primeFactors, localMean k Ω p)| := by
      have h_triangle : ∑ h ∈ ((Fintype.piFinset fun _ : Fin (k - 1) => Finset.Icc (1 : ℤ) ⌈(q : ℝ) / (crtSubset q Ω).card * ∑ i, X.sides i⌉).filter (fun h => inScaledBox X ((q : ℝ) / (crtSubset q Ω).card) (fun _ => 0) h)), ((tupleCount (crtSubset q Ω) (Fin.cons (0 : ZMod q) fun i => (h i : ZMod q)) : ℝ) - ∏ p ∈ q.primeFactors, localMean k Ω p) = ∑ d ∈ q.divisors.filter (1 < ·), ∑ h ∈ ((Fintype.piFinset fun _ : Fin (k - 1) => Finset.Icc (1 : ℤ) ⌈(q : ℝ) / (crtSubset q Ω).card * ∑ i, X.sides i⌉).filter (fun h => inScaledBox X ((q : ℝ) / (crtSubset q Ω).card) (fun _ => 0) h)), ((∏ p ∈ d.primeFactors, (localCount Ω q (Fin.cons (0 : ZMod q) fun i => (h i : ZMod q)) p - localMean k Ω p)) * ∏ p ∈ q.primeFactors \ d.primeFactors, localMean k Ω p) := by
        rw [ ← Finset.sum_comm ];
        refine' Finset.sum_congr rfl fun x hx => _;
        convert deviation_product_difference q hq Ω ( Fin.cons 0 fun i => ( x i : ZMod q ) ) using 1;
        · grind;
        · grind;
      exact h_triangle.symm ▸ Finset.abs_sum_le_sum_abs _ _;
    convert mul_le_mul_of_nonneg_left h_triangle ( show ( 0 : ℝ ) ≤ 1 / ( # ( crtSubset q Ω ) : ℝ )
      by positivity ) using 1;
    · rw [ abs_mul, abs_of_nonneg ( by positivity ) ];
    · simp +decide only [← Finset.mul_sum _ _ _, abs_mul,
          abs_of_nonneg (by positivity : (0 : ℝ) ≤ 1 / (#(crtSubset q Ω)))];
  convert h_triangle.trans _ using 1;
  · rw [ globalMean_eq_prod_localMean k q hq Ω ];
  · -- Split the d-sum by (d : ℝ) ≤ s via sum_filter_add_sum_filter_not,
    -- matching deviation_small_divisors (≤ s) and deviation_large_divisors (> s).
    convert add_le_add ( hK₁ q hq ) ( hK₂ q hq ) using 1;
    · rw [ Finset.sum_filter_add_sum_filter_not ];
    · ring

private lemma deviation_expression_uniform_bound (ε : ℝ) (hε : 0 < ε) (k : ℕ) (hk : 2 ≤ k)
    (Ω : ∀ p : ℕ, Finset (ZMod p))
    (hΩ : ∀ p, p.Prime → (Ω p).Nonempty)
    (hWD : ∀ (p : ℕ) [Fact p.Prime], WellDistributed ε p (Ω p) k)
    (hsp : ∀ (p : ℕ), p.Prime →
      (p : ℝ) / (Ω p).card ≤ (p : ℝ) ^ (lambdaExponent k - ε))
    (hrp : ∀ (p : ℕ), p.Prime → 1 - (Ω p).card / (p : ℝ) ≤ k / (p : ℝ))
    (hε_lt : ε < lambdaExponent k)
    (X : Box (k - 1))
    (C_lp : ℝ) (_hC_lp_pos : 0 < C_lp)
    (_hC_lp : ∀ (v : Fin (k - 1) → ℝ), (∀ i, 0 ≤ v i ∧ v i ≤ 1) → ∀ (s : ℝ), 1 ≤ s →
      |(((Fintype.piFinset fun _ : Fin (k - 1) =>
          Finset.Icc (1 : ℤ) ⌈s * ∑ i, X.sides i⌉).filter
        (fun h => inScaledBox X s v h)).card : ℝ) - s ^ (k - 1 : ℕ) * X.volume| ≤
        C_lp * s ^ (((k - 1 : ℕ) : ℤ) - 1)) :
    ∃ δ : ℝ, 0 < δ ∧ ∃ K : ℝ, 0 < K ∧ ∀ (q : ℕ) [NeZero q] (hq_sq : Squarefree q),
      let Ω_q := crtSubset q Ω
      let s := (q : ℝ) / Ω_q.card
      |(1 / (Ω_q.card : ℝ)) *
        ∑ h ∈ ((Fintype.piFinset fun _ : Fin (k - 1) =>
            Finset.Icc (1 : ℤ) ⌈s * ∑ i, X.sides i⌉).filter
          (fun h => inScaledBox X s (fun _ => 0) h)),
        ((tupleCount Ω_q (Fin.cons (0 : ZMod q) fun i => (h i : ZMod q)) : ℝ) -
          (Ω_q.card : ℝ) ^ k / (q : ℝ) ^ (k - 1))| ≤ K * s ^ (-δ) := by
  exact ⟨ε / 2, half_pos hε,
    deviation_expression_fixed_delta ε hε k hk Ω hΩ hWD hsp hrp hε_lt X C_lp _hC_lp_pos _hC_lp⟩

/-- **Final deviation synthesis.** For any `ε > 0`, `k ≥ 2`,
and admissible local sets `Ω`, there exist `δ > 0` and
`K > 0` (depending on `ε`, `k`, the box `X`, and the
lattice-point constant `C_lp`) such that for every
squarefree `q`:
`|D(q)| ≤ K · s(q)^{−δ}`.
The proof splits into the `ε = λ_k` case (trivial: all
local sets are full) and `ε < λ_k` (the spatial synthesis
combining small- and large-divisor contributions via
inclusion-exclusion). -/
public theorem deviation_final_synthesis (ε : ℝ) (hε : 0 < ε) (k : ℕ) (hk : 2 ≤ k)
    (Ω : ∀ p : ℕ, Finset (ZMod p))
    (hΩ : ∀ p, p.Prime → (Ω p).Nonempty)
    (hWD : ∀ (p : ℕ) [Fact p.Prime], WellDistributed ε p (Ω p) k)
    (hsp : ∀ (p : ℕ), p.Prime →
      (p : ℝ) / (Ω p).card ≤ (p : ℝ) ^ (lambdaExponent k - ε))
    (hrp : ∀ (p : ℕ), p.Prime → 1 - (Ω p).card / (p : ℝ) ≤ k / (p : ℝ))
    (X : Box (k - 1))
    (C_lp : ℝ) (hC_lp_pos : 0 < C_lp)
    (hC_lp : ∀ (v : Fin (k - 1) → ℝ), (∀ i, 0 ≤ v i ∧ v i ≤ 1) → ∀ (s : ℝ), 1 ≤ s →
      |(((Fintype.piFinset fun _ : Fin (k - 1) =>
          Finset.Icc (1 : ℤ) ⌈s * ∑ i, X.sides i⌉).filter
        (fun h => inScaledBox X s v h)).card : ℝ) - s ^ (k - 1 : ℕ) * X.volume| ≤
        C_lp * s ^ (((k - 1 : ℕ) : ℤ) - 1)) :
    ∃ δ : ℝ, 0 < δ ∧ ∃ K : ℝ, 0 < K ∧ ∀ (q : ℕ) [NeZero q] (hq_sq : Squarefree q),
      let Ω_q := crtSubset q Ω
      let s := (q : ℝ) / Ω_q.card
      |(1 / (Ω_q.card : ℝ)) *
        ∑ h ∈ ((Fintype.piFinset fun _ : Fin (k - 1) =>
            Finset.Icc (1 : ℤ) ⌈s * ∑ i, X.sides i⌉).filter
          (fun h => inScaledBox X s (fun _ => 0) h)),
        ((tupleCount Ω_q (Fin.cons (0 : ZMod q) fun i => (h i : ZMod q)) : ℝ) -
          (Ω_q.card : ℝ) ^ k / (q : ℝ) ^ (k - 1))| ≤ K * s ^ (-δ) := by
  -- Split based on ε vs lambdaExponent k
  have hε_le := spacing_forces_eps_le_lambda ε hε k hk Ω hΩ hsp
  rcases eq_or_lt_of_le hε_le with heq | hlt
  · -- Case ε = λ_k: all local subsets are full, deviation is zero
    have hall := all_full_of_eps_eq_lambda ε k hk Ω hΩ hsp heq
    refine ⟨1, one_pos, 1, one_pos, fun q inst hq_sq => ?_⟩
    have hfull := crtSubset_full_of_all_full q Ω hall
    have hdev := deviation_zero_of_card_eq_q hk q Ω X hfull
    simp +decide only at hdev ⊢
    have hs1 : (q : ℝ) / ((crtSubset q Ω).card : ℝ) = 1 := by
      rw [hfull]; exact div_self (Nat.cast_ne_zero.mpr (NeZero.ne q))
    rw [hs1] at hdev ⊢
    simp +decide only [Real.one_rpow, mul_one] at hdev ⊢
    nlinarith [abs_nonneg (1 / ((crtSubset q Ω).card : ℝ) *
      ∑ h ∈ ((Fintype.piFinset fun _ : Fin (k - 1) =>
          Finset.Icc (1 : ℤ) ⌈1 * ∑ i, X.sides i⌉).filter
        (fun h => inScaledBox X 1 (fun _ => 0) h)),
      ((tupleCount (crtSubset q Ω) (Fin.cons (0 : ZMod q) fun i => (h i : ZMod q)) : ℝ) -
        ((crtSubset q Ω).card : ℝ) ^ k / (q : ℝ) ^ (k - 1)))]
  · -- Case ε < λ_k: use deviation_expression_uniform_bound directly.
    exact deviation_expression_uniform_bound ε hε k hk Ω hΩ hWD hsp hrp hlt X C_lp hC_lp_pos hC_lp

/-- Uniform exponent version of `deviation_final_synthesis`: the decay exponent `δ` is
chosen independently of the box `X` and lattice-point constant `C_lp`. Only the
multiplicative constant `K` is allowed to depend on `X`. -/
public theorem deviation_uniform_exponent (ε : ℝ) (hε : 0 < ε) (k : ℕ) (hk : 2 ≤ k)
    (Ω : ∀ p : ℕ, Finset (ZMod p))
    (hΩ : ∀ p, p.Prime → (Ω p).Nonempty)
    (hWD : ∀ (p : ℕ) [Fact p.Prime], WellDistributed ε p (Ω p) k)
    (hsp : ∀ (p : ℕ), p.Prime →
      (p : ℝ) / (Ω p).card ≤ (p : ℝ) ^ (lambdaExponent k - ε))
    (hrp : ∀ (p : ℕ), p.Prime → 1 - (Ω p).card / (p : ℝ) ≤ k / (p : ℝ)) :
    ∃ δ : ℝ, 0 < δ ∧ ∀ (X : Box (k - 1))
      (C_lp : ℝ) (hC_lp_pos : 0 < C_lp)
      (hC_lp : ∀ (v : Fin (k - 1) → ℝ), (∀ i, 0 ≤ v i ∧ v i ≤ 1) → ∀ (s : ℝ), 1 ≤ s →
        |(((Fintype.piFinset fun _ : Fin (k - 1) =>
            Finset.Icc (1 : ℤ) ⌈s * ∑ i, X.sides i⌉).filter
          (fun h => inScaledBox X s v h)).card : ℝ) - s ^ (k - 1 : ℕ) * X.volume| ≤
          C_lp * s ^ (((k - 1 : ℕ) : ℤ) - 1)),
      ∃ K : ℝ, 0 < K ∧ ∀ (q : ℕ) [NeZero q] (_ : Squarefree q),
        let Ω_q := crtSubset q Ω
        let s := (q : ℝ) / Ω_q.card
        |(1 / (Ω_q.card : ℝ)) *
          ∑ h ∈ ((Fintype.piFinset fun _ : Fin (k - 1) =>
              Finset.Icc (1 : ℤ) ⌈s * ∑ i, X.sides i⌉).filter
            (fun h => inScaledBox X s (fun _ => 0) h)),
          ((tupleCount Ω_q (Fin.cons (0 : ZMod q) fun i => (h i : ZMod q)) : ℝ) -
            (Ω_q.card : ℝ) ^ k / (q : ℝ) ^ (k - 1))| ≤
        K * s ^ (-δ) := by
  have hε_le := spacing_forces_eps_le_lambda ε hε k hk Ω hΩ hsp
  rcases eq_or_lt_of_le hε_le with heq | hlt
  · -- Case ε = λ_k: all local subsets are full, deviation is zero
    refine ⟨1, one_pos, fun X C_lp hC_lp_pos hC_lp => ?_⟩
    have hall := all_full_of_eps_eq_lambda ε k hk Ω hΩ hsp heq
    refine ⟨1, one_pos, fun q inst hq_sq => ?_⟩
    have hfull := crtSubset_full_of_all_full q Ω hall
    have hdev := deviation_zero_of_card_eq_q hk q Ω X hfull
    simp +decide only at hdev ⊢
    have hs1 : (q : ℝ) / ((crtSubset q Ω).card : ℝ) = 1 := by
      rw [hfull]; exact div_self (Nat.cast_ne_zero.mpr (NeZero.ne q))
    rw [hs1] at hdev ⊢
    simp +decide only [Real.one_rpow, mul_one] at hdev ⊢
    nlinarith [abs_nonneg (1 / ((crtSubset q Ω).card : ℝ) *
      ∑ h ∈ ((Fintype.piFinset fun _ : Fin (k - 1) =>
          Finset.Icc (1 : ℤ) ⌈1 * ∑ i, X.sides i⌉).filter
        (fun h => inScaledBox X 1 (fun _ => 0) h)),
      ((tupleCount (crtSubset q Ω) (Fin.cons (0 : ZMod q) fun i => (h i : ZMod q)) : ℝ) -
        ((crtSubset q Ω).card : ℝ) ^ k / (q : ℝ) ^ (k - 1)))]
  · -- Case ε < λ_k: the spatial synthesis approach (via
    -- `deviation_expression_fixed_delta`) handles all k ≥ 2 uniformly.
    -- The exponent `ε / 2` is independent of the box `X`, so we extract it
    -- once and then for each `X` obtain the multiplicative constant `K`.
    refine ⟨ε / 2, half_pos hε, fun X C_lp hC_lp_pos hC_lp => ?_⟩
    exact deviation_expression_fixed_delta ε hε k hk Ω hΩ hWD hsp hrp hlt X C_lp hC_lp_pos hC_lp


/-- Replaces the L1/L2 spatial deviation bound with the Fourier Parseval equivalent.
    The sum is bounded unconditionally over all frequencies using the Fourier-ANOVA decomposition. -/
private lemma deviation_dft_bound (ε : ℝ) (hε : 0 < ε) (k : ℕ) (hk : 2 ≤ k)
    (Ω : ∀ p : ℕ, Finset (ZMod p))
    (hΩ : ∀ p, p.Prime → (Ω p).Nonempty)
    (hWD : ∀ (p : ℕ) [Fact p.Prime], WellDistributedFourier ε p (Ω p) k)
    (hsp : ∀ (p : ℕ), p.Prime →
      (p : ℝ) / (Ω p).card ≤ (p : ℝ) ^ (lambdaExponent k - ε))
    (hrp : ∀ (p : ℕ), p.Prime → 1 - (Ω p).card / (p : ℝ) ≤ k / (p : ℝ))
    (X : Box (k - 1)) :
    ∃ K : ℝ, 0 < K ∧ ∀ (q : ℕ) [NeZero q] (hq_sq : Squarefree q),
      let Ω_q := crtSubset q Ω
      let s := (q : ℝ) / Ω_q.card
      |(1 / (Ω_q.card : ℝ)) *
        ∑ h ∈ ((Fintype.piFinset fun _ : Fin (k - 1) =>
            Finset.Icc (1 : ℤ) ⌈s * ∑ i, X.sides i⌉).filter
          (fun h => inScaledBox X s (fun _ => 0) h)),
        ((tupleCount Ω_q (Fin.cons (0 : ZMod q) fun i => (h i : ZMod q)) : ℝ) -
          (Ω_q.card : ℝ) ^ k / (q : ℝ) ^ (k - 1))| ≤ K * s ^ (-(ε / 2)) := by
  -- Split based on ε vs lambdaExponent k
  have hε_le := spacing_forces_eps_le_lambda ε hε k hk Ω hΩ hsp
  rcases eq_or_lt_of_le hε_le with heq | hlt
  · -- Case ε = λ_k: all local subsets are full, deviation is zero
    have hall := all_full_of_eps_eq_lambda ε k hk Ω hΩ hsp heq
    refine ⟨1, one_pos, fun q inst hq_sq => ?_⟩
    have hfull := crtSubset_full_of_all_full q Ω hall
    have hdev := deviation_zero_of_card_eq_q hk q Ω X hfull
    simp +decide only at hdev ⊢
    have hs1 : (q : ℝ) / ((crtSubset q Ω).card : ℝ) = 1 := by
      rw [hfull]; exact div_self (Nat.cast_ne_zero.mpr (NeZero.ne q))
    rw [hs1] at hdev ⊢
    simp +decide only [Real.one_rpow, mul_one] at hdev ⊢
    nlinarith [abs_nonneg (1 / ((crtSubset q Ω).card : ℝ) *
      ∑ h ∈ ((Fintype.piFinset fun _ : Fin (k - 1) =>
          Finset.Icc (1 : ℤ) ⌈1 * ∑ i, X.sides i⌉).filter
        (fun h => inScaledBox X 1 (fun _ => 0) h)),
      ((tupleCount (crtSubset q Ω) (Fin.cons (0 : ZMod q) fun i => (h i : ZMod q)) : ℝ) -
        ((crtSubset q Ω).card : ℝ) ^ k / (q : ℝ) ^ (k - 1)))]
  · -- Case ε < λ_k: Fourier-ANOVA synthesis via the change-of-variables
    -- and spatial→frequency approach.
    --
    -- Proof outline (see PROVIDED SOLUTION below for full mathematical detail):
    --
    -- Step 1 (Decoupling): Change variables from h to differences
    --   x_i = h_i - h_{i-1}, so `inScaledBox` becomes the uncoupled product
    --   condition 1 ≤ x_i ≤ ⌊s · b_i⌋.
    --
    -- Step 2 (Spatial → Frequency): Express the deviation sum as
    --   ∑_r G(r) f(r) where G is the periodized box indicator and f is the
    --   deviation function. Apply `spatial_to_frequency_swap` to obtain
    --   ∑_ξ q^{k-1} \hat{f}(ξ) \hat{G}(-ξ).
    --
    -- Step 3 (DFT bounds): Use `deviation_dft_q1_q2_bound` to get
    --   |\hat{f}(ξ)| ≤ d(ξ)^{-ε} · μ, and `dft_boxIndicator_subgrid_bound`
    --   to bound the box indicator DFT on each subgrid.
    --
    -- Step 4 (Divisor sum): Group frequencies by their support divisor d,
    --   bound the d-sum using the spacing bound `hsp` to relate q and s,
    --   yielding the final K · s^{-ε/2} decay.
    --
    -- NOTE: The full Fourier-ANOVA synthesis proof requires substantial additional
    -- infrastructure beyond what `deviation_dft_expansion`, `deviation_dft_q1_q2_bound`,
    -- and `dft_boxIndicator_subgrid_bound` provide. Specifically:
    --   (a) Handling the box condition `⌊s * X.sides j⌋₊ < q` (true for all but
    --       finitely many q) and bounding the finitely many exceptions.
    --   (b) Relating the ℝ-valued deviation sum to the ℂ-valued DFT expansion.
    --   (c) Grouping frequencies ξ by the support divisor of the differenced
    --       frequency Δξ, and bounding the subgrid DFT sums.
    --   (d) Summing the divisor-grouped bounds using the spacing hypothesis `hsp`
    --       to extract the s^{-ε/2} decay rate.
    -- Note: `WellDistributedFourier` does NOT imply `WellDistributed` with useful
    -- parameters, so this proof cannot be reduced to `deviation_expression_fixed_delta`.
    sorry

end PoissonCRT
