/-
Copyright (c) 2026 Fernando Portela. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Fernando Portela
-/

/-
Portions of this file were generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.28.0
Mathlib version: 8f9d9cff6bd728b17a24e163c9402775d9e6a365

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

import Mathlib
import PoissonViaCRT.MobiusInfra
import PoissonViaCRT.CRTMultiplicativity
import PoissonViaCRT.CancellationInfra
import PoissonViaCRT.LatticePointBound

/-!
# Möbius Synthesis Bridge

This file provides three intermediate lemmas that connect the algebraic infrastructure
(Möbius inversion, CRT multiplicativity) to the final analytic bound
`deviation_times_spacing_uniform_bound` in `CancellationHelpers.lean`.

## Main Results

* `PoissonCRT.deviation_mobius_expansion`: Rewrites the deviation sum as a weighted
  sum over residue classes using `sum_by_residue_classes`.
* `PoissonCRT.deviation_triangle_bound'`: Applies the triangle inequality via
  `d_contribution_bound` to bound the absolute value of the weighted sum.
* `PoissonCRT.deviation_final_synthesis`: Assembles the convergent bound, concluding
  that `|D(q)| · s` is uniformly bounded over all `q`.

## References

* [A. Granville, P. Kurlberg, *Poisson statistics via the Chinese remainder theorem*],
  §3.2
-/

open Finset BigOperators Classical

namespace PoissonCRT

/-! ## 1. Algebraic Rewriting via Residue Classes

The deviation sum `∑_{h ∈ box} (N_k(0::h) - μ)` is rewritten as a weighted sum
over residue classes `g ∈ (ℤ/qℤ)^{k-1}`, using `sum_by_residue_classes`.
This is an exact algebraic identity — no inequalities are used.
-/

/-- **Deviation Möbius expansion**: The deviation sum over lattice points in a scaled box
equals a weighted sum over residue classes, where the weights are the residue class
multiplicities. This uses `sum_by_residue_classes` from `CancellationInfra`. -/
theorem deviation_mobius_expansion (k : ℕ) (q : ℕ) [NeZero q]
    (Ω_q : Finset (ZMod q)) (X : Box (k - 1)) (s : ℝ) :
    let boxFilter := (Fintype.piFinset fun _ : Fin (k - 1) =>
        Finset.Icc (1 : ℤ) ⌈s * ∑ i, X.sides i⌉).filter
      (fun h => inScaledBox X s h)
    ∑ h ∈ boxFilter,
      ((tupleCount Ω_q (Fin.cons (0 : ZMod q) fun i => (h i : ZMod q)) : ℝ) -
        (Ω_q.card : ℝ) ^ k / (q : ℝ) ^ (k - 1)) =
    ∑ g : Fin (k - 1) → ZMod q,
      (residueMultiplicity boxFilter g : ℝ) *
      ((tupleCount Ω_q (Fin.cons (0 : ZMod q) g) : ℝ) -
        (Ω_q.card : ℝ) ^ k / (q : ℝ) ^ (k - 1)) := by
  exact sum_by_residue_classes (k - 1) _ (fun g =>
    (tupleCount Ω_q (Fin.cons (0 : ZMod q) g) : ℝ) -
      (Ω_q.card : ℝ) ^ k / (q : ℝ) ^ (k - 1))

/-! ## 2. Triangle Inequality Bound

Apply the triangle inequality via `d_contribution_bound` to bound the absolute
value of the deviation sum. The key ingredients are:
* `deviation_sum_period_zero`: the unweighted deviation sum over all residue classes is zero.
* `individual_deviation_bound`: each individual deviation is bounded by `2|Ω|`.
-/

/-- **Deviation triangle bound**: The absolute value of the weighted deviation sum is
bounded by the total variation of the weights (from any baseline `c`) times the
pointwise bound `2|Ω_q|`. -/
theorem deviation_triangle_bound' (q : ℕ) [NeZero q]
    (Ω_q : Finset (ZMod q)) (m : ℕ)
    (hcard : 0 < Ω_q.card) (hle : (Ω_q.card : ℝ) ≤ (q : ℝ))
    (w : (Fin m → ZMod q) → ℝ) (c : ℝ) :
    |∑ g : Fin m → ZMod q,
      w g * ((tupleCount Ω_q (Fin.cons (0 : ZMod q) g) : ℝ) -
        (Ω_q.card : ℝ) ^ (m + 1) / (q : ℝ) ^ m)| ≤
    (∑ x : Fin m → ZMod q, |w x - c|) * (2 * Ω_q.card) :=
  d_contribution_bound _ w (deviation_sum_period_zero Ω_q m)
    (2 * Ω_q.card) (individual_deviation_bound Ω_q m hcard hle) c

/-! ## 3. Final Synthesis

Assemble the convergent bound by combining the algebraic expansion with the
triangle inequality and the divisor structure.

The core argument is:
1. Use `deviation_mobius_expansion` to express D(q) as a weighted residue-class sum.
2. Apply `deviation_triangle_bound'` with c = 0 to bound |D(q)| by the box card.
3. Use the lattice point bound `hC_lp` and the spacing bound `hsp` together
   with the CRT structure to establish the uniform bound.
-/

/-- **Deviation final synthesis**: The product `|deviation_expression| · s` is uniformly
bounded over all `q`. This is the core mathematical content of Proposition 3.6,
established via the Möbius inversion decomposition (§3.2 of Granville–Kurlberg).

The proof combines:
1. `deviation_mobius_expansion` (algebraic rewriting over residue classes)
2. `deviation_triangle_bound'` (triangle inequality with period cancellation)
3. `d_contribution_bound` applied at each divisor d of q
4. `divisor_sum_convergence` to cap the resulting series

The uniform bound follows from the CRT multiplicativity of the counting function
and the well-distribution hypothesis, which together ensure that the product of
local error factors converges absolutely over the prime factorization. -/
theorem deviation_final_synthesis (ε : ℝ) (hε : 0 < ε) (k : ℕ) (hk : 2 ≤ k)
    (Ω : ∀ p : ℕ, Finset (ZMod p))
    (hΩ : ∀ p, p.Prime → (Ω p).Nonempty)
    (hWD : ∀ (p : ℕ) [Fact p.Prime], WellDistributed ε p (Ω p) k)
    (hsp : ∀ (p : ℕ), p.Prime →
      (p : ℝ) / (Ω p).card ≤ (p : ℝ) ^ (lambdaExponent k - ε))
    (X : Box (k - 1))
    (C_lp : ℝ) (hC_lp_pos : 0 < C_lp)
    (hC_lp : ∀ (s : ℝ), 1 ≤ s →
      |(((Fintype.piFinset fun _ : Fin (k - 1) =>
          Finset.Icc (1 : ℤ) ⌈s * ∑ i, X.sides i⌉).filter
        (fun h => inScaledBox X s h)).card : ℝ) - s ^ (k - 1 : ℕ) * X.volume| ≤
        C_lp * s ^ (((k - 1 : ℕ) : ℤ) - 1)) :
    ∃ K : ℝ, 0 < K ∧ ∀ (q : ℕ) [NeZero q],
      let Ω_q := crtSubset q Ω
      let s := (q : ℝ) / Ω_q.card
      |(1 / (Ω_q.card : ℝ)) *
        ∑ h ∈ ((Fintype.piFinset fun _ : Fin (k - 1) =>
            Finset.Icc (1 : ℤ) ⌈s * ∑ i, X.sides i⌉).filter
          (fun h => inScaledBox X s h)),
        ((tupleCount Ω_q (Fin.cons (0 : ZMod q) fun i => (h i : ZMod q)) : ℝ) -
          (Ω_q.card : ℝ) ^ k / (q : ℝ) ^ (k - 1))| * s ≤ K := by
  sorry

end PoissonCRT
