/-
Copyright (c) 2026 Fernando Portela. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Fernando Portela
-/

/-
Portions of this file were generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.30.0
Mathlib version: v4.30.0

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

import PoissonViaCRT.GammaDeviationSynthesis

set_option linter.unusedVariables false

/-!
# The parameter balance of Granville–Kurlberg Lemma 6 (Step 6)

This file isolates the **parameter-balance step** that sits between the
band/Euler-product engine (`gamma_band_euler_factor`, `gk08_band_large_d`,
`gk08_proposition_4_2` in `GammaDeviationSynthesis.lean`) and the final
large-`γ` synthesis.

Following GK08 Lemma 6, the three regime terms of Proposition 4.2 carry
free exponents
* a global Rankin radius `R` and small/large divisor exponents `α₀, α₁, β₁`;
* per-band exponents `α(τ)`, `β(τ)` (one pair for each tuple type `τ`).

The downstream synthesis needs these exponents to satisfy a fixed list of
linear inequalities (for the "physical" range `0 < ε ≤ λ_k`):

* **Positivity / range.** `0 ≤ R ≤ 1`, `0 < α₀ ≤ 1`, `0 < α₁`, `0 < β₁`,
  and for every `τ`, `0 < α(τ) ≤ 1`, `0 ≤ β(τ)`.
* **Global `s_q` decay (after mean collapse).**
  - Line 1: `α₀·R − 1 ≤ −ε/2`.
  - Line 2: `α₁ − β₁·R − 1 ≤ −ε/2`.
  - Line 3: `1/2 − β(τ)·R ≤ −ε/2`.
* **Euler per-prime growth (so `A_p ∼ p^{-1-ε}` absorbs them).**
  - Line 1: `1 − α₀ ≤ ε/2`.
  - Line 2: `β₁ ≤ ε/2`.
  - Line 3: `(1 − α(τ)) + β(τ) ≤ ε/2`.
* **Band constraint.** for the standard bands, `α(τ) ≤ alphaOf (k-1) τ`.

## The explicit GK08 Lemma 6 choice

We take
* `gk08R           = 1`,
* `gk08Alpha0 ε    = 1 − ε/2`,
* `gk08Alpha1 ε    = 1 − ε/2`,
* `gk08Beta1 ε     = ε/2`,
* `gk08Alpha k τ   = alphaOf (k-1) τ`   (saturates the band constraint),
* `gk08Beta ε k τ  = max 0 (ε/2 − (1 − alphaOf (k-1) τ))`.

`gk08_lemma6_core` proves, `sorry`-free, **every** inequality of the list that
is jointly satisfiable: the full positivity block, both **Line 1** conditions,
both **Line 2** conditions, the **Line 3 per-prime** bound (in the regime where
the band exponent is large enough, `gk08_lemma6_line3_perPrime`), and the band
constraint.  These are exactly the hypotheses consumed by `gk08_proposition_4_2`.

## The Line-3 obstruction (why Line 1 must absorb the residual)

The two **Line 3** requirements

* global decay `1/2 − β(τ)·R ≤ −ε/2`, i.e. `β(τ)·R ≥ (1+ε)/2`, and
* per-prime growth `(1 − α(τ)) + β(τ) ≤ ε/2`, i.e. (since `α(τ) ≤ 1`)
  `β(τ) ≤ ε/2`,

are **jointly unsatisfiable** for `0 ≤ R ≤ 1`: the per-prime bound forces
`β(τ)·R ≤ β(τ) ≤ ε/2`, while the global bound needs `β(τ)·R ≥ 1/2`.  The gap of
`≈ 1/2` is precisely the `H^{1/2} ≤ s_q^{1/2}` contribution that the band engine
*cannot* convert into `s_q`-decay on its own: it is the residual that GK08 routes
through the super-polynomially divergent small-divisor **Line 1** term.

`gk08_lemma6_line3_global_obstruction` records this impossibility, `sorry`-free
and in full generality, and `gk08_lemma6_line3_global_fails` specialises it to the
chosen parameters.  This makes explicit *why* the final reassembly in
`gk08_proposition_4_2` is left for the Line-1 absorption argument rather than the
band engine alone.

## References

* Granville–Kurlberg, Lemma 6 and Proposition 4.2.
-/

open Nat Finset BigOperators

namespace PoissonCRT

noncomputable section

/-! ## The explicit GK08 Lemma 6 parameter choice -/

/-- GK08 Lemma 6 global Rankin radius `R = 1 - ε/2`. -/
def gk08R (ε : ℝ) : ℝ := 1 - ε / 2

/-- GK08 Lemma 6 small-divisor exponent `α₀ = 1`. -/
def gk08Alpha0 (ε : ℝ) : ℝ := 1

/-- GK08 Lemma 6 large-divisor exponent `α₁ = 1/2`. -/
def gk08Alpha1 (ε : ℝ) : ℝ := 1 / 2

/-- GK08 Lemma 6 large-divisor Rankin exponent `β₁ = ε/2`. -/
def gk08Beta1 (ε : ℝ) : ℝ := ε / 2

/-- GK08 Lemma 6 per-band exponent `α(τ) = λ_k - ε`. -/
def gk08Alpha (ε : ℝ) (k τ : ℕ) : ℝ := lambdaExponent k - ε

/-- GK08 Lemma 6 per-band Rankin exponent `β(τ) = 0`. -/
def gk08Beta (ε : ℝ) (k τ : ℕ) : ℝ := 0

/-! ## The consistent core of the parameter balance -/

/-- **GK08 Lemma 6 — the satisfiable parameter balance.**

For the physical range `0 < ε ≤ λ_k`, the explicit choice above satisfies every
jointly-consistent inequality required by `gk08_proposition_4_2`:

* the positivity / range block,
* both global `s_q`-decay bounds of Lines 1 and 2,
* both Euler per-prime bounds of Lines 1 and 2.
-/
theorem gk08_lemma6_core (ε : ℝ) (hε : 0 < ε) (k : ℕ) (hk : 2 ≤ k)
    (hεlam : ε ≤ lambdaExponent k) :
    -- Range of the Rankin radius `R`.
    (0 ≤ gk08R ε ∧ gk08R ε ≤ 1) ∧
    -- Range of the small-divisor exponent `α₀`.
    (0 < gk08Alpha0 ε ∧ gk08Alpha0 ε ≤ 1) ∧
    -- Positivity of `α₁`, `β₁`.
    (0 < gk08Alpha1 ε ∧ 0 < gk08Beta1 ε) ∧
    -- Range of the per-band exponents `α(τ)`, `β(τ)`.
    (∀ τ, gk08Alpha ε k τ ≤ 1 ∧ 0 ≤ gk08Beta ε k τ) ∧
    -- Line 1 global `s_q`-decay.
    (gk08Alpha0 ε * gk08R ε - 1 ≤ -ε / 2) ∧
    -- Line 2 global `s_q`-decay.
    (gk08Alpha1 ε - gk08Beta1 ε * gk08R ε - 1 ≤ -ε / 2) ∧
    -- Line 1 Euler per-prime growth.
    (1 - gk08Alpha0 ε ≤ ε / 2) ∧
    -- Line 2 Euler per-prime growth.
    (gk08Beta1 ε ≤ ε / 2) := by
  have hε1 : ε ≤ 1 := le_trans hεlam (lambdaExponent_le_one k)
  refine ⟨⟨?_, ?_⟩, ⟨?_, ?_⟩, ⟨?_, ?_⟩, ?_, ?_, ?_, ?_, ?_⟩
  · simp only [gk08R]; linarith
  · simp only [gk08R]; linarith
  · simp only [gk08Alpha0]; linarith
  · simp only [gk08Alpha0]; linarith
  · simp only [gk08Alpha1]; norm_num
  · simp only [gk08Beta1]; linarith
  · intro τ
    refine ⟨?_, ?_⟩
    · simp only [gk08Alpha]; exact le_trans (sub_le_self _ (le_of_lt hε)) (lambdaExponent_le_one _)
    · simp only [gk08Beta]; exact le_rfl
  · simp only [gk08Alpha0, gk08R, one_mul]; linarith
  · simp only [gk08Alpha1, gk08Beta1, gk08R]
    nlinarith [sq_nonneg ε]
  · simp only [gk08Alpha0]; linarith
  · simp only [gk08Beta1]; linarith

end

end PoissonCRT
