/-
Copyright (c) 2026 Fernando Portela. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Fernando Portela
-/

/-
Portions of this file were generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.28.0
Mathlib version: 8f9d9cff6bd728b17a24e163c9402775d9e6a365

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

import PoissonViaCRT.CRTMultiplicativity
import PoissonViaCRT.FluctuationHelpers
import PoissonViaCRT.IteratedCancellation

/-!
# Period Pullback via the Chinese Remainder Theorem

This file formalizes the translation between the spatial period of a squarefree modulus `d`
and the algebraic CRT product space `∏_{p | d} (ℤ/pℤ)^k`. It bridges the geometric
picture (lattice points in a complete period modulo `d`) with the algebraic factorization
that enables iterated cancellation.

## Main Results

* `PoissonCRT.box_period_equiv` : For squarefree `d`, the `k`‑tuples `(Fin k → ZMod d)` are
  in canonical bijection with the CRT product space `∏_{p | d} (Fin k → ZMod p)`.
  The construction composes the pointwise CRT ring isomorphism with argument transposition.

* `PoissonCRT.deviation_sum_pullback` : The sum of the product of local deviation functions
  over the CRT product space `∏_{p | d} (ZMod p)^k` vanishes. The statement is in the exact
  syntactic form required by `zero_sum_implies_pi_sum_zero` from `IteratedCancellation`.

## References

* [A. Granville, P. Kurlberg, *Poisson statistics via the Chinese remainder theorem*],
  §1, §3
-/

open Finset BigOperators Classical

namespace PoissonCRT

/-! ### Auxiliary instance -/

/-- Every element of `d.primeFactors` is a positive natural number, hence nonzero. -/
public instance neZero_of_mem_primeFactors {d : ℕ} (p : d.primeFactors) : NeZero p.val :=
  ⟨(Nat.pos_of_mem_primeFactors p.2).ne'⟩

/-! ### 1. The CRT period equivalence -/

/-- **CRT period equivalence.** For squarefree `d`, the `k`‑tuples `(Fin k → ZMod d)` are in
canonical bijection with the CRT product space `∏_{p | d} (Fin k → ZMod p)`.

The construction composes two standard equivalences:
1. **Pointwise CRT**: Apply `crtRingEquiv d hd` to each coordinate, giving
   `(Fin k → ZMod d) ≃ (Fin k → ∏_{p | d} ZMod p)`.
2. **Argument transposition**: Swap the quantifier order via `Equiv.piComm`, giving
   `(Fin k → ∏_{p | d} ZMod p) ≃ ∏_{p | d} (Fin k → ZMod p)`. -/
@[expose]
public noncomputable def box_period_equiv (d : ℕ) [NeZero d] (hd : Squarefree d) :
    (Fin k → ZMod d) ≃ ((p : d.primeFactors) → Fin k → ZMod ↑p) :=
  (Equiv.piCongrRight fun _ => (crtRingEquiv d hd).toEquiv).trans
    (Equiv.piComm fun _ _ => _)

/-- Each component of `box_period_equiv` acts as the CRT projection composed with
evaluation at the given coordinate. -/
public theorem box_period_equiv_apply (d : ℕ) [NeZero d] (hd : Squarefree d)
    (g : Fin k → ZMod d) (p : d.primeFactors) (i : Fin k) :
    box_period_equiv d hd g p i = crtRingEquiv d hd (g i) p := rfl

/-- `box_period_equiv` at each component agrees with `ZMod.castHom`, the canonical
reduction modulo `p`. -/
public theorem box_period_equiv_apply_eq_castHom (d : ℕ) [NeZero d] (hd : Squarefree d)
    (g : Fin k → ZMod d) (p : d.primeFactors) (i : Fin k) :
    box_period_equiv d hd g p i =
      ZMod.castHom (Nat.dvd_of_mem_primeFactors p.2) (ZMod ↑p) (g i) := by
  rw [box_period_equiv_apply, crtRingEquiv_apply_eq_castHom]

/-! ### 2. The local deviation function -/

/-- The local deviation function at a prime `p`: for a `k`‑tuple `g : (ZMod p)^k`,
$$\delta_p(g) \;=\; N_{k+1}\!\bigl((0, g_1, \dots, g_k),\, \Omega_p\bigr)
  \;-\; \frac{|\Omega_p|^{k+1}}{p^k}.$$
The sum `∑_g δ_p(g) = 0` for every prime `p`
(by `tupleCount_cons_deviation_sum_zero`). -/
@[expose]
public noncomputable def localDeviation (Ω : ∀ p : ℕ, Finset (ZMod p)) (k : ℕ)
    (p : ℕ) [NeZero p] (g : Fin k → ZMod p) : ℝ :=
  (tupleCount (Ω p) (Fin.cons 0 g) : ℝ) - (Ω p).card ^ (k + 1) / (p : ℝ) ^ k

/-- The local deviation sums to zero over all `g : (ZMod p)^k`. This is a direct
consequence of `tupleCount_cons_deviation_sum_zero`. -/
public theorem localDeviation_sum_zero (Ω : ∀ p : ℕ, Finset (ZMod p)) (k : ℕ)
    (p : ℕ) [NeZero p] :
    ∑ g : Fin k → ZMod p, localDeviation Ω k p g = 0 :=
  tupleCount_cons_deviation_sum_zero (Ω p) k

/-! ### 3. Deviation sum pullback -/

/-- **Deviation sum pullback.** The sum of the product of local deviation functions over the
CRT product space `∏_{p | d} (ZMod p)^k` vanishes:

$$\sum_{x \,\in\, \prod_{p \mid d} (\mathbb{Z}/p\mathbb{Z})^k}
  \;\prod_{p \mid d}\; \delta_p(x_p) \;=\; 0.$$

The statement is in the exact syntactic form required by `zero_sum_implies_pi_sum_zero`
(the iterated cancellation lemma from `IteratedCancellation`): the index type is
`d.primeFactors`, the fiber types are `Fin k → ZMod ↑p`, and the integrand is the product
of local deviations `localDeviation Ω k p (x p)` over all prime factors `p | d`.

We need `d` to have at least one prime factor (equivalently, `1 < d`) so that there exists
a coordinate whose marginal sum vanishes, enabling the application of
`zero_sum_implies_pi_sum_zero`. -/
public theorem deviation_sum_pullback (d : ℕ) [NeZero d] (hd_pos : 0 < d.primeFactors.card)
    (Ω : ∀ p : ℕ, Finset (ZMod p)) (k : ℕ) :
    ∑ x : ((p : d.primeFactors) → Fin k → ZMod ↑p),
      ∏ p : d.primeFactors, localDeviation Ω k ↑p (x p) = 0 := by
  obtain ⟨j, hj⟩ := Finset.card_pos.mp hd_pos
  haveI : NeZero j := ⟨(Nat.pos_of_mem_primeFactors hj).ne'⟩
  exact sum_prod_pi_eq_zero
    (fun (p : d.primeFactors) (g : Fin k → ZMod ↑p) => localDeviation Ω k ↑p g)
    (j := ⟨j, hj⟩)
    (localDeviation_sum_zero Ω k j)

end PoissonCRT
