/-
Copyright (c) 2026 Fernando Portela. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Fernando Portela
-/

/-
Portions of this file were generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.28.0
Mathlib version: 8f9d9cff6bd728b17a24e163c9402775d9e6a365

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

import Mathlib.Algebra.BigOperators.Ring.Finset
import Mathlib.Data.Finset.Powerset
import Mathlib.Tactic.Ring

/-!
# Product-Difference Expansion

This file proves the finite product-difference identity: for `a b : ι → R` over a commutative ring
and a finite set `S`, the difference of products decomposes as a sum over nonempty subsets:

$$\prod_{i \in S} a_i - \prod_{i \in S} b_i
  = \sum_{\emptyset \neq T \subseteq S}
      \Bigl(\prod_{i \in T}(a_i - b_i)\Bigr)\,
      \Bigl(\prod_{i \in S \setminus T} b_i\Bigr).$$

## Main results

* `prod_sub_prod_expansion`: the identity above.
-/

open Finset in
/-- **Product-difference expansion.**
For a commutative ring `R`, a finset `S`, and functions `a b : ι → R`,

  `∏ i ∈ S, a i - ∏ i ∈ S, b i = ∑ T ∈ S.powerset.filter (· ≠ ∅),
      (∏ i ∈ T, (a i - b i)) * ∏ i ∈ S \ T, b i`

The proof rewrites `a i = (a i - b i) + b i`, applies `Finset.prod_add` to expand the product
over all subsets `T ⊆ S`, and then subtracts the `T = ∅` term (which is `∏ i ∈ S, b i`). -/
theorem prod_sub_prod_expansion {ι : Type*} {R : Type*} [CommRing R] [DecidableEq ι]
    (a b : ι → R) (S : Finset ι) :
    ∏ i ∈ S, a i - ∏ i ∈ S, b i =
      ∑ T ∈ S.powerset.filter (· ≠ ∅), (∏ i ∈ T, (a i - b i)) * ∏ i ∈ S \ T, b i := by
  have h_prod_add : ∏ i ∈ S, a i = ∑ T ∈ S.powerset, (∏ i ∈ T, (a i - b i)) * (∏ i ∈ S \ T, b i) := by
    convert Finset.prod_add _ _ _ using 2;
    ring;
  simp +decide [h_prod_add, Finset.filter_ne']
