/-
Copyright (c) 2026 Fernando Portela. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Fernando Portela

Portions of this file were generated by Aristotle (https://aristotle.harmonic.fun).
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

import PoissonViaCRT.AnalyticInputs

/-!
# Rankin–Euler lemmas (Blueprint §3)

After the summation swap (`sum_T_gamma_swap`), for a fixed `γ` the inner sum over
large divisors `T` with `R ⊆ T ⊆ q.primeFactors` (`R := γ.primeFactors`) is
bounded by an Euler product and the Rankin saving `s^{-ε/2}`.

* `rankin_euler_factorisation` absorbs the large-divisor constraint `∏_{p∈T} p > s`
  into `s^{-ε/2}` and factorises the sum over `T ⊇ R` as an Euler product
  (`Finset.prod_add` engine).
* `rankin_euler_tail_bounded` bounds the well-distributed Euler tail uniformly by a
  constant via `euler_product_converges`.
-/

open Nat Finset BigOperators Classical

namespace PoissonCRT

/-
**Rankin factorisation.** The large-divisor constraint `∏_{p∈T} p > s` is
absorbed into `s^{−ε/2}` and the sum over `T ⊇ R` factorises as an Euler product.
-/
lemma rankin_euler_factorisation
    (q : ℕ) (s : ℝ) (hs : 0 < s) (ε : ℝ) (hε : 0 < ε)
    (R : Finset ℕ) (hR : R ⊆ q.primeFactors)
    (a b : ℕ → ℝ)
    (ha : ∀ p ∈ q.primeFactors, 0 ≤ a p) (hb : ∀ p ∈ q.primeFactors, 0 ≤ b p) :
    ∑ T ∈ q.primeFactors.powerset.filter
        (fun T => R ⊆ T ∧ ¬((∏ p ∈ T, (p : ℝ)) ≤ s)),
        (∏ p ∈ q.primeFactors \ T, a p) * (∏ p ∈ T \ R, b p) ≤
    s ^ (-(ε / 2)) * (∏ p ∈ R, (p : ℝ) ^ (ε / 2)) *
      ∏ p ∈ q.primeFactors \ R, (a p + b p * (p : ℝ) ^ (ε / 2)) := by
  -- Applying the bound from rankin_euler_factorisation
  have h_bound : ∀ T ∈ (q.primeFactors).powerset.filter (fun T => R ⊆ T ∧ ¬∏ p ∈ T, (p : ℝ) ≤ s), (∏ p ∈ (q.primeFactors)\T, a p) * (∏ p ∈ T\R, b p) ≤ (s ^ (-(ε / 2))) * (∏ p ∈ T, (p : ℝ) ^ (ε / 2)) * (∏ p ∈ (q.primeFactors)\T, a p) * (∏ p ∈ T\R, b p) := by
    intro T hT
    have h_prod : (∏ p ∈ T, (p : ℝ) ^ (ε / 2)) ≥ s ^ (ε / 2) := by
      rw [ Real.finsetProd_rpow _ _ fun x hx => Nat.cast_nonneg _ ] ; exact Real.rpow_le_rpow ( by positivity ) ( le_of_not_ge <| by aesop ) ( by positivity ) ;
    simp_all +decide [ Real.rpow_neg hs.le ];
    exact mul_le_mul_of_nonneg_right ( le_mul_of_one_le_left ( Finset.prod_nonneg fun _ _ => ha _ ( Nat.prime_of_mem_primeFactors ( Finset.mem_sdiff.mp ‹_› |>.1 ) ) ( Nat.dvd_of_mem_primeFactors ( Finset.mem_sdiff.mp ‹_› |>.1 ) ) ( by aesop ) ) ( by rw [ inv_mul_eq_div, le_div_iff₀ ( by positivity ) ] ; linarith ) ) ( Finset.prod_nonneg fun _ _ => hb _ ( Nat.prime_of_mem_primeFactors ( hT.1 ( Finset.mem_sdiff.mp ‹_› |>.1 ) ) ) ( Nat.dvd_of_mem_primeFactors ( hT.1 ( Finset.mem_sdiff.mp ‹_› |>.1 ) ) ) ( by aesop ) );
  -- Applying the bound from rankin_euler_factorisation to each term in the sum.
  have h_sum_bound : ∑ T ∈ (q.primeFactors).powerset.filter (fun T => R ⊆ T ∧ ¬∏ p ∈ T, (p : ℝ) ≤ s), (∏ p ∈ (q.primeFactors)\T, a p) * (∏ p ∈ T\R, b p) ≤ s ^ (-(ε / 2)) * (∏ p ∈ R, (p : ℝ) ^ (ε / 2)) * ∑ T ∈ (q.primeFactors \ R).powerset, (∏ p ∈ (q.primeFactors \ R)\T, a p) * (∏ p ∈ T, b p * (p : ℝ) ^ (ε / 2)) := by
    refine le_trans ( Finset.sum_le_sum h_bound ) ?_;
    refine' le_trans _ ( mul_le_mul_of_nonneg_left ( Finset.sum_le_sum_of_subset_of_nonneg _ _ ) _ );
    case refine'_2 => exact Finset.image ( fun T => T \ R ) ( Finset.filter ( fun T => R ⊆ T ∧ ¬∏ p ∈ T, ( p : ℝ ) ≤ s ) ( Finset.powerset ( q.primeFactors ) ) );
    · rw [ Finset.sum_image ];
      · rw [ Finset.mul_sum _ _ _ ];
        refine' Finset.sum_le_sum fun T hT => _;
        simp_all +decide [ Finset.prod_mul_distrib, mul_assoc, mul_comm ];
        rw [ ← Finset.prod_sdiff hT.2.1 ];
        rw [ show ( q.primeFactors \ R ) \ ( T \ R ) = q.primeFactors \ T from ?_ ] ; ring_nf ; norm_num;
        grind;
      · intro T hT T' hT' h_eq; simp_all +decide [ Finset.ext_iff ] ;
        grind;
    · grind;
    · exact fun _ _ _ => mul_nonneg ( Finset.prod_nonneg fun p hp => ha p <| Finset.mem_sdiff.mp hp |>.1 |> Finset.mem_sdiff.mp |>.1 ) ( Finset.prod_nonneg fun p hp => mul_nonneg ( hb p <| Finset.mem_sdiff.mp ( Finset.mem_powerset.mp ‹_› hp ) |>.1 ) <| Real.rpow_nonneg ( Nat.cast_nonneg _ ) _ );
    · exact mul_nonneg ( Real.rpow_nonneg hs.le _ ) ( Finset.prod_nonneg fun _ _ => Real.rpow_nonneg ( Nat.cast_nonneg _ ) _ );
  convert h_sum_bound using 2;
  simp +decide [ add_comm ( a _ ), Finset.prod_add ];
  ac_rfl

/-
**Euler-tail convergence.** The well-distributed Euler tail is bounded by a
constant uniformly over `q` and `R`, via `euler_product_converges`.
-/
lemma rankin_euler_tail_bounded
    (ε : ℝ) (hε : 0 < ε) (k : ℕ) (hk : 2 ≤ k)
    (Ω : ∀ p : ℕ, Finset (ZMod p))
    (hrp : ∀ p, p.Prime → 1 - (Ω p).card / (p : ℝ) ≤ k / (p : ℝ))
    (hΩle : ∀ p, p.Prime → (Ω p).card ≤ p) :
    ∃ M : ℝ, 0 < M ∧ ∀ (S : Finset ℕ), (∀ p ∈ S, p.Prime) →
      ∏ p ∈ S, (((Ω p).card / (p : ℝ)) ^ (k - 1) +
        (1 - (Ω p).card / (p : ℝ)) * (p : ℝ) ^ (-ε) *
          ((Ω p).card / (p : ℝ)) ^ (k - 1) * (p : ℝ) ^ (ε / 2)) ≤ M := by
  -- Set `M := max M₀ 1`; then `0 < M` (since `1 ≤ max M₀ 1`).
  obtain ⟨M₀, hM₀⟩ : ∃ M₀ : ℝ, ∀ (S : Finset ℕ), (∀ p ∈ S, p.Prime) → ∏ p ∈ S, (1 + (k : ℝ) / (p : ℝ) ^ (1 + ε / 2)) ≤ M₀ := by
    convert euler_product_converges ( k : ℝ ) ( ε / 2 ) ( by positivity ) using 1
  use max M₀ 1
  simp;
  refine' fun S hS => Or.inl <| le_trans ( Finset.prod_le_prod _ fun p hp => _ ) ( hM₀ S hS );
  · intro p hp; specialize hrp p ( hS p hp ) ; specialize hΩle p ( hS p hp ) ;
    exact add_nonneg ( pow_nonneg ( div_nonneg ( Nat.cast_nonneg _ ) ( Nat.cast_nonneg _ ) ) _ ) ( mul_nonneg ( mul_nonneg ( mul_nonneg ( sub_nonneg.2 <| div_le_one_of_le₀ ( mod_cast hΩle ) <| Nat.cast_nonneg _ ) <| Real.rpow_nonneg ( Nat.cast_nonneg _ ) _ ) <| pow_nonneg ( div_nonneg ( Nat.cast_nonneg _ ) ( Nat.cast_nonneg _ ) ) _ ) <| Real.rpow_nonneg ( Nat.cast_nonneg _ ) _ );
  · refine' add_le_add _ _;
    · exact pow_le_one₀ ( by positivity ) ( div_le_one_of_le₀ ( mod_cast hΩle p ( hS p hp ) ) ( by positivity ) );
    · refine' le_trans ( mul_le_mul_of_nonneg_right ( mul_le_mul_of_nonneg_right ( mul_le_mul_of_nonneg_right ( hrp p ( hS p hp ) ) ( by positivity ) ) ( by positivity ) ) ( by positivity ) ) _;
      rw [ Real.rpow_add ( Nat.cast_pos.mpr <| Nat.Prime.pos <| hS p hp ), Real.rpow_neg ( Nat.cast_nonneg _ ) ] ; ring_nf ; norm_num [ hS p hp |> Nat.Prime.ne_zero ];
      field_simp;
      rw [ div_le_div_iff₀ ] <;> norm_num [ Nat.Prime.pos ( hS p hp ) ];
      · rw [ show ( ε : ℝ ) = ε / 2 + ε / 2 by ring, Real.rpow_add ( Nat.cast_pos.mpr <| Nat.Prime.pos <| hS p hp ) ] ; ring_nf ; norm_num [ Nat.Prime.pos ( hS p hp ) ];
        rw [ mul_assoc, mul_comm ] ; gcongr ; aesop;
      · exact Real.rpow_pos_of_pos ( Nat.cast_pos.mpr ( Nat.Prime.pos ( hS p hp ) ) ) _;
      · exact Real.rpow_pos_of_pos ( Nat.cast_pos.mpr ( Nat.Prime.pos ( hS p hp ) ) ) _

end PoissonCRT