/-
Copyright (c) 2026 Fernando Portela. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Fernando Portela

The architectural design of this LatticeCounting framework was developed by
Antigravity (Google DeepMind) to formalize combinatorial CRT counting arguments.

Portions of this file were generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.28.0
Mathlib version: 8f9d9cff6bd728b17a24e163c9402775d9e6a365

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>

References:
- Granville & Kurlberg (2008), arXiv:math/0412135
- Iwaniec & Kowalski, Analytic Number Theory
-/

import Mathlib.Algebra.Order.Ring.Star
import Mathlib.Data.Int.Interval
import Mathlib.Data.Int.ModEq
import Mathlib.Data.Int.Star
import Mathlib.Data.Real.Basic
import Mathlib.Tactic

/-!
# Module 3: OneDimCounting

Bounds on the number of solutions to 1D congruences within intervals,
specifically handling the "zero-exclusion" boundary condition.

## Main results

* `LatticeCounting.count_multiples_strict`: The number of nonzero multiples of `M`
  in `[-S, S]` is exactly `2 * ⌊S/M⌋`.
* `LatticeCounting.count_congruence_interval_strict`: The number of elements
  `x ∈ [A, A+S]` with `x ≡ c [ZMOD M]` and `x ≠ c` is at most `2 * S / M`.
-/

namespace LatticeCounting

/-- The number of multiples of `M` in `[-S, S]` excluding `0` is exactly `2 * ⌊S/M⌋`. -/
public lemma count_multiples_strict (S M : ℤ) (hM : 0 < M) (hS : 0 ≤ S) :
    ((Finset.Icc (-S) S).filter (fun y => M ∣ y ∧ y ≠ 0)).card = 2 * (S / M).toNat := by
  -- Let's simplify the expression inside the cardinality.
  have h_simp : Finset.filter (fun y => M ∣ y ∧ y ≠ 0) (Finset.Icc (-S) S) = Finset.image (fun k : ℕ => M * k) (Finset.Icc 1 (Int.toNat (S / M))) ∪ Finset.image (fun k : ℕ => -M * k) (Finset.Icc 1 (Int.toNat (S / M))) := by
    ext y;
    simp +zetaDelta at *;
    constructor;
    · intro hy
      obtain ⟨k, hk⟩ : ∃ k : ℤ, y = M * k := hy.right.left
      have hk_bounds : -Int.toNat (S / M) ≤ k ∧ k ≤ Int.toNat (S / M) := by
        constructor <;> nlinarith [ Int.mul_ediv_add_emod S M, Int.emod_nonneg S hM.ne', Int.emod_lt_of_pos S hM, Int.toNat_of_nonneg ( Int.ediv_nonneg hS hM.le ) ];
      cases lt_or_gt_of_ne ( show k ≠ 0 by aesop ) <;> [ exact Or.inr ⟨ Int.natAbs k, ⟨ by omega, by omega ⟩, by simp +decide [ abs_of_neg, * ] ⟩ ; exact Or.inl ⟨ Int.natAbs k, ⟨ by omega, by omega ⟩, by simp +decide [ abs_of_pos, * ] ⟩ ];
    · rintro ( ⟨ a, ⟨ ha₁, ha₂ ⟩, rfl ⟩ | ⟨ a, ⟨ ha₁, ha₂ ⟩, rfl ⟩ ) <;> refine' ⟨ ⟨ _, _ ⟩, _, _ ⟩ <;> try nlinarith [ Int.mul_ediv_add_emod S M, Int.emod_nonneg S hM.ne', Int.emod_lt_of_pos S hM, Int.toNat_of_nonneg ( Int.ediv_nonneg hS hM.le ) ];
      · exact dvd_mul_right _ _;
      · exact dvd_neg.mpr ( dvd_mul_right _ _ );
  rw [ h_simp, Finset.card_union_of_disjoint ];
  · rw [ Finset.card_image_of_injective, Finset.card_image_of_injective ] <;> norm_num [ Function.Injective, hM.ne' ] ; ring;
  · norm_num [ Finset.disjoint_left ];
    intros; subst_vars; nlinarith;

/-- If `c ∈ [A, A+S]`, then the number of elements `x ∈ [A, A+S]` such that
`x ≡ c [ZMOD M]` and `x ≠ c` is bounded by `2 * (S/M)`. -/
public lemma count_congruence_interval_strict (A S c M : ℤ) (hM : 0 < M) (hS : 0 ≤ S)
    (hc : c ∈ Finset.Icc A (A + S)) :
    (((Finset.Icc A (A + S)).filter (fun x => x ≡ c [ZMOD M] ∧ x ≠ c)).card : ℝ) ≤
      2 * (S : ℝ) / (M : ℝ) := by
  -- By mapping $x \mapsto x - c$, we can injectively map the filtered set into the set of nonzero multiples of $M$ in $[-S, S]$.
  have h_inj : Finset.card ((Finset.Icc A (A + S)).filter (fun x => x ≡ c [ZMOD M] ∧ x ≠ c)) ≤ Finset.card ((Finset.Icc (-S) S).filter (fun y => M ∣ y ∧ y ≠ 0)) := by
    have h_inj : Finset.image (fun x => x - c) ((Finset.Icc A (A + S)).filter (fun x => x ≡ c [ZMOD M] ∧ x ≠ c)) ⊆ (Finset.Icc (-S) S).filter (fun y => M ∣ y ∧ y ≠ 0) := by
      simp_all +decide [ Finset.subset_iff, Int.modEq_iff_dvd ];
      rintro x y hy₁ hy₂ hy₃ hy₄ rfl; exact ⟨ ⟨ by linarith, by linarith ⟩, by simpa using hy₃.neg_right, by contrapose! hy₄; linarith ⟩ ;
    have := Finset.card_le_card h_inj; rw [ Finset.card_image_of_injective _ ( sub_left_injective ) ] at this; aesop;
  rw [ le_div_iff₀ ] <;> norm_cast;
  have := count_multiples_strict S M hM hS;
  nlinarith [ Int.mul_ediv_add_emod S M, Int.emod_nonneg S hM.ne', Int.emod_lt_of_pos S hM, Int.toNat_of_nonneg ( Int.ediv_nonneg hS hM.le ) ]

end LatticeCounting
