/-
Copyright (c) 2026 Fernando Portela. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Fernando Portela

The architectural design of this LatticeCounting framework was developed by
Antigravity (Google DeepMind) to formalize combinatorial CRT counting arguments.

Portions of this file were generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.29.0
Mathlib version: 8a178386ffc0f5fef0b77738bb5449d50efeea95

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>

References:
- Granville & Kurlberg (2008), arXiv:math/0412135
- Iwaniec & Kowalski, Analytic Number Theory
-/

import PoissonViaCRT.BoxCollisionIntegration

set_option linter.unusedVariables false

/-!
# Module 5: BoxCollisionIntegration

## Goal
Prove `box_collision_sum_bound` by expanding the product of indicators into a sum over
choice functions `σ ∈ U.pi pairsBelow`, and then sequentially bounding each coordinate
via CRT.
-/

set_option maxHeartbeats 800000

namespace PoissonCRT

open Finset BigOperators Classical
open LatticeCounting

/-
The collision sum is bounded by the number of box elements (trivial bound, each
product factor is at most 1).
-/
lemma collision_sum_le_card_box (m : ℕ) (X : Box m) (s : ℝ)
    (U : Finset ℕ) :
    ∑ h ∈ ((Fintype.piFinset fun _ => Finset.Icc (1:ℤ) ⌈s * ∑ i, X.sides i⌉).filter
        (fun h => inScaledBox X s (fun _ => 0) h)),
      (∏ p ∈ U, if Function.Injective (Fin.cons (0 : ZMod p) (fun i => (h i : ZMod p)))
       then (0:ℝ) else 1)
    ≤ ((Fintype.piFinset fun _ : Fin m => Finset.Icc (1:ℤ) ⌈s * ∑ i, X.sides i⌉).filter
        (fun h => inScaledBox X s (fun _ => 0) h)).card := by
  refine' le_trans ( Finset.sum_le_sum fun x hx => _ ) _;
  use fun x => 1;
  · exact Finset.prod_le_one ( fun _ _ => by split_ifs <;> norm_num ) fun _ _ => by split_ifs <;> norm_num;
  · norm_num [ Finset.sum_const ]



/-
The scaled box has at most `⌈s * ∑ sides⌉ ^ m` lattice points.
## Currently unused -/
lemma card_box_le_pow (m : ℕ) (X : Box m) (s : ℝ) (hs : 1 ≤ s) :
    ((Fintype.piFinset fun _ : Fin m => Finset.Icc (1:ℤ) ⌈s * ∑ i, X.sides i⌉).filter
        (fun h => inScaledBox X s (fun _ => 0) h)).card
    ≤ (⌈s * ∑ i, X.sides i⌉).toNat ^ m := by
  convert Finset.card_le_card ( Finset.filter_subset _ _ ) using 1;
  erw [ Fintype.card_piFinset ] ; norm_num



/-- The sequential cardinality bound for a fixed choice function `σ`.
**Corrected statement**: the per-coordinate bound is `⌊N / M_k⌋ + 1` instead of `2 * ⌊N / M_k⌋`,
which is the maximum number of integers in a congruence class within an interval.
## Currently unused -/
lemma validHForSigma_card_le (m : ℕ) (X : Box m) (s : ℝ) (hs : 1 ≤ s)
    (U : Finset ℕ) (hp_prime : ∀ p ∈ U, p.Prime)
    (σ : ∀ p ∈ U, Fin (m + 1) × Fin (m + 1))
    (h_sigma : ∀ p (hp_mem : p ∈ U), (σ p hp_mem) ∈ pairsBelow m) :
    (validHForSigma m X s U σ).card ≤
      ∏ j : Fin m, (⌈s * ∑ i, X.sides i⌉ / ∏ p ∈ U.filter (fun p =>
        ∃ hp_mem : p ∈ U, (σ p hp_mem).2 = j.succ), (p:ℤ) + 1).toNat := by
  set S := ⌈s * ∑ i, X.sides i⌉ with hS_def
  have hS_nn : (0 : ℤ) ≤ S := Int.ceil_nonneg (mul_nonneg (by linarith) (Finset.sum_nonneg
    fun _ _ => le_of_lt (X.sides_pos _)))
  apply LatticeCounting.seq_bound_nat
  intro k h_prefix
  -- Define the target c for the CRT counting
  set U_k := U.filter (fun p => ∃ hp_mem : p ∈ U, (σ p hp_mem).2 = k.succ) with hU_k_def
  have hU_k_prime : ∀ p ∈ U_k, p.Prime := fun p hp => hp_prime p (Finset.mem_filter.mp hp).1
  -- Define target residues
  let c : ℕ → ℤ := fun p => if hp : p ∈ U then extendH m h_prefix (σ p hp).1 else 0
  -- Bound the image by the filtered interval
  apply le_trans (Finset.card_le_card _) (card_filter_coprime_dvd_le S hS_nn U_k hU_k_prime c)
  -- Prove the image is contained in the filtered interval
  intro x hx
  simp only [Finset.mem_image, Finset.mem_filter] at hx
  obtain ⟨h, ⟨hh_valid, hh_agree⟩, rfl⟩ := hx
  simp only [Finset.mem_filter, Finset.mem_Icc]
  exact ⟨validHForSigma_coord_mem_Icc m X s U σ h hh_valid k,
    validHForSigma_divisibility_at_coord m X s U hp_prime σ h_sigma k h_prefix h hh_valid
      hh_agree c rfl⟩

