/-
Copyright (c) 2026 Fernando Portela. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Fernando Portela
-/

/-
Portions of this file were generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.28.0
Mathlib version: 8f9d9cff6bd728b17a24e163c9402775d9e6a365

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

import PoissonViaCRT.FluctuationHelpers

/-!
# Helper lemmas for the fluctuation bound (Proposition 3.6)
-/

open Finset BigOperators

namespace PoissonCRT

variable {q : ℕ} [NeZero q]

/-- `kCorrelation` is nonneg. -/
theorem kCorrelation_nonneg (Ω : Finset (ZMod q)) (X : Box m) :
    0 ≤ kCorrelation Ω X := by
  unfold kCorrelation
  apply mul_nonneg
  · positivity
  · apply Finset.sum_nonneg
    intros; positivity

