/-
Copyright (c) 2026 Fernando Portela. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Fernando Portela
-/

/-
Portions of this file were generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.28.0
Mathlib version: 8f9d9cff6bd728b17a24e163c9402775d9e6a365

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

import PoissonViaCRT.MobiusInfra

/-!
# Möbius Decomposition Infrastructure

Infrastructure lemmas for the multiplicative Möbius decomposition described in §3.2
of the Granville–Kurlberg paper. These support the eventual proof of
`deviation_sum_bound_q_indep` in `CancellationHelpers.lean`.

## Main Results

* `PoissonCRT.crt_counting_mobius_decomp`: The Möbius inversion sum over
  `n.divisorsAntidiagonal` splits into a **main term** `μ(n) · f(1)` (from the pair
  `(n, 1)`) and an **error sum** `∑_{d|n, d>1} μ(n/d) · f(d)` over proper divisors.
  This is the algebraic identity that reorganises the counting function into the
  form `∑_{d|q, d>1}`.

* `PoissonCRT.d_contribution_bound`: When a function `f` sums to zero over all
  residue classes (as guaranteed by `deviation_sum_period_zero`) and is pointwise
  bounded by `M` (as guaranteed by `individual_deviation_bound`), the weighted
  sum `∑ w · f` is controlled by the **total variation** of the weights from any
  constant `c` times `M`. The total variation captures exactly the boundary
  (incomplete-period) contribution for a single divisor `d`, and is bounded by
  `box_card_upper_bound` applied with scaling `s/d`.

* `PoissonCRT.divisor_sum_convergence`: The p-series `∑ d^{-(k-2+ε)}` converges
  whenever the exponent exceeds 1. For `k ≥ 3` this is automatic; for `k = 2`
  the critical exponent `λ₂` ensures convergence via a separate bound.

## References

* [A. Granville, P. Kurlberg, *Poisson statistics via the Chinese remainder theorem*],
  §3.2
-/

open Finset BigOperators Classical

namespace PoissonCRT

/-! ## 1. Möbius Decomposition Identity

The algebraic core of the Möbius decomposition: for any function `f` and positive
integer `n`, the Möbius inversion sum `∑_{(a,b) ∈ n.divisorsAntidiagonal} μ(a)·f(b)`
splits into the main term from `b = 1` and the error sum from `b > 1`.
-/

/-
**Convergence for k ≥ 3**: The p-series `∑ d^{-(k-2+ε)}` converges when
`k ≥ 3` and `ε > 0`, as the exponent `k - 2 + ε ≥ 1 + ε > 1`.

Apply Real.summable_nat_rpow_inv.mpr. Need to show 1 < (k : ℝ) - 2 + ε. Since k ≥ 3 (cast to ℝ), we have (k:ℝ) - 2 ≥ 1, so (k:ℝ) - 2 + ε ≥ 1 + ε > 1. Use linarith with the cast.
-/
theorem divisor_sum_convergence_k_ge_3 {k : ℕ} (hk : 3 ≤ k) (ε : ℝ) (hε : 0 < ε) :
    Summable (fun n : ℕ => ((n : ℝ) ^ ((k : ℝ) - 2 + ε))⁻¹) := by
  exact Real.summable_nat_rpow_inv.mpr ( by linarith [ show ( k : ℝ ) ≥ 3 by norm_cast ] )



/-
**Convergence for k = 2 (critical exponent)**: For `k = 2`, the divisor sum
convergence requires the exponent `α` to exceed 1. The paper's critical exponent
`λ₂ = (√17 - 3)/2 ≈ 0.56` combined with the spacing bound `s ≤ p^{λ₂ - ε}`
ensures an effective exponent `> 1` after accounting for the divisor function bound.

This lemma captures the general summability criterion used in both the `k = 2`
and `k ≥ 3` regimes.

Directly apply Real.summable_nat_rpow_inv.mpr hα.
-/
theorem divisor_sum_convergence_k_eq_2 (α : ℝ) (hα : 1 < α) :
    Summable (fun n : ℕ => ((n : ℝ) ^ α)⁻¹) := by
  exact Real.summable_nat_rpow_inv.2 hα

