/-
Copyright (c) 2026 Fernando Portela. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Fernando Portela
-/

/-
Portions of this file were generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.28.0
Mathlib version: 8f9d9cff6bd728b17a24e163c9402775d9e6a365

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

import PoissonViaCRT.TupleCount

/-!
# Properties of the Counting Function `N_k`

This file contains key properties of the tuple counting function `N_k(h, Ω)` from
"Poisson statistics via the Chinese remainder theorem" by Granville–Kurlberg.

## Main Results

* `PoissonCRT.tupleCount_sum_eq`: `∑_h N_k(h, Ω) = q · |Ω|^k`.
* `PoissonCRT.tupleCount_sum_cons_eq`: The paper's version with `h₀ = 0` fixed:
  `∑_{g} N_k(0 :: g, Ω) = |Ω|^{k+1}` (Lemma 3.5).
* `PoissonCRT.tupleCount_le_card`: `N_{k+1}(h, Ω) ≤ |Ω|`.

## References

* [A. Granville, P. Kurlberg, *Poisson statistics via the Chinese remainder theorem*]
  [arXiv:math/0412135v2], §3.2
-/

open Finset BigOperators

namespace PoissonCRT

variable {q : ℕ} [NeZero q]

/-! ### Basic properties -/

/-- When `k = 0`, `N_0(h, Ω)` counts all elements of `ℤ/qℤ`, i.e., equals `q`. -/
theorem tupleCount_zero (Ω : Finset (ZMod q)) (h : Fin 0 → ZMod q) :
    tupleCount Ω h = q := by
  unfold tupleCount
  simp_all only [IsEmpty.forall_iff, filter_true, card_univ, ZMod.card]



/-- Shifting all offsets by a constant doesn't change `N_k`. -/
theorem tupleCount_shift (Ω : Finset (ZMod q)) (h : Fin k → ZMod q) (c : ZMod q) :
    tupleCount Ω (fun i => h i + c) = tupleCount Ω h := by
  unfold tupleCount
  rw [Finset.card_filter, Finset.card_filter]
  apply Finset.sum_bij (fun i _ => i + c)
  · exact fun _ _ => Finset.mem_univ _
  · intro a₁ ha₁ a₂ ha₂ a
    simp_all only [mem_univ, add_left_inj]
  · exact fun b _ => ⟨b - c, Finset.mem_univ _, sub_add_cancel _ _⟩
  · simp +decide only [add_comm, add_left_comm]
    tauto

/-! ### The sum formula

The fundamental identity `∑_h N_k(h, Ω) = q · |Ω|^k` is established by exchanging the order
of summation. Each `t ∈ ℤ/qℤ` contributes `|Ω|^k` to the sum (by independence of coordinates).

The paper uses the variant with `h₀ = 0` fixed (Lemma 3.5): summing over `g : Fin k → ℤ/qℤ`,
we have `∑_g N_{k+1}(0 :: g, Ω) = |Ω|^{k+1}`. The condition `t + 0 ∈ Ω` restricts `t` to
`Ω`, giving `|Ω|` choices of `t`, each contributing `|Ω|^k` from the remaining coordinates.
-/



/-- `N_k(h, Ω)` is monotone in `Ω`. -/
theorem tupleCount_mono {Ω₁ Ω₂ : Finset (ZMod q)} (h : Fin k → ZMod q)
    (hsub : Ω₁ ⊆ Ω₂) : tupleCount Ω₁ h ≤ tupleCount Ω₂ h :=
  Finset.card_mono fun x hx => by aesop



/-- `N_k(h, ∅) = 0` for `k ≥ 1`. -/
theorem tupleCount_empty (h : Fin (k + 1) → ZMod q) :
    tupleCount (∅ : Finset (ZMod q)) h = 0 := by
  unfold tupleCount
  simp_all only [notMem_empty, forall_const, filter_false, card_empty]

