/-
Copyright (c) 2026 Fernando Portela. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Fernando Portela

The architectural design of this LatticeCounting framework was developed by
Antigravity (Google DeepMind) to formalize combinatorial CRT counting arguments.

Portions of this file were generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.28.0
Mathlib version: 8f9d9cff6bd728b17a24e163c9402775d9e6a365

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>

References:
- Granville & Kurlberg (2008), arXiv:math/0412135
- Iwaniec & Kowalski, Analytic Number Theory
-/

import PoissonViaCRT.CommonTactics
import Mathlib.Algebra.BigOperators.Group.Finset.Basic
import Mathlib.Data.Finset.Card
import Mathlib.Data.Fintype.Basic

/-!
# Module 4: SequentialCounting

Count valid tuples `(h₁, …, hₘ)` where the constraints on `hⱼ` depend on the
previously chosen prefix `(h₁, …, hⱼ₋₁)`.

## Main definitions

* `AgreeOn k h₁ h₂` – `h₁` and `h₂` agree on all coordinates strictly less than `k`.

## Main results

* `seq_bound_nat` – A sequential bounding lemma for subsets of `Fin m → α`: if for every
  coordinate `k` and every prefix the number of valid choices for the `k`-th coordinate is
  bounded by `B k`, then `|X| ≤ ∏ j, B j`.
-/

namespace LatticeCounting

open Finset

/-- `AgreeOn k h₁ h₂` means that `h₁` and `h₂` agree on all coordinates strictly less
than `k`. -/
@[expose] public def AgreeOn {m : ℕ} {α : Type*} (k : ℕ) (h1 h2 : Fin m → α) : Prop :=
  ∀ i : Fin m, (i : ℕ) < k → h1 i = h2 i

public instance instDecidableAgreeOn {m : ℕ} {α : Type*} [DecidableEq α] (k : ℕ)
    (h1 h2 : Fin m → α) : Decidable (AgreeOn k h1 h2) :=
  inferInstanceAs (Decidable (∀ i : Fin m, (i : ℕ) < k → h1 i = h2 i))

private lemma agreeOn_zero {m : ℕ} {α : Type*} (h1 h2 : Fin m → α) :
    AgreeOn 0 h1 h2 := fun _ hi => absurd hi (Nat.not_lt_zero _)

private lemma agreeOn_m_eq {m : ℕ} {α : Type*} {h1 h2 : Fin m → α}
    (h : AgreeOn m h1 h2) : h1 = h2 :=
  funext fun i => h i i.isLt

/-
Auxiliary induction step: for each `k ≤ m`, the number of elements of `X` that agree
with a given prefix on coordinates `< k` is at most
`∏ j ∈ Finset.univ.filter (fun j : Fin m => k ≤ j), B j`.
-/
private lemma seq_bound_aux {m : ℕ} {α : Type*} [DecidableEq α]
    (X : Finset (Fin m → α)) (B : Fin m → ℕ)
    (h_bound : ∀ (k : Fin m) (h_prefix : Fin m → α),
        ((X.filter (fun h => AgreeOn (k : ℕ) h h_prefix)).image (fun h => h k)).card ≤ B k)
    (k : ℕ) (hk : k ≤ m) (h_prefix : Fin m → α) :
    (X.filter (fun h => AgreeOn k h h_prefix)).card ≤
      ∏ j ∈ Finset.univ.filter (fun j : Fin m => k ≤ (j : ℕ)), B j := by
  induction n : m - k generalizing k h_prefix X
  case zero =>
    simp_all +decide only [Nat.sub_eq_zero_iff_le]
    cases le_antisymm hk n
    rw [ Finset.prod_eq_one ]
    · exact Finset.card_le_one.mpr fun x hx y hy =>
        agreeOn_m_eq ( Finset.mem_filter.mp hx |>.2 ) ▸
        agreeOn_m_eq ( Finset.mem_filter.mp hy |>.2 ) ▸ rfl
    · grind
  case succ d hd =>
    -- Let `k' : Fin m := ⟨k, by omega⟩`.
    obtain ⟨k', hk'⟩ : ∃ k' : Fin m, k = k'.val := by
      exact ⟨ ⟨ k, by omega ⟩, rfl ⟩
    -- By `card_le_card` and `card_biUnion_le`, card of filter ≤ sum over V of card of each piece.
    have h_card_biUnion :
      (Finset.filter (fun h => AgreeOn k h h_prefix) X).card
      ≤ ∑ a ∈ Finset.image (fun h => h k') (Finset.filter (fun h => AgreeOn k h h_prefix) X),
        (Finset.filter (fun h => AgreeOn (k + 1) h (Function.update h_prefix k' a)) X).card := by
      have h_card_biUnion :
        Finset.filter (fun h => AgreeOn k h h_prefix) X ⊆ Finset.biUnion
          (Finset.image (fun h => h k') (Finset.filter (fun h => AgreeOn k h h_prefix) X))
          (fun a => Finset.filter (fun h =>
            AgreeOn (k + 1) h (Function.update h_prefix k' a)) X) := by
        simp +decide [ Finset.subset_iff, AgreeOn ]
        grind
      exact le_trans ( Finset.card_le_card h_card_biUnion ) ( Finset.card_biUnion_le )
    -- By IH (at `k+1`), each piece has card ≤ `∏ j ∈ univ.filter (fun j => k+1 ≤ j), B j`.
    have h_card_piece : ∀ a ∈ Finset.image (fun h => h k')
        (Finset.filter (fun h => AgreeOn k h h_prefix) X),
        (Finset.filter (fun h => AgreeOn (k + 1) h (Function.update h_prefix k' a)) X).card
        ≤ ∏ j ∈ Finset.filter (fun j : Fin m => k + 1 ≤ j.val) Finset.univ, B j := by
      intro a ha
      convert hd X h_bound ( k + 1 ) ( by omega ) ( Function.update h_prefix k' a ) ( by omega )
        using 1
    apply le_trans h_card_biUnion ( le_trans ( Finset.sum_le_sum h_card_piece ) _ )
    simp +decide only [hk', Order.add_one_le_iff, Fin.val_fin_lt, sum_const, smul_eq_mul,
      Fin.val_fin_le]
    rw [ show ( Finset.filter ( fun x : Fin m => k' ≤ x ) Finset.univ ) =
              Finset.filter ( fun x : Fin m => k' < x ) Finset.univ ∪ { k' }
              from ?_, Finset.prod_union ] <;> norm_num
    · rw [ mul_comm ] ; gcongr ; aesop
    · grind

/-
A sequential bounding lemma for subsets of `Fin m → α`.
If for every coordinate `k`, and every prefix, the number of valid choices for the `k`-th
coordinate is bounded by `B k`, then the total cardinality of `X` is bounded by `∏ B k`.
-/
public lemma seq_bound_nat {m : ℕ} {α : Type*} [DecidableEq α]
    (X : Finset (Fin m → α)) (B : Fin m → ℕ)
    (h_bound : ∀ (k : Fin m) (h_prefix : Fin m → α),
        ((X.filter (fun h => AgreeOn (k : ℕ) h h_prefix)).image (fun h => h k)).card ≤ B k) :
    X.card ≤ ∏ j : Fin m, B j := by
  nontriviality
  contrapose! h_bound
  by_contra h_contra
  convert seq_bound_aux X B ( fun k h_prefix => le_of_not_gt fun h => h_contra ⟨ k, h_prefix, h ⟩ )
          0 bot_le 0 using 1
  simp +decide [ agreeOn_zero ]
  · grind +qlia
  · exact ⟨ fun _ => Classical.choice ( show Nonempty α from by
      exact ⟨ Classical.choose ( Finset.card_pos.mp ( pos_of_gt h_bound ) ) ‹_› ⟩ ) ⟩

end LatticeCounting
